## Instalación de librerías

In [ ]:
!pip install -q scrapy
#!pip install -q newspaper4k
!pip install -q newspaper3k
!pip install -q lxml_html_clean

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.8/259.8 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.9/104.9 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 36.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 3.6 MB/s eta 0:00:00
  Building wheel for tinysegmenter (setup.py) ... done
  Building wheel for feedfinder2 (setup.py) ... done
  Building wheel for jieba3k (setup.py) ... done
  Building wheel for sgmllib3k (setup.py) ... done

# Articulos de mapas de sitio usando scrapy

In [ ]:
!scrapy startproject news_scraper

New Scrapy project 'news_scraper', using template directory '/usr/local/lib/python3.11/dist-packages/scrapy/templates/project', created in:
    /content/news_scraper

You can start your first spider with:
    cd news_scraper
    scrapy genspider example example.com

## Extracción de URLs

In [1]:
%cd news_scraper

c:\Users\rebec\OneDrive - Universidad de Oviedo\Escritorio\TFG\news_scraper

In [7]:
%%writefile "news_extractor_spider.py"
import scrapy
from newspaper import build, Config, Article
import requests
from urllib.parse import urljoin, urlparse
import os
import time
import re
from datetime import datetime
import gzip
from scrapy.selector import Selector
import dateutil


class NewsUrlExtractorSpider(scrapy.Spider):
    name = 'news_extractor'

    def __init__(self, date="2025-01-01", *args, **kwargs):
        super(NewsUrlExtractorSpider, self).__init__(*args, **kwargs)
        self.from_date = datetime.strptime(date, '%Y-%m-%d').date()
        self.invalid_url_words = {'section', 'tag', 'template',
                                  'category', 'author', 'page-sitemap'
                                  'categories', 'video', 'image', 'temas',
								                  'live', 'microsite', 'focus', 'blog',
                                  'ocio', 'cine', 'board', 'character',
                                  'galeria', 'categoria', 'ficha', 'firmante',
                                  'secciones'}

    # Metadata: nombre y sitemap
    metadata_urls={
        'https://www.elcomercio.es/': {'nombre': 'El Comercio'},
        'https://www.lne.es/': {'nombre': 'La Nueva España'},
        'https://www.lavanguardia.com/': {'nombre': 'La Vanguardia',
                                          'sitemap': 'sitemap-google-news.xml'},
        'https://www.larazon.es/': {'nombre': 'La Razón'},
        'https://www.rtpa.es/': {'nombre': 'Radiotelevisión del Principado de Asturias (RTPA)',
                                 'sitemap': 'sitemap-noticias.xml'},
        'https://www.europapress.es/': {'nombre': 'Europa Press'},
        'https://www.20minutos.es/': {'nombre': '20 Minutos',
                                      'sitemap': 'sitemap-google-news.xml'},
        'https://www.elperiodico.com/' : {'nombre': 'El Periódico',
                                          'sitemap': 'google-news.xml'},
        'https://www.eldiario.es/' : {'nombre': 'ElDiario.es'},
        'https://www.elconfidencial.com/': {'nombre': 'El Confidencial',
                                            'sitemap': 'newsitemap_4.xml'},
        'https://www.culturalgijonesa.org/': {'nombre': 'Cultural Gijonesa'},
        'https://www.elespanol.com/' : {'nombre': 'El Español',
                                        'sitemap': 'sitemap_google_news.xml'},
        'https://www.nortes.me/': {'nombre': 'Nortes'},
        'https://www.lavozdegalicia.es/': {'nombre': 'La Voz de Galicia'},
        'https://www.asturiasmundial.com/': {'nombre': 'Asturias Mundial'},
        'https://www.tribunasalamanca.com/': {'nombre': 'Tribuna Salamanca'},
        'https://migijon.com/': {'nombre': 'Mi Gijón'},
        'https://www.infobae.com/' : {'nombre': 'Infobae',
                                      'sitemap': 'arc/outboundfeeds/news-sitemap2/'},
        'https://www.telecinco.es/' : {'nombre': 'Telecinco'},
        'https://www.laprovincia.es/' : {'nombre': 'La Provincia'},
        'https://www.laopiniondemalaga.es/': {'nombre': 'La Opinión de Málaga'},
        'https://www.elfielato.es/': {'nombre': 'El Fielato y El Nora'},
        'https://www.teleprensa.com/': {'nombre': 'Teleprensa'},

        'https://forbes.es/': {'nombre': 'Forbes'},
        'https://itg.es/': {'nombre': 'ITG centro tecnológico'},
        'https://www.eldia.es/': {'nombre': 'El Dia'},
        'https://www.nationalgeographic.es/': {'nombre': 'Historia National Geographic'},
        'https://iymagazine.es/': {'nombre': 'IyMagazine'},
        'https://www.lacerca.com/': {'nombre': 'La Cerca'},
        'https://www.tribunaavila.com/': {'nombre': 'Tribuna de Ávila'},
        'https://www.latribunadealbacete.es/': {'nombre': 'La Tribuna de Albacete'},
        'https://www.eldiariomontanes.es/': {'nombre': 'El Diario Montañés'},
        "https://www.larioja.com/":{"nombre": "La Rioja"},
        "https://www.almerianoticias.es/":{"nombre": "Almería Noticias"},
        "https://news.ual.es/":{"nombre": "UALNEWS"},
        "https://www.farodevigo.es/":{"nombre": "Faro de Vigo"},
        "https://www.diariocordoba.com/": {'nombre': 'Diario Córdoba'},
        "https://www.diariodeibiza.es/": {'nombre': 'Diario de Ibiza'},
        "https://segoviaudaz.es/": {'nombre': 'SegoviAudaz'},
        'https://www.abc.es/': {'nombre': 'ABC'}, #newspaper
        'https://www.lavozdeasturias.es/': {'nombre': 'La Voz de Asturias'}, #newspaper
        'https://cualia.es/': {'nombre': 'Cualia'}, #newspaper
        'http://www.gentedigital.es/' : {'nombre': 'Gente Digital'}, #newspaper
        'https://www.8directo.com/':{'nombre': '8directo'}, #newspaper
        'https://www.lanuevacronica.com/': {'nombre': 'La Nueva Crónica'}, #newspaper
        'https://elpais.com/': {'nombre': 'El Pais'},
        'https://www.elperiodicodecanarias.es/': {'nombre': 'El Periodico de Canarias'}
    }

    custom_settings = {
        'USER_AGENT': "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
    #    'USER_AGENT': "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/W.X.Y.Z Safari/537.36"
    }

    # Para extracción de xmls
    namespaces = {
        'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9',  # Default namespace
        'news': 'http://www.google.com/schemas/sitemap-news/0.9'
    }

    def get_base_url(self, url):
        parsed_url = urlparse(url)
        return f"{parsed_url.scheme}://{parsed_url.netloc}/"

    def normalize_date(self, date_string):
        try:
            # Conviertir la cadena de fechas en un objeto datetime
            parsed_date = dateutil.parser.parse(date_string)
            # Formatea el objeto datetime como 'YYYY-MM-DD'
            #return parsed_date.strftime('%Y-%m-%d')
            return parsed_date.date()
        except (ValueError, TypeError):
            raise ValueError(f"Formato de fecha inválido: '{date_string}'")

    def is_valid_xml_url(self, sitemap_url):
        for invalid_word in self.invalid_url_words:
            if invalid_word in sitemap_url:
                return False

        pattern = r'\b(1[0-9]{3}|20[0-1][0-9]|202[0-4])\b' # Matches 1000-1999, 2000-2019, and 2020-2024
        match_url = re.search(pattern, sitemap_url)
        if match_url:
            return False
        else:
            return True

    def start_requests(self):
        for url in self.metadata_urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response):
        robots_url = urljoin(response.url, "/robots.txt")
        print(f'Robots URL: {robots_url}')
        yield scrapy.Request(robots_url, callback=self.parse_robots, meta={'domain': response.url})


    def parse_robots(self, response):
        if response.status != 200:
            print(f"Error al acceder a la url: {response.status}")
            return

        domain = response.meta['domain']
        domain_base = self.get_base_url(domain)
        current_sitemap_urls = set() #[]

        # Extraer urls de sitemaps de robots.txt
        for line in response.text.splitlines():
            if line.lower().startswith('sitemap:'):
                sitemap_url = line.split(':', 1)[1].strip()
                parsed_url = urlparse(sitemap_url)
                file_path = parsed_url.path
                file_name, file_extension = os.path.splitext(file_path)
                #if file_extension.lower() == ".xml" and self.is_valid_xml_url(sitemap_url):
                if self.is_valid_xml_url(sitemap_url):
                    current_sitemap_urls.add(sitemap_url)

        if len(current_sitemap_urls) > 0:
            print(f"Se encontraron los siguientes enlaces xml: {current_sitemap_urls}")
            for sitemap_url in current_sitemap_urls:
                print(f"Accediendo al siguiente enlace... {sitemap_url}")
                #yield scrapy.Request(sitemap_url, callback=self.parse_sitemap)  # Llamada recursiva
                yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain) )

        elif domain_base in self.metadata_urls and 'sitemap' in self.metadata_urls[domain_base]:
            print("No se encontraron enlaces xml en robots.txt.", end=" ")
            sitemap_name = self.metadata_urls[domain_base]['sitemap']
            sitemap_url = urljoin(domain_base, sitemap_name)
            print(f"Accediendo al siguiente enlace especificado... {sitemap_url}")
            yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain_base) )
        else:
            print("No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...")
            # Si no se encuentra ningún mapa del sitio,
            # utilizar Newspaper4k para obtener las URL de los artículos de noticias
            yield from self.get_news_urls(domain)



    def parse_sitemap(self, response, domain=None):

        # Sitemaps anidados. Tag <sitemap>
        for sitemap in response.xpath('//ns:sitemap', namespaces=self.namespaces):
            sitemap_loc = sitemap.xpath('./ns:loc/text()', namespaces=self.namespaces).get()

            # Omitir sitemaps antiguos
            last_mod = sitemap.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()
            if last_mod:
                lastmod = self.normalize_date(last_mod)
                if lastmod < self.from_date:
                    continue

            # Verificar que la url es un archivo xml
            parsed_url = urlparse(sitemap_loc)
            file_path = parsed_url.path
            file_name, file_extension = os.path.splitext(file_path)

            #if file_extension.lower() == ".xml" and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
            if file_extension.lower() != '.gz' and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                #print(f'Se encontró otro xml dentro del archivo actual: {sitemap_loc}') ## lots of outputs
                if sitemap_loc:
                    #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap)  # Llamada recursiva
                    yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap(response, domain) )
            elif file_extension.lower() == '.gz'  and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                print(f"Se encontró archivo comprimido {sitemap_loc}")
                #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap_gz)
                yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap_gz(response, domain) )



        # Verificar que el archivo tenga noticias recientes
        selector_list = response.xpath('//ns:url', namespaces=self.namespaces)
        if len(selector_list) > 1:
            first_publication_date = selector_list[0].xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            if first_publication_date is None:
                first_publication_date = selector_list[0].xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            last_publication_date = selector_list[-1].xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            if last_publication_date is None:
                last_publication_date = selector_list[-1].xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            first_publication_date = self.normalize_date(first_publication_date)
            last_publication_date = self.normalize_date(last_publication_date)
            if first_publication_date < self.from_date and last_publication_date < self.from_date:
                return

        # Extraer datos de cada tag <url>
        for url in selector_list:
        #for url in response.xpath('//ns:url', namespaces=self.namespaces):
            loc = url.xpath('./ns:loc/text()', namespaces=self.namespaces).get()
            title = url.xpath('./news:news/news:title/text()', namespaces=self.namespaces).get()
            publication_date = url.xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            fuente = url.xpath('./news:news/news:publication/news:name/text()', namespaces=self.namespaces).get()

            if loc is None:
                break

            title = "" if title is None else title

            if publication_date is None:
                publication_date = url.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            if publication_date is not None:
                publication_date_comp = self.normalize_date(publication_date)
                #publication_date_ = dateutil.parser.parse(publication_date).date()
                if publication_date_comp < self.from_date:
                    continue
                    #break
            else:
                continue


            if domain is not None:
                domain_base = self.get_base_url(domain)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']

            yield {
                'fuente': fuente,
                'url': loc,
                'titulo': title,
                'fecha_publicacion': publication_date,
            }

    def parse_sitemap_gz(self, response, domain=None):

        compressed_file = response.body
        decompressed_file = gzip.decompress(compressed_file).decode("utf-8")
        selector = Selector(text=decompressed_file, type="xml")
        #yield from self.parse_sitemap(selector)
        yield from self.parse_sitemap(selector, domain)

    def get_news_urls(self, domain):

        config = Config()
        config.request_timeout = 5
        config.language= 'es'
        config.thread_timeout_seconds = 5
        config.memoize_articles = False
        config.fetch_images = False
        config.follow_meta_refresh = True
        config.number_threads = 4
        config.browser_user_agent = self.custom_settings['USER_AGENT']
        config.headers = {
            "User-Agent": self.custom_settings['USER_AGENT'],
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate",
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
            "Cache-Control": "max-age=0",
        }

        try:
            print(f'Extrayendo noticias con librería Newspaper para url: {domain}')
            start_time = time.time()
            paper = build(domain, config=config)
            print(f"--- {(time.time() - start_time):.2f}s segundos ---")
            articulos_urls = set(paper.article_urls())
            print(f'Se encontraron {len(articulos_urls)} enlaces de noticias.')

            # Obtener fuente
            if domain is not None:
                domain_base = self.get_base_url(domain)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']
                else:
                    found_match = re.search(r"www\.(.*?)\.(.+)", domain)
                    fuente = ''
                    if found_match:
                        fuente = found_match.group(1)


            titulo, fecha_publicacion = '', None
            for articulo_url in articulos_urls:
                yield {
                    'fuente': fuente,
                    'url': articulo_url,
                    'titulo': titulo,
                    'fecha_publicacion': fecha_publicacion,
                }
        except Exception as e:
            print(f"No se pudieron obtener noticias de {domain}")

Overwriting news_extractor_spider.py

Copiar archivo spider a carpeta para ejecutar

In [12]:
# !cp news_extractor_spider.py news_scraper/spiders
!copy news_extractor_spider.py news_scraper\spiders

        1 archivo(s) copiado(s).

Eliminar csv para generar uno nuevo

In [13]:
# Eliminar csv
import os
output_file_csv = "news_output.csv"
if os.path.exists(output_file_csv):
    os.remove(output_file_csv)

Ejecutar spyder de scrapy para gener el archivo csv con los enlaces

In [14]:
!scrapy crawl news_extractor -o news_output.csv -s LOG_ENABLED=False -s ROBOTSTXT_OBEY=False -a date=2025-02-15
#!scrapy crawl news_extractor -o news_output.csv -s ROBOTSTXT_OBEY=False

Robots URL: https://www.elcomercio.es/robots.txt
Robots URL: https://www.20minutos.es/robots.txt
Robots URL: https://www.europapress.es/robots.txt
Robots URL: https://www.lne.es/robots.txt
Robots URL: https://www.elconfidencial.com/robots.txt
Robots URL: https://www.larazon.es/robots.txt
Robots URL: https://www.eldiario.es/robots.txt
Robots URL: https://www.asturiasmundial.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.elcomercio.es/sitemap.incremental.xml', 'https://www.elcomercio.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.incremental.xml
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.xml
Robots URL: https://www.rtpa.es/robots.txt
Robots URL: https://www.culturalgijonesa.org/robots.txt
Robots URL: https://migijon.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.lne.es/sitemap_today_52e19.xml', 'https://www.lne.es/sitemap_google_news_52e19.xml'}
Accediendo al siguiente enlace... https://www.lne.es/sitemap_today_52e19.xml
Accediendo al siguiente enlace... https://www.lne.es/sitemap_google_news_52e19.xml
Se encontraron los siguientes enlaces xml: {'https://www.larazon.es/sitemaps/news.xml', 'https://www.larazon.es/sitemaps/content_sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/news.xml
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/content_sitemap_index.xml
Robots URL: https://www.elperiodico.com/robots.txt
Robots URL: https://www.infobae.com/robots.txt
Robots URL: https://www.laprovincia.es/robots.txt
Robots URL: https://www.elespanol.com/robots.txt
Robots URL: https://www.nortes.me/robots.txt
Robots URL: https://www.telecinco.es/robots.txt
Robots URL: https://www.lavanguardia.com/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.20minutos.es/sitemap-google-news.xml
Robots URL: https://www.laopiniondemalaga.es/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elconfidencial.com/newsitemap_4.xml
Se encontraron los siguientes enlaces xml: {'https://www.europapress.es/sitemap.xml', 'https://www.europapress.es/sitemap_index/'}
Accediendo al siguiente enlace... https://www.europapress.es/sitemap.xml
Accediendo al siguiente enlace... https://www.europapress.es/sitemap_index/
Robots URL: https://www.lavozdegalicia.es/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-google-news.xml
Se encontraron los siguientes enlaces xml: {'https://www.nortes.me/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.nortes.me/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/', 'https://www.infobae.com/arc/outboundfeeds/sitemap2/', 'https://www.infobae.com/arc/outboundfeeds/news-sitemap2/'}
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap2/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/news-sitemap2/
Se encontraron los siguientes enlaces xml: {'https://www.elperiodico.com/es/sitemap-noticias.xml', 'https://www.elperiodico.com/es/google-news.xml'}
Accediendo al siguiente enlace... https://www.elperiodico.com/es/sitemap-noticias.xml
Accediendo al siguiente enlace... https://www.elperiodico.com/es/google-news.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elespanol.com/sitemap_google_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.laprovincia.es/sitemap_index_89aa6.xml', 'https://www.laprovincia.es/sitemap_google_news_89aa6.xml'}
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_index_89aa6.xml
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_google_news_89aa6.xml
Se encontraron los siguientes enlaces xml: {'https://www.telecinco.es/sitemap_index.xml', 'https://www.telecinco.es/sitemap_google_news.xml', 'https://www.telecinco.es/sitemap_ampstories.xml'}
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_index.xml
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_google_news.xml
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_ampstories.xml
Robots URL: https://www.nationalgeographic.es/robots.txt
Robots URL: https://forbes.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://migijon.com/xmlsitemap.xml', 'https://migijon.com/sitemap_index.xml'}
Accediendo al siguiente enlace... https://migijon.com/xmlsitemap.xml
Accediendo al siguiente enlace... https://migijon.com/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.culturalgijonesa.org/sitemap.xml', 'https://www.culturalgijonesa.org/sitemap.rss'}
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.xml
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.rss
Se encontraron los siguientes enlaces xml: {'https://www.rtpa.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.rtpa.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml', 'https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml'}
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml
Robots URL: https://www.eldia.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.eldiario.es/sitemap_index_25b87.xml', 'https://www.eldiario.es/sitemap_google_news_25b87.xml'}
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_index_25b87.xml
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_google_news_25b87.xml
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.asturiasmundial.com/
--- 13.04s segundos ---
Se encontraron 1 enlaces de noticias.
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.lavozdegalicia.es/
--- 42.29s segundos ---
Se encontraron 3 enlaces de noticias.
Robots URL: https://itg.es/robots.txt
Robots URL: https://www.elfielato.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.nationalgeographic.es/google-news.xml', 'https://www.nationalgeographic.es/sitemap/sitemap.xml'}
Accediendo al siguiente enlace... https://www.nationalgeographic.es/google-news.xml
Accediendo al siguiente enlace... https://www.nationalgeographic.es/sitemap/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://forbes.es/wp-sitemap.xml'}
Accediendo al siguiente enlace... https://forbes.es/wp-sitemap.xml
Robots URL: https://www.tribunasalamanca.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.eldia.es/sitemap_google_news_f10b6.xml', 'https://www.eldia.es/sitemap_index_f10b6.xml'}
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_google_news_f10b6.xml
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_index_f10b6.xml
Robots URL: https://www.teleprensa.com/robots.txt
Robots URL: https://iymagazine.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.teleprensa.com/sitemap.xml', 'https://www.teleprensa.com/sitemap.news.xml.gz'}
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.xml
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.news.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.tribunasalamanca.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunasalamanca.com/sitemap_last_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.elfielato.es/sitemap.news.xml.gz', 'https://www.elfielato.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.news.xml.gz
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://itg.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://itg.es/sitemap_index.xml
Se encontró archivo comprimido https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.categories.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.03.1.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.02.1.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.01.1.xml.gz
Se encontraron los siguientes enlaces xml: {'https://iymagazine.es/sitemap.xml'}
Accediendo al siguiente enlace... https://iymagazine.es/sitemap.xml
Se encontró archivo comprimido https://iymagazine.es/sitemaps/sitemap_1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.categories.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.24.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.25.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.26.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.27.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.28.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.29.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.30.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.24.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.25.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.26.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.27.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.28.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.29.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.30.xml.gz
Robots URL: https://www.lacerca.com/robots.txt
Robots URL: https://www.tribunaavila.com/robots.txt
Robots URL: https://www.eldiariomontanes.es/robots.txt
Robots URL: https://www.larioja.com/robots.txt
Robots URL: https://www.latribunadealbacete.es/robots.txt
Robots URL: https://www.farodevigo.es/robots.txt
Robots URL: https://www.diariocordoba.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.larioja.com/sitemap.xml', 'https://www.larioja.com/sitemap.incremental.xml'}
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.xml
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.incremental.xml
Se encontraron los siguientes enlaces xml: {'https://www.tribunaavila.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunaavila.com/sitemap_last_news.xml
Robots URL: https://www.diariodeibiza.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.eldiariomontanes.es/sitemap.xml', 'https://www.eldiariomontanes.es/sitemap.incremental.xml'}
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.xml
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.incremental.xml
Robots URL: https://news.ual.es/robots.txt
Robots URL: https://www.almerianoticias.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.farodevigo.es/sitemap_google_news_246e7.xml', 'https://www.farodevigo.es/sitemap_index_246e7.xml'}
Accediendo al siguiente enlace... https://www.farodevigo.es/sitemap_google_news_246e7.xml
Accediendo al siguiente enlace... https://www.farodevigo.es/sitemap_index_246e7.xml
Se encontraron los siguientes enlaces xml: {'https://www.diariodeibiza.es/sitemap_index_fdff0.xml', 'https://www.diariodeibiza.es/sitemap_google_news_fdff0.xml'}
Accediendo al siguiente enlace... https://www.diariodeibiza.es/sitemap_index_fdff0.xml
Accediendo al siguiente enlace... https://www.diariodeibiza.es/sitemap_google_news_fdff0.xml
Se encontraron los siguientes enlaces xml: {'https://www.latribunadealbacete.es/sitemap.xml', 'https://www.latribunadealbacete.es/sitemap.news.xml'}
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.diariocordoba.com/sitemap_google_news_9665f.xml', 'https://www.diariocordoba.com/sitemap_index_9665f.xml'}
Accediendo al siguiente enlace... https://www.diariocordoba.com/sitemap_google_news_9665f.xml
Accediendo al siguiente enlace... https://www.diariocordoba.com/sitemap_index_9665f.xml
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.news.xml
Se encontraron los siguientes enlaces xml: {'http://www.lacerca.com/system/sitemaps/sitemap.xml'}
Accediendo al siguiente enlace... http://www.lacerca.com/system/sitemaps/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.almerianoticias.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.almerianoticias.es/sitemap_index.xml
Robots URL: https://segoviaudaz.es/robots.txt
Se encontraron los siguientes enlaces xml: {'http://news.ual.es/sitemap_index.xml'}
Accediendo al siguiente enlace... http://news.ual.es/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'http://segoviaudaz.es/sitemap.xml'}
Accediendo al siguiente enlace... http://segoviaudaz.es/sitemap.xml
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-10.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-11.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-12.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-13.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-14.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-15.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-1.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-2.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-3.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-4.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-5.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-6.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-7.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-8.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-9.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-news-es-1.xml.gz

## Filtrar articulos por fecha

In [20]:
import pandas as pd
from datetime import datetime
import numpy as np

# Cargar la data extraída
data_df = pd.read_csv("news_output.csv")
# Fecha inicial
fecha_inicial = "2025-2-21"

data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'], format='mixed', errors='coerce', utc=True)
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'].dt.strftime("%Y-%m-%d"))
data_df = data_df[(data_df['fecha_publicacion'].between(fecha_inicial, datetime.now().strftime('%Y-%m-%d'))) | (pd.isna(data_df['fecha_publicacion']))]
data_df = data_df.sort_values(by='fecha_publicacion', ascending=False).drop_duplicates().reset_index(drop=True)
data_df

,fuente,url,titulo,fecha_publicacion
0,La Nueva España,https://www.lne.es/oriente/2025/03/02/rey-carn...,"El ""rey"" del Carnaval llega desde Gijón y se c...",2025-03-02
1,Faro de Vigo,https://www.farodevigo.es/motogp/2025/03/02/ma...,Marc Márquez gana en Tailandia y completa un d...,2025-03-02
2,Diario Córdoba,https://www.diariocordoba.com/tiempo/2025/03/0...,TIEMPO CARMONA | El tiempo en Carmona: previsi...,2025-03-02
3,Diario Córdoba,https://www.diariocordoba.com/tiempo/2025/03/0...,TIEMPO CAMAS | El tiempo en Camas: previsión m...,2025-03-02
4,Diario Córdoba,https://www.diariocordoba.com/tiempo/2025/03/0...,TIEMPO CABRA | El tiempo en Cabra: previsión m...,2025-03-02
...,...,...,...,...
58216,El Periodico de Canarias,https://www.elperiodicodecanarias.es/los-llano...,NaN,NaT
58217,El Periodico de Canarias,https://www.elperiodicodecanarias.es/gamarra-d...,NaN,NaT
58218,El Periodico de Canarias,https://www.elperiodicodecanarias.es/ucrania-o...,NaN,NaT
58219,El Periodico de Canarias,https://www.elperiodicodecanarias.es/forjando-...,NaN,NaT
58220,El Periodico de Canarias,https://www.elperiodicodecanarias.es/educacion...,NaN,NaT

In [21]:
data_df['fuente'].value_counts()

fuente
Europa Press                                         15526
Faro de Vigo                                          5392
La Razón                                              4587
Teleprensa                                            4555
El Dia                                                3713
La Opinión de Málaga                                  3712
Diario de Ibiza                                       3386
ElDiario.es                                           3071
El Comercio                                           1439
El Periódico                                          1437
Forbes                                                1197
La Cerca                                              1155
Diario Córdoba                                         981
La Rioja                                               979
El Diario Montañés                                     838
La Provincia                                           799
La Vanguardia                                          774
La Nueva España                                        728
El Confidencial                                        680
El Español                                             591
20 Minutos                                             399
Almería Noticias                                       271
Telecinco                                              265
Radiotelevisión del Principado de Asturias (RTPA)      255
Infobae                                                200
Mi Gijón                                               184
El Periodico de Canarias                               159
La Nueva Crónica                                       119
Historia National Geographic                           104
Tribuna Salamanca                                       93
SegoviAudaz                                             90
El Fielato y El Nora                                    88
La Tribuna de Albacete                                  86
Nortes                                                  85
8directo                                                71
IyMagazine                                              68
Tribuna de Ávila                                        60
Cualia                                                  29
UALNEWS                                                 17
ITG centro tecnológico                                  16
ABC                                                     13
La Voz de Galicia                                        3
Gente Digital                                            3
La Voz de Asturias                                       2
Asturias Mundial                                         1
Name: count, dtype: int64

### Eliminar enlaces duplicados

In [22]:
import os
def remover_url_duplicados(df):
    df['non_null_count'] = df.notnull().sum(axis=1)
    df = df.sort_values(by=['url', 'non_null_count'], ascending=[True, False])
    df = df.drop_duplicates(subset=['url'], keep='first')
    df = df.drop(columns=['non_null_count'])
    df = df.sort_values(by='fecha_publicacion', ascending=False).reset_index(drop=True)
    return df

data_df = remover_url_duplicados(data_df)
data_df

# Obtener la fecha actual en formato YYYY-MM-DD
fecha_hoy = datetime.today().strftime('%Y-%m-%d')

# Definir la ruta del directorio
output_dir = 'news_scraper'
os.makedirs(output_dir, exist_ok=True)

# Guardar en un archivo CSV dentro de la carpeta new_scraper
data_df.to_csv(os.path.join(output_dir, f'{fecha_hoy}.csv'), index=False)

data_df

,fuente,url,titulo,fecha_publicacion
0,Tribuna Salamanca,https://www.tribunasalamanca.com/noticias/3959...,Persecución y tiroteo en las calles de Salaman...,2025-03-02
1,La Vanguardia,https://www.lavanguardia.com/internacional/202...,"Palermo, la Cosa Nostra sigue aquí",2025-03-02
2,El Dia,https://www.eldia.es/opinion/2025/03/02/manos-...,En manos de quién estamos,2025-03-02
3,La Vanguardia,https://www.lavanguardia.com/internacional/202...,“Hemos de seguir en el frente”,2025-03-02
4,El Dia,https://www.eldia.es/opinion/2025/03/02/muerto...,OPINION: Muertos de mierda,2025-03-02
...,...,...,...,...
48311,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/asturia...,NaN,NaT
48312,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/internac...,NaN,NaT
48313,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/sociedad...,NaN,NaT
48314,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/vigo/202...,NaN,NaT
48315,El Periodico de Canarias,https://www.museosdetenerife.org/muna-museo-de...,NaN,NaT

In [23]:
data_df['fuente'].value_counts()

fuente
Europa Press                                         10538
Faro de Vigo                                          4887
Teleprensa                                            4555
La Razón                                              3873
El Dia                                                3552
La Opinión de Málaga                                  3309
Diario de Ibiza                                       3004
ElDiario.es                                           2632
Forbes                                                1197
La Cerca                                              1155
El Comercio                                           1121
El Periódico                                          1014
La Vanguardia                                          774
La Rioja                                               765
El Confidencial                                        680
El Diario Montañés                                     639
El Español                                             591
Diario Córdoba                                         545
La Nueva España                                        533
La Provincia                                           438
20 Minutos                                             399
Almería Noticias                                       271
Telecinco                                              265
Radiotelevisión del Principado de Asturias (RTPA)      255
Mi Gijón                                               182
El Periodico de Canarias                               159
La Nueva Crónica                                       119
Infobae                                                101
Historia National Geographic                            94
Tribuna Salamanca                                       93
SegoviAudaz                                             90
El Fielato y El Nora                                    87
Nortes                                                  85
8directo                                                71
Tribuna de Ávila                                        60
IyMagazine                                              56
La Tribuna de Albacete                                  43
Cualia                                                  29
UALNEWS                                                 17
ITG centro tecnológico                                  16
ABC                                                     13
Gente Digital                                            3
La Voz de Galicia                                        3
La Voz de Asturias                                       2
Asturias Mundial                                         1
Name: count, dtype: int64

In [24]:
import pandas as pd
from datetime import datetime, timedelta

# Cargar la data extraída
data_df = pd.read_csv("news_output.csv")

# Obtener la fecha de ayer y hoy
hoy = datetime.utcnow().strftime('%Y-%m-%d')
ayer = (datetime.utcnow() - timedelta(days=1)).date()

# Convertir las fechas de publicación
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'], format='mixed', errors='coerce', utc=True)

# Convertir a solo fecha (sin hora)
data_df['fecha_publicacion'] = data_df['fecha_publicacion'].dt.date

# Filtrar solo las noticias de ayer y hoy
data_df = data_df[data_df['fecha_publicacion'].isin([ayer, datetime.utcnow().date()])]

# Eliminar duplicados y ordenar por fecha de publicación
data_df = data_df.sort_values(by='fecha_publicacion', ascending=False).drop_duplicates().reset_index(drop=True)


# Guardar el CSV con la fecha de hoy en el nombre
nombre_archivo = f"{hoy}.csv"
data_df.to_csv(nombre_archivo, index=False)

# Mostrar el nombre del archivo guardado
print(f"Archivo guardado como: {nombre_archivo}")

# Mostrar el resultado
data_df

Archivo guardado como: 2025-03-02.csv

,fuente,url,titulo,fecha_publicacion
0,La Nueva España,https://www.lne.es/oriente/2025/03/02/rey-carn...,"El ""rey"" del Carnaval llega desde Gijón y se c...",2025-03-02
1,Faro de Vigo,https://www.farodevigo.es/celta-de-vigo/2025/0...,La Ponferradina pone a prueba al Celta Fortuna,2025-03-02
2,Faro de Vigo,https://www.farodevigo.es/pontevedra/2025/03/0...,La Brilat se adiestra en el hielo de Eslovaquia,2025-03-02
3,Europa Press,https://www.europapress.es/la-rioja/noticia-ma...,Marqués de Murrieta preservará el ecosistema ú...,2025-03-02
4,Europa Press,https://www.europapress.es/internacional/notic...,Alemania calibra el impacto de las elecciones ...,2025-03-02
...,...,...,...,...
12389,Europa Press,https://www.europapress.es/illes-balears/notic...,A juicio un hombre por abusar sexualmente de u...,2025-03-01
12390,Europa Press,https://www.europapress.es/galicia/noticia-ind...,"La industria automovilística gallega ve con ""p...",2025-03-01
12391,Europa Press,https://www.europapress.es/la-rioja/noticia-ma...,"Más de 300 corredores, este domingo en la 18 e...",2025-03-01
12392,Europa Press,https://www.europapress.es/deportes/motociclis...,Marc Márquez arrasa con Ducati y se impone en ...,2025-03-01
12393,Almería Noticias,https://www.almerianoticias.es/detenidos-dos-i...,NaN,2025-03-01

## Acceder al contenido de las noticias

### Extracción con request

In [ ]:
import requests
from bs4 import BeautifulSoup


# Lista de user-agents para probar
user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/W.X.Y.Z Safari/537.36"
]

def extraer_texto_articulos_request(url):
    try:
        # Primer intento sin user-agent
        response = requests.get(url)

        # Si la respuesta no es exitosa o el contenido está vacío, intente con agentes de usuario
        if response.status_code != 200 or not response.content:
            for user_agent in user_agents:
                headers = {
                    "User-Agent": user_agent,
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                    "Accept-Language": "en-US,en;q=0.5",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
                response = requests.get(url, headers=headers)

                if response.status_code == 200 and response.content:
                    #print("Encontrado con user-agent")
                    break

        html_str = response.content
        soup = BeautifulSoup(html_str, 'lxml')

        # Remover footer
        footer = soup.find('footer')
        if footer:
            footer.decompose()

        text_content = soup.find_all('p')

        text = ''
        for i in text_content:
            text += i.text.strip() + " "

        return text.strip() if text.strip() else None

    except Exception as e:
        print(f"Error in url: {url}, error: {e}")
        return None

In [ ]:
from concurrent.futures import ThreadPoolExecutor
import time

num_threads = 16

start_time = time.time()
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    data_df['texto'] = list(executor.map(extraer_texto_articulos_request, data_df['url']))
print(f"--- {(time.time() - start_time):.2f}s seconds ---")

<ipython-input-376-3475ade41072>:35: XMLParsedAsHTMLWarning: It looks like you're using an HTML parser to parse an XML document.

Assuming this really is an XML document, what you're doing might work, but you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the Python package 'lxml' installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.

If you want or need to use an HTML parser on this document, you can make this warning go away by filtering it. To do that, run this code before calling the BeautifulSoup constructor:

    from bs4 import XMLParsedAsHTMLWarning
    import warnings

    warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

  soup = BeautifulSoup(html_str, 'lxml')

--- 1999.83s seconds ---

In [ ]:
data_df

,fuente,url,titulo,fecha_publicacion,texto
0,Infobae,https://www.infobae.com/america/agencias/2024/...,"Eddy Merckx, tras romperse la cadera en bici: ...",2025-02-23,"23 Feb, 2025 Por Newsroom Infobae Bruselas, ..."
1,La Nueva España,https://www.lne.es/economia/2025/02/23/marufin...,"Marufina, los armadores que dejaron el mar par...",2025-02-23,EMPRESAS Rafael López muestra uno de los carpa...
2,Europa Press,https://www.europapress.es/murcia/noticia-prev...,"Previsión meteorológica para este domingo, 23 ...",2025-02-23,Menú Boletines Abonados MURCIA 23 Feb. (EUROPA...
3,El Comercio,https://www.elcomercio.es/cronica-negra/rastro...,El rastro sangriento del asesino en serie de T...,2025-02-23,MiComercio Mis noticias Mis intereses Newslett...
4,La Opinión de Málaga,https://www.laopiniondemalaga.es/sociedad/2025...,"El Papa pasa una noche ""tranquila"" después de ...",2025-02-23,Vaticano El papa Francisco. / EP EP El Vatica...
...,...,...,...,...,...
17091,ABC,https://www.semana.es/familia-real-espanola/de...,NaN,NaT,Ingrediente antiedad Carolina de Mónaco Marido...
17092,ABC,https://www.semana.es/familia-real-espanola/pr...,NaN,NaT,Reina Letizia Ingrediente antiedad Looks Fashi...
17093,ABC,https://www.semana.es/living/entramos-casa-osc...,NaN,NaT,Reina Letizia Ingrediente antiedad Looks Fashi...
17094,ABC,https://www.semana.es/moda/nagore-robles-a-ani...,NaN,NaT,Reina Letizia Ingrediente antiedad Looks Fashi...
17095,La Voz de Galicia,https://www.turium.es/destinos/nijar-pueblo-bl...,NaN,NaT,Newsletter Buscar en Turium NO TE PIERDAS\nEl ...

In [ ]:
data_df['texto'].isna().sum()

1435

In [ ]:
(data_df['texto'] == '').sum()

0

In [ ]:
data_df['texto'].iloc[-2]

'Reina Letizia Ingrediente antiedad Looks Fashion Week Marido Laura Madrueño  Carolina de Mónaco Iker Casillasa Pilar Molina Letizia Supervivientes Amalia de Holanda Itziar Miranda Horóscopo diario: Hoy, domingo 23 de febrero de 2025 Ya en tu quiosco Moda Redactor especializado en Moda y Belleza Actualizado a 21 de febrero de 2025, 11:18 De Nagore Robles a Anita Matamoros: los peores y mejores looks de las influencers en la primera jornada de la Madrid Fashion Week 2025 Ayer dio comienzo la Mercedes Benz Fashion Week Madrid 2025, y como cada año, las expectativas estaban por las nubes. La cosa empezó fuerte con un desfile de Baro Lucas, una auténtica declaración de intenciones que marcó el tono de lo que sería una jornada llena de talento y espectáculo. El diseñador nos dejó boquiabiertos con su capacidad de reinventar siluetas clásicas en clave contemporánea. Pero esto solo fue el aperitivo. La jornada continuó con desfiles de diseñadores de renombre: Pedro del Hierro, Álex Riviere, Menchen Tomas y, por supuesto,- y uno de nuestros favoritos-\xa0Claro Couture. Y es que la primera jornada de la MBFWM no solo es una pasarela de moda, sino también un escaparate de influencers que acuden para dar rienda suelta a las musas, listas para absorber tendencias y convertirlas en contenido viral. Estas creadoras de contenido se nutren de los desfiles no solo para inspirarse, sino también para dar visibilidad a las marcas, cerrar colaboraciones y, por supuesto, alimentar sus cuentas de Instagram con looks milimétricamente estudiados. Las influencers toman el front row de la Mercedez-Benz Fashion Week Madrid 2025 (Gtres) Claro Couture nos emocionó con una colección que se basaba en cuatro colores vibrantes: naranja, morado, turquesa y blanco. Una paleta cromática que resonó en cada prenda, envolviendo la pasarela en un aura de energía y sofisticación. Al ritmo de temazos y versiones de Rosalía, con algún que otro toque folclórico que encajó a la perfección, los diseños desfilaron con una fuerza arrolladora. Flecos con abalorios que bailaban al compás de la música, cortes imposibles que desafiaban las leyes de la geometría, plumas que añadían un toque etéreo, apliques brillantes que atrapaban la luz desde cualquier ángulo y tejidos de tul y transparencias. Todo fue sencillamente impresionante, tanto que el público no pudo contenerse y estalló en aplausos al finalizar el espectáculo. También te interesará De Sara Carbonero a Tamara Falcó: todos los looks del desfile más esperado de la Madrid Fashion Week Laura Campos Ahora bien, más allá de la creatividad de los diseñadores, la primera jornada de la MBFWM fue una auténtica pasarela de street style protagonizada por las influencers más seguidas del país. Desde Nagore Robles hasta Anita Matamoros, los looks no pasaron desapercibidos. Algunas acertaron de pleno con estilismos impecables que redefinieron la elegancia contemporánea, mientras que otras... bueno, digamos que arriesgaron demasiado. Pero, como ya sabemos, la moda es subjetiva y cada cual tiene su propia interpretación del estilo. Por eso, te invitamos a explorar nuestra galería, en la que podrás ver todos los detalles de los looks de estas creadoras de contenido que tanto influyen en las tendencias actuales. ¿Quiénes acertaron y quiénes se quedaron a medio camino? La respuesta está en el scroll. (Gtres) La pareja de influencers no pudo perderse esta cita de moda y lo hicieron con dos grandes looks. A la izquierda, Alba Paul se decantaba por una blusa blanca escotada con volantes XXL, unos pantalones vaqueros carrot, mocasines, calcetines blancos y un precioso trench en color verde militar. Por otro lado, Aida Domenech se enfundó en un dos piezas de tartán en color marrón chocolate y azul bebé, con maxisolapas, botonadura cruzada y pantalones pata de elefante que cubrían por completo sus zapatos y hacían que se viera más alta. (Gtres) La influencer se decantó por un dos piezas formado por una blazer torera negra con escote en uve y una falda mini avolantada en color blanco. Para rematar, unas sandalias finas con tiras en color nude. (Gtres) La influencer hizo gala de su gusto por lo preppy con un dos piezas formado por un top de raya diplomática y una falda larga con abertura por la que asomaban unas Adidas de charol negro y unas llamativas medias rojas. Remató con una americana efecto piel con grandes hombreras, muy ochentera, y unas gafas de pasta. (Gtres) La colaboradora de televisión se decantó por un vestido blanco con detalles negros en la zona del pecho, vivos en negro, manga corta y falda de flecos de corte midi. Este último elemento se repitió en varios looks del desfile de Claro. Sí, estamos ante una tendencia en alza. ¡Todo por los flecos! (Gtres) Ángela Rozas empezó con un total denim look formado por camiseta básica blanca, bustier sin copas de tejido tejado, unos pantalones vaqueros baggy y un abrigo con trenzas de lana blanca. Remató con unas curiosas sandalias de terciopelo dorado y un mini Jacquemus de borrego y piel dorada. (Gtres) Muy sobria, la actriz e influencer, se decantó por un top palabra de honor negro confeccionado en terciopelo y unos pantalones sastre grises. Remató con unos zapatos de cordones y un bolso shoulder negro. más'

In [ ]:
data_df.iloc[-3].values

array(['ABC',
       'https://www.semana.es/living/entramos-casa-oscar-higares-su-refugio-espacios-abiertos-salon-a-doble-altura-impresionante-jardin-y-museo-aire-libre_2794918',
       nan, NaT,
       'Reina Letizia Ingrediente antiedad Looks Fashion Week Marido Laura Madrueño  Carolina de Mónaco Iker Casillasa Pilar Molina Letizia Supervivientes Amalia de Holanda Itziar Miranda Horóscopo diario: Hoy, domingo 23 de febrero de 2025 Ya en tu quiosco Living Periodista especializada en Corazón Actualizado a 20 de febrero de 2025, 21:11 Óscar Higares en su casa de Madrid Su casa es ese refugio al que siempre volver y donde pasa la mayor parte del tiempo. Pese a tener que viajar, en numerosas ocasiones, por trabajo, Óscar Higares siempre regresa a casa. "Aunque parezca lo contrario, paso la mayor parte del tiempo en mi casa. No suelo ir a sitios donde me tenga que quedar a dormir. No viajaba a nada que me impidieran luego volver a casa", confesaba él mismo hace unos años en una entrevista. El torero, que también es actor, empresario, y ahora participante de \'Maestros de la Costura\' en su primera edición \'celebrity\', vive a caballo entre Madrid y su querido Sur, donde disfruta cada vez que puede de la preciosa casa que tiene en Chiclana de la Frontera, Cádiz. Aquella se ha convertido en un paraíso en el que disfrutar de sus "momentos de soledad, paseos por la playa...", confesaba él mismo. Pero la de Madrid también es un auténtico refugio y remanso de paz. Higares vive en el barrio madrileño de Las Rozas junto a su mujer, Sandra, y sus tres hijas,\xa0que “son su vida”. Juntos comparten una preciosa casa de estilo industrial que presume de tener espacios abiertos y en la que el torero tiene claro cuál es su rincón favorito. ¡Te la enseñamos! También te interesará Pilar Rubio se derrumba en \'Maestros de la costura Celebrity\' tras el toque de atención de Lorenzo Caprile: "La culpa es mía" Julia Alegre "Vivo en una casa que defino como cómoda y habitable, con espacios abiertos y líneas limpias", comentaba Óscar Higares en una entrevista para \'Architectural Digest\'. Su lugar favorito está en la parte baja, donde cuenta con un salón grande de dos alturas en el que ha puesto un proyector y en el que disfruta de sus ratos libres, tanto solo como en compañía de su familia. Reinan los espacios abiertos, de hecho la planta baja cuenta con salón, comedor y cocina totalmente integrados en un solo espacio. Salón de la casa de Óscar Higares tve También le guarda un especial cariño a su dormitorio. Allí, precisamente, como en el resto de la casa, combina los colores claros con el estilo especial que le otorgan materiales como\xa0el hierro o la madera de roble, especialmente para el suelo. Él mismo se ha declarado \'fan\' de los ambientes neutros, por lo que apuesta por los colores blanco y gris en la mayoría de los espacios. En su dormitorio podemos ver como integra ese toque industrial con un espejo de hierro con forma de sol que ha colocado encima de la cama, en una pared blanca. Al no tener cabecero, el espejo funciona como tal.  Una publicación compartida por Oscar Higares (@oscarhigares)  "Me gustan el estilo industrial y el\xa0mid-century", confiesa. Sin embargo, este último lo prefiere para su casa de la playa, en cambio, para la de Madrid se decanta por el primero. En su casa no falta un rinconcito especial para dedicarlo a una de sus grandes pasiones: la costura. Precisamente ahora el torero está haciendo gala de sus dotes en el \'talent\' de Televisión Española.  Una publicación compartida por Oscar Higares (@oscarhigares) Otro de sus espacios favoritos: su jardín. Se ha confesado un auténtico apasionado de los ratitos de sol, por lo que este espacio es perfecto para cargarse de vitamina D.  Una publicación compartida por Oscar Higares (@oscarhigares) Una publicación compartida de Oscar Higares (@oscarhigares) Pero si hay un espacio que centra toda la tención de su casa, ese es su \'museo\' al aire libre. Óscar Higares cuenta con un rincón en el que tiene esculturas de hierro y varios trajes de luces expuestos: "Esto nace de los cuentos que les contaba a mis hijas antes de ir a dormir, esos trajes que toman vida y decidan contarse lo que fueron, sus hazañas, aventuras...", explicaba en Televisión Española, "por eso no pueden estar metidos en un armario o un cajón". En el espacio de Televisión Española también mostraba su cocina, abierta al salón y otro de los espacios favoritos del diestro: "Me encanta cocinar, por gusto, no por obligación". Cocina de Óscar Higares TVE Así lo demostró en \'MasterChef Celebrity 3\', donde se mostró pasional e implicadísimo ante los fogones. El torero y empresario ha vuelto a Televisión Española dispuesto a demostrar que no hay nada que se le dé mal: ni los fogones ni las máquinas de coser, a Óscar Higares no hay reto que se le resista. De momento, continúa conquistando al público y a los jueces... Las primeras semanas del \'talent\' vimos como Silvia Superstar y Rosa López se convertían en las expulsadas.\xa0De los diez\xa0concursantes que quedan; Edu Soto, Canco Rodríguez, Laura Sánchez, Oscar Higares, María Esteve, Carmen Farala, Eduardo Casanova, Pilar Rubio, La Terremoto y Mónica Cruz,\xa0semana a semana, uno de ellos se convertirá en el expulsado.  más'],
      dtype=object)

## Filtrar textos

### Buscar textos que tengan al menos una palabra clave

In [ ]:
# Filtrar por palabras clave
keywords = ['universidad', 'oviedo']

# Regex pattern
pattern = '|'.join(keywords)

# Filtrar dataframe
filtered_df = data_df[data_df['texto'].str.contains(pattern, case=False, na=False)].reset_index(drop=True)

filtered_df

,fuente,url,titulo,fecha_publicacion,texto
0,La Opinión de Málaga,https://www.laopiniondemalaga.es/sociedad/2025...,Más parcialidad y menos sueldo: al ritmo actua...,2025-02-23,DESIGUALDAD Las mujeres trabajan gratis varios...
1,La Vanguardia,https://www.lavanguardia.com/cultura/culturas/...,Más divertido que ver cómo se seca la pintura,2025-02-23,Cultura|s Una escena de 'Paint Draying' Begoña...
2,La Nueva España,https://www.lne.es/deportes/deporte-astur/2025...,El Vetusta reina en el derbi ovetense del grup...,2025-02-23,El jugador del Vetusta Carbajo lanza a la port...
3,La Nueva España,https://www.lne.es/deportes/deporte-astur/2025...,El Universidad remonta en Ávila (89-94) y se a...,2025-02-23,Gran triunfo en el que consiguió anoche el Uni...
4,La Nueva España,https://www.lne.es/deportes/deporte-astur/2025...,El Club Bádminton Oviedo gana al Alicante y ju...,2025-02-23,"Por la izquierda, Nicolás García, Yelozabeta, ..."
...,...,...,...,...,...
2902,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/yes/2025...,NaN,NaT,"Año 2024, primero de bachillerato en una clase..."
2903,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/yes/2025...,NaN,NaT,Luz llevaba 13 años de relación con su anterio...
2904,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/yes/2025...,NaN,NaT,Un ejemplo para los que se sorprenden por la e...
2905,La Voz de Galicia,https://www.lavozdegalicia.es/xlsemanal/cienci...,NaN,NaT,Récord submarino https://www.lavozdegalicia.es...
2906,La Voz de Galicia,https://www.lavozdegalicia.es/xlsemanal/natura...,NaN,NaT,Pon a prueba tu olfato https://www.lavozdegali...

In [ ]:
filtered_df['url'].values[0:100]

array(['https://www.laopiniondemalaga.es/sociedad/2025/02/23/parcialidad-sueldo-ritmo-actual-espana-114594185.html',
       'https://www.lavanguardia.com/cultura/culturas/20250223/10393586/mas-divertido-ver-como-seca-pintura.html',
       'https://www.lne.es/deportes/deporte-astur/2025/02/23/vetusta-reina-derbi-ovetense-grupo-114591063.html',
       'https://www.lne.es/deportes/deporte-astur/2025/02/23/universidad-remonta-avila-89-94-114591071.html',
       'https://www.lne.es/deportes/deporte-astur/2025/02/23/club-badminton-oviedo-gana-alicante-114591072.html',
       'https://www.lne.es/deportes/deporte-astur/2025/02/23/lobas-le-sobra-ultima-jugada-114591070.html',
       'https://www.lne.es/deportes/deporte-astur/2025/02/23/lucas-langarita-experiencia-seleccion-espanola-114591420.html',
       'https://www.lne.es/gijon/2025/02/23/proxima-semana-negra-memoria-angel-114591417.html',
       'https://www.lne.es/gijon/2025/02/23/abraham-menendez-ilustrador-estrellas-cine-114592935.html',
       'https://www.lne.es/gijon/2025/02/23/valientes-continuan-haciendo-latir-comercio-114592922.html',
       'https://www.lavanguardia.com/comprar/rebajas-ofertas/20250223/10406997/chollos-dia-amazon-23-febrero-24-50-descuento.html',
       'https://www.lne.es/gijon/gijon-oeste/2025/02/23/codigo-administrativo-prometer-cargo-toma-114592883.html',
       'https://www.lne.es/gijon/gijon-oeste/2025/02/23/cuatro-anos-he-tratado-presidencialista-114592931.html',
       'https://www.lne.es/gijon/opinion/2025/02/23/esther-gomez-talante-bondad-114589879.html',
       'https://www.elespanol.com/ciencia/salud/20250223/dia-hora-quimio-influye-mes-estacion-ano-tratamiento-cancer/925907895_0.html',
       'https://www.lne.es/espana/2025/02/23/asistente-begona-gomez-juez-peinado-cuarta-imputada-tras-declarar-testigo-114595751.html',
       'https://www.lavanguardia.com/cultura/20250223/10409624/andres-orozco-estrada-jardinero-fiel-clasica-ibercamera-entrevista.html',
       'https://www.elconfidencial.com/el-tiempo/2025-02-23/el-tiempo-en-siero-domingo_4071263/',
       'https://www.elespanol.com/alicante/elda/20250223/villena-cumple-anos-titulo-ciudad-efemeride-mirar-futuro-celebrar-presente/925407930_0.html',
       'https://www.lne.es/asturias/2025/02/23/cgpj-busca-perfil-penalista-plaza-114592607.html',
       'https://www.lne.es/asturias/2025/02/23/cronistas-oficiales-asturianos-quieren-implantar-114592597.html',
       'https://www.lne.es/asturias/2025/02/23/guia-perderse-polemica-parques-baterias-114588061.html',
       'https://www.lne.es/asturias/2025/02/23/hay-presiones-acabar-liderazgo-medicos-114592545.html',
       'https://www.lne.es/asturias/2025/02/23/numero-academia-mir-deja-puesto-114592544.html',
       'https://www.lne.es/asturias/2025/02/23/parques-eolicos-barbecho-instalado-asturias-114588219.html',
       'https://www.lne.es/asturias/2025/02/23/peticiones-cientificos-asturianos-nota-ponen-114588941.html',
       'https://www.lne.es/asturias/2025/02/23/principado-impulsa-nuevas-exhumaciones-represaliados-114592598.html',
       'https://www.elconfidencial.com/el-tiempo/2025-02-23/el-tiempo-en-oviedo-domingo_4071262/',
       'https://www.lne.es/cuencas/2025/02/23/sebastian-alvaro-rojo-impenitente-cumbre-114587765.html',
       'https://www.lne.es/aviles/2025/02/23/inversion-global-aviles-supera-150-114588767.html',
       'https://www.lne.es/aviles/2025/02/23/jose-ramon-rodriguez-cronista-corvera-114588900.html',
       'https://www.lne.es/aviles/2025/02/23/manuel-herminio-garcia-existe-sola-114588299.html',
       'https://www.larazon.es/salud/cura-ceguera-made-spain_2025022367b6127e500f9600011258dc.html',
       'https://www.lne.es/siero/siero-opinion/2025/02/23/llegado-momento-114595038.html',
       'https://www.elespanol.com/espana/politica/20250223/motosierra-espanola-recortar-no-siga-arruinando-ciudadanos/924157847_0.html',
       'https://www.lne.es/sociedad/2025/02/23/agenda-asturias-hoy-domingo-23-114592083.html',
       'https://www.lne.es/sociedad/2025/02/23/parcialidad-sueldo-ritmo-actual-espana-114594174.html',
       'https://www.larazon.es/sociedad/asi-fabrica-deportista-elite_2025022367ba7fe6500f960001163fde.html',
       'https://www.elespanol.com/invertia/disruptores/grandes-actores/investigacion/20250223/flexible-biocompatible-invisible-revolucion-sensores-grafeno-lideraluigi-occhipinti/924907978_0.html',
       'https://www.elespanol.com/invertia/disruptores/opinion/20250223/shenzhen-silicon-valley-ganara-guerra-talento-ia/925527439_12.html',
       'https://www.elespanol.com/invertia/disruptores/opinion/20250223/tecnologia-frente-desafios-geopoliticos-sxxi/925777420_12.html',
       'https://www.elespanol.com/invertia/disruptores/politica-digital/espana/20250223/salarios-competitivos-cambio-especializacion-ia-busca-expertos-regulacion-ciberseguridad/924157765_0.html',
       'https://www.lne.es/oviedo/opinion/2025/02/23/cosas-uria-114592758.html',
       'https://www.elconfidencial.com/espana/2025-02-23/ano-caso-begona-exclusivas-destaparon-agenda-secreta-mujer-sdanchez_4071010/',
       'https://www.elconfidencial.com/espana/2025-02-23/monedero-complutense-sancion-acoso-sexual-alumnas_4070777/',
       'https://www.lne.es/mas-domingo/2025/02/23/asalto-cuartel-santa-clara-114541232.html',
       'https://www.20minutos.es/tecnologia/aplicaciones/como-evitar-anadan-grupos-whatsapp-sin-permiso-5678016/',
       'https://www.lne.es/opinion/2025/02/23/puttering-114589753.html',
       'https://www.larazon.es/sociedad/sede-vacante-impedida-francisco-gobierna-gemelli_2025022367ba7e93500f960001163f24.html',
       'https://www.lne.es/oviedo/2025/02/23/candidatura-capital-cultural-oviedo-cita-114592633.html',
       'https://www.lne.es/oviedo/2025/02/23/dia-jovenes-descubrieron-america-oviedo-114592790.html',
       'https://www.lne.es/oviedo/2025/02/23/gabino-lorenzo-rompe-siete-anos-114538012.html',
       'https://www.lne.es/oviedo/2025/02/23/hay-quiere-ver-zarzuela-vio-114591408.html',
       'https://www.lne.es/oviedo/2025/02/23/historia-fidela-o-vivir-enfermedad-114588194.html',
       'https://www.lne.es/oviedo/2025/02/23/honores-45-anos-taller-3-114592792.html',
       'https://www.lne.es/oviedo/2025/02/23/medio-siglo-servicio-policial-prueba-114592674.html',
       'https://www.lne.es/oviedo/2025/02/23/ovetense-torero-ahora-truhan-senor-114592791.html',
       'https://www.lne.es/oriente/2025/02/23/humor-mejor-medicina-receta-doctor-114572698.html',
       'https://www.elconfidencial.com/cultura/2025-02-23/una-protestante-americana-y-una-catolica-gallega-dos-mujeres-que-cambiaron-la-educacion-en-espana_4069505/',
       'https://www.laopiniondemalaga.es/nacional/2025/02/23/asistente-begona-gomez-juez-peinado-cuarta-imputada-tras-declarar-testigo-114595730.html',
       'https://www.lavanguardia.com/internacional/20250223/10411427/estados-unidos-trump-musk-democracia.html',
       'https://www.lavanguardia.com/deportes/futbol/20250223/0/laliga-segunda-division-2024-2025-calendario-horario-partidos-ca-jornada-28-ctx.html',
       'https://www.lavanguardia.com/deportes/futbol/20250223/0/laliga-segunda-division-2024-2025-pichichi-maximo-asistente-ca-jornada-28-ctx.html',
       'https://www.lavanguardia.com/deportes/futbol/20250223/16062/horario-partido-ca-levante-mirandes-ctx.html',
       'https://www.lavanguardia.com/deportes/futbol/20250223/16046/horario-partido-ca-rc-deportivo-huesca-ctx.html',
       'https://www.lavanguardia.com/deportes/futbol/20250223/16023/horario-partido-ca-albacete-eldense-ctx.html',
       'https://www.elconfidencial.com/alma-corazon-vida/2025-02-23/doctora-vision-truco-gratis-miopia-mejorar-1qrt_4068649/',
       'https://www.infobae.com/salud/2025/02/24/el-superalimento-amazonico-que-trae-beneficios-para-el-metabolismo-y-el-corazon/',
       'https://www.laopiniondemalaga.es/economia/empresas-malaga/2025/02/23/liceo-frances-internacional-excelencia-educativa-114558991.html',
       'https://www.laopiniondemalaga.es/economia/empresas-malaga/2025/02/23/estudiar-levels-alternativa-instituto-114559062.html',
       'https://www.laopiniondemalaga.es/economia/empresas-malaga/2025/02/23/entrevista-cristobal-alonso-114556896.html',
       'https://www.laopiniondemalaga.es/malaga/2025/02/23/regularan-aguas-subterraneas-acabar-pozos-ilegales-114579068.html',
       'https://www.lavanguardia.com/economia/20250223/10413196/jefe-tecnoplutocratas.html',
       'https://www.laopiniondemalaga.es/libros/2025/02/23/amor-contamindo-historia-nothomb-114581139.html',
       'https://www.elconfidencial.com/deportes/otros-deportes/2025-02-23/mercedes-coghen-hocky-alejandro-blanco-noos_4069724/',
       'https://www.elconfidencial.com/economia/2025-02-23/mitad-de-pymes-desconfia-de-la-reduccion-de-jornada_4068605/',
       'https://www.infobae.com/america/agencias/2024/12/10/el-uso-de-vacunas-conjugadas-frente-al-neumococo-puede-prevenir-las-infecciones-en-forma-de-biofilms/',
       'https://www.infobae.com/america/agencias/2024/12/10/el-turismo-dispara-su-contribucion-al-cambio-climatico/',
       'https://www.lne.es/asturias-exterior/2025/02/23/risto-moscon-vuela-alto-hockey-114589407.html',
       'https://www.elconfidencial.com/el-tiempo/2025-02-23/el-tiempo-en-leon-domingo_4071244/',
       'https://www.elconfidencial.com/el-tiempo/2025-02-23/el-tiempo-en-gijon-domingo_4071261/',
       'https://www.infobae.com/america/mundo/2025/02/23/rabino-abraham-cooper-el-conflicto-palestino-israeli-ya-no-tiene-poder-de-veto-sobre-la-paz-en-medio-oriente/',
       'https://www.infobae.com/espana/agencias/2025/02/23/el-lider-de-ugt-participa-en-el-tradicional-homenaje-a-manuel-llaneza-en-mieres-asturias/',
       'https://www.infobae.com/espana/agencias/2024/12/10/tres-responsables-de-contratacion-y-gestion-economica-de-la-ucm-comparecen-manana-en-la-comision-de-investigacion/',
       'https://www.infobae.com/america/agencias/2024/12/10/pew-financia-ocho-equipos-para-realizar-una-investigacion-biomedica-colaborativa/',
       'https://migijon.com/2025/02/', 'https://migijon.com',
       'https://www.larazon.es/economia/casi-70-pais-cesiones-fiscales-cataluna_2025022367ba7f36b1a8db0001d182a3.html',
       'https://www.larazon.es/deportes/raducanu-seles-deportistas-terror-acoso_2021050267bac4bab1a8db0001d19ee1.html',
       'https://migijon.com/2025/02/page/29/',
       'https://migijon.com/2025/02/page/13/',
       'https://migijon.com/2025/02/page/22/',
       'https://migijon.com/2025/02/page/2/',
       'https://migijon.com/2025/02/page/19/',
       'https://migijon.com/2025/02/page/14/',
       'https://www.larazon.es/deportes/hugo-gonzalez-ganar-mundial-ano-olimpico-lleve-nada_2025022367b8b7d4417ec2000101bef5.html',
       'https://www.larazon.es/deportes/futbol/palmas-barcelona-directo-hoy-jornada-25-laliga-vivo-online_2025022267b8827eb1a8db0001d04edd.html',
       'https://www.elperiodico.com/es/ciencia/20250223/hay-montanas-valles-centro-tierra-114467805',
       'https://migijon.com/2025/02/page/28/',
       'https://www.larazon.es/espana/dia-noche-cuchillos-largos-izquierda_2025022367ba1f43b1a8db0001d15191.html'],
      dtype=object)

## Buscar textos que tengan todas las palabras clave

In [ ]:
# Lista de palabras clave
keywords = ['universidad', 'oviedo']

# Crear una condición de filtro para cada palabra clave
filter_condition = data_df['texto'].str.contains(keywords[0], case=False, na=False)

for keyword in keywords[1:]:
    filter_condition &= data_df['texto'].str.contains(keyword, case=False, na=False)

# Aplicar filtro
filtered_df_all = data_df[filter_condition].reset_index(drop=True)

filtered_df_all

,fuente,url,titulo,fecha_publicacion,texto
0,La Opinión de Málaga,https://www.laopiniondemalaga.es/sociedad/2025...,Más parcialidad y menos sueldo: al ritmo actua...,2025-02-23,DESIGUALDAD Las mujeres trabajan gratis varios...
1,La Nueva España,https://www.lne.es/deportes/deporte-astur/2025...,El Universidad remonta en Ávila (89-94) y se a...,2025-02-23,Gran triunfo en el que consiguió anoche el Uni...
2,La Nueva España,https://www.lne.es/gijon/2025/02/23/abraham-me...,"Abraham Menéndez, el ilustrador de las estrell...",2025-02-23,La figura de la semana El ilustrador de las es...
3,La Nueva España,https://www.lne.es/asturias/2025/02/23/guia-pe...,POLÉMICAS PARQUES DE BATERÍAS | Guía para no p...,2025-02-23,Parques de baterías en Asturias Xuan Fernández...
4,La Nueva España,https://www.lne.es/asturias/2025/02/23/peticio...,LEY DE CIENCIA ASTURIAS | Las peticiones de lo...,2025-02-23,alarmLas peticiones de los científicos asturia...
...,...,...,...,...,...
129,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/oviedo/...,NaN,NaT,La Consejería de Educación inaugurará el próxi...
130,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/oviedo/...,NaN,NaT,Andrew Silin y Kate Yakusheva se conocían de c...
131,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/siero/2...,NaN,NaT,"El alcalde de Siero, Ángel García, se ha mostr..."
132,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/turismo...,NaN,NaT,La Comarca Vaqueira toma su nombre de los vaqu...
133,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/turismo...,NaN,NaT,El concejo de Oviedo tiene en su corazón la ci...

In [ ]:
def mostrar_informacion(data_df):

    for index, fila in data_df.iterrows():
        if pd.isna(fila['fecha_publicacion']):
            fecha = 'Desconocido'
        else:
            fecha = fila['fecha_publicacion'].strftime('%Y/%m/%d')
        fuente = fila['fuente']

        titulo = 'Desconocido'
        if pd.notna(fila['titulo']):
            titulo = fila['titulo']

        print(titulo)
        print(fila['url'])
        print(f'{fecha} - {fuente}')
        print()

mostrar_informacion(filtered_df_all)

Más parcialidad y menos sueldo: al ritmo actual, España tardará 32 años en cerrar la brecha salarial de género
https://www.laopiniondemalaga.es/sociedad/2025/02/23/parcialidad-sueldo-ritmo-actual-espana-114594185.html
2025/02/23 - La Opinión de Málaga

El Universidad remonta en Ávila (89-94) y se acerca al segundo puesto
https://www.lne.es/deportes/deporte-astur/2025/02/23/universidad-remonta-avila-89-94-114591071.html
2025/02/23 - La Nueva España

Abraham Menéndez, el ilustrador de las estrellas de cine que adora pasear por el Muro
https://www.lne.es/gijon/2025/02/23/abraham-menendez-ilustrador-estrellas-cine-114592935.html
2025/02/23 - La Nueva España

POLÉMICAS PARQUES DE BATERÍAS | Guía para no perderse en la polémica de los parques de baterías en Asturias: qué son y por qué no se para de hablar de ellos
https://www.lne.es/asturias/2025/02/23/guia-perderse-polemica-parques-baterias-114588061.html
2025/02/23 - La Nueva España

LEY DE CIENCIA ASTURIAS | Las peticiones de los científicos asturianos y la nota que ponen a la nueva ley de Ciencia: "Tenemos demasiado papeleo"
https://www.lne.es/asturias/2025/02/23/peticiones-cientificos-asturianos-nota-ponen-114588941.html
2025/02/23 - La Nueva España

Jose Ramón Rodríguez, cronista de Corvera: "Quiero investigar más de la represión franquista en Corvera"
https://www.lne.es/aviles/2025/02/23/jose-ramon-rodriguez-cronista-corvera-114588900.html
2025/02/23 - La Nueva España

Más parcialidad y menos sueldo: al ritmo actual, España tardará 32 años en cerrar la brecha salarial de género
https://www.lne.es/sociedad/2025/02/23/parcialidad-sueldo-ritmo-actual-espana-114594174.html
2025/02/23 - La Nueva España

COLEGIO AMÉRICA OVIEDO | El día que unos jóvenes descubrieron el América en Oviedo: de vuelta a la residencia universitaria
https://www.lne.es/oviedo/2025/02/23/dia-jovenes-descubrieron-america-oviedo-114592790.html
2025/02/23 - La Nueva España

El humor, la mejor medicina: la receta del doctor José Antonio Flórez para una vida larga y plena
https://www.lne.es/oriente/2025/02/23/humor-mejor-medicina-receta-doctor-114572698.html
2025/02/23 - La Nueva España

Desconocido
https://migijon.com/2025/02/page/30/
2025/02/23 - Mi Gijón

Desconocido
https://migijon.com/2025/02/page/34/
2025/02/23 - Mi Gijón

Desconocido
https://migijon.com/2025/02/page/31/
2025/02/23 - Mi Gijón

Más parcialidad y menos sueldo: al ritmo actual, España tardará 32 años en cerrar la brecha salarial de género
https://www.eldia.es/sociedad/2025/02/23/parcialidad-sueldo-ritmo-actual-espana-114594184.html
2025/02/23 - El Dia

Más parcialidad y menos sueldo: al ritmo actual, España tardará 32 años en cerrar la brecha salarial de género
https://www.laprovincia.es/sociedad/2025/02/23/parcialidad-sueldo-ritmo-actual-espana-114594180.html
2025/02/23 - La Provincia

Desconocido
https://www.nortes.me/2025/02/22/los-neonazis-trasladan-a-oviedo-su-homenaje-al-23f/
2025/02/22 - Nortes

Desconocido
https://www.nortes.me/2025/02/22/taller-3-una-historia-de-arte-educacion-y-democracia/
2025/02/22 - Nortes

Desconocido
https://www.nortes.me/articulos-recientes/
2025/02/22 - Nortes

Desconocido
https://www.rtpa.es/audio:Un-buen-dia-para-viajar_1740223499.html
2025/02/22 - Radiotelevisión del Principado de Asturias (RTPA)

Los derechos humanos en el cine, a debate en San Pedro
https://www.lne.es/gijon/2025/02/22/derechos-humanos-cine-debate-san-114568498.html
2025/02/22 - La Nueva España

El Círculo Gijón Baloncesto, de prestado en el ovetense polideportivo de Pumarín
https://www.lne.es/deportes/deporte-astur/2025/02/22/circulo-gijon-baloncesto-prestado-ovetense-114565533.html
2025/02/22 - La Nueva España

El RIDEA acoge desde este jueves un ciclo sobre el yacimiento llanerense de Lucus Asturum
https://www.lne.es/llanera/2025/02/22/real-instituto-estudios-asturianos-acoge-114589321.html
2025/02/22 - La Nueva España

¿Cuál será el futuro de los socialistas ovetenses? La AMSO, entre persistir o virar
https://www.lne.es/oviedo/2025/02/22/sera-futuro-socialistas-ovetenses-amso-114568123.html
2025/02/22 - La Nueva España

"Mi padre me vio nacer detenido por un guardia  y un falangista que le iban a  ‘dar el paseo’"
https://www.lne.es/oviedo/2025/02/22/padre-vio-nacer-detenido-guardia-114083627.html
2025/02/22 - La Nueva España

¿Qué hacen más de 130 universitarios de toda España discutiendo en Oviedo? Un torneo para elevar la voz
https://www.lne.es/oviedo/2025/02/22/130-universitarios-espana-discutiendo-oviedo-114568205.html
2025/02/22 - La Nueva España

Pasión por la lírica para analizar desde Salamanca el estado del repertorio en España
https://www.tribunasalamanca.com/noticias/394948/pasion-por-la-lirica-para-analizar-desde-salamanca-el-estado-del-repertorio-en-espana
2025/02/22 - Tribuna Salamanca

Duro rifirrafe entre el gobierno y Vox por la vivienda
https://www.lne.es/aviles/2025/02/22/duro-rifirrafe-gobierno-vox-vivienda-114564838.html
2025/02/22 - La Nueva España

El Rotary Club otorga el premio "Mujer Trabajadora" del año a Ángeles Rivero, directora general de LA NUEVA ESPAÑA
https://www.lne.es/asturias/2025/02/22/rotary-club-otorga-premio-mujer-114567694.html
2025/02/22 - La Nueva España

Sin miedo a las alturas
https://www.lne.es/asturias-exterior/2025/02/22/miedo-alturas-114584299.html
2025/02/22 - La Nueva España

La revolución cultural de los ochenta
https://www.eldiario.es/comunitat-valenciana/el-tilo/revolucion-cultural-ochenta_132_12075414.html
2025/02/22 - ElDiario.es

España no es país para doctores: el número de tesis aprobadas se reduce un 44% desde 2016 por la precariedad y los abusos
https://www.elespanol.com/ciencia/20250222/espana-no-pais-doctores-numero-tesis-aprobadas-reduce-precariedad-abusos/925907810_0.html
2025/02/22 - El Español

Iñaki Cañal toma el mando para la final de los 400 en el Nacional
https://www.elcomercio.es/deportes/atletismo/inaki-canal-toma-mando-final-400-nacional-20250223225243-nt.html
2025/02/22 - El Comercio

«Salir fuera te hace romper con la timidez»
https://www.elcomercio.es/asturianos-por-el-mundo/salir-romper-timidez-20250223223824-nt.html
2025/02/22 - El Comercio

«Vamos a tener unos 30 parques de baterías, son necesarias, pero tienen sus riesgos»
https://www.elcomercio.es/asturias/vamos-tener-parques-baterias-necesarias-riesgos-20250223224008-nt.html
2025/02/22 - El Comercio

«Entre todos hemos hecho que la historia del Colegio Mayor América sea grande»
https://www.elcomercio.es/oviedo/historia-colegio-mayor-america-grande-20250223230402-nt.html
2025/02/22 - El Comercio

Nieves Roqueñí, una presidenta del Puerto de Gijón «abrumada de ver aquí a tantos amigos»
https://www.elcomercio.es/gijon/nieves-roqueni-presidenta-puerto-gijon-amigos-familia-20250222210930-nt.html
2025/02/22 - El Comercio

El Rector pide un compromiso inversor "serio" para la ley de Ciencia
https://www.lne.es/asturias/2025/02/21/rector-pide-compromiso-inversor-serio-114559649.html
2025/02/21 - La Nueva España

Desconocido
https://www.lne.es/siero/2025/02/21/rector-universidad-oviedo-dispuesto-avanzar-114547345.html
2025/02/21 - La Nueva España

Noelia Rico presentará su plan de trabajo para el centro de IA
https://www.elcomercio.es/area-metropolitana-asturias/siero-centro/noelia-rico-presentara-plan-trabajo-centro-ia-20250222223016-nt.html
2025/02/21 - El Comercio

Gijón estrenará unas jornadas contra el acoso escolar: estas son las charlas que se impartirán, abiertas para todo el público
https://www.lne.es/gijon/2025/02/21/gijon-estrenara-jornadas-acoso-escolar-114561917.html
2025/02/21 - La Nueva España

Susana Madera, una guardiana del medio ambiente con raíces mineras
https://www.elcomercio.es/asturias/susana-madera-guardiana-medio-ambiente-raices-mineras-20250222223118-nt.html
2025/02/21 - El Comercio

La Universidad despide el encuentro Ingenium: «Llevad lejos lo aprendido esta semana»
https://www.elcomercio.es/asturias/universidad-despide-encuentro-ingenium-llevad-lejos-aprendido-20250222223114-nt.html
2025/02/21 - El Comercio

Desconocido
https://www.lne.es/gijon/2025/02/21/emtusa-estrena-primeros-seis-autobuses-114547133.html
2025/02/21 - La Nueva España

«La Ley de Ciencia de Asturias es ambiciosa, pero si no hay un compromiso económico serio puede ser papel mojado»
https://www.elcomercio.es/asturias/ley-ciencia-asturias-ambiciosa-ignacio-villaverde-universidad-oviedo-20250221154943-nt.html
2025/02/21 - El Comercio

«La Ley de Ciencia debe tener detrás un compromiso económico serio»
https://www.elcomercio.es/asturias/ley-ciencia-debe-tener-detras-compromiso-economico-20250222223108-nt.html
2025/02/21 - El Comercio

Desconocido
https://www.elcomercio.es/oviedo/antiguos-alumnos-colegio-mayor-america-miguel-cuesta-20250221080826-nt.html
2025/02/21 - El Comercio

Recoletas Carbajosa encara la visita al líder lastrado por las lesiones
https://www.tribunasalamanca.com/noticias/394921/recoletas-carbajosa-encara-la-visita-al-lider-lastrado-por-las-lesiones
2025/02/21 - Tribuna Salamanca

La sierense Susana Madera será la nueva viceconsejera de Medio Ambiente
https://www.rtpa.es/noticias-asturias/2025-02-21/La-sierense-Susana-Madera-sera-la-nueva-viceconsejera-de-Medio-Ambiente_111740125730.html
2025/02/21 - Radiotelevisión del Principado de Asturias (RTPA)

Desconocido
https://www.nortes.me/2025/02/21/video-entrevista-con-juan-ponte-sobre-su-libro-el-capitalismo-no-existe/
2025/02/21 - Nortes

Desconocido
https://www.nortes.me/2025/02/21/una-estatua-para-el-rector-alas/
2025/02/21 - Nortes

Universidad de Deusto en Bilbao acoge este sábado la fase regional de la Olimpiada sobre la Unión Europea
https://www.europapress.es/euskadi/noticia-universidad-deusto-bilbao-acoge-sabado-fase-regional-olimpiada-union-europea-20250221140825.html
2025/02/21 - Europa Press

Desconocido
https://www.larazon.es/asturias/fernando-laserna-cocina-nombrado-nuevo-fiscal-delegado-comunidad-autonoma-personas-discapacidad-mayores_2025022167b7b4e5500f9600011436eb.html
2025/02/21 - La Razón

<![CDATA[¿Quién era Alfredo Brañas, el ejemplo que el PP pone como modelo de unidad y respeto?]]>
https://www.larazon.es/galicia/quien-era-alfredo-branas-ejemplo-que-pone-como-modelo-unidad-respeto-p7m_2025022167b868cc417ec20001013b82.html
2025/02/21 - La Razón

Drones para estudiar a las carabelas portuguesas y predecir su llegada a la costa de Gran Canaria
https://www.eldiario.es/canariasahora/ciencia_y_medio_ambiente/drones-estudiar-carabelas-portuguesas-predecir-llegada-costa-gran-canaria_1_12073769.html
2025/02/21 - ElDiario.es

Desconocido
https://www.elfielato.es/articulo/comarca-picos-de-europa/usana-madera-viceconsejera-medio-ambiente/20250221173329075537.html
2025/02/21 - El Fielato y El Nora

Desconocido
http://www.asturiasmundial.com/noticia/111057/peter-burke-id-arcelormittal-gregory-ludkovsky-honoris-causa-por-oviedo/#.XcBLIdT1TaQ.tumblr
Desconocido - Asturias Mundial

Desconocido
http://www.asturiasmundial.com/noticia/139005/asturias-consolida-como-referente-computacion-cuantica-avances-clave-simulacion-aplicaciones-empresariales/
Desconocido - Asturias Mundial

Desconocido
http://www.asturiasmundial.com/noticia/139025/aguas-aviles-lanza-plan-estrategico-resencialr-30-medidas-transformar-gestion-agua-ciudad/
Desconocido - Asturias Mundial

Desconocido
http://www.gentedigital.es/albacete/noticia/4005052/una-marcha-en-albacete-dara-10-millones-de-pasos-y-recaudara-3000-euros-para-reparar-el-restaurante-el-buho-de-letur/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/albacete/noticia/4006825/uclm-acoge-en-albacete-el-i-congreso-internacional-sobre-la-enfermedad-neurodegenerativa-demencia-con-cuerpos-de-lewy/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4006757/el-cenid-presenta-un-metodo-para-agilizar-procesos-administrativos-mediante-automatizacion-e-ia/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4007606/un-estudio-de-csic-umh-revela-un-mecanismo-clave-para-controlar-la-actividad-que-regula-la-identidad-neuronal/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4008564/investigadores-de-la-ua-reutilizan-residuos-de-posidonia-oceanica-para-recuperar-el-sabor-del-tomate/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4008669/hydros-power-del-parque-cientifico-de-la-ua-capta-190000-euros-del-instituto-de-tecnologia-europeo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4009028/elvira-lindo-proxima-invitada-del-club-de-lectura-mestres-de-la-ua/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4009031/dos-proyectos-de-la-umh-demuestran-la-viabilidad-de-reutilizar-la-paja-del-arroz-en-calzado-y-cosmetica/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/almeria/noticia/4009492/un-total-de-170-ninos-participan-en-la-first-lego-league-de-la-ual-para-impulsar-las-ramas-cientificas/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/avila/noticia/4005365/la-ucav-bate-record-de-participacion-en-el-85-encuentro-de-universitarios-con-mas-de-170-participantes/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/avila/noticia/4007892/la-ucav-aborda-en-unas-jornadas-la-proteccion-de-la-naturaleza-en-el-ambito-policial/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/burgos/noticia/4003371/proteccion-civil-de-burgos-se-centra-en-2024-en-la-concienciacion-en-seguridad-en-los-centros-escolares/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cartagena/noticia/4009244/murcia-acoge-el-martes-el-i-congreso-de-educacion-inclusiva-inclu-yo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cartagena/noticia/4009326/el-parque-principe-de-asturias-de-san-javier-sostenibilidad-entretenimiento-y-homenaje-a-su-tradicion-aeronautica/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ciudad-real/noticia/4007043/rozalen-y-la-unidad-militar-de-emergencias-entre-los-reconocimientos-del-consejo-social-de-la-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cordoba/noticia/4009001/la-proyeccion-del-documental-la-vida-en-una-gota-pone-el-foco-en-el-diagnostico-precoz-de-enfermedades-raras/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/gijon/noticia/4008117/diaz-avanza-una-futura-ley-de-democracia-en-la-empresa-basada-en-propuestas-de-expertos-uno-de-la-universidad-de-oviedo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/granada/noticia/4009212/fundacion-descubre-muestra-la-ineficienciade-los-protectores-microclimaticos-para-mejorar-el-desarrollo-de-las-encinas/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/guadalajara/noticia/4005020/c-lm-tendra-lista-antes-de-semana-santa-la-estrategia-para-blindar-la-gratuidad-del-primer-ano-de-matricula-en-la-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/guadalajara/noticia/4005186/video-c-lm-tendra-lista-antes-de-semana-santa-la-estrategia-para-blindar-gratuidad-del-primer-ano-de-matricula-en-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4008100/el-proyecto-bioecon4fish-incorpora-la-dimension-economica-y-social-a-la-pesqueria-del-boqueron-en-el-golfo-de-cadiz/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4008222/rosa-maria-leon-y-rosario-marquez-reciben-el-premio-a-la-excelencia-investigadora-jose-luis-garcia-palacios/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4009456/la-uhu-acoge-un-encuentro-con-24-representantes-de-las-universidades-publicas-para-fortalecer-la-alianza-europea/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ibiza/noticia/4006628/educacion-gestionara-la-cobertura-de-las-plazas-de-los-ates-a-partir-de-septiembre/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ibiza/noticia/4006894/el-govern-inicia-las-obras-de-ampliacion-del-ceip-can-misses-de-ibiza/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/jaen/noticia/4008250/ccoo-se-moviliza-contra-los-incumplimientos-reiterados-de-la-junta-en-el-sistema-universitario-publico/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/jaen/noticia/4008698/unia--la-sede-de-la-unia-acoge-una-conferencia-sobre-antonio-machado-y-baeza/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/lleida/noticia/4001508/lleidanet-firma-contratos-de-672000-euros-en-colombia-y-peru-en-el-tercer-trimestre-de-2024/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/logrono/noticia/4009239/el-programa-erasmus-rural-busca-entidades-de-zonas-con-problemas-de-despoblacion-para-acoger-a-alumnos-de-grado-y-master/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/logrono/noticia/4009440/abierto-el-plazo-de-inscripcion-para-el-campamento-de-verano-para-menores-con-altas-capacidades-summer-camp-ur/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/malaga/noticia/4009257/la-profesora-de-bellas-artes-blanca-montalvo-lleva-una-muestra-sobre-la-mujer-al-instituto-cervantes-de-palermo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/pamplona/noticia/4009111/navarrabiomed-e-idisna-desarrollan-un-estudio-sobre-salud-infantil-con-estudiantes-de-paz-de-ziganda/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/pamplona/noticia/4009181/estudiantes-de-la-upna-se-forman-en-cooperacion-al-desarrollo-con-un-curso-impartido-por-ong-y-profesorado-universitario/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/segovia/noticia/4007001/el-mapa-de-machado-lleva-a-visitantes-y-vecinos-de-segovia-a-los-lugares-por-los-que-se-movia-el-poeta-en-la-ciudad/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/sevilla/noticia/4009155/un-estudio-andaluz-demuestra-que-los-protectores-microclimaticos-no-mejoran-la-supervivencia-de-las-encinas/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/sevilla/noticia/4009391/mas-de-700-alumnos-se-presentan-a-las-pruebas-de-admision-para-los-grados-de-la-universidad-loyola/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/tenerife/noticia/4008196/canarias-invertira-425000-euros-en-ayudas-exclusivas-a-apoyar-el-desarrollo-de-artes-visuales-en-las-islas/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/teruel/noticia/4009325/el-x-curso-de-truficultura-practica-de-mora-de-rubielos-teruel-muestra-las-novedades-del-sector/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/toledo/noticia/4008609/la-uclm-el-grupo-cecap-y-laborvalia-presentan-nuevas-iniciativas-para-la-inclusion-social/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/valencia/noticia/4009214/isabial-e-idibe-crean-una-unidad-para-desarrollar-organoides-con-aplicaciones-en-biomedicina-y-biotecnologia/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/valladolid/noticia/4008757/psoe-valladolid-propondra-en-el-pleno-recordar-el-50-aniversario-del-cierre-de-la-uva-y-las-protestas-sociales-de-1975/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/vigo/noticia/4001273/robots-para-ayudar-a-ninos-con-autismo-para-hacer-inventarios-o-para-emergencias-participan-en-las-jai/
Desconocido - Gente Digital

Desconocido
https://cualia.es/el-que-susurra-john-dickson-carr/
Desconocido - Cualia

Desconocido
https://elpais.com/economia/2025-02-20/diaz-impulsa-la-ley-de-democracia-en-las-empresas-con-una-comision-de-expertos-hay-corporaciones-autocraticas.html
Desconocido - El Pais

Desconocido
https://www.8directo.com/mas-que-8/asteroide-2024-yr4-experto-resuelve-dudas-sobre-su-posible-impacto-en-tierra-en-2032_623237_102.html
Desconocido - 8directo

Desconocido