In [ ]:
!pip install -q scrapy
#!pip install -q newspaper4k
!pip install -q newspaper3k
!pip install -q lxml_html_clean

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 817.6 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 18.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.8/259.8 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.9/104.9 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 kB 4.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 50.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 6.8 MB/s eta 0:00:00
  Building wheel for tinysegmenter (setup.py) ... done
  Building wheel for feedfinder2 (setup.py) ... done
  Building wheel for jieba3k (setup.py) ... done
  Building wheel for sgmllib3k (setup.py) ... done

# Articulos de mapas de sitio usando scrapy

In [ ]:
!scrapy startproject news_scraper

New Scrapy project 'news_scraper', using template directory '/usr/local/lib/python3.11/dist-packages/scrapy/templates/project', created in:
    /content/news_scraper

You can start your first spider with:
    cd news_scraper
    scrapy genspider example example.com

## Extracción de URLs

In [ ]:
%cd news_scraper

/content/news_scraper

In [ ]:
%%writefile "news_extractor_spider.py"
import scrapy
from newspaper import build, Config, Article
import requests
from urllib.parse import urljoin, urlparse
import os
import time
import re
from datetime import datetime
import gzip
from scrapy.selector import Selector
import dateutil

class NewsUrlExtractorSpider(scrapy.Spider):
    name = 'news_extractor'

    def __init__(self, date="2025-01-01", *args, **kwargs):
        super(NewsUrlExtractorSpider, self).__init__(*args, **kwargs)
        self.from_date = datetime.strptime(date, '%Y-%m-%d').date()
        self.invalid_url_words = {'section', 'tag', 'template',
                                  'category', 'author', 'page-sitemap'
                                  'categories', 'video', 'image', 'temas',
								                  'live', 'microsite', 'focus', 'blog',
                                  'ocio', 'cine', 'board', 'character'}


    # Lista de páginas web
    start_urls=[
        'https://www.elcomercio.es/',
        'https://www.lne.es/',
        'https://www.lavanguardia.com/',
        'https://www.larazon.es/',
        'https://www.rtpa.es/',
        'https://www.europapress.es/',
        'https://www.20minutos.es/',
        'https://www.elperiodico.com/',
        'https://www.eldiario.es/',
        'https://www.elconfidencial.com/',
        'https://www.culturalgijonesa.org/',
        'https://www.elespanol.com/',
        'https://www.nortes.me/',
        'https://www.tribunasalamanca.com/',
        'https://migijon.com/',
        'https://www.telecinco.es/',
        'https://www.laprovincia.es/',
        'https://www.laopiniondemalaga.es/',
        'https://www.elfielato.es/',
        'https://www.teleprensa.com/',
        'https://www.infobae.com/',
        'https://www.asturiasmundial.com/', #newspaper
        'https://www.abc.es/', #newspaper
        'https://www.lavozdeasturias.es/', #newspaper
        'https://cualia.es/', #newspaper
        'https://www.lavozdegalicia.es/', # newspaper
        'http://www.gentedigital.es/', #newspaper
    ]

    # Metadata: nombre y sitemap
    metadata_urls={
        'https://www.elcomercio.es/': {'nombre': 'El Comercio',
                                       'sitemap': 'sitemap.xml'},
        'https://www.lne.es/': {'nombre': 'La Nueva España',
                                'sitemap': 'sitemap_google_news_52e19.xml'},
        'https://www.lavanguardia.com/': {'nombre': 'La Vanguardia',
                                          'sitemap': 'sitemap-google-news.xml'},
        'https://www.larazon.es/': {'nombre': 'La Razón',
                                    'sitemap': 'sitemaps/news.xml'},
        'https://www.rtpa.es/': {'nombre': 'Radiotelevisión del Principado de Asturias (RTPA)',
                                 'sitemap': 'sitemap-noticias.xml'},
        'https://www.europapress.es/': {'nombre': 'Europa Press'},
        'https://www.abc.es/': {'nombre': 'ABC'},
        'https://www.20minutos.es/': {'nombre': '20 Minutos',
                                      'sitemap': 'sitemap-google-news.xml'},
        'https://www.elperiodico.com/' : {'nombre': 'El Periódico',
                                          'sitemap': 'es/google-news.xml'},
        'https://www.eldiario.es/' : {'nombre': 'ElDiario.es',
                                      'sitemap': 'sitemap_google_news_25b87.xml'},
        'https://www.lavozdeasturias.es/': {'nombre': 'La Voz de Asturias'}, #newspaper
        'https://www.elconfidencial.com/': {'nombre': 'El Confidencial',
                                            'sitemap': 'newsitemap_4.xml'},
        'https://cualia.es/': {'nombre': 'Cualia'}, #newspaper
        'https://www.culturalgijonesa.org/': {'nombre': 'Cultural Gijonesa'},
        'https://www.elespanol.com/' : {'nombre': 'El Español',
                                        'sitemap': 'sitemap_google_news.xml'},
        'https://www.nortes.me/': {'nombre': 'Nortes'},
        'https://www.lavozdegalicia.es/': {'nombre': 'La Voz de Galicia'},
        'https://www.asturiasmundial.com/': {'nombre': 'Asturias Mundial'},
        'https://www.tribunasalamanca.com/': {'nombre': 'Tribuna Salamanca',
                                              'sitemap': 'sitemap_last_news.xml'},
        'https://migijon.com/': {'nombre': 'Mi Gijón',
                                 'sitemap': 'sitemap_index.xml'},
        'http://www.gentedigital.es/' : {'nombre': 'Gente Digital'}, #newspaper
        'https://www.infobae.com/' : {'nombre': 'Infobae',
                                      'sitemap': 'arc/outboundfeeds/news-sitemap2/'},
        'https://www.telecinco.es/' : {'nombre': 'Telecinco',
                                       'sitemap': 'sitemap_google_news.xml'},
        'https://www.laprovincia.es/' : {'nombre': 'La Provincia',
                                         'sitemap': 'sitemap_google_news_89aa6.xml'},
        'https://www.laopiniondemalaga.es/': {'nombre': 'La Opinión de Málaga',
                                              'sitemap': 'sitemap_google_news_fcad9.xml'},
        'https://www.elfielato.es/': {'nombre': 'El Fielato y El Nora',
                                      'sitemap': 'sitemap.news.xml'},
        'https://www.teleprensa.com/': {'nombre': 'Teleprensa',
                                        'sitemap': 'sitemap.news.xml'}
    }


    custom_settings = {
        'USER_AGENT': "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
    }

    # Para extracción de xmls
    namespaces = {
        'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9',  # Default namespace
        'news': 'http://www.google.com/schemas/sitemap-news/0.9'
    }

    def get_base_url(self, url):
        parsed_url = urlparse(url)
        return f"{parsed_url.scheme}://{parsed_url.netloc}/"

    def normalize_date(self, date_string):
        try:
            # Conviertir la cadena de fechas en un objeto datetime
            parsed_date = dateutil.parser.parse(date_string)
            # Formatea el objeto datetime como 'YYYY-MM-DD'
            #return parsed_date.strftime('%Y-%m-%d')
            return parsed_date.date()
        except (ValueError, TypeError):
            raise ValueError(f"Formato de fecha inválido: '{date_string}'")

    def is_valid_xml_url(self, sitemap_url):
        for invalid_word in self.invalid_url_words:
            if invalid_word in sitemap_url:
                return False

        pattern = r'\b(1[0-9]{3}|20[0-1][0-9]|202[0-4])\b' # Matches 1000-1999, 2000-2019, and 2020-2024
        match_url = re.search(pattern, sitemap_url)
        if match_url:
            return False
        else:
            return True

    def parse(self, response):
        domain_base = self.get_base_url(response.url)
        # Empezar explorando los archivos xml predefinidos
        if domain_base in self.metadata_urls and 'sitemap' in self.metadata_urls[domain_base]:
            sitemap_name = self.metadata_urls[domain_base]['sitemap']
            #sitemap_name = self.sitemap_urls[domain]
            sitemap_url = urljoin(domain_base, sitemap_name)
            print(f"Accediendo al siguiente enlace especificado... {sitemap_url}")
            #yield scrapy.Request(sitemap_url, callback=self.parse_sitemap)
            yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain_base) )
        else:
            # Usar robots en caso no se tengas archivo xml predefinido
            robots_url = urljoin(response.url, "/robots.txt")
            print(f'Robots URL: {robots_url}')
            yield scrapy.Request(robots_url, callback=self.parse_robots, meta={'domain': response.url})

    def parse_robots(self, response):
        if response.status != 200:
            print(f"Error al acceder a la url: {response.status}")
            return
        domain = response.meta['domain']
        domain_base = self.get_base_url(domain)
        current_sitemap_urls = set()

        # Extraer urls de sitemaps de robots.txt
        for line in response.text.splitlines():
            if line.lower().startswith('sitemap:'):
                sitemap_url = line.split(':', 1)[1].strip()
                parsed_url = urlparse(sitemap_url)
                file_path = parsed_url.path
                file_name, file_extension = os.path.splitext(file_path)
                if file_extension.lower() == ".xml" and self.is_valid_xml_url(sitemap_url):
                    current_sitemap_urls.add(sitemap_url)

        if len(current_sitemap_urls) > 0:
            print(f"Se encontraron los siguientes enlaces xml: {current_sitemap_urls}")
            for sitemap_url in current_sitemap_urls:
                print(f"Accediendo al siguiente enlace... {sitemap_url}")
                #yield scrapy.Request(sitemap_url, callback=self.parse_sitemap)  # Llamada recursiva
                yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain) )
        else:
            print("No se encontraron enlaces xml en robots.txt. Accediendo a enlaces con librería Newspaper...")
            # Si no se encuentra ningún mapa del sitio,
            # utilizar Newspaper para obtener las URL de los artículos de noticias
            yield from self.get_news_urls(domain)

    def parse_sitemap(self, response, domain=None):

        # Sitemaps anidados. Tag <sitemap>
        for sitemap in response.xpath('//ns:sitemap', namespaces=self.namespaces):
            sitemap_loc = sitemap.xpath('./ns:loc/text()', namespaces=self.namespaces).get()

            # Omitir sitemaps antiguos
            last_mod = sitemap.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()
            if last_mod:
                lastmod = self.normalize_date(last_mod)
                if lastmod < self.from_date:
                    continue

            # Verificar que la url es un archivo xml
            parsed_url = urlparse(sitemap_loc)
            file_path = parsed_url.path
            file_name, file_extension = os.path.splitext(file_path)

            if file_extension.lower() == ".xml" and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                #print(f'Se encontró otro xml dentro del archivo actual: {sitemap_loc}') ## lots of outputs
                if sitemap_loc:
                    #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap)  # Llamada recursiva
                    yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap(response, domain) )
            elif file_extension.lower() == '.gz'  and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                print(f"Se encontró archivo comprimido {sitemap_loc}")
                #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap_gz)
                yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap_gz(response, domain) )


        # Extraer datos de cada tag <url>
        for url in response.xpath('//ns:url', namespaces=self.namespaces):

            loc = url.xpath('./ns:loc/text()', namespaces=self.namespaces).get()
            title = url.xpath('./news:news/news:title/text()', namespaces=self.namespaces).get()
            publication_date = url.xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            fuente = url.xpath('./news:news/news:publication/news:name/text()', namespaces=self.namespaces).get()

            if loc is None:
                break

            #if title is None or publication_date is None or loc is None:
            #    #self.logger.warning(f"Sitemap {response} contiene otra información. Omitiendo...")
            #    #print(f"Sitemap {response} no contiene la información requerida. Omitiendo...")
            #    #break
            title = "" if title is None else title
            if publication_date is None:
               publication_date = url.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            if publication_date is not None:
                publication_date_comp = self.normalize_date(publication_date)
                #publication_date_ = dateutil.parser.parse(publication_date).date()
                if publication_date_comp < self.from_date:
                    continue

            #if fuente is None:
            #    found_match = re.search(r"www\.(.*?)\.(.+)", loc)
            #    if found_match:
            #        fuente = found_match.group(1)

            if domain is not None:
                domain_base = self.get_base_url(domain)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']
            #fuente = self.metadata_urls[domain]['nombre']
            yield {
                'fuente': fuente,
                'url': loc,
                'titulo': title,
                'fecha_publicacion': publication_date,
            }

    def parse_sitemap_gz(self, response, domain=None):

        compressed_file = response.body
        decompressed_file = gzip.decompress(compressed_file).decode("utf-8")
        selector = Selector(text=decompressed_file, type="xml")
        #yield from self.parse_sitemap(selector)
        yield from self.parse_sitemap(selector, domain)

    def get_news_urls(self, domain):

        config = Config()
        config.request_timeout = 5
        config.language= 'es'
        config.thread_timeout_seconds = 5
        config.memoize_articles = False
        config.fetch_images = False
        config.follow_meta_refresh = True
        config.number_threads = 4
        config.browser_user_agent = self.custom_settings['USER_AGENT']
        config.headers = {
            "User-Agent": self.custom_settings['USER_AGENT'],
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate",
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
            "Cache-Control": "max-age=0",
        }
        try:
            print(f'Extrayendo noticias con librería Newspaper para url: {domain}')
            start_time = time.time()
            paper = build(domain, config=config)
            print(f"--- {(time.time() - start_time):.2f}s segundos ---")
            articulos_urls = set(paper.article_urls())
            print(f'Se encontraron {len(articulos_urls)} enlaces de noticias.')

            # Obtener fuente
            if domain is not None:
                domain_base = self.get_base_url(domain)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']
                else:
                    found_match = re.search(r"www\.(.*?)\.(.+)", domain)
                    fuente = ''
                    if found_match:
                        fuente = found_match.group(1)


            titulo, fecha_publicacion = '', None
            for articulo_url in articulos_urls:
                yield {
                    'fuente': fuente,
                    'url': articulo_url,
                    'titulo': titulo,
                    'fecha_publicacion': fecha_publicacion,
                }
        except Exception as e:
            print(f"No se pudieron obtener noticias de {domain}")

Overwriting news_extractor_spider.py

Copiar archivo spider a carpeta para ejecutar

In [ ]:
!cp news_extractor_spider.py news_scraper/spiders

Eliminar csv para generar uno nuevo

In [ ]:
# Eliminar csv
import os
output_file_csv = "news_output.csv"
if os.path.exists(output_file_csv):
    os.remove(output_file_csv)

Ejecutar spyder de scrapy para gener el archivo csv con los enlaces

In [ ]:
!scrapy crawl news_extractor -o news_output.csv -s LOG_ENABLED=False -s ROBOTSTXT_OBEY=False -a date=2025-02-01
#!scrapy crawl news_extractor -o news_output.csv

Accediendo al siguiente enlace especificado... https://www.20minutos.es/sitemap-google-news.xml
Accediendo al siguiente enlace especificado... https://www.eldiario.es/sitemap_google_news_25b87.xml
Robots URL: https://www.nortes.me/robots.txt
Accediendo al siguiente enlace especificado... https://www.lne.es/sitemap_google_news_52e19.xml
Accediendo al siguiente enlace especificado... https://www.elcomercio.es/sitemap.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-google-news.xml
Accediendo al siguiente enlace especificado... https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml
Accediendo al siguiente enlace especificado... https://www.elperiodico.com/es/google-news.xml
Se encontraron los siguientes enlaces xml: {'https://www.nortes.me/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.nortes.me/sitemap_index.xml
Accediendo al siguiente enlace especificado... https://www.elconfidencial.com/newsitemap_4.xml
Accediendo al siguiente enlace especificado... https://www.telecinco.es/sitemap_google_news.xml
Accediendo al siguiente enlace especificado... https://www.elespanol.com/sitemap_google_news.xml
Accediendo al siguiente enlace especificado... https://www.laprovincia.es/sitemap_google_news_89aa6.xml
Robots URL: https://www.europapress.es/robots.txt
Accediendo al siguiente enlace especificado... https://www.rtpa.es/sitemap-noticias.xml
Accediendo al siguiente enlace especificado... https://www.tribunasalamanca.com/sitemap_last_news.xml
Accediendo al siguiente enlace especificado... https://www.infobae.com/arc/outboundfeeds/news-sitemap2/
Robots URL: https://www.culturalgijonesa.org/robots.txt
Accediendo al siguiente enlace especificado... https://www.elfielato.es/sitemap.news.xml
Accediendo al siguiente enlace especificado... https://www.teleprensa.com/sitemap.news.xml
Accediendo al siguiente enlace especificado... https://www.larazon.es/sitemaps/news.xml
Robots URL: https://www.abc.es/robots.txt
Accediendo al siguiente enlace especificado... https://migijon.com/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.culturalgijonesa.org/sitemap.xml'}
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.xml
Robots URL: https://www.asturiasmundial.com/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.abc.es/
--- 8.90s segundos ---
Se encontraron 1226 enlaces de noticias.
Se encontraron los siguientes enlaces xml: {'https://www.europapress.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.europapress.es/sitemap.xml
No se encontraron enlaces xml en robots.txt. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.asturiasmundial.com/
--- 5.07s segundos ---
Se encontraron 167 enlaces de noticias.
Robots URL: https://www.lavozdeasturias.es/robots.txt
Robots URL: http://www.gentedigital.es/robots.txt
Robots URL: https://www.lavozdegalicia.es/robots.txt
Robots URL: https://cualia.es/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.lavozdegalicia.es/
--- 32.04s segundos ---
Se encontraron 1637 enlaces de noticias.
No se encontraron enlaces xml en robots.txt. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://cualia.es/
--- 3.52s segundos ---
Se encontraron 24 enlaces de noticias.
No se encontraron enlaces xml en robots.txt. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: http://www.gentedigital.es/
--- 33.75s segundos ---
Se encontraron 1575 enlaces de noticias.
No se encontraron enlaces xml en robots.txt. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.lavozdeasturias.es/
--- 19.23s segundos ---
Se encontraron 375 enlaces de noticias.

## Filtrar articulos por fecha

In [ ]:
import pandas as pd
from datetime import datetime
import numpy as np

# Cargar la data extraída
data_df = pd.read_csv("news_output.csv")

# Fecha inicial
fecha_inicial = "2025-2-18"

data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'], format='mixed', errors='coerce', utc=True)
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'].dt.strftime("%Y-%m-%d"))
data_df = data_df[(data_df['fecha_publicacion'].between(fecha_inicial, datetime.now().strftime('%Y-%m-%d'))) | (pd.isna(data_df['fecha_publicacion']))]
data_df = data_df.sort_values(by='fecha_publicacion', ascending=False).drop_duplicates().reset_index(drop=True)
data_df

,fuente,url,titulo,fecha_publicacion
0,ElDiario.es,https://www.eldiario.es/castilla-la-mancha/soc...,Exigen ante el juzgado la clausura de los labo...,2025-02-21
1,Teleprensa,https://www.teleprensa.com/articulo/nacional-3...,El conductor que mató a una menor en Gurb (Bar...,2025-02-21
2,La Nueva España,https://www.lne.es/sociedad/2025/02/21/agenda-...,Agenda: qué hacer hoy 21 de febrero en Asturias,2025-02-21
3,La Nueva España,https://www.lne.es/economia/2025/02/21/comprav...,La compraventa de pisos se dispara el 18% en A...,2025-02-21
4,La Nueva España,https://www.lne.es/asturias-exterior/2025/02/2...,"Homenaje póstumo a Juan Velarde en Madrid: ""Er...",2025-02-21
...,...,...,...,...
12691,Gente Digital,http://www.gentedigital.es/getafe/noticia/3967...,NaN,NaT
12692,Gente Digital,http://www.gentedigital.es/pontevedra/noticia/...,NaN,NaT
12693,Gente Digital,http://www.gentedigital.es/palencia/noticia/40...,NaN,NaT
12694,Gente Digital,http://www.gentedigital.es/logrono/noticia/400...,NaN,NaT
12695,Gente Digital,http://www.gentedigital.es/valladolid/noticia/...,NaN,NaT

In [ ]:
conteos = data_df['fuente'].value_counts()
conteos

fuente
La Voz de Galicia                                    1637
Gente Digital                                        1575
ABC                                                  1226
La Razón                                              969
El Confidencial                                       958
La Vanguardia                                         916
El Español                                            840
20 Minutos                                            701
El Periódico                                          495
ElDiario.es                                           473
Telecinco                                             441
La Nueva España                                       408
La Voz de Asturias                                    375
El Comercio                                           315
Teleprensa                                            300
La Opinión de Málaga                                  217
Asturias Mundial                                      167
Radiotelevisión del Principado de Asturias (RTPA)     123
Europa Press                                          120
Tribuna Salamanca                                     114
Infobae                                               100
La Provincia                                           73
Mi Gijón                                               73
Nortes                                                 37
Cualia                                                 24
El Fielato y El Nora                                   17
Cultural Gijonesa                                       2
Name: count, dtype: int64

In [ ]:
len(data_df['fuente'].value_counts())

27

### Eliminar enlaces duplicados

In [ ]:
def remover_url_duplicados(df):
    df['non_null_count'] = df.notnull().sum(axis=1)
    df = df.sort_values(by=['url', 'non_null_count'], ascending=[True, False])
    df = df.drop_duplicates(subset=['url'], keep='first')
    df = df.drop(columns=['non_null_count'])
    df = df.sort_values(by='fecha_publicacion', ascending=False).reset_index(drop=True)
    return df

data_df = remover_url_duplicados(data_df)
data_df

,fuente,url,titulo,fecha_publicacion
0,Mi Gijón,https://migijon.com/about-us/,NaN,2025-02-21
1,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,La Policía investiga la muerte de una niña en ...,2025-02-21
2,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,Homicidios investiga si el exalcalde de Gandía...,2025-02-21
3,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,El hombre y la mujer fallecidos en Córdoba mur...,2025-02-21
4,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,ROBO ATRIO PELÍCULA | Hollywood ofrece a los l...,2025-02-21
...,...,...,...,...
12686,ABC,https://www.semana.es/familia-real-espanola/de...,NaN,NaT
12687,ABC,https://www.semana.es/familia-real-espanola/pr...,NaN,NaT
12688,ABC,https://www.semana.es/living/entramos-casa-osc...,NaN,NaT
12689,ABC,https://www.semana.es/moda/nagore-robles-a-ani...,NaN,NaT
12690,ABC,https://www.turium.es/destinos/nijar-pueblo-bl...,NaN,NaT

In [ ]:
data_df['fuente'].value_counts()

fuente
La Voz de Galicia                                    1632
Gente Digital                                        1575
ABC                                                  1226
La Razón                                              969
El Confidencial                                       958
La Vanguardia                                         916
El Español                                            840
20 Minutos                                            701
El Periódico                                          495
ElDiario.es                                           473
Telecinco                                             441
La Nueva España                                       408
La Voz de Asturias                                    375
El Comercio                                           315
Teleprensa                                            300
La Opinión de Málaga                                  217
Asturias Mundial                                      167
Radiotelevisión del Principado de Asturias (RTPA)     123
Europa Press                                          120
Tribuna Salamanca                                     114
Infobae                                               100
La Provincia                                           73
Mi Gijón                                               73
Nortes                                                 37
Cualia                                                 24
El Fielato y El Nora                                   17
Cultural Gijonesa                                       2
Name: count, dtype: int64

## Acceder al contenido de las noticias

### Extracción con request

In [ ]:
import requests
from bs4 import BeautifulSoup


# Lista de user-agents para probar
user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/W.X.Y.Z Safari/537.36"
]

def extraer_texto_articulos_request(url):
    try:
        # Primer intento sin user-agent
        response = requests.get(url)

        # Si la respuesta no es exitosa o el contenido está vacío, intente con agentes de usuario
        if response.status_code != 200 or not response.content:
            for user_agent in user_agents:
                headers = {
                    "User-Agent": user_agent,
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                    "Accept-Language": "en-US,en;q=0.5",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
                response = requests.get(url, headers=headers)

                if response.status_code == 200 and response.content:
                    #print("Encontrado con user-agent")
                    break

        html_str = response.content
        soup = BeautifulSoup(html_str, 'lxml')

        # Remover footer
        footer = soup.find('footer')
        if footer:
            footer.decompose()

        text_content = soup.find_all('p')

        text = ''
        for i in text_content:
            text += i.text.strip() + " "

        return text.strip() if text.strip() else None

    except Exception as e:
        print(f"Error in url: {url}, error: {e}")
        return None

In [ ]:
extraer_texto_articulos_request("https://cualia.es/carl-barks-el-creador-del-tio-gilito/")

'El encanto es la clave de la obra de Carl Barks (1901-2000). Con una calidad gráfica excepcional, este dibujante logró un completo equilibrio entre las convenciones del tebeo infantil y esa idea de la imaginación realizada\xa0que defiende Fernando Savater, y que, a lo largo de más de medio siglo, vino a ser la característica de publicaciones como Dumbo o Don Miki. En este aspecto, el atractivo de los cómics de Barks no necesita demasiadas explicaciones. Hay que embarcarse en su lectura, sin darle más vueltas, y reconocer en ellos esa diversión sin límites que uno experimenta en la infancia. Más allá de ese valor sentimental, la figura de Barks merece atención por razones que tienen que ver con el propio desarrollo de los estudios Disney. Ahora les explicaré por qué. En agosto de 1923 Walt y Roy Disney piden dinero a su tío Robert y con ese capital fundan los Estudios Disney. El equipo de animadores lo encabeza Ub Iwerks, a cuyas ordenes trabajan Fritz Freleng, Rudolph Ising, Les Clark y otros jóvenes artistas que, con el tiempo, tendrán mucho que aportar al mundo del dibujo animado. En 1927, Disney recibe una sugerencia de su distribuidor Charles Mintz, esposo de Margaret J. Winkler. Mintz le propone una nueva serie con algún personaje fijo, preferentemente un animal antropomórfico. El resultado será\xa0Oswald the lucky rabbit, un simpático conejo cuyos rasgos prefiguran los de Mickey Mouse. La primera película con este personaje es\xa0Trolley troubles\xa0(1927). El mismo año, el equipo de Disney completa nuevos cortometrajes de Oswald:\xa0Oh, teacher,\xa0The mechanical cow,\xa0Great guns,\xa0The ocean hop,\xa0The banker’s daughter,\xa0Empty stocks\xa0y\xa0Rickety gin. Pero un nuevo animador, Walter Lantz (luego creador del Pájaro Loco), pacta con Mintz la propiedad del personaje y la serie escapa del control de Disney. La situación se complica enormemente para el estudio tras el abandono de Mintz. Afortunadamente, Ub Iwerks prueba varios diseños hasta dar con una idea brillante: el ratón Mickey Mouse, protagonista de un enloquecido cortometraje,\xa0Plane crazy\xa0(1927), que Iwerks anima en su totalidad. Años después, Disney, que va reafirmando su autoridad en el estudio, contará que la paternidad del personaje le corresponde, pues lo imaginó durante un viaje a Nueva York y su esposa le sugirió el nombre (como sucederá en otros casos, Walt Disney acredita su habilidad para la gestión del talento ajeno).  Mientras tanto, el sonido ha hecho su aparición en el cine, y Disney resuelve tomar la iniciativa en el campo del dibujo animado. Se rueda entonces el primer cortometraje sonoro de Mickey Mouse,\xa0Steamboat Willie, estrenado el 18 de noviembre de 1928 en el Colony Theater de Nueva York. Un año después, el ratón pasa a protagonizar una serie de cómics distribuidos por la cadena King Features Syndicate. Disney comprende tras esta iniciativa el enorme negocio de los productos derivados, y empieza a vender licencias para la fabricación de juguetes con sus creaciones. Mickey Mouse protagoniza historietas a partir de enero de 1930. Cuando crece su imperio económico, Disney contrata a numerosos dibujantes para que lleven al tebeo a otros personajes de animación. Y es ahí donde entran en liza creadores de la talla de Floyd Gottfredson, Carl Barks, Al Taliaferro, Bill Shaw, Walt Kelly, Al Levin y Fred Quimby. Todos ellos –empezando por el propio Barks– renuncian a su firma, convenientemente sustituida por la del omnipresente Walt Disney. Por las mismas fechas, llega al mercado la pícara Betty Boop. Les hablo de una maravillosa creación de los Fleischer Brothers Animation Studios que aparece en el cine en 1930, y que a partir del 23 de julio de 1934, dibujada por Grim Natwick y Max Fleischer, también será protagonista de innumerables cómics. Frente a esa competencia, Carl Barks se hace cargo de un personaje aún más carismático: el pato Donald, creado por los dibujantes Art Babbit y Dick Huemer, quienes lo incluyeron en el cortometraje de dibujos animados\xa0The wise little hen\xa0(1934). Un doblaje muy característico, obra de Clarence Nash, y su peculiar diseño, con vestido de marinero, hacen de este irascible palmípedo una de las más populares y características figuras de todo el universo Disney. Acompañado por su novia, Daisy, el millonario Tío Gilito y sus tres sobrinos, Donald es protagonista de infinidad de aventuras cinematográficas… y por supuesto, también de muchos tebeos. El dibujante Al Taliaferro y el guionista Ted Osborne adaptaron al cómic\xa0The wise little hen\xa0el 11 de agosto de 1934. En 1942, Carl Barks tomó el relevo y prosiguió la realización de los cómics de Donald durante décadas. Inspirándose en el avaro Ebezener Scrooge de la\xa0Canción\xa0de Navidad\xa0que escribiera Charles Dickens, Carl Barks ideó al Tío Gilito (Scrooge McDuck) para incluirlo en el cómic\xa0Christmas on Bear Mountain, publicado en diciembre de 1947. Gracias a la buena acogida de las historietas protagonizadas por este personaje, la compañía Disney decidió convertirlo en dibujo animado. Como ven, lejos de ser circunstancial, la intervención de Barks en la maquinaria creativa de la empresa fue decisiva. Hasta no hace mucho, tuvimos que conformarnos con disfrutar de su obra en publicaciones dispersas, en las que no se concedía importancia a nuestro autor. Los más enterados ya descubrieron las soberbias ediciones de Fantagraphics o de Gemstone Publishing, depositarios de la licencia de Disney Publishing Worldwide que permite editar en el mercado norteamericano comic books de Mickey, Minnie, Donald, Goofy y otras criaturas disneyanas. Por fortuna, gracias a la iniciativa de Planeta DeAgostini, que reeditó este material entre nosotros, la oportunidad de admirar sin descanso a Barks quedó al alcance de todos los lectores hispanohablantes. Artículos relacionados El Pato Donald: del cine a la historieta Mickey Mouse, un detective de tebeo Patomas, el justiciero enmascarado de Patolandia Vida y leyenda de Walter Elias Disney Copyright del artículo © Guzmán Urrero. Reservados todos los derechos. Ilustraciones de la Biblioteca Carl Barks © Disney Enterprises Inc. Cortesía del Departamento de Prensa de Planeta DeAgostini Comics. Reservados todos los derechos. Colaborador de la sección cultural de \'The Objective\'. Escribió de forma habitual en \'La Lectura\', revista cultural de \'El Mundo\'. Tras una etapa profesional en la Agencia EFE, se convirtió en colaborador de las páginas de cultura del diario \'ABC\' y de revistas como "Cuadernos Hispanoamericanos", "Álbum Letras-Artes" y "Scherzo".\nComo colaborador honorífico de la Universidad Complutense de Madrid, se ocupó del diseño de recursos educativos, una actividad que también realizó en instituciones como el Centro Nacional de Información y Comunicación Educativa (Ministerio de Educación, Cultura y Deporte).\nAsimismo, accedió al sector tecnológico como autor en las enciclopedias de Micronet y Microsoft, al tiempo que emprendía una larga trayectoria en el Instituto Cervantes, preparando exposiciones digitales y numerosos proyectos de divulgación sobre temas literarios y artísticos. Ha trabajado en el sector editorial y es autor de trece libros (en papel) sobre arte y cultura audiovisual. Los mitos del tebeo y la novela popular han estado siempre en estrecha relación. De ahí que no sorprenda a casi nadie que Mickey Mouse se convirtiese en un detective\xa0hardboiled, al más puro estilo de Raymond Chandler o... Dumbo, el cuarto largometraje de Disney es, hasta el momento, la película más corta del estudio con sus sesenta y cuatro minutos de duración. Fue asimismo la que contó con menos presupuesto para su producción. En...  Cualia recoge lo más destacado del arte, la ciencia y la cultura, con el propósito de enriquecer los grandes debates de nuestro tiempo.  Copyright © 2025 Guzmán Urrero, Cualia.es. Reservados todos los derechos.'

In [ ]:
from concurrent.futures import ThreadPoolExecutor
import time

num_threads = 16

start_time = time.time()
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    data_df['texto'] = list(executor.map(extraer_texto_articulos_request, data_df['url']))
print(f"--- {(time.time() - start_time):.2f}s seconds ---")

Error in url: http://www.gentedigital.es/caceres/noticia/4008039/abre-sus-puertas-en-majadas-de-tietar-caceres-el-museo-de-historia-de-la-computacion-tras-casi-cuatro-anos-de-obras/, error: HTTPConnectionPool(host='www.gentedigital.es', port=80): Max retries exceeded with url: /caceres/noticia/4008039/abre-sus-puertas-en-majadas-de-tietar-caceres-el-museo-de-historia-de-la-computacion-tras-casi-cuatro-anos-de-obras/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x789359710950>, 'Connection to www.gentedigital.es timed out. (connect timeout=None)'))

<ipython-input-108-2b36f8adf2b6>:34: XMLParsedAsHTMLWarning: It looks like you're using an HTML parser to parse an XML document.

Assuming this really is an XML document, what you're doing might work, but you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the Python package 'lxml' installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.

If you want or need to use an HTML parser on this document, you can make this warning go away by filtering it. To do that, run this code before calling the BeautifulSoup constructor:

    from bs4 import XMLParsedAsHTMLWarning
    import warnings

    warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

  soup = BeautifulSoup(html_str, 'lxml')

--- 1448.13s seconds ---

In [ ]:
data_df

,fuente,url,titulo,fecha_publicacion,texto
0,Mi Gijón,https://migijon.com/about-us/,NaN,2025-02-21,"Pablo Cardona, semifinalista en el P1 de Riad ..."
1,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,La Policía investiga la muerte de una niña en ...,2025-02-21,INVESTIGACIÓN Archivo - Coche de Policía Nacio...
2,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,Homicidios investiga si el exalcalde de Gandía...,2025-02-21,INVESTIGACIÓN Perales Iborra Teresa Domínguez ...
3,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,El hombre y la mujer fallecidos en Córdoba mur...,2025-02-21,Investigación José Antonio Aguilar Juan Pablo ...
4,La Opinión de Málaga,https://www.laopiniondemalaga.es/sucesos/2025/...,ROBO ATRIO PELÍCULA | Hollywood ofrece a los l...,2025-02-21,"1,6 MILLONES DE EUROS EN VINO EFE Luis Renduel..."
...,...,...,...,...,...
12686,ABC,https://www.semana.es/familia-real-espanola/de...,NaN,NaT,Isa Pantoja Admirador Reina Letizia Ausencia G...
12687,ABC,https://www.semana.es/familia-real-espanola/pr...,NaN,NaT,Isa Pantoja Admirador Reina Letizia Ausencia G...
12688,ABC,https://www.semana.es/living/entramos-casa-osc...,NaN,NaT,Isa Pantoja Admirador Reina Letizia Ausencia G...
12689,ABC,https://www.semana.es/moda/nagore-robles-a-ani...,NaN,NaT,Isa Pantoja Admirador Reina Letizia Ausencia G...
12690,ABC,https://www.turium.es/destinos/nijar-pueblo-bl...,NaN,NaT,Newsletter Buscar en Turium NO TE PIERDAS\nEst...

In [ ]:
data_df['texto'].iloc[-1]

'Newsletter Buscar en Turium NO TE PIERDAS\nEste pueblo blanco de Almería está entre los más bonitos de España Níjar no solo está en la lista de los Pueblos más bonitos de España, sino que además se ha convertido en uno de los destinos más visitados de Andalucía durante 2024. Lucía Lorenzo | 20 Feb 2025 España está llena de pueblos preciosos, donde las calles estrechas y empedradas llevan a quienes los recorren hasta pequeñas iglesias y joyas desconocidas. La belleza se multiplica cuando ponemos rumbo al sur y llegamos hasta Andalucía, donde los pueblos llenos de casas señoriales nos reciben con los brazos abiertos. Justo aquí, en la provincia de Almería, se encuentra uno de los destinos más bonitos: Níjar. Este municipio almeriense no solo se ha hecho con un merecido puesto en el listado de los Pueblos más bonitos de España, sino que se ha convertido en uno de los más turísticos de la región, con más de dos millones de visitantes durante el 2024. Algunos dicen que aquí se ocultan las mejores playas de Almería, mientras que otros afirman que su encanto reside en sus casas blancas y su ubicación junto al Parque Natural de Cabo de Gata-Níjar. A los pies de la Sierra de Alhamilla, Níjar se extiende como un manto blanco que llega hasta el mar. Protegida por las montañas y abierta el mar, esta localidad se convirtió en un enclave estratégico, codiciado por numerosos pueblos a lo largo de la historia. Fenicios, griegos, cartagineses, íberos, romanos y árabes conquistaron estas tierras antes de que los cristianos se hicieran definitivamente con su control. Sin embargo, este lugar ya estaba poblado mucho antes de que los fenicios desembarcaran en sus costas allá por el 800 a.C. Muestra de ello son los restos encontrados en la necrópolis de El Barranquete y los yacimientos de El Tarajal y Amarguilla, donde se encuentran enterramientos de la cultura de los Millares. Entre las construcciones más emblemáticas del municipio hallamos la Atalaya de Níjar. Esta torre de origen musulmán, construida en piedra, vigila el mar Mediterráneo y regala a quienes suben hasta lo alto unas vistas impresionantes del Cabo de Gata. No debes confundirla con la Torre de la Atalaya, situada en el barrio de la Atalaya y bastante posterior. Construida entre los siglos XIV y XVI, compite con la anterior por ver cuál tiene la mejor panorámica de la localidad. Pero no todo son edificios históricos aquí, pues la naturaleza es la otra gran protagonista en el que muchos consideran el pueblo más bonito de Andalucía. El Parque Natural del Cabo de Gata-Níjar es una parada obligada, pues es muy difícil encontrar su diversidad de paisajes en otro lugar. Aquí no solo encontrarás largos kilómetros de arena dorada bañados por aguas azules, sino que también podrás ver humedales llenos de flamencos y hasta llanuras desérticas. Solo al caminar por las calles de Níjar, entre viviendas bajas y encaladas, llegamos a descubrir los tesoros que oculta esta preciosa localidad. Los barrios del Portillo, la Atalaya y el Casco Histórico se despliegan como un laberinto de calles empedradas y edificios blancos, donde las macetas repletas de flores de colores resaltan sobre la pureza de las fachadas. Aunque basta con pasear para dejarse enamorar por el encanto de esta localidad andaluza, no te quedes sin entrar en los talleres de artesanía que pueblan sus estrechas avenidas. La alfarería lleva presente en el territorio desde la época árabe, lo que explica la exposición de colores que inunda las piezas elaboradas por los artesanos locales. Platos y cuencos de colores, jarras cuidadosamente decoradas y jarrones preciosos hacen las delicias de los visitantes, que rara vez se van con las manos vacías. Los telares también inundan las calles del pueblo, pues de aquí salen las típicas jarapas con las que se elaboran mantas, colchas, alfombras y hasta glamurosos bolsos. Como no podía ser de otra manera en Andalucía, la espartería sigue muy presente en Níjar, y es común ver cestos, bolsos y sombreros colgados de las fachadas de las tiendas. Y es que en este pueblo el arte, lejos de quedarse confinado en los museos, sale a la calle para recibir a todo el que lo visita. Visita La Selecta de Níjar, un taller artesanal donde se venden bolsos exclusivos, confeccionados a mano con las típicas jarapas de la localidad. En este taller artesano puedes comprar piezas únicas e incluso encargar un accesorio personalizado, siempre y cuando no te importe entrar en su concurrida lista de espera. Muchos dicen que la playa del Mónsul, situada dentro del Parque Natural de Cabo de Gata-Níjar, es una de las playas más bonitas de Almería. Rodeada de montañas y con una enorme roca dominando el paisaje, el arenal se extiende durante kilómetros de playa virgen, bañado por las aguas cristalinas. También te interesa Destinos Lucía Lorenzo 20 Feb 2025 Destinos Lucía Lorenzo 20 Feb 2025 Ni Oporto ni Venecia, la librería más bonita está en Madrid y tiene ediciones especiales de libros imposibles de encontrar La llaman la librería más bonita de Madrid y no es de extrañar, pero la librería Miguel de Miranda no solo destaca por su precioso interior, sino también por su larga historia y por la singularidad de sus ediciones. Lucía Lorenzo Recibe las últimas novedades Cómo conseguir un upgrade a primera clase en tu próximo vuelo: los trucos de los que vuelan a diario Esta es la ciudad con el carnaval más antiguo de España: tiene forma de estrella y un castillo donde puedes quedarte a dormir El mejor plan para hacer en febrero en Madrid es esta exposición sobre Egipto Guía de Viena: qué ver y hacer en la ciudad de la música Los secretos de las auroras boreales: esto es todo lo que tienes que saber para disfrutar de las luces del norte Dónde están las zonas erógenas de las mujeres y cómo estimularlas para lograr el máximo placer Labios rusos, pómulos exagerados y cara de alien: el peligro de los retoques de Instagram que ves a las influencers Los mejores adaptógenos para mejorar el equilibrio emocional Redes sociales Ni Oporto ni Venecia, la librería más bonita está en Madrid y tiene ediciones especiales de libros imposibles de encontrar La llaman la librería más bonita de Madrid y no es de extrañar, pero la librería Miguel de Miranda no solo destaca por su precioso interior, sino también por su larga historia y por la singularidad de sus ediciones. Lucía Lorenzo Recibe las últimas novedades Cómo conseguir un upgrade a primera clase en tu próximo vuelo: los trucos de los que vuelan a diario Esta es la ciudad con el carnaval más antiguo de España: tiene forma de estrella y un castillo donde puedes quedarte a dormir El mejor plan para hacer en febrero en Madrid es esta exposición sobre Egipto Guía de Viena: qué ver y hacer en la ciudad de la música Los secretos de las auroras boreales: esto es todo lo que tienes que saber para disfrutar de las luces del norte Dónde están las zonas erógenas de las mujeres y cómo estimularlas para lograr el máximo placer Labios rusos, pómulos exagerados y cara de alien: el peligro de los retoques de Instagram que ves a las influencers Los mejores adaptógenos para mejorar el equilibrio emocional Redes sociales'

In [ ]:
data_df[data_df['fuente'] == 'El Comercio'].iloc[0].values

array(['El Comercio',
       'https://www.elcomercio.es/real-aviles/ovetense-marcarle-real-oviedo-era-queria-tachar-20250221204111-nt.html',
       '«Soy ovetense y marcarle al Real Oviedo era algo que quería tachar de la lista»',
       Timestamp('2025-02-21 00:00:00'),
       "MiComercio Mis noticias Mis intereses Newsletters  Mi suscripción Mi cuenta Mis dispositivos Ayuda / Contacto El Club Descuentos Nuevo Cerrar sesión Buscar en El Comercio: Diario de Asturias Secciones Servicios Destacamos Es noticia Ampliar Alberto Santos Avilés Viernes, 21 de febrero 2025, 01:00 El Real Avilés Industrial Femenino aún no se ha repuesto de su 'semana grande' en la que tumbó a Sporting y Real Oviedo y ya  ... tiene que visitar mañana sábado (16 horas, La Planchada) a otro 'hueso' de la categoría como el Racing de Santander. Las jugadoras que entrena Pedro Arboleya afrontan esta cita con la moral por las nubes tras una excelente racha en la que destaca el olfato goleador de una de sus delanteras, Ángela Ávila, que contribuyó con dos goles a las victorias en Mareo y en La Toba ante el líder. La jugadora ovetense de 17 años asegura que «al final siempre es bueno aportar al equipo. Para una delantera es gratificante hacer gol». A pesar de la vitola de favorito con la que llegaba a Avilés el Real Oviedo, Ávila defiende que «confiaba en el nivel que puede dar el equipo. Siempre es bueno ayudar con goles, pero hubiese estado también contenta». El gol del empate –Daniela marcó el de la victoria– que anotó ante el equipo de su ciudad natal, aunque se crió y creció en Albacete, fue muy especial. «Soy ovetense y marcarle al Oviedo era algo que quería tachar de la lista», recuerda. Se da la paradoja de que apenas pudo festejarlo, «porque fue algo peculiar, me dio en la cara la portera, no sabía que había sido gol, me quedé en el suelo y me lo dijeron mis compañeras. Les pregunté: ¿en serio?». El derbi ante el Oviedo no fue una jornada más en la vida deportiva de Ávila. «Estuve muy nerviosa todo el día, con mucha euforia después del partido. Durante los 90 minutos el ritmo de partido fue muy alto e intenso. Ellas apretaron al final y supimos sufrir». La delantera blanquiazul comenzó a jugar al fútbol en el Almansa, equipo del pueblo en el que vivía junto a sus padres y a partir de los 12 años se trasladó a la cantera del Albacete. A pesar de llevar tanto tiempo fuera de Oviedo, «allí está toda mi familia, siempre he estado muy unida a Asturias», dice. De hecho, el pasado sábado tuvo ocasión de celebrar su gol con parte de ellos, «en la grada estaban mis tíos y mi tío se emocionó mucho». La delantera del Real Avilés Industrial Femenino sólo tiene 17 años de edad y todo el futuro por delante en el mundo del fútbol. «No me pongo techo, a seguir creciendo y estoy súper a gusto con el cuerpo técnico y con los compañeras. He crecido un montón», añade orgullosa sobre el Avilés. Al igual que el resto de jugadoras y su entrenador, Pedro Arboleya, defiende que el nivel de la Segunda RFEF femenina «es muy bueno» y, en el caso del Real Avilés, se están recogiendo los resultados que no llegaban a principios de liga, a pesar del buen juego del equipo. «El nivel era muy bueno y no se veía reflejado, y ahora parece que eso nos viene un poco más de cara. Sabíamos que los resultados iban a llegar antes o después. También hay muchas jugadoras nuevas y nos entendemos mejor ahora», valora. Aunque en principio el objetivo del Avilés es la permanencia, defiende que «se está viendo que en la categoría y el grupo puede pasar cualquier cosa. Sabemos el nivel que podemos dar, puede pasar de todo. La permanencia es un objetivo claro, pero Pedro también nos ha dicho que tenemos capacidad para estar arriba y no conformarnos. Somos capaces de mucho», concluye la delantera que ha sido capaz de golear al Sporting y al Real Oviedo. Límite de sesiones alcanzadas El acceso al contenido Premium está abierto por cortesía del establecimiento donde te encuentras, pero ahora mismo hay demasiados usuarios conectados a las vez. Por favor, inténtalo pasados unos minutos. Sesión cerrada Al iniciar sesión desde un dispositivo distinto, por seguridad, se cerró la última sesión en este. Para continuar disfrutando de su suscripción digital, inicie sesión en este dispositivo. ¿Ya eres suscriptor/a? Inicia sesión Publicidad Lo más leído    Publicidad Te puede interesar Se abre el plazo de inscripción para las oposiciones del SAS: estos son los puestos y las fechas de los exámenes ABC de Sevilla Última hora sobre el estado de salud del Papa Francisco, en directo: rueda de prensa de los médicos y noticias hoy ABC El nuevo canal autonómico que obligará a resintonizar millones de televisores en España Las Provincias Una novia de Jaén interrumpe su boda: «No puedo dar el 'sí quiero' si no pasa esto» El Diario Vasco Marc Anthony actuará en Simancas el 18 de julio El Norte de Castilla Publicidad Publicidad Nuestra selección El nuevo Aston Martin de Fernando Alonso ya brilla  Autorizados los dos primeros parques de baterías, en Siero y Corvera, con 21 millones de inversión El Festival Monoloco, por primera vez en Asturias Esta funcionalidad es exclusiva para suscriptores. Comentar es una ventaja exclusiva para suscriptores ¿Ya eres suscriptor? Necesitas ser suscriptor para poder responder. Necesitas ser suscriptor para poder votar. Reporta un error en esta noticia * Campos obligatorios  «Soy ovetense y marcarle al Real Oviedo era algo que quería tachar de la lista» WhatsApp Facebook X LinkedIn Telegram Bluesky Threads"],
      dtype=object)

In [ ]:
data_df[data_df['texto'].isna()]

,fuente,url,titulo,fecha_publicacion,texto
1051,El Español,https://www.elespanol.com/opinion/vinetas/2025...,El pensador de Podemos,2025-02-21,None
1581,Tribuna Salamanca,https://www.tribunasalamanca.com/noticias/3948...,Señal de televisión y telefonía para todos los...,2025-02-21,None
5184,El Fielato y El Nora,https://www.elfielato.es/articulo/el-nora/alum...,Los alumnos del CP San Cucao recaudan más de 1...,2025-02-20,None
7941,Gente Digital,http://www.gentedigital.es/caceres/noticia/400...,NaN,NaT,None
9334,La Voz de Galicia,https://edicionimpresa.lavozdegalicia.es/la-vo...,NaN,NaT,None
...,...,...,...,...,...
12643,La Voz de Galicia,https://www.lavozdegalicia.es/video/gradario/2...,NaN,NaT,None
12644,La Voz de Galicia,https://www.lavozdegalicia.es/video/gradario/2...,NaN,NaT,None
12645,La Voz de Galicia,https://www.lavozdegalicia.es/video/gradario/2...,NaN,NaT,None
12646,La Voz de Galicia,https://www.lavozdegalicia.es/video/torremarat...,NaN,NaT,None
12647,La Voz de Galicia,https://www.lavozdegalicia.es/video/torremarat...,NaN,NaT,None

In [ ]:
mascara_faltantes = data_df['texto'].isnull() | (data_df['texto'] == '')
datos_faltantes = data_df[mascara_faltantes]
print(f'Articulos que no pudo extraer texto: {len(datos_faltantes)}')

Articulos que no pudo extraer texto: 140

In [ ]:
datos_faltantes.values[:50]

array([['El Español',
        'https://www.elespanol.com/opinion/vinetas/20250221/pensador-podemos/925847407_19.html',
        'El pensador de Podemos', Timestamp('2025-02-21 00:00:00'), None],
       ['Tribuna Salamanca',
        'https://www.tribunasalamanca.com/noticias/394881/senal-de-television-y-telefonia-para-todos-los-ciudadanos-de-la-region',
        'Señal de televisión y telefonía para todos los ciudadanos de la región ',
        Timestamp('2025-02-21 00:00:00'), None],
       ['El Fielato y El Nora',
        'https://www.elfielato.es/articulo/el-nora/alumnos-cp-san-cucao-recaudan-mas-1000-euros-ela/20250220082316075483.html',
        'Los alumnos del CP San Cucao recaudan más de 1.000 euros contra la ELA',
        Timestamp('2025-02-20 00:00:00'), None],
       ['Gente Digital',
        'http://www.gentedigital.es/caceres/noticia/4008039/abre-sus-puertas-en-majadas-de-tietar-caceres-el-museo-de-historia-de-la-computacion-tras-casi-cuatro-anos-de-obras/',
        nan, NaT, None],
       ['La Voz de Galicia',
        'https://edicionimpresa.lavozdegalicia.es/la-voz-de-galicia-a-coruna',
        nan, NaT, None],
       ['ABC',
        'https://tienda.abc.es/suscripcion/esp-3mes1eumes-on-1m-cap--220207-abc.html#vca=esp-3mes1eumes-on-1m-cap--220207-abc&vso=abc&vmc=on&vli=cabecera-a',
        nan, NaT, None],
       ['ABC',
        'https://tienda.abc.es/suscripcion/esp-3mes1eumes-on-1m-cap--220207-abc.html#vca=esp-3mes1eumes-on-1m-cap--220207-abc&vso=abc&vmc=on&vli=cabecera-a-pt',
        nan, NaT, None],
       ['Europa Press', 'https://www.europapress.es', nan, NaT, None],
       ['Europa Press', 'https://www.europapress.es/andalucia/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/andalucia/almeria-00350/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/andalucia/cadiz-00351/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/andalucia/granada-00353/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/andalucia/malaga-00356/', nan, NaT,
        None],
       ['Europa Press', 'https://www.europapress.es/aragon/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/aragon/feriazaragoza-01088/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/aragon/innova-00241/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/aragon/teruel-00359/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/aragon/zaragoza-00360/', nan, NaT,
        None],
       ['Europa Press', 'https://www.europapress.es/asturias/', nan, NaT,
        None],
       ['Europa Press', 'https://www.europapress.es/cantabria/', nan,
        NaT, None],
       ['Europa Press', 'https://www.europapress.es/castilla-lamancha/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-lamancha/albacete-00362/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-lamancha/ciudad-real-00363/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-lamancha/cuenca-00364/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-lamancha/guadalajara-00365/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-lamancha/toledo-00366/',
        nan, NaT, None],
       ['Europa Press', 'https://www.europapress.es/castilla-y-leon/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/avila-00367/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/burgos-00368/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/leon-00369/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/palencia-00370/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/salamanca-00371/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/segovia-00372/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/soria-00373/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/valladolid-00374/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/castilla-y-leon/zamora-00375/', nan,
        NaT, None],
       ['Europa Press', 'https://www.europapress.es/catalunya/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/catalunya/barcelona-00376/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/catalunya/girona-00377/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/catalunya/lleida-00378/', nan, NaT,
        None],
       ['Europa Press', 'https://www.europapress.es/ceuta-y-melilla/',
        nan, NaT, None],
       ['Europa Press', 'https://www.europapress.es/comunicados/', nan,
        NaT, None],
       ['Europa Press',
        'https://www.europapress.es/comunitat-valenciana/', nan, NaT,
        None],
       ['Europa Press',
        'https://www.europapress.es/comunitat-valenciana/alicante-00391/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/comunitat-valenciana/castellon-00392/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/comunitat-valenciana/valencia-00393/',
        nan, NaT, None],
       ['Europa Press', 'https://www.europapress.es/contacto/', nan, NaT,
        None],
       ['Europa Press', 'https://www.europapress.es/cultura/', nan, NaT,
        None],
       ['Europa Press', 'https://www.europapress.es/cultura/cine-00128/',
        nan, NaT, None],
       ['Europa Press',
        'https://www.europapress.es/cultura/exposiciones-00131/', nan,
        NaT, None]], dtype=object)

## Filtrar textos

### Buscar textos que tengan al menos una palabra clave

In [ ]:
# Filtrar por palabras clave
keywords = ['universidad', 'oviedo']

# Regex pattern
pattern = '|'.join(keywords)

# Filtrar dataframe
filtered_df = data_df[data_df['texto'].str.contains(pattern, case=False, na=False)].reset_index(drop=True)

filtered_df

,fuente,url,titulo,fecha_publicacion,texto
0,La Opinión de Málaga,https://www.laopiniondemalaga.es/tendencias21/...,Descubren en Egipto la primera tumba real desd...,2025-02-21,Arqueología / Egiptología La tumba fue descubi...
1,La Opinión de Málaga,https://www.laopiniondemalaga.es/tendencias21/...,Un nuevo estudio comprueba una alarmante reduc...,2025-02-21,Ciencias de la Tierra Glaciares en las Montaña...
2,La Opinión de Málaga,https://www.laopiniondemalaga.es/nacional/2025...,DENUNCIAS DE ACOSO SEXUAL | El Gobierno evita ...,2025-02-21,DENUNCIAS DE ACOSO SEXUAL El fundador de Podem...
3,La Opinión de Málaga,https://www.laopiniondemalaga.es/opinion/2025/...,"López, Rodríguez, Navarro y asociados",2025-02-21,Opinión | La Libreta del Duque de Chantada Mel...
4,La Provincia,https://www.laprovincia.es/buzzeando/2025/02/2...,VIRAL INFLUENCER CANARIAS | Una influencer sob...,2025-02-21,C. P. L. Mar Molina El desconocimiento de aspe...
...,...,...,...,...,...
2585,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/yes/2025...,NaN,NaT,Cuando Javier Cascón te cuenta su filosofía de...
2586,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/yes/2025...,NaN,NaT,"Año 2024, primero de bachillerato en una clase..."
2587,La Voz de Galicia,https://www.lavozdegalicia.es/xlsemanal/cienci...,NaN,NaT,Récord submarino https://www.lavozdegalicia.es...
2588,La Voz de Galicia,https://www.lavozdegalicia.es/xlsemanal/natura...,NaN,NaT,Pon a prueba tu olfato https://www.lavozdegali...
2589,La Voz de Galicia,https://www.mujerhoy.com/celebrities/gonzalo-v...,NaN,NaT,Crear una cuenta Se abre la veda con la prince...

In [ ]:
filtered_df['url'].values[0:100]

array(['https://www.laopiniondemalaga.es/tendencias21/2025/02/21/descubren-egipto-primera-tumba-real-114551152.html',
       'https://www.laopiniondemalaga.es/tendencias21/2025/02/21/nuevo-estudio-comprueba-alarmante-reduccion-114536622.html',
       'https://www.laopiniondemalaga.es/nacional/2025/02/21/gobierno-ahondar-caso-monedero-errejon-114541399.html',
       'https://www.laopiniondemalaga.es/opinion/2025/02/21/lopez-rodriguez-navarro-asociados-114524177.html',
       'https://www.laprovincia.es/buzzeando/2025/02/21/influencer-archipielago-islas-canarias-son-como-jackson-five-solo-te-sabes-dos-dv-114545469.html',
       'https://www.laopiniondemalaga.es/medio-ambiente/2025/02/21/millones-personas-queman-plastico-cocinar-114543379.html',
       'https://www.infobae.com/espana/agencias/2025/02/21/podemos-justifica-su-actuacion-ante-las-acusaciones-de-acoso-contra-monedero/',
       'https://www.infobae.com/colombia/2025/02/21/la-culpa-de-que-les-suban-las-cuotas-del-icetex-a-los-estudiantes-es-de-la-corte-constitucional-aseguro-el-presidente-gustavo-petro-no-entiendo-las-razones/',
       'https://www.infobae.com/america/ciencia-america/2025/02/21/sorprendente-hallazgo-en-egipto-restauran-un-templo-y-encuentran-un-antiguo-mito-de-la-creacion/',
       'https://www.infobae.com/america/ciencia-america/2025/02/21/nuevas-evidencias-sugierieron-que-la-vida-en-la-tierra-pudo-haber-comenzado-mucho-antes-de-lo-que-se-pensaba/',
       'https://www.infobae.com/america/ciencia-america/2025/02/21/hepatitis-b-identificaron-un-mecanismo-clave-en-la-infeccion-y-podria-usarse-contra-el-herpes-y-el-vph/',
       'https://www.infobae.com/america/america-latina/2025/02/21/tres-de-cada-diez-ecuatorianos-caen-del-sistema-financiero-tras-acceso-a-creditos/',
       'https://www.laopiniondemalaga.es/malaga/2025/02/21/malaga-aprueba-ordenanza-quiere-tramitar-114546317.html',
       'https://www.laopiniondemalaga.es/malaga/2025/02/21/foro-satelites-sssif-malaga-crece-alabanza-nasa-114541789.html',
       'https://www.infobae.com/peru/2025/02/20/ingreso-al-nuevo-aeropuerto-jorge-chavez-tuvo-que-ser-redisenado-y-sigue-en-construccion-a-poco-de-la-inauguracion/',
       'https://www.laopiniondemalaga.es/cultura-espectaculos/2025/02/21/museo-picasso-maf-presentan-conferencias-114546661.html',
       'https://www.eldiario.es/la-rioja/liga-senderismo-2025-recorrera-rioja-doce-marchas_1_12073588.html',
       'https://www.larazon.es/espana/belarra-dice-ahora-que-revelaron-acusaciones-monedero-proteger-victimas_2025022167b8609a500f96000114b65b.html',
       'https://www.larazon.es/emergente/semaforo_2025022167b8329a500f960001148355.html',
       'https://www.larazon.es/espana/vejaciones-monedero-sus-alumnas_2025022167b7de2db1a8db0001cfa43e.html',
       'https://www.larazon.es/espana/juan-carlos-monedero-contesta-acusaciones-podemos-tendra-que-aclarar-cosas_2025022167b88d3d417ec20001018fbc.html',
       'https://www.larazon.es/deportes/futbol/estadio-que-marruecos-quiere-quitar-espana-final-mundial-2030_2025022167b84d81500f960001149d6f.html',
       'https://www.larazon.es/medio-ambiente/silice-cristalina-minusculo-polvo-silente_2025022167b755edb1a8db0001cedb05.html',
       'https://www.larazon.es/galicia/quien-era-alfredo-branas-ejemplo-que-pone-como-modelo-unidad-respeto-p7m_2025022167b868cc417ec20001013b82.html',
       'https://www.larazon.es/galicia/galicia-podio-absentismo-laboral-xunta-busca-respuestas-factura-millonaria-p7m_2025022167b850bcb1a8db0001cfeb62.html',
       'https://www.larazon.es/internacional/australia-desvia-cinco-vuelos-ser-alertada-disparos-fuego-real-tres-barcos-guerra-chinos-maniobras_2025022167b85379417ec20001011624.html',
       'https://www.larazon.es/andalucia/sumar-designa-este-sabado-esperanza-gomez-raul-garcia-como-coordinadores-andaluces_2025022167b87720417ec20001015cd6.html',
       'https://www.larazon.es/asturias/fernando-laserna-cocina-nombrado-nuevo-fiscal-delegado-comunidad-autonoma-personas-discapacidad-mayores_2025022167b7b4e5500f9600011436eb.html',
       'https://www.larazon.es/castilla-la-mancha/trabajador-resulta-herido-grave-caerle-encima-tolva-fabrica-villacanas-toledo/20250221/1168744.html',
       'https://www.laprovincia.es/medio-ambiente/2025/02/21/millones-personas-queman-plastico-cocinar-114543391.html',
       'https://www.laprovincia.es/tendencias21/2025/02/21/nuevo-estudio-comprueba-alarmante-reduccion-114536686.html',
       'https://www.laprovincia.es/tendencias21/2025/02/21/descubren-egipto-primera-tumba-real-114551149.html',
       'https://www.larazon.es/castilla-la-mancha/semana-pasado-lluvia-tormentas-vuelta-frio-castilla-mancha-aemet/20250221/1168741.html',
       'https://www.larazon.es/castilla-y-leon/burgos-acoge-foro-trabajo-saborea-espana-participacion-14-destinos-gastronomicos_2025022167b85939417ec20001012020.html',
       'https://www.larazon.es/castilla-y-leon/universidad-leon-suma-c2iet-ponferrada_2025022167b886fb417ec200010187dd.html',
       'https://www.larazon.es/castilla-y-leon/ucav-inaugura-ciclo-teresiano-abordando-oracion-enfoque-escenico_2025022167b85cbdb1a8db0001d000ce.html',
       'https://www.larazon.es/castilla-y-leon/estudio-que-reconstruye-rostro-santa-teresa-jesus_2025022167b8432e500f9600011492f1.html',
       'https://www.larazon.es/castilla-y-leon/espera-marzo-intenso-futuro-autonomia-leonesa_2025022167b8786e417ec20001016182.html',
       'https://www.larazon.es/ciencia/senal-television-llega-aviones-big-bang_2025022167b86786b1a8db0001d01428.html',
       'https://www.larazon.es/cataluna/pere-aragones-negociador-inesperado-dara-conferencia-yale-desescalar-conflictos-secesionistas_2025022167b846dd500f9600011496ea.html',
       'https://www.elespanol.com/eldigitalcastillalamancha/region/20250221/denuncian-impagos-trabajadores-encargan-jardineria-uclm-toledo-talavera-reina/925907505_0.html',
       'https://www.elespanol.com/eldigitalcastillalamancha/cultura/educacion-y-universidad/20250221/uclm-grupo-cecap-laborvalia-presentan-nuevas-iniciativas-inclusion-social/925907716_0.html',
       'https://www.elespanol.com/espana/politica/20250221/actualidad-politica-directo-isa-serra-reitera-podemos-actuo-conocer-denuncias-violencia-sexual-monedero/926007392_10.html',
       'https://www.elespanol.com/el-cultural/escenarios/musica/20250221/zahara-metoo-musica-visto-permitido-deberian-tener-noches-malisimas/924157842_0.html',
       'https://www.elespanol.com/el-cultural/cine/20250221/sam-peckinpah-anos-violento-oeste-perdedores/924907931_0.html',
       'https://www.elespanol.com/espana/politica/20250221/podemos-oculto-denuncias-violencia-sexual-monedero-igual-hizo-sumar-caso-errejon/925657603_0.html',
       'https://www.elespanol.com/invertia/mercados/20250221/ibex-bolsa-directo-hoy-cotizaciones-noticias-tiempo-real/926007391_10.html',
       'https://www.elespanol.com/malaga/deporte/malaga-c-f/20250221/malaga-cf-vs-cd-tenerife-fecha-horario-verlo/925907662_0.html',
       'https://www.elespanol.com/invertia/disruptores/america-tech/20250221/litio-nuevo-oro-siglo-xxi/925277464_12.html',
       'https://www.elespanol.com/invertia/disruptores/ecosistema-startup/startups/20250221/herramienta-ayudara-prensa-aterrizar-ia-abrir-nuevos-nichos-negocio-retorno-real-inversion/925157915_0.html',
       'https://www.elespanol.com/invertia/disruptores/autonomias/navarra/20250221/burocracia-regulacion-desconexion-investigacion-industria-retos-agrotech-navarro/925657621_0.html',
       'https://www.elespanol.com/alicante/vega-baja/20250221/orihuela-aprueba-presupuestos-euros-fortalecer-servicios-municipales/925907506_0.html',
       'https://www.elespanol.com/alicante/economia/innovacion/20250221/posible-recuperar-sabor-original-tomate-ua-impulsa-proyecto-utilizando-residuos-posidonia/925907558_0.html',
       'https://www.elespanol.com/alicante/cultura/musica/20250221/conocieron-tinder-musicos-benidorm-fest-hecho-cancion-ano/925658016_0.html',
       'https://www.eldiario.es/viajes/siete-maravillas-naturales-puedes-disfrutar-visita-navarra_1_12072446.html',
       'https://www.eldiario.es/viajes/ruta-senderista-une-pueblos-malaguenos-axarquia_1_12072738.html',
       'https://www.eldiario.es/vertele/videos/actualidad/sabates-senala-monedero-intermedio-escandalo-acoso-sexual-deja-desear_7_12072694.html',
       'https://www.elespanol.com/aragon/cultura/20250221/lluis-bassat-publicista-coleccionista-arte-ganado-vida-colgado-paredes/925657907_0.html',
       'https://www.elespanol.com/aragon/actualidad/zaragoza/20250221/centro-montecanal-barrio-exclusivo-zaragoza-comprar-casa/925657863_0.html',
       'https://www.eldiario.es/politica/belarra-defiende-actuo-correctamente-monedero-recibieron-testimonios-acoso-sexual-asegura-victimas-pidieron-discrecion_1_12072691.html',
       'https://www.eldiario.es/politica/ayuntamiento-adrada-avila-investiga-si-chale-juez-juan-carlos-peinado-ilegal_1_12073974.html',
       'https://www.eldiario.es/politica/anticorrupcion-pide-cuatro-anos-carcel-caso-rato-abogados-pareja-ayuso_1_12072392.html',
       'https://www.eldiario.es/navarra/chivite-anuncia-programa-inversion-apoyar-sector-industrial_1_12072962.html',
       'https://www.eldiario.es/murcia/politica/organizacion-bds-denuncia-llegada-cartagena-israel-barco-armamento_1_12073724.html',
       'https://www.eldiario.es/murcia/politica/iu-verdes-denuncia-vox-fiscalia-incitar-odio-region-murcia_1_12073069.html',
       'https://www.eldiario.es/murcia/murcia-y-aparte/hilo-carcel-vieja_132_12069252.html',
       'https://www.eldiario.es/murcia/cultura/prostibulos-escuelas-egea-bruno-analiza-prostitucion-cartagena-durante-siglos-xix-xx_1_12072520.html',
       'https://www.eldiario.es/motor/sector_y_mercado/hibridos-mild-hybrid-acapararan-40-ventas-2025_1_12072585.html',
       'https://www.eldiario.es/madrid/somos/tetuan/nueva-venta-suelo-municipal-tetuan-sale-concurso-vivienda-libre-parcela-calle-pamplona_1_12061080.html',
       'https://www.eldiario.es/madrid/somos/mujer-nuevas-placas-ayuntamiento-madrid-homenajean-personalidades-culturales-bancos-retiro_1_12072447.html',
       'https://www.eldiario.es/la-rioja/tesis-ur-certifica-control-seguridad-produccion-carne-rioja_1_12073041.html',
       'https://www.eldiario.es/la-rioja/rastro-festivales-holika-gran-reserva-miami-semana-fechas-previstas_1_12073040.html',
       'https://www.eldiario.es/la-rioja/logrono/logrono-suspende-altas-ampliaciones-terrazas-centro-durante-ano_1_12073158.html',
       'https://www.eldiario.es/la-rioja/logrono/logrono-acoge-homenaje-sabina-flamenco_1_12072777.html',
       'https://www.eldiario.es/politica/decano-abogacia-madrilena-reconoce-consideraron-delictivo-comunicado-fiscalia-caso-pareja-ayuso_1_12072382.html',
       'https://www.eldiario.es/politica/jenni-hermoso-recurrira-sentencia-condena-rubiales-agresion-sexual-le-absuelve-coacciones_1_12073571.html',
       'https://www.eldiario.es/politica/monedero-niega-acusaciones-acoso-sexual-dice-tendra-aclarar-salida-partido_1_12074093.html',
       'https://www.eldiario.es/sociedad/pasar-denuncia-monedero-complutense-acoso-sexual-actuacion-plazos-previstos_1_12072631.html',
       'https://www.eldiario.es/unrwa/todavia-no-he-regresado-hogar-gaza_132_12069361.html',
       'https://www.eldiario.es/tecnologia/elon-musk-cambiara-vez-sistema-verificacion-x-desmentidos-trump-ucrania_1_12072474.html',
       'https://www.eldiario.es/spot/web-nasa-ensena-nombre-imagen-satelite_1_12072965.html',
       'https://www.eldiario.es/sociedad/primera-denuncia-mujer-monedero-llego-cupula_1_12072004.html',
       'https://www.eldiario.es/sociedad/mitad-mayores-cuida-nietos-siente-peor-atendido-hijos-generaciones-anteriores_1_12070069.html',
       'https://www.eldiario.es/politica/supremo-avala-registro-guardia-civil-despacho-fiscal-general_1_12040204.html',
       'https://www.eldiario.es/sociedad/frente-atlantico-dejara-fuertes-lluvias-cielos-cubiertos-oeste-peninsular-viernes_1_12073079.html',
       'https://www.eldiario.es/sociedad/donde-festivo-28-febrero-2025-puente_1_12041929.html',
       'https://www.eldiario.es/sevilla/sevilla-digital/custodiat-nueva-plataforma-impulsa-digitalizacion-eficiencia-gestion-documental-diputacion-sevilla_132_12073725.html',
       'https://www.eldiario.es/sevilla/multitudinaria-marcha-24-pueblos-sevilla-agobio-asistencial-sanidad-publica_1_12072536.html',
       'https://www.eldiario.es/sevilla/grafiti-fondo-negro-animo-lucro-pintara-muros-ies-san-pablo-sevilla_1_12072695.html',
       'https://www.eldiario.es/politica/ultima-hora-actualidad-politica-directo_6_12072595.html',
       'https://www.elespanol.com/castilla-y-leon/region/valladolid/20250221/jana-burgalesa-queria-pintora-hace-magia-fibras-vegetales-conocido-pueblo-valladolid/925407851_0.html',
       'https://www.elespanol.com/castilla-y-leon/region/zamora/20250221/universidad-salamanca-estudia-implantar-nuevas-formaciones-especializacion-campusdezamora/925907654_0.html',
       'https://www.elespanol.com/castilla-y-leon/region/valladolid/20250221/pianista-vallisoletano-guillermo-hernandez-finalista-premio-princesa-girona-arte/925907726_0.html',
       'https://www.elespanol.com/castilla-y-leon/region/valladolid/20250221/operacion-policial-exitosa-detener-ladron-reincidente-escuela-ingenierias-industriales-uva/925907664_0.html',
       'https://www.elespanol.com/ciencia/nutricion/20250221/adios-atun-lata-pescado-sal-espana-bueno-corazon-nutricionista-luis-zamora/924907947_0.html',
       'https://www.elespanol.com/ciencia/nutricion/20250221/fruto-seco-saludable-triunfa-mercadona-barato-rico-magnesio-recomendado-adelgazar/925157522_0.html',
       'https://www.elespanol.com/castilla-y-leon/region/salamanca/20250221/estudio-sepulcro-santa-teresa-alba-tormes-permitira-reconstruccion-rostro/925907707_0.html',
       'https://www.elperiodico.com/es/internacional/20250221/santorini-terremotos-grecia-volcan-etna-hoy-ultima-hora-directo-114073834',
       'https://www.elperiodico.com/es/internacional/20250221/donald-trump-aranceles-ultima-hora-directo-113951568',
       'https://www.elperiodico.com/es/opinion/20250221/smi-distinto-ciudad-o-barrio-articulo-marti-saballs-pons-114546150'],
      dtype=object)

## Buscar textos que tengan todas las palabras clave

In [ ]:
# Lista de palabras clave
keywords = ['universidad', 'oviedo']

# Crear una condición de filtro para cada palabra clave
filter_condition = data_df['texto'].str.contains(keywords[0], case=False, na=False)

for keyword in keywords[1:]:
    filter_condition &= data_df['texto'].str.contains(keyword, case=False, na=False)

# Aplicar filtro
filtered_df_all = data_df[filter_condition].reset_index(drop=True)

filtered_df_all

,fuente,url,titulo,fecha_publicacion,texto
0,La Razón,https://www.larazon.es/galicia/quien-era-alfre...,"<![CDATA[¿Quién era Alfredo Brañas, el ejemplo...",2025-02-21,Galicia España Local Opinión Internacional Eco...
1,La Razón,https://www.larazon.es/asturias/fernando-laser...,"Fernando Laserna Cocina, nombrado nuevo Fiscal...",2025-02-21,Asturias España Local Opinión Internacional Ec...
2,Nortes,https://www.nortes.me/articulos-recientes/,NaN,2025-02-21,El general Augusto Pinochet quería ser un augu...
3,Nortes,https://www.nortes.me/2025/02/21/video-entrevi...,NaN,2025-02-21,El filósofo asturiano desglosa en esta convers...
4,Nortes,https://www.nortes.me/2025/02/21/una-estatua-p...,NaN,2025-02-21,Las políticas asturianas de memoria han sido a...
...,...,...,...,...,...
120,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/oviedo/...,NaN,NaT,Un total de 72 investigadoras de la Universida...
121,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/oviedo/...,NaN,NaT,La Consejería de Educación inaugurará el próxi...
122,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/oviedo/...,NaN,NaT,Andrew Silin y Kate Yakusheva se conocían de c...
123,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/siero/2...,NaN,NaT,"El alcalde de Siero, Ángel García, se ha mostr..."
124,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/lemos/ch...,NaN,NaT,Saltó la sorpresa en Chantada. El Universidad ...

In [ ]:
def mostrar_informacion(data_df):

    for index, fila in data_df.iterrows():
        if pd.isna(fila['fecha_publicacion']):
            fecha = 'Desconocido'
        else:
            fecha = fila['fecha_publicacion'].strftime('%Y/%m/%d')
        fuente = fila['fuente']

        titulo = 'Desconocido'
        if pd.notna(fila['titulo']):
            titulo = fila['titulo']

        print(titulo)
        print(fila['url'])
        print(f'{fecha} - {fuente}')
        print()

mostrar_informacion(filtered_df_all)

<![CDATA[¿Quién era Alfredo Brañas, el ejemplo que el PP pone como modelo de unidad y respeto?]]>
https://www.larazon.es/galicia/quien-era-alfredo-branas-ejemplo-que-pone-como-modelo-unidad-respeto-p7m_2025022167b868cc417ec20001013b82.html
2025/02/21 - La Razón

Fernando Laserna Cocina, nombrado nuevo Fiscal Delegado en la comunidad autónoma de Personas con Discapacidad y Mayores
https://www.larazon.es/asturias/fernando-laserna-cocina-nombrado-nuevo-fiscal-delegado-comunidad-autonoma-personas-discapacidad-mayores_2025022167b7b4e5500f9600011436eb.html
2025/02/21 - La Razón

Desconocido
https://www.nortes.me/articulos-recientes/
2025/02/21 - Nortes

Desconocido
https://www.nortes.me/2025/02/21/video-entrevista-con-juan-ponte-sobre-su-libro-el-capitalismo-no-existe/
2025/02/21 - Nortes

Desconocido
https://www.nortes.me/2025/02/21/una-estatua-para-el-rector-alas/
2025/02/21 - Nortes

La sierense Susana Madera será la nueva viceconsejera de Medio Ambiente
https://www.rtpa.es/noticias-asturias/2025-02-21/La-sierense-Susana-Madera-sera-la-nueva-viceconsejera-de-Medio-Ambiente_111740125730.html
2025/02/21 - Radiotelevisión del Principado de Asturias (RTPA)

Gijón estrena sus primeros seis autobuses eléctricos mientras ultima su plan para dar servicio a la zona rural
https://www.lne.es/gijon/2025/02/21/emtusa-estrena-primeros-seis-autobuses-114547133.html
2025/02/21 - La Nueva España

Así abrirá el nuevo IES de La Corredoria: con más de medio millar de alumnos, 40 profesores y los seis cursos
https://www.lne.es/oviedo/la-corredoria/2025/02/21/problemas-masificacion-resolveran-proximo-curso-114535565.html
2025/02/21 - La Nueva España

"A cualquier universitario le recomendaría ir a un colegio mayor"
https://www.lne.es/oviedo/2025/02/21/universitario-le-recomendaria-colegio-mayor-114527400.html
2025/02/21 - La Nueva España

Un torneo de debate reúne a más de 130 estudiantes en el Cristo
https://www.lne.es/oviedo/2025/02/21/torneo-debate-reune-130-estudiantes-114529229.html
2025/02/21 - La Nueva España

El rector de la Universidad de Oviedo, dispuesto a "avanzar en los proyectos en común" con Siero en el Centro de Inteligencia Artificial
https://www.lne.es/siero/2025/02/21/rector-universidad-oviedo-dispuesto-avanzar-114547345.html
2025/02/21 - La Nueva España

Así es Steven Verplancken, la nueva pieza del Alimerka en Primera FEB: "Pregunté por Oviedo y me dijeron ‘si no defiendes no vayas’"
https://www.lne.es/deportes/deporte-astur/2025/02/21/steven-verplancken-nueva-pieza-alimerka-114524452.html
2025/02/21 - La Nueva España

Cuatro mil hogares ya pueden conocer en tiempo real su consumo de agua
https://www.lne.es/aviles/2025/02/21/cuatro-mil-hogares-conocer-tiempo-114528069.html
2025/02/21 - La Nueva España

Una escucha activa y empatía, claves para una mejor relación paternofilial
https://www.lne.es/aviles/2025/02/21/escucha-activa-empatia-claves-mejor-114528055.html
2025/02/21 - La Nueva España

El llamativo experimento de un científico asturiano en la Antártida (y tiene relación con la basura y el whiskey)
https://www.lne.es/asturias-exterior/2025/02/21/llamativo-experimento-cientifico-asturiano-antartida-114535615.html
2025/02/21 - La Nueva España

Los exrectores ven "necesaria" la nueva ley de Ciencia y piden cumplirla: "Puede llegar a ser insuficiente"
https://www.lne.es/asturias/2025/02/21/exrectores-ven-necesaria-nueva-ley-114528568.html
2025/02/21 - La Nueva España

La firme voluntad de Asturias de crecer en innovación: solo Galicia crece tanto en la inversión (pero seguimos por debajo de la media)
https://www.lne.es/asturias/2025/02/21/firme-voluntad-asturias-crecer-innovacion-114528260.html
2025/02/21 - La Nueva España

Drones para estudiar a las carabelas portuguesas y predecir su llegada a la costa de Gran Canaria
https://www.eldiario.es/canariasahora/ciencia_y_medio_ambiente/drones-estudiar-carabelas-portuguesas-predecir-llegada-costa-gran-canaria_1_12073769.html
2025/02/21 - ElDiario.es

La Fiscalía recurre la absolución del exministro Álvarez-Cascos por uso indebido de fondos de Foro Asturias
https://www.eldiario.es/asturias/fiscalia-recurre-absolucion-exministro-alvarez-cascos-indebido-fondos-foro-asturias_1_12073557.html
2025/02/21 - ElDiario.es

«Somos el altavoz del Colegio Mayor América»
https://www.elcomercio.es/oviedo/antiguos-alumnos-colegio-mayor-america-miguel-cuesta-20250221080826-nt.html
2025/02/21 - El Comercio

«La Ley de Ciencia de Asturias es ambiciosa, pero si no hay un compromiso económico serio puede ser papel mojado»
https://www.elcomercio.es/asturias/ley-ciencia-asturias-ambiciosa-ignacio-villaverde-universidad-oviedo-20250221154943-nt.html
2025/02/21 - El Comercio

Qué hacer en Asturias hoy, 20 de febrero
https://www.elcomercio.es/planes/que-hacer-asturias-20-febrero-agenda-planes-20250220093928-nt.html
2025/02/20 - El Comercio

¿Cuál es el origen de la expresión ponerse como el Quico?
https://www.telecinco.es/noticias/curioso/20250220/origen-expresion-ponerse-como-quico_18_014595274.html
2025/02/20 - Telecinco

SOCIALISTAS DE ASTURIAS | De los gusanitos y el albergue a lo más alto del socialismo asturiano: la historia de la generación de Barbón que controla la FSA
https://www.lne.es/asturias/2025/02/20/gusanitos-albergue-alto-socialismo-asturiano-114299241.html
2025/02/20 - La Nueva España

La sierense Susana Madera, nueva viceconsejera de Medio Ambiente del Principado
https://www.lne.es/asturias/2025/02/20/sierense-susana-madera-nueva-viceconsejera-114526767.html
2025/02/20 - La Nueva España

Divulgar para combatir los bulos y la pseudociencia
https://www.elcomercio.es/asturias/alba-moran-divulgar-combatir-bulos-pseudociencia-20250220165646-nt.html
2025/02/20 - El Comercio

Susana Madera será viceconsejera de Medio Ambiente del Principado de Asturias
https://www.elcomercio.es/asturias/susana-madera-viceconsejera-medio-ambiente-principado-asturias-20250220213822-nt.html
2025/02/20 - El Comercio

Álex Tirador, del Alimerka Oviedo Baloncesto, pasa a jugar en Tercera FEB con el Universidad
https://www.lne.es/deportes/deporte-astur/2025/02/20/alex-tirador-alimerka-oviedo-baloncesto-114524469.html
2025/02/20 - La Nueva España

Carlos López: «La orografía hace que Asturias sea una potencia investigadora y un referente en geología»
https://www.elcomercio.es/culturas/aula-cultura/aula-cultura-voz-aviles-carlos-lopez-argayos-asturias-20250220104352-nt.html
2025/02/20 - El Comercio

El nuevo instituto de La Corredoria Margarita Salas se inaugurará en septiembre
https://www.rtpa.es/noticias-asturias/2025-02-20/El-nuevo-instituto-de-La-Corredoria-Margarita-Salas-se-inaugurara-en-septiembre_111740058734.html
2025/02/20 - Radiotelevisión del Principado de Asturias (RTPA)

Noelia Rico sustituye a Roger Campione al frente del Centro de Estudios sobre el Impacto Social de la Inteligencia Artificial
https://www.rtpa.es/noticias-asturias/2025-02-20/Noelia-Rico-sustituye-a-Roger-Campione-al-frente-del-Centro-de-Estudios-sobre-el-Impacto-Social-de-la-Inteligencia-Artificial_111740044761.html
2025/02/20 - Radiotelevisión del Principado de Asturias (RTPA)

El Acuario de Gijón pasa a jugar "en la Champions League": "Sois un modelo a seguir en la élite de la conservación"
https://www.lne.es/gijon/gijon-oeste/2025/02/20/acuario-gijon-pasa-jugar-champions-114525005.html
2025/02/20 - La Nueva España

PROYECTOS SOCIALES | La Fundación Vinjoy quiere exportar sus proyectos a Iberoamérica
https://www.lne.es/oviedo/2025/02/20/fundacion-vinjoy-quiere-exportar-proyectos-114525237.html
2025/02/20 - La Nueva España

ACTOS LA REGENTA OVIEDO | Oviedo celebra los  140 años de La Regenta" con cine, teatro, zarzuela, conciertos, lecturas: fechas y horas de las actividades
https://www.lne.es/oviedo/2025/02/20/oviedo-celebra-140-anos-regenta-114516730.html
2025/02/20 - La Nueva España

Dos candidaturas optan a dirigir el PSOE de Oviedo: Delia Losa disputa el cargo con Aquilino Díaz
https://www.eldiario.es/asturias/candidaturas-optan-dirigir-agrupacion-socialista-oviedo-delia-losa-disputa-cargo-aquilino-diaz_1_12069529.html
2025/02/20 - ElDiario.es

Fernando Laserna, nuevo fiscal delegado en Asturias de Personas con Discapacidad y Mayores
https://www.eldiario.es/asturias/fernando-laserna-nuevo-fiscal-delegado-asturias-personas-discapacidad-mayores_1_12068985.html
2025/02/20 - ElDiario.es

La plantilla de la UD Las Palmas vale 120 millones de euros
https://www.eldiario.es/canariasahora/Deportes/futbol/plantilla-ud-palmas-vale-120-millones-euros_1_12069658.html
2025/02/20 - ElDiario.es

Yolanda Díaz arranca el estudio para que los trabajadores ganen poder en las empresas: “Es una revolución democrática”
https://www.eldiario.es/economia/yolanda-diaz-arranca-estudio-dar-trabajadores-empresas-revolucion-democratica_1_12070002.html
2025/02/20 - ElDiario.es

Yolanda Díaz avanza una futura Ley de Democracia en la Empresa basándose en propuestas de expertos
https://www.elespanol.com/invertia/empresas/20250220/yolanda-diaz-avanza-futura-ley-democracia-empresa-basandose-propuestas-expertos/925657799_0.html
2025/02/20 - El Español

La profesora Noelia Rico, nueva directora del centro de Inteligencia Artificial de Lugones
https://www.elcomercio.es/area-metropolitana-asturias/siero-centro/noelia-rico-directora-centro-inteligencia-artificial-lugones-20250219202621-nt.html
2025/02/19 - El Comercio

Alba Rodríguez, nueva secretaria general de las Juventudes Socialistas de Avilés
https://www.elcomercio.es/aviles/alba-rodriguez-secretaria-general-juventudes-socialistas-aviles-20250219175846-nt.html
2025/02/19 - El Comercio

El PSOE dice que Foro y PP están convirtiendo Gijón en una ciudad gregaria de Oviedo
https://www.elcomercio.es/gijon/psoe-foro-pp-gijon-ciudad-gregaria-oviedo-20250219203919-nt.html
2025/02/19 - El Comercio

Encontrado en Ribadeo el gusano invasor que come mejillones y ostras
https://www.rtpa.es/noticias-asturias/2025-02-19/Encontrado-en-Ribadeo-el-gusano-invasor-que-devora-mejillones-y-ostras_111739966898.html
2025/02/19 - Radiotelevisión del Principado de Asturias (RTPA)

Reunión del Ingenium Alliance Council en la Universidad de Oviedo
https://www.rtpa.es/noticias-asturias/2025-02-18/Reunion-del-Ingenium-Alliance-Council-en-la-Universidad-de-Oviedo_111739885990.html
2025/02/18 - Radiotelevisión del Principado de Asturias (RTPA)

Desconocido
https://migijon.com/los-tres-templos-de-el-bibio/
2025/02/18 - Mi Gijón

Desconocido
https://www.culturalgijonesa.org/laboral-centro-de-arte-y-asturias-el-experimentalismo-popular-de-pablo-de-soto/
2025/02/18 - Cultural Gijonesa

Desconocido
http://www.asturiasmundial.com/noticia/111057/peter-burke-id-arcelormittal-gregory-ludkovsky-honoris-causa-por-oviedo/#.XcBLIdT1TaQ.tumblr
Desconocido - Asturias Mundial

Desconocido
http://www.asturiasmundial.com/noticia/138972/asturias-convierte-8m-mes-accion-educacion-cine-deporte-impulsar-igualdad-real/
Desconocido - Asturias Mundial

Desconocido
http://www.asturiasmundial.com/noticia/138978/asturias-blinda-futuro-cientifico-nueva-ley-ciencia-mas-financiacion-csic-propio-ecosistema-innovador/
Desconocido - Asturias Mundial

Desconocido
http://www.asturiasmundial.com/noticia/138997/noelia-rico-nueva-directora-ceisia-una-experta-inteligencia-artificial-frente-futuro-tecnologico-asturias/
Desconocido - Asturias Mundial

Desconocido
http://www.asturiasmundial.com/noticia/139005/asturias-consolida-como-referente-computacion-cuantica-avances-clave-simulacion-aplicaciones-empresariales/
Desconocido - Asturias Mundial

Desconocido
http://www.asturiasmundial.com/noticia/139025/aguas-aviles-lanza-plan-estrategico-resencialr-30-medidas-transformar-gestion-agua-ciudad/
Desconocido - Asturias Mundial

Desconocido
http://www.gentedigital.es/albacete/noticia/4005052/una-marcha-en-albacete-dara-10-millones-de-pasos-y-recaudara-3000-euros-para-reparar-el-restaurante-el-buho-de-letur/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/albacete/noticia/4006825/uclm-acoge-en-albacete-el-i-congreso-internacional-sobre-la-enfermedad-neurodegenerativa-demencia-con-cuerpos-de-lewy/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4006506/teatre-arniches-presenta-la-maestra-de-la-compania-de-titeres-anita-maravillas/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4006757/el-cenid-presenta-un-metodo-para-agilizar-procesos-administrativos-mediante-automatizacion-e-ia/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4007606/un-estudio-de-csic-umh-revela-un-mecanismo-clave-para-controlar-la-actividad-que-regula-la-identidad-neuronal/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4008564/investigadores-de-la-ua-reutilizan-residuos-de-posidonia-oceanica-para-recuperar-el-sabor-del-tomate/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4008669/hydros-power-del-parque-cientifico-de-la-ua-capta-190000-euros-del-instituto-de-tecnologia-europeo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/almeria/noticia/4008134/diputacion-la-alianza-almeria-unida-por-la-igualdad-presenta-sus-actividades-de-cara-al-dia-de-la-mujer/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/avila/noticia/4005365/la-ucav-bate-record-de-participacion-en-el-85-encuentro-de-universitarios-con-mas-de-170-participantes/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/avila/noticia/4007892/la-ucav-aborda-en-unas-jornadas-la-proteccion-de-la-naturaleza-en-el-ambito-policial/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/burgos/noticia/4002695/el-73-de-los-jovenes-de-burgos-que-usan-el-servicio-de-salud-joven-consultan-por-ansiedad-y-gestion-emocional/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/burgos/noticia/4002816/la-ubu-se-une-al-observatorio-tecnologico-del-hidrogeno-enagas-para-impulsar-la-innovacion-en-hidrogeno-renovable/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/burgos/noticia/4003371/proteccion-civil-de-burgos-se-centra-en-2024-en-la-concienciacion-en-seguridad-en-los-centros-escolares/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ciudad-real/noticia/4007043/rozalen-y-la-unidad-militar-de-emergencias-entre-los-reconocimientos-del-consejo-social-de-la-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cordoba/noticia/4008177/cien-escolares-de-cabra-aprenderan-a-prevenir-accidentes-con-la-campana-aprende-a-crecer-con-seguridad/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cordoba/noticia/4008297/villamandos-apuesta-por-el-liderazgo-de-los-andaluces-como-eslabon-crucial-en-la-cadena-innovadora/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/gijon/noticia/4008117/diaz-avanza-una-futura-ley-de-democracia-en-la-empresa-basada-en-propuestas-de-expertos-uno-de-la-universidad-de-oviedo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/granada/noticia/4008084/el-escritor-jorge-volpi-reflexionara-sobre-la-historia-del-mundo-en-una-charla-en-la-madraza/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/guadalajara/noticia/4005020/c-lm-tendra-lista-antes-de-semana-santa-la-estrategia-para-blindar-la-gratuidad-del-primer-ano-de-matricula-en-la-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/guadalajara/noticia/4005186/video-c-lm-tendra-lista-antes-de-semana-santa-la-estrategia-para-blindar-gratuidad-del-primer-ano-de-matricula-en-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4008100/el-proyecto-bioecon4fish-incorpora-la-dimension-economica-y-social-a-la-pesqueria-del-boqueron-en-el-golfo-de-cadiz/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4008222/rosa-maria-leon-y-rosario-marquez-reciben-el-premio-a-la-excelencia-investigadora-jose-luis-garcia-palacios/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ibiza/noticia/4006628/educacion-gestionara-la-cobertura-de-las-plazas-de-los-ates-a-partir-de-septiembre/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ibiza/noticia/4006894/el-govern-inicia-las-obras-de-ampliacion-del-ceip-can-misses-de-ibiza/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/jaen/noticia/4008037/el-colegio-san-agustin-de-linares-cuenta-con-una-nueva-aula-de-educacion-especial-en-este-curso-escolar/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/jaen/noticia/4008250/ccoo-se-moviliza-contra-los-incumplimientos-reiterados-de-la-junta-en-el-sistema-universitario-publico/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/jaen/noticia/4008698/unia--la-sede-de-la-unia-acoge-una-conferencia-sobre-antonio-machado-y-baeza/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/lleida/noticia/4001508/lleidanet-firma-contratos-de-672000-euros-en-colombia-y-peru-en-el-tercer-trimestre-de-2024/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/logrono/noticia/4007910/hector-serrat-ibarz-del-ies-la-laboral-campeon-de-la-fase-local-de-la-xvi-olimpiada-espanola-de-geologia/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/logrono/noticia/4008536/la-uned-rehabilita-un-calado-en-sus-instalaciones-para-seguir-protegiendo-la-tradicion-que-nos-define-como-region/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/malaga/noticia/4008571/pp-destaca-la-apuesta-sin-precedente-de-la-junta-en-financiacion-y-modernizacion-de-universidad-publica/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/segovia/noticia/4007001/el-mapa-de-machado-lleva-a-visitantes-y-vecinos-de-segovia-a-los-lugares-por-los-que-se-movia-el-poeta-en-la-ciudad/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/sevilla/noticia/4008581/tres-alumnos-de-la-us-entre-los-diez-mejores-en-examenes-de-especializacion-de-medicina-biologia-y-enfermeria/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/sevilla/noticia/4008617/cuatro-universidades-andaluza-acogen-el-programa-first-lego-league-para-fomentar-la-creatividad-y-el-talento-digital/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/sevilla/noticia/4008684/la-fundacion-descubre-presenta-en-tanger-una-exposicion-sobre-el-analisis-matematico-y-artistico-de-la-cultura-andalusi/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/tenerife/noticia/4008196/canarias-invertira-425000-euros-en-ayudas-exclusivas-a-apoyar-el-desarrollo-de-artes-visuales-en-las-islas/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/toledo/noticia/4008609/la-uclm-el-grupo-cecap-y-laborvalia-presentan-nuevas-iniciativas-para-la-inclusion-social/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/valladolid/noticia/4008757/psoe-valladolid-propondra-en-el-pleno-recordar-el-50-aniversario-del-cierre-de-la-uva-y-las-protestas-sociales-de-1975/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/vigo/noticia/4001273/robots-para-ayudar-a-ninos-con-autismo-para-hacer-inventarios-o-para-emergencias-participan-en-las-jai/
Desconocido - Gente Digital

Desconocido
https://cualia.es/el-que-susurra-john-dickson-carr/
Desconocido - Cualia

Desconocido
https://www.abc.es/salud/enfermedades/mejores-otorrinos-espanoles-elegidos-especialistas-oido-nariz-20250218041756-nt.html
Desconocido - ABC

Desconocido
https://www.abc.es/salud/enfermedades/mejores-otorrinos-espanoles-elegidos-especialistas-oido-nariz-20250218041756-nt.html#vtm_modulosEngag=lomas:salud:noticia:5
Desconocido - ABC

Desconocido
https://www.asturiasmundial.com/fotonews/852/entrega-premio-ana-casanueva-aspace-asturias/
Desconocido - Asturias Mundial

Desconocido