## Instalación de librerías

In [4]:
!pip install -q scrapy
#!pip install -q newspaper4k
!pip install -q newspaper3k
!pip install -q lxml_html_clean

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\rebec\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\rebec\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\rebec\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

# Articulos de mapas de sitio usando scrapy

In [5]:
!scrapy startproject news_scraper

Error: scrapy.cfg already exists in C:\Users\rebec\OneDrive - Universidad de Oviedo\Escritorio\TFG\news_scraper

## Extracción de URLs

In [6]:
%cd news_scraper

c:\Users\rebec\OneDrive - Universidad de Oviedo\Escritorio\TFG\news_scraper

In [ ]:
%%writefile "news_extractor_spider.py"
import scrapy
from newspaper import build, Config, Article
import requests
from urllib.parse import urljoin, urlparse
import os
import time
import re
from datetime import datetime
import gzip
from scrapy.selector import Selector
import dateutil

class NewsUrlExtractorSpider(scrapy.Spider):
    name = 'news_extractor'

    def __init__(self, date="2025-01-01", *args, **kwargs):
        super(NewsUrlExtractorSpider, self).__init__(*args, **kwargs)
        self.from_date = datetime.strptime(date, '%Y-%m-%d').date()
        self.invalid_url_words = {'section', 'tag', 'template',
                                  'category', 'author', 'page-sitemap'
                                  'categories', 'video', 'image', 'temas',
								                  'live', 'microsite', 'focus', 'blog',
                                  'ocio', 'cine', 'board', 'character'}


    # Lista de páginas web
    start_urls=[
        'https://www.elcomercio.es/',
        'https://www.lne.es/',
        'https://www.lavanguardia.com/',
        'https://www.larazon.es/',
        'https://www.rtpa.es/',
        'https://www.europapress.es/',
        'https://www.abc.es/',
        'https://www.20minutos.es/',
        'https://www.elperiodico.com/',
        'https://www.eldiario.es/',
        'https://www.elconfidencial.com/',
        'https://www.culturalgijonesa.org/',
        'https://www.elespanol.com/',
        'https://www.nortes.me/',
        'https://www.asturiasmundial.com/',
        'https://www.tribunasalamanca.com/',
        'https://migijon.com/',
        'https://www.telecinco.es/',
        'https://www.laprovincia.es/',
        'https://www.laopiniondemalaga.es/',
        'https://www.elfielato.es/',
        'https://www.teleprensa.com/',
        'https://www.infobae.com/',
        'https://www.lavozdeasturias.es/', #newspaper
        'https://cualia.es/', #newspaper
        'https://www.lavozdegalicia.es/', # newspaper
        'http://www.gentedigital.es/', #newspaper
    ]

    # Metadata: nombre y sitemap
    metadata_urls={
        'https://www.elcomercio.es/': {'nombre': 'El Comercio'},
        'https://www.lne.es/': {'nombre': 'La Nueva España'},
        'https://www.lavanguardia.com/': {'nombre': 'La Vanguardia',
                                          'sitemap': 'sitemap-google-news.xml'},
        'https://www.larazon.es/': {'nombre': 'La Razón'},
        'https://www.rtpa.es/': {'nombre': 'Radiotelevisión del Principado de Asturias (RTPA)',
                                 'sitemap': 'sitemap-noticias.xml'},
        'https://www.europapress.es/': {'nombre': 'Europa Press'},
        'https://www.abc.es/': {'nombre': 'ABC'},
        'https://www.20minutos.es/': {'nombre': '20 Minutos',
                                      'sitemap': 'sitemap-google-news.xml'},
        'https://www.elperiodico.com/' : {'nombre': 'El Periódico',
                                          'sitemap': 'google-news.xml'},
        'https://www.eldiario.es/' : {'nombre': 'ElDiario.es'},
        'https://www.lavozdeasturias.es/': {'nombre': 'La Voz de Asturias'}, #newspaper
        'https://www.elconfidencial.com/': {'nombre': 'El Confidencial',
                                            'sitemap': 'newsitemap_4.xml'},
        'https://cualia.es/': {'nombre': 'Cualia'}, #newspaper
        'https://www.culturalgijonesa.org/': {'nombre': 'Cultural Gijonesa'},
        'https://www.elespanol.com/' : {'nombre': 'El Español',
                                        'sitemap': 'sitemap_google_news.xml'},
        'https://www.nortes.me/': {'nombre': 'Nortes'},
        'https://www.lavozdegalicia.es/': {'nombre': 'La Voz de Galicia'},
        'https://www.asturiasmundial.com/': {'nombre': 'Asturias Mundial'},
        'https://www.tribunasalamanca.com/': {'nombre': 'Tribuna Salamanca'},
        'https://migijon.com/': {'nombre': 'Mi Gijón'},
        'http://www.gentedigital.es/' : {'nombre': 'Gente Digital'}, #newspaper
        'https://www.infobae.com/' : {'nombre': 'Infobae',
                                      'sitemap': 'arc/outboundfeeds/news-sitemap2/'},
        'https://www.telecinco.es/' : {'nombre': 'Telecinco'},
        'https://www.laprovincia.es/' : {'nombre': 'La Provincia'},
        'https://www.laopiniondemalaga.es/': {'nombre': 'La Opinión de Málaga'},
        'https://www.elfielato.es/': {'nombre': 'El Fielato y El Nora'},
        'https://www.teleprensa.com/': {'nombre': 'Teleprensa'}
    }


    custom_settings = {
        'USER_AGENT': "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0"
    }


    # Para extracción de xmls
    namespaces = {
        'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9',  # Default namespace
        'news': 'http://www.google.com/schemas/sitemap-news/0.9'
    }

    def get_base_url(self, url):
        parsed_url = urlparse(url)
        return f"{parsed_url.scheme}://{parsed_url.netloc}/"

    def normalize_date(self, date_string):
        try:
            # Conviertir la cadena de fechas en un objeto datetime
            parsed_date = dateutil.parser.parse(date_string)
            # Formatea el objeto datetime como 'YYYY-MM-DD'
            #return parsed_date.strftime('%Y-%m-%d')
            return parsed_date.date()
        except (ValueError, TypeError):
            raise ValueError(f"Formato de fecha inválido: '{date_string}'")

    def is_valid_xml_url(self, sitemap_url):
        for invalid_word in self.invalid_url_words:
            if invalid_word in sitemap_url:
                return False

        pattern = r'\b(1[0-9]{3}|20[0-1][0-9]|202[0-4])\b' # Matches 1000-1999, 2000-2019, and 2020-2024
        match_url = re.search(pattern, sitemap_url)
        if match_url:
            return False
        else:
            return True

    def parse(self, response):#se construye la url del archivo robots.txt para buscar los sidemaps
        robots_url = urljoin(response.url, "/robots.txt")
        print(f'Robots URL: {robots_url}')
        yield scrapy.Request(robots_url, callback=self.parse_robots, meta={'domain': response.url})


    def parse_robots(self, response):
        if response.status != 200: #verificamos que robots sea accesible
            print(f"Error al acceder a la url: {response.status}")
            return

        domain = response.meta['domain']
        domain_base = self.get_base_url(domain)
        current_sitemap_urls = set() #[]

        # Extraer urls de sitemaps de robots.txt
        for line in response.text.splitlines():
            if line.lower().startswith('sitemap:'):
                sitemap_url = line.split(':', 1)[1].strip()
                parsed_url = urlparse(sitemap_url)
                file_path = parsed_url.path
                file_name, file_extension = os.path.splitext(file_path)
                if file_extension.lower() == ".xml" and self.is_valid_xml_url(sitemap_url):
                    current_sitemap_urls.add(sitemap_url)

        if len(current_sitemap_urls) > 0:#Primero, si en robots apaerecen sidemaps
            print(f"Se encontraron los siguientes enlaces xml: {current_sitemap_urls}")
            for sitemap_url in current_sitemap_urls:
                print(f"Accediendo al siguiente enlace... {sitemap_url}")
                #yield scrapy.Request(sitemap_url, callback=self.parse_sitemap)  # Llamada recursiva
                yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain) )

        elif domain_base in self.metadata_urls and 'sitemap' in self.metadata_urls[domain_base]:#Segundo, sino, se accede al sidemap especificado
            print("No se encontraron enlaces xml en robots.txt.", end=" ")
            sitemap_name = self.metadata_urls[domain_base]['sitemap']
            #sitemap_name = self.sitemap_urls[domain]
            sitemap_url = urljoin(domain_base, sitemap_name)
            print(f"Accediendo al siguiente enlace especificado... {sitemap_url}")
            #yield scrapy.Request(sitemap_url, callback=self.parse_sitemap)
            yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain_base) )
        else:#Tercero, accedemos con newspaper
            print("No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...")
            # Si no se encuentra ningún mapa del sitio,
            # utilizar Newspaper4k para obtener las URL de los artículos de noticias
            yield from self.get_news_urls(domain)



    def parse_sitemap(self, response, domain=None):#Accedemos a los sidemaps

        # Sitemaps anidados. Tag <sitemap>
        for sitemap in response.xpath('//ns:sitemap', namespaces=self.namespaces):
            sitemap_loc = sitemap.xpath('./ns:loc/text()', namespaces=self.namespaces).get()

            # Omitir sitemaps antiguos
            last_mod = sitemap.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()
            if last_mod:
                lastmod = self.normalize_date(last_mod)
                if lastmod < self.from_date:
                    continue

            # Verificar que la url es un archivo xml
            parsed_url = urlparse(sitemap_loc)
            file_path = parsed_url.path
            file_name, file_extension = os.path.splitext(file_path)

            if file_extension.lower() == ".xml" and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                #print(f'Se encontró otro xml dentro del archivo actual: {sitemap_loc}') ## lots of outputs
                if sitemap_loc:
                    #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap)  # Llamada recursiva
                    yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap(response, domain) )
            elif file_extension.lower() == '.gz'  and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                print(f"Se encontró archivo comprimido {sitemap_loc}")
                #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap_gz)
                yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap_gz(response, domain) )


        # Extraer datos de cada tag <url>
        for url in response.xpath('//ns:url', namespaces=self.namespaces):

            loc = url.xpath('./ns:loc/text()', namespaces=self.namespaces).get()
            title = url.xpath('./news:news/news:title/text()', namespaces=self.namespaces).get()
            publication_date = url.xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            fuente = url.xpath('./news:news/news:publication/news:name/text()', namespaces=self.namespaces).get()

            if loc is None:
                break

            title = "" if title is None else title
            if publication_date is None:
               publication_date = url.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            if publication_date is not None:
                publication_date_comp = self.normalize_date(publication_date)
                #publication_date_ = dateutil.parser.parse(publication_date).date()
                if publication_date_comp < self.from_date:
                    continue

            if domain is not None:
                domain_base = self.get_base_url(domain)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']

            yield {
                'fuente': fuente,
                'url': loc,
                'titulo': title,
                'fecha_publicacion': publication_date,
            }

    def parse_sitemap_gz(self, response, domain=None):

        compressed_file = response.body
        decompressed_file = gzip.decompress(compressed_file).decode("utf-8")
        selector = Selector(text=decompressed_file, type="xml")
        #yield from self.parse_sitemap(selector)
        yield from self.parse_sitemap(selector, domain)

    def get_news_urls(self, domain):

        config = Config()
        config.request_timeout = 5
        config.language= 'es'
        config.thread_timeout_seconds = 5
        config.memoize_articles = False
        config.fetch_images = False
        config.follow_meta_refresh = True
        config.number_threads = 4
        config.browser_user_agent = self.custom_settings['USER_AGENT']
        config.headers = {
            "User-Agent": self.custom_settings['USER_AGENT'],
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate",
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
            "Cache-Control": "max-age=0",
        }

        try:
            print(f'Extrayendo noticias con librería Newspaper para url: {domain}')
            start_time = time.time()
            paper = build(domain, config=config)
            print(f"--- {(time.time() - start_time):.2f}s segundos ---")
            articulos_urls = set(paper.article_urls())
            print(f'Se encontraron {len(articulos_urls)} enlaces de noticias.')

            # Obtener fuente
            if domain is not None:
                domain_base = self.get_base_url(domain)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']
                else:
                    found_match = re.search(r"www\.(.*?)\.(.+)", domain)
                    fuente = ''
                    if found_match:
                        fuente = found_match.group(1)


            titulo, fecha_publicacion = '', None
            for articulo_url in articulos_urls:
                yield {
                    'fuente': fuente,
                    'url': articulo_url,
                    'titulo': titulo,
                    'fecha_publicacion': fecha_publicacion,
                }
        except Exception as e:
            print(f"No se pudieron obtener noticias de {domain}")

Writing news_extractor_spider.py

Copiar archivo spider a carpeta para ejecutar

In [15]:
# !cp news_extractor_spider.py news_scraper/spiders
!copy news_extractor_spider.py news_scraper\spiders\

        1 archivo(s) copiado(s).

Eliminar csv para generar uno nuevo

In [16]:
# Eliminar csv
import os
output_file_csv = "news_output.csv"
if os.path.exists(output_file_csv):
    os.remove(output_file_csv)

Ejecutar spyder de scrapy para gener el archivo csv con los enlaces

In [17]:
!scrapy crawl news_extractor -o news_output.csv -s LOG_ENABLED=False -s ROBOTSTXT_OBEY=False -a date=2025-02-01
#!scrapy crawl news_extractor -o news_output.csv

Robots URL: https://www.europapress.es/robots.txt
Robots URL: https://www.abc.es/robots.txt
Robots URL: https://www.eldiario.es/robots.txt
Robots URL: https://www.elconfidencial.com/robots.txt
Robots URL: https://www.elcomercio.es/robots.txt
Robots URL: https://www.20minutos.es/robots.txt
Robots URL: https://www.lne.es/robots.txt
Robots URL: https://www.elespanol.com/robots.txt
Robots URL: https://www.lavanguardia.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.europapress.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.europapress.es/sitemap.xml
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.abc.es/
--- 72.48s segundos ---
Se encontraron 1548 enlaces de noticias.
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elespanol.com/sitemap_google_news.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elconfidencial.com/newsitemap_4.xml
Robots URL: https://www.rtpa.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.lne.es/sitemap_google_news_52e19.xml', 'https://www.lne.es/sitemap_today_52e19.xml'}
Accediendo al siguiente enlace... https://www.lne.es/sitemap_google_news_52e19.xml
Accediendo al siguiente enlace... https://www.lne.es/sitemap_today_52e19.xml
Se encontraron los siguientes enlaces xml: {'https://www.elcomercio.es/sitemap.xml', 'https://www.elcomercio.es/sitemap.incremental.xml'}
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.xml
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.incremental.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.20minutos.es/sitemap-google-news.xml
Robots URL: https://www.larazon.es/robots.txt
Robots URL: https://www.tribunasalamanca.com/robots.txt
Robots URL: https://www.asturiasmundial.com/robots.txt
Robots URL: https://www.nortes.me/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-google-news.xml
Se encontraron los siguientes enlaces xml: {'https://www.eldiario.es/sitemap_index_25b87.xml', 'https://www.eldiario.es/sitemap_google_news_25b87.xml'}
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_index_25b87.xml
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_google_news_25b87.xml
Robots URL: https://www.culturalgijonesa.org/robots.txt
Robots URL: https://www.laopiniondemalaga.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.nortes.me/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.nortes.me/sitemap_index.xml
Robots URL: https://www.elperiodico.com/robots.txt
Robots URL: https://www.laprovincia.es/robots.txt
Robots URL: https://migijon.com/robots.txt
Robots URL: https://www.telecinco.es/robots.txt
Robots URL: https://www.teleprensa.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.larazon.es/sitemaps/news.xml', 'https://www.larazon.es/sitemaps/content_sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/news.xml
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/content_sitemap_index.xml
Robots URL: https://www.lavozdeasturias.es/robots.txt
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.asturiasmundial.com/
--- 14.53s segundos ---
Se encontraron 152 enlaces de noticias.
Se encontraron los siguientes enlaces xml: {'https://www.laprovincia.es/sitemap_index_89aa6.xml', 'https://www.laprovincia.es/sitemap_google_news_89aa6.xml'}
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_index_89aa6.xml
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_google_news_89aa6.xml
Robots URL: https://www.infobae.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.elperiodico.com/es/google-news.xml', 'https://www.elperiodico.com/es/sitemap-noticias.xml'}
Accediendo al siguiente enlace... https://www.elperiodico.com/es/google-news.xml
Accediendo al siguiente enlace... https://www.elperiodico.com/es/sitemap-noticias.xml
Se encontraron los siguientes enlaces xml: {'https://www.tribunasalamanca.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunasalamanca.com/sitemap_last_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.culturalgijonesa.org/sitemap.xml'}
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml', 'https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml'}
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml
Se encontraron los siguientes enlaces xml: {'https://migijon.com/xmlsitemap.xml', 'https://migijon.com/sitemap_index.xml'}
Accediendo al siguiente enlace... https://migijon.com/xmlsitemap.xml
Accediendo al siguiente enlace... https://migijon.com/sitemap_index.xml
Robots URL: https://www.elfielato.es/robots.txt
Robots URL: https://cualia.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.teleprensa.com/sitemap.xml'}
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.telecinco.es/sitemap_google_news.xml', 'https://www.telecinco.es/sitemap_ampstories.xml', 'https://www.telecinco.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_google_news.xml
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_ampstories.xml
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.rtpa.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.rtpa.es/sitemap.xml
Robots URL: http://www.gentedigital.es/robots.txt
Robots URL: https://www.lavozdegalicia.es/robots.txt
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: http://www.gentedigital.es/
--- 5.98s segundos ---
Se encontraron 18 enlaces de noticias.
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.lavozdegalicia.es/
--- 47.95s segundos ---
Se encontraron 816 enlaces de noticias.
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.categories.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.24.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.25.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.26.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.27.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.28.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.29.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.30.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.elfielato.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.xml
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://cualia.es/
--- 49.36s segundos ---
Se encontraron 76 enlaces de noticias.
Se encontró archivo comprimido https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.categories.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.02.1.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.01.1.xml.gz
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.infobae.com/arc/outboundfeeds/news-sitemap2/
No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...
Extrayendo noticias con librería Newspaper para url: https://www.lavozdeasturias.es/
--- 16.41s segundos ---
Se encontraron 201 enlaces de noticias.

## Filtrar articulos por fecha

In [31]:
import pandas as pd
from datetime import datetime, timedelta

# Cargar la data extraída
data_df = pd.read_csv("news_output.csv")

# Obtener la fecha de ayer y hoy
hoy = datetime.utcnow().strftime('%Y-%m-%d')
ayer = (datetime.utcnow() - timedelta(days=1)).date()

# Convertir las fechas de publicación
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'], format='mixed', errors='coerce', utc=True)

# Convertir a solo fecha (sin hora)
data_df['fecha_publicacion'] = data_df['fecha_publicacion'].dt.date

# Filtrar solo las noticias de ayer y hoy
data_df = data_df[data_df['fecha_publicacion'].isin([ayer, datetime.utcnow().date()])]

# Eliminar duplicados y ordenar por fecha de publicación
data_df = data_df.sort_values(by='fecha_publicacion', ascending=False).drop_duplicates().reset_index(drop=True)


# Guardar el CSV con la fecha de hoy en el nombre
nombre_archivo = f"{hoy}.csv"
data_df.to_csv(nombre_archivo, index=False)

# Mostrar el nombre del archivo guardado
print(f"Archivo guardado como: {nombre_archivo}")

# Mostrar el resultado
data_df

Archivo guardado como: 2025-02-21.csv

,fuente,url,titulo,fecha_publicacion
0,El Comercio,https://www.elcomercio.es/culturas/fetehn-2025...,NaN,2025-02-21
1,ElDiario.es,https://www.eldiario.es/politica/ultima-hora-a...,NaN,2025-02-21
2,ElDiario.es,https://www.eldiario.es/vertele/noticias/bronc...,NaN,2025-02-21
3,ElDiario.es,https://www.eldiario.es/euskadi/blogs/viento-d...,NaN,2025-02-21
4,ElDiario.es,https://www.eldiario.es/castilla-la-mancha/pro...,NaN,2025-02-21
...,...,...,...,...
12195,La Razón,https://www.larazon.es/sociedad/mayor-peligro-...,"El mayor peligro, que necesite intubación en l...",2025-02-20
12196,La Razón,https://www.larazon.es/andalucia/psoe-montero-...,El PSOE de Montero retoma la idea de una «banc...,2025-02-20
12197,La Razón,https://www.larazon.es/andalucia/via-andaluza-...,"<![CDATA[La ""vía andaluza"" llega a Europa]]>",2025-02-20
12198,La Razón,https://www.larazon.es/lifestyle/moda/tributo-...,Del tributo a la DANA de María Lafuente al apr...,2025-02-20
12199,La Provincia,https://www.laprovincia.es/videos/sucesos/2025...,NaN,2025-02-20

In [19]:
data_df['fuente'].value_counts()

fuente
La Razón                                             1677
Teleprensa                                           1454
ElDiario.es                                          1040
El Periódico                                         1010
La Nueva España                                      1007
La Vanguardia                                         844
El Español                                            843
La Opinión de Málaga                                  801
El Confidencial                                       722
La Provincia                                          710
20 Minutos                                            653
El Comercio                                           608
Telecinco                                             409
Tribuna Salamanca                                     111
Radiotelevisión del Principado de Asturias (RTPA)     109
Infobae                                               100
El Fielato y El Nora                                   40
Mi Gijón                                               36
Nortes                                                 26
Name: count, dtype: int64

### Eliminar enlaces duplicados

In [20]:
def remover_url_duplicados(df):
    df['non_null_count'] = df.notnull().sum(axis=1)
    df = df.sort_values(by=['url', 'non_null_count'], ascending=[True, False])
    df = df.drop_duplicates(subset=['url'], keep='first')
    df = df.drop(columns=['non_null_count'])
    df = df.sort_values(by='fecha_publicacion', ascending=False).reset_index(drop=True)
    return df

data_df = remover_url_duplicados(data_df)
data_df

,fuente,url,titulo,fecha_publicacion
0,Mi Gijón,https://migijon.com/about-us/,NaN,2025-02-21
1,La Razón,https://www.larazon.es/andalucia/sevilla/amena...,<![CDATA[Amenaza de muerte con una navaja a un...,2025-02-21
2,La Razón,https://www.larazon.es/asturias/fernando-laser...,"Fernando Laserna Cocina, nombrado nuevo Fiscal...",2025-02-21
3,La Razón,https://www.larazon.es/asturias/ampliada-astur...,Ampliada en Asturias la temporada de caza a ma...,2025-02-21
4,La Razón,https://www.larazon.es/animales-mascotas/cucar...,<![CDATA[Las cucarachas 'patas arriba' no apar...,2025-02-21
...,...,...,...,...
9055,ElDiario.es,https://www.eldiario.es/canariasahora/turismo/...,NaN,2025-02-20
9056,La Razón,https://www.larazon.es/deportes/futbol/cuando-...,<![CDATA[¿A qué hora es el sorteo de octavos d...,2025-02-20
9057,La Razón,https://www.larazon.es/deportes/futbol/claves-...,"Las claves del nuevo Real Madrid: una bronca, ...",2025-02-20
9058,La Razón,https://www.larazon.es/deportes/futbol/champio...,<![CDATA[Real Madrid - City: Las redes y los '...,2025-02-20
9059,La Provincia,https://www.laprovincia.es/deportes/2025/02/20...,NaN,2025-02-20

In [21]:
data_df['fuente'].value_counts()

fuente
Teleprensa                                           1154
La Razón                                              870
La Vanguardia                                         844
El Español                                            843
El Confidencial                                       722
20 Minutos                                            653
El Periódico                                          624
ElDiario.es                                           592
La Provincia                                          563
La Opinión de Málaga                                  540
La Nueva España                                       516
Telecinco                                             409
El Comercio                                           327
Tribuna Salamanca                                     111
Radiotelevisión del Principado de Asturias (RTPA)     109
Infobae                                               100
Mi Gijón                                               36
Nortes                                                 26
El Fielato y El Nora                                   21
Name: count, dtype: int64

## Acceder al contenido de las noticias

### Extracción con request

In [22]:
import requests
from bs4 import BeautifulSoup


# Lista de user-agents para probar
user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/W.X.Y.Z Safari/537.36"
]

def extraer_texto_articulos_request(url):
    try:
        # Primer intento sin user-agent
        response = requests.get(url)

        # Si la respuesta no es exitosa o el contenido está vacío, intente con agentes de usuario
        if response.status_code != 200 or not response.content:
            for user_agent in user_agents:
                headers = {
                    "User-Agent": user_agent,
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                    "Accept-Language": "en-US,en;q=0.5",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
                response = requests.get(url, headers=headers)

                if response.status_code == 200 and response.content:
                    #print("Encontrado con user-agent")
                    break

        html_str = response.content
        soup = BeautifulSoup(html_str, 'lxml')

        # Remover footer
        footer = soup.find('footer')
        if footer:
            footer.decompose()

        text_content = soup.find_all('p')

        text = ''
        for i in text_content:
            text += i.text.strip() + " "

        return text.strip() if text.strip() else None

    except Exception as e:
        print(f"Error in url: {url}, error: {e}")
        return None

In [23]:
from concurrent.futures import ThreadPoolExecutor
import time

num_threads = 16

start_time = time.time()
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    data_df['texto'] = list(executor.map(extraer_texto_articulos_request, data_df['url']))
print(f"--- {(time.time() - start_time):.2f}s seconds ---")

Error in url: https://www.elperiodico.com/es/https:/www.elperiodico.com/politica/armas-espana-guerra-ucrania-sh/index.html, error: HTTPSConnectionPool(host='www.elperiodico.com', port=443): Max retries exceeded with url: /es/https:/www.elperiodico.com/politica/armas-espana-guerra-ucrania-sh/index.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D217F2D0>, 'Connection to www.elperiodico.com timed out. (connect timeout=None)'))
Error in url: https://www.laprovincia.es/deportes/2025/02/21/roma-athletic-real-sociedad-manchester-octavos-europa-league-114547563.html, error: HTTPSConnectionPool(host='www.laprovincia.es', port=443): Max retries exceeded with url: /deportes/2025/02/21/roma-athletic-real-sociedad-manchester-octavos-europa-league-114547563.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D29F8810>, 'Connection to www.laprovincia.es timed out. (connect timeout=None)'))
Error in url: https://www.laopiniondemalaga.es/nacional/2025/02/21/gobierno-ahondar-caso-monedero-errejon-114541399.html, error: HTTPSConnectionPool(host='www.laopiniondemalaga.es', port=443): Max retries exceeded with url: /nacional/2025/02/21/gobierno-ahondar-caso-monedero-errejon-114541399.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D30AEF50>, 'Connection to www.laopiniondemalaga.es timed out. (connect timeout=None)'))
Error in url: https://www.laopiniondemalaga.es/internacional/2025/02/21/reino-unido-prepara-pacto-movilidad-ue-joevens-18-30-anos-114546447.html, error: HTTPSConnectionPool(host='www.laopiniondemalaga.es', port=443): Max retries exceeded with url: /internacional/2025/02/21/reino-unido-prepara-pacto-movilidad-ue-joevens-18-30-anos-114546447.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D2F096D0>, 'Connection to www.laopiniondemalaga.es timed out. (connect timeout=None)'))
Error in url: https://www.laopiniondemalaga.es/cultura-espectaculos/2025/02/21/sergio-peris-mencheta-enfermedad-imaginacion-114560343.html, error: HTTPSConnectionPool(host='www.laopiniondemalaga.es', port=443): Max retries exceeded with url: /cultura-espectaculos/2025/02/21/sergio-peris-mencheta-enfermedad-imaginacion-114560343.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D422DD10>, 'Connection to www.laopiniondemalaga.es timed out. (connect timeout=None)'))
Error in url: https://www.lne.es/asturias/2025/02/21/hallada-osa-muerta-arroyo-somiedo-114553736.html, error: HTTPSConnectionPool(host='www.lne.es', port=443): Max retries exceeded with url: /asturias/2025/02/21/hallada-osa-muerta-arroyo-somiedo-114553736.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D34FFD10>, 'Connection to www.lne.es timed out. (connect timeout=None)'))
Error in url: https://www.teleprensa.com/articulo/nacional-3/jueza-investiga-presunta-tentativa-asesinato-detenido-apunalar-mujer-jaen/202502201202402039586.html, error: ('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))
Error in url: https://www.teleprensa.com/articulo/nacional-3/cabildo-rechaza-hospital-migrantes-hierro-pide-mas-personal-sanitario-viene-mejorar-nada/202502201217322039618.html, error: ('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))
Error in url: https://www.teleprensa.com/articulo/capital/mesa-tren-traslada-demandas-comision-fomento-vivienda-parlamento-andaluz/202502201416502039763.html, error: ('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))
Error in url: https://www.teleprensa.com/articulo/granada/almunecar-solicita-competencias-junta-agilizar-ayudas-damnificados-incendio/202502201302322039714.html, error: ('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))
Error in url: https://www.teleprensa.com/articulo/internacional/guterres-anuncia-plan-financiar-fuerza-multinacional-desplegada-haiti-restablecer-seguridad/202502201117242039480.html, error: ('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))
Error in url: https://www.laprovincia.es/deportes/2025/02/20/sentencia-integra-condena-luis-rubiales-114510252.html, error: HTTPSConnectionPool(host='www.laprovincia.es', port=443): Max retries exceeded with url: /deportes/2025/02/20/sentencia-integra-condena-luis-rubiales-114510252.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6CFBD4190>, 'Connection to www.laprovincia.es timed out. (connect timeout=None)'))
Error in url: https://www.elperiodico.com/es/deportes/20250220/sede-espanola-lider-mundial-conectividad-114508626, error: HTTPSConnectionPool(host='www.elperiodico.com', port=443): Max retries exceeded with url: /es/deportes/20250220/sede-espanola-lider-mundial-conectividad-114508626 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D20A2550>, 'Connection to www.elperiodico.com timed out. (connect timeout=None)'))
Error in url: https://www.elperiodico.com/es/tendencias-21/20250220/crean-base-datos-microbiana-digital-114508501, error: HTTPSConnectionPool(host='www.elperiodico.com', port=443): Max retries exceeded with url: /es/tendencias-21/20250220/crean-base-datos-microbiana-digital-114508501 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6CFE02C50>, 'Connection to www.elperiodico.com timed out. (connect timeout=None)'))
Error in url: https://www.laopiniondemalaga.es/costa-sol-occidental/2025/02/20/ampliacion-ies-torre-almenara-114485097.html, error: HTTPSConnectionPool(host='www.laopiniondemalaga.es', port=443): Max retries exceeded with url: /costa-sol-occidental/2025/02/20/ampliacion-ies-torre-almenara-114485097.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6CF36F890>, 'Connection to www.laopiniondemalaga.es timed out. (connect timeout=None)'))
Error in url: https://www.elperiodico.com/es/politica/20250220/jueza-contundente-investigacion-hermano-sanchez-no-recortes-prensa-indicios-114505073, error: HTTPSConnectionPool(host='www.elperiodico.com', port=443): Max retries exceeded with url: /es/politica/20250220/jueza-contundente-investigacion-hermano-sanchez-no-recortes-prensa-indicios-114505073 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D2DEF7D0>, 'Connection to www.elperiodico.com timed out. (connect timeout=None)'))
Error in url: https://www.elperiodico.com/es/opinion/20250220/precio-paz-litio-uranio-grafito-eeuu-ucrania-rusia-articulo-olga-merino-114510577, error: HTTPSConnectionPool(host='www.elperiodico.com', port=443): Max retries exceeded with url: /es/opinion/20250220/precio-paz-litio-uranio-grafito-eeuu-ucrania-rusia-articulo-olga-merino-114510577 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6CDC954D0>, 'Connection to www.elperiodico.com timed out. (connect timeout=None)'))
Error in url: https://www.elperiodico.com/es/sucesos/20250220/detenido-autor-incendio-molar-114501100, error: HTTPSConnectionPool(host='www.elperiodico.com', port=443): Max retries exceeded with url: /es/sucesos/20250220/detenido-autor-incendio-molar-114501100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D323A4D0>, 'Connection to www.elperiodico.com timed out. (connect timeout=None)'))
Error in url: https://www.elperiodico.com/es/sociedad/20250220/andaluza-explota-catalanofobia-tiktok-video-dv-114363039, error: HTTPSConnectionPool(host='www.elperiodico.com', port=443): Max retries exceeded with url: /es/sociedad/20250220/andaluza-explota-catalanofobia-tiktok-video-dv-114363039 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D2859A10>, 'Connection to www.elperiodico.com timed out. (connect timeout=None)'))
Error in url: https://www.laprovincia.es/sociedad/2025/02/20/ulpgc-cultura-lengua-de-signos-114518583.html, error: HTTPSConnectionPool(host='www.laprovincia.es', port=443): Max retries exceeded with url: /sociedad/2025/02/20/ulpgc-cultura-lengua-de-signos-114518583.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D2197010>, 'Connection to www.laprovincia.es timed out. (connect timeout=None)'))
Error in url: https://www.laprovincia.es/ud-las-palmas/2025/02/20/enfermeria-ud-palmas-pelmard-fabio-114513894.html, error: HTTPSConnectionPool(host='www.laprovincia.es', port=443): Max retries exceeded with url: /ud-las-palmas/2025/02/20/enfermeria-ud-palmas-pelmard-fabio-114513894.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E6D2FEA410>, 'Connection to www.laprovincia.es timed out. (connect timeout=None)'))
--- 2006.11s seconds ---

In [24]:
data_df

,fuente,url,titulo,fecha_publicacion,texto
0,Mi Gijón,https://migijon.com/about-us/,NaN,2025-02-21,"Pablo Cardona, semifinalista en el P1 de Riad ..."
1,La Razón,https://www.larazon.es/andalucia/sevilla/amena...,<![CDATA[Amenaza de muerte con una navaja a un...,2025-02-21,Andalucía Sevilla España Local Opinión Intern...
2,La Razón,https://www.larazon.es/asturias/fernando-laser...,"Fernando Laserna Cocina, nombrado nuevo Fiscal...",2025-02-21,Asturias España Local Opinión Internacional Ec...
3,La Razón,https://www.larazon.es/asturias/ampliada-astur...,Ampliada en Asturias la temporada de caza a ma...,2025-02-21,Asturias España Local Opinión Internacional Ec...
4,La Razón,https://www.larazon.es/animales-mascotas/cucar...,<![CDATA[Las cucarachas 'patas arriba' no apar...,2025-02-21,Animales y mascotas España Local Opinión Inter...
...,...,...,...,...,...
9055,ElDiario.es,https://www.eldiario.es/canariasahora/turismo/...,NaN,2025-02-20,"Hoy hablamos de... Por favor, actualiza tus da..."
9056,La Razón,https://www.larazon.es/deportes/futbol/cuando-...,<![CDATA[¿A qué hora es el sorteo de octavos d...,2025-02-20,Deportes Fútbol España Local Opinión Internac...
9057,La Razón,https://www.larazon.es/deportes/futbol/claves-...,"Las claves del nuevo Real Madrid: una bronca, ...",2025-02-20,Deportes Fútbol España Local Opinión Internac...
9058,La Razón,https://www.larazon.es/deportes/futbol/champio...,<![CDATA[Real Madrid - City: Las redes y los '...,2025-02-20,Deportes Fútbol Champions League España Loca...
9059,La Provincia,https://www.laprovincia.es/deportes/2025/02/20...,NaN,2025-02-20,LA CRISIS DEL GIGANTE INGLÉS Pep Guardiola. /...

In [25]:
data_df['texto'].isna().sum()

24

In [26]:
(data_df['texto'] == '').sum()

0

In [27]:
data_df['texto'].iloc[-2]

"Deportes  Fútbol  Champions League España Local Opinión Internacional Economía Cultura Sociedad Deportes Gente A Tu Salud Televisión Ciencia Motor Lifestyle Emergente Premios LR Juegos y pasatiempos 25 Aniversario De Compras La tienda de La Razón Lea el periódico en PDF Stories La Razón Suplementos en PDF Promociones Directo Última hora del estado de salud del Papa Directo Última hora de la guerra de Ucrania: Musk arremete contra Zelenski y Trump le pide que firme ya el acuerdo de las tierras raras Champions League Todavía colea la resaca del partido de anoche en el Santiago Bernabéu, con la contundente victoria del Real Madrid sobre el Manchester City (3-1). Las portadas de toda la prensa europea hablan del partido, del gran papel de Mbappé... y del annus horribilis en que esta temporada se está tornando para Pep Guardiola. Como era de esperar, también las redes han hecho su 'trabajo' con el desempeño del técnico catalán. Incapaz de encontrar una solución y sin meter a Haaland en ningún momento del encuentro, se vio claramente superado por el equipo blanco. Hay para todos los gustos, tanto en inglés como en español. A nadie le pasó inadvertida la falta de soluciones de Guardiola, que está firmando -de lejos- la peor temporada desde que llegó al City. Por primera vez, su equipo no estará ni entre los 16 mejores de Europa. Incluso en Argentina echaban de menos a antiguos jugadores del equipo celeste como Julián Álvarez que, a diferencia de su anterior equipo, sí estará en los octavos de final en las filas del Atlético de Madrid. Que, por cierto, mañana podría quedar emparejado con el Real Madrid en el sorteo de octavos.  Directo Polémica Champions Investigación"

In [28]:
data_df.iloc[-3].values

array(['La Razón',
       'https://www.larazon.es/deportes/futbol/claves-nuevo-real-madrid-bronca-442-canterano-jugador-que-vale-todo_2025022067b6fd23b1a8db0001ce6b47.html',
       'Las claves del nuevo Real Madrid: una bronca, el 4-4-2, Mbappé, un canterano y un jugador que vale para todo ',
       datetime.date(2025, 2, 20),
       'Deportes  Fútbol España Local Opinión Internacional Economía Cultura Sociedad Deportes Gente A Tu Salud Televisión Ciencia Motor Lifestyle Emergente Premios LR Juegos y pasatiempos 25 Aniversario De Compras La tienda de La Razón Lea el periódico en PDF Stories La Razón Suplementos en PDF Promociones Directo Última hora del estado de salud del Papa Directo Última hora de la guerra de Ucrania: Musk arremete contra Zelenski y Trump le pide que firme ya el acuerdo de las tierras raras Fútbol Carlo Ancelotti se ha pasado lo que llevamos de temporada buscando el punto de inflexión del equipo. Porque el Real Madrid ha ido mezclando momentos buenos con otros regulares y otros definitivamente muy malos. Cuando aparecía uno de estos, el entrenador confiaba en que ya no se podía caer más y que, como se había tocado fondo, se había alcanzado el punto de inflexión. También pasó cuando el Real Madrid sumó bastantes partidos de LaLiga con buenos resultados. Ancelotti quiso creer que ya había encontrado la fórmula. Pero ni él ni el madridismo terminaban de estar convencidos. Ahora sí, ese punto ha llegado. «Nos ha costado mucho encontrar el equipo y ahora hay que trabajar para estar a este nivel y, si es posible, mejorarlo», aseguraba el entrenador italiano el miércoles por la noche, después de haber sido muy superior al City. Nunca, en todas las eliminatorias en las que se han enfrentado a lo largo de estos años, el Real Madrid había mostrado estar tantos pisos por encima del equipo de Guardiola. «Su dinámica y calidad individual son muy buenas. Ahora tienen capacidad de hundirte y hacer jugadas de gol a través de los pases. Te atraen mucho y te ganan la espalda por arriba. Es un equipo que, en años anteriores, pensaba que podíamos hacerles daño por algunos lados. Pero esta vez han crecido mucho», explicó también el entrenador catalán, muy lejos de aquella vez con el Bayern, cuando, lleno de rabia, habló del Madrid, y con toda la intención, como de un equipo de atletas. Es verdad que la versión del Manchester City fue la de un equipo en descomposición y sin rumbo, pero el Real Madrid se ha enfrentado a rivales peores que el City durante esta temporada y no ha resuelto los encuentros con tanta seguridad ni jugando tan bien como ha sucedido en esta eliminatoria de la Champions. El equipo de Carlo Ancelotti viene haciendo buenos partidos desde el segundo tiempo contra el Atlético de Madrid. Fue en el descanso de ese partido cuando Ancelotti se puso muy serio con los de arriba y les pidió sacrificio defensivo para ganar, porque, si no, no había manera. Contra el City, se demostró que, si eso sucede, el equipo, naturalmente desequilibrado, puede mejorar en defensa y no perder la potencia que tienen los de arriba. Que con Mbappé en este estado, es infinita. El 4-4-2 para defender es inamovible ya. Eso supone que Vinicius y Mbappé tienen que juntarse arriba, en el medio, y retroceder con el resto del equipo. Y supone, sobre todo, que Rodrygo y Bellingham ocupan las bandas sin despistarse. «La idea de defender en 4-4-2 es correcta. El equipo se encuentra cómodo y trabaja bien. Hay que destacar también el gran trabajo de los dos extremos: Bellingham y Rodrygo. Tenemos que seguir así: con esta dinámica, en esta línea y con este sistema», continuaba Carlo Ancelotti para explicar el buen momento del equipo. «Estamos jugando muy bien cada día y nos entendemos mejor. Con la calidad y el sacrificio que tenemos, seguiremos jugando de esta forma», confirmaba Rodrygo, el futbolista que más ha mejorado en todas las facetas del equipo. Aporta en defensa y es desequilibrante cuando llega arriba. El trabajo de los delanteros ha cambiado al Real Madrid, pero hay más factores: en el centro del campo, Ancelotti lleva ya tiempo apostando por un jugador de creación como Ceballos, con otro más físico. Solían ser Camavinga o Valverde, pero Tchouaméni ha vuelto a su posición y ha roto a jugar como no lo había hecho otras veces. Es posible que verse más acompañado le ayude a mejorar. «Su asociación con Ceballos viene bien al equipo porque Dani es más de posesión de balón y él es más posicional. Es un jugador muy importante porque tiene este tipo de características. No puede ser ni Ceballos ni Kroos ni Modric, pero ni Ceballos, ni Kroos ni Modric pueden ser Tchouaméni. Para ser un buen equipo hay que combinar las características de cada uno», decía Carlo.  Directo Polémica Champions Investigación'],
      dtype=object)

## Filtrar textos

### Buscar textos que tengan al menos una palabra clave

In [29]:
# Filtrar por palabras clave
keywords = ['universidad', 'oviedo']

# Regex pattern
pattern = '|'.join(keywords)

# Filtrar dataframe
filtered_df = data_df[data_df['texto'].str.contains(pattern, case=False, na=False)].reset_index(drop=True)

filtered_df

,fuente,url,titulo,fecha_publicacion,texto
0,La Razón,https://www.larazon.es/asturias/fernando-laser...,"Fernando Laserna Cocina, nombrado nuevo Fiscal...",2025-02-21,Asturias España Local Opinión Internacional Ec...
1,La Razón,https://www.larazon.es/andalucia/sumar-designa...,Sumar designa este sábado a Esperanza Gómez y ...,2025-02-21,Andalucía España Local Opinión Internacional E...
2,La Razón,https://www.larazon.es/castilla-y-leon/burgos-...,Burgos acoge el Foro de Trabajo de Saborea Esp...,2025-02-21,Castilla y León España Local Opinión Internaci...
3,La Razón,https://www.larazon.es/castilla-la-mancha/trab...,<![CDATA[Un trabajador resulta herido grave tr...,2025-02-21,Hoy Suscríbase a nuestro canal de WhatsApp Ser...
4,La Razón,https://www.larazon.es/castilla-la-mancha/sema...,"Fin de semana pasado por lluvia, tormentas y v...",2025-02-21,Hoy Suscríbase a nuestro canal de WhatsApp Ser...
...,...,...,...,...,...
804,La Razón,https://www.larazon.es/comunidad-valenciana/po...,"Quién es Arturo Torró, exalcalde de Gandía y f...",2025-02-20,Comunidad Valenciana España Local Opinión Inte...
805,La Razón,https://www.larazon.es/cultura/irse-cerros-ube...,<![CDATA['Irse por los cerros de Úbeda': Dónde...,2025-02-20,Hoy Suscríbase a nuestro canal de WhatsApp Car...
806,ElDiario.es,https://www.eldiario.es/catalunya/muere-viqui-...,NaN,2025-02-20,"Hoy hablamos de... Por favor, actualiza tus da..."
807,La Razón,https://www.larazon.es/economia/eae-business-s...,"EAE Business School Madrid, centro de Innovaci...",2025-02-20,Economía España Local Opinión Internacional Ec...
808,ElDiario.es,https://www.eldiario.es/cantabria/ultimas-noti...,Diversificar el turismo para lograr un equilib...,2025-02-20,"Hoy hablamos de... Por favor, actualiza tus da..."

In [30]:
filtered_df['url'].values[0:100]

array(['https://www.larazon.es/asturias/fernando-laserna-cocina-nombrado-nuevo-fiscal-delegado-comunidad-autonoma-personas-discapacidad-mayores_2025022167b7b4e5500f9600011436eb.html',
       'https://www.larazon.es/andalucia/sumar-designa-este-sabado-esperanza-gomez-raul-garcia-como-coordinadores-andaluces_2025022167b87720417ec20001015cd6.html',
       'https://www.larazon.es/castilla-y-leon/burgos-acoge-foro-trabajo-saborea-espana-participacion-14-destinos-gastronomicos_2025022167b85939417ec20001012020.html',
       'https://www.larazon.es/castilla-la-mancha/trabajador-resulta-herido-grave-caerle-encima-tolva-fabrica-villacanas-toledo/20250221/1168744.html',
       'https://www.larazon.es/castilla-la-mancha/semana-pasado-lluvia-tormentas-vuelta-frio-castilla-mancha-aemet/20250221/1168741.html',
       'https://www.larazon.es/castilla-la-mancha/acabar-espana-vaciada-empueblate-ofrece-soluciones-exito-impulsar-repoblar-pueblos/20250221/1168766.html',
       'https://www.larazon.es/cultura/cinco-palabras-vienen-arabe-seguramente-sabias/20250221/1168763.html',
       'https://www.larazon.es/castilla-y-leon/universidad-leon-suma-c2iet-ponferrada_2025022167b886fb417ec200010187dd.html',
       'https://www.larazon.es/castilla-y-leon/ucav-inaugura-ciclo-teresiano-abordando-oracion-enfoque-escenico_2025022167b85cbdb1a8db0001d000ce.html',
       'https://www.larazon.es/castilla-y-leon/estudio-que-reconstruye-rostro-santa-teresa-jesus_2025022167b8432e500f9600011492f1.html',
       'https://www.larazon.es/castilla-y-leon/espera-marzo-intenso-futuro-autonomia-leonesa_2025022167b8786e417ec20001016182.html',
       'https://www.larazon.es/ciencia/senal-television-llega-aviones-big-bang_2025022167b86786b1a8db0001d01428.html',
       'https://www.larazon.es/cataluna/pere-aragones-negociador-inesperado-dara-conferencia-yale-desescalar-conflictos-secesionistas_2025022167b846dd500f9600011496ea.html',
       'https://www.laprovincia.es/medio-ambiente/2025/02/21/millones-personas-queman-plastico-cocinar-114543391.html',
       'https://www.laprovincia.es/espana/2025/02/21/chat-desmonta-monedero-siguio-direccion-114561393.html',
       'https://www.laprovincia.es/espana/2025/02/21/gobierno-ahondar-caso-monedero-errejon-114541420.html',
       'https://www.laprovincia.es/ocio/tv/2025/02/14/paso-tercera-valeria-resumimos-temporada-3-114300561.html',
       'https://www.laprovincia.es/tendencias21/2025/02/21/nuevo-estudio-comprueba-alarmante-reduccion-114536686.html',
       'https://www.laprovincia.es/tendencias21/2025/02/21/descubren-egipto-primera-tumba-real-114551149.html',
       'https://www.laprovincia.es/tendencias21/2025/02/16/comprender-oraciones-escritas-parpadeo-110824589.html',
       'https://www.laprovincia.es/tendencias21/2023/05/07/chimpances-forman-oraciones-palabras-comunicarse-86914805.html',
       'https://www.laprovincia.es/sociedad/2025/02/21/aplicacion-metodo-cer-graciosa-logra-114556606.html',
       'https://www.laprovincia.es/opinion/2025/02/21/antiguos-canarios-frikadas-114528520.html',
       'https://www.larazon.es/deportes/futbol/estadio-que-marruecos-quiere-quitar-espana-final-mundial-2030_2025022167b84d81500f960001149d6f.html',
       'https://www.larazon.es/television/programas/hemos-visto-agresores-ser-ovacionados-opina-exdiputada-podemos-caso-juan-carlos-monedero-p7m_2025022167b87a09500f96000114ea7d.html',
       'https://www.larazon.es/television/programas/ana-rosa-muy-critica-monedero-editorial-aplico-ley-silencio_2025022167b84d8d500f960001149d77.html',
       'https://www.lavanguardia.com/ciencia/20250221/10409824/catalunya-anuncia-inversion-43-millones-cinco-anos-tecnologias-cuanticas.html',
       'https://www.larazon.es/sociedad/estudio-avala-diagnostico-asistido-enfermedades-inmunologicas_2025022167b85a27b1a8db0001cffccb.html',
       'https://www.lavanguardia.com/comprar/moda-belleza/20250221/10405308/consigue-bolso-misako-moderno-funcional-elegante-50-euros-amazon-mkt-misa.html',
       'https://www.lavanguardia.com/dinero/20250220/10404376/laura-gomez-asesora-estudios-revela-mejor-ciudad-espanola-mayor-calidad-vida-espana-madrid-barcelona-gvm.html',
       'https://www.larazon.es/espana/juan-carlos-monedero-contesta-acusaciones-podemos-tendra-que-aclarar-cosas_2025022167b88d3d417ec20001018fbc.html',
       'https://www.larazon.es/espana/belarra-dice-ahora-que-revelaron-acusaciones-monedero-proteger-victimas_2025022167b8609a500f96000114b65b.html',
       'https://www.larazon.es/emergente/semaforo_2025022167b8329a500f960001148355.html',
       'https://www.larazon.es/galicia/quien-era-alfredo-branas-ejemplo-que-pone-como-modelo-unidad-respeto-p7m_2025022167b868cc417ec20001013b82.html',
       'https://www.larazon.es/galicia/galicia-podio-absentismo-laboral-xunta-busca-respuestas-factura-millonaria-p7m_2025022167b850bcb1a8db0001cfeb62.html',
       'https://www.larazon.es/espana/vejaciones-monedero-sus-alumnas_2025022167b7de2db1a8db0001cfa43e.html',
       'https://www.larazon.es/medio-ambiente/silice-cristalina-minusculo-polvo-silente_2025022167b755edb1a8db0001cedb05.html',
       'https://www.larazon.es/salud/bienestar/mejor-ejercicio-mayores-60-anos-que-reduce-riesgo-demencia-p7m_2025022167b8b31e500f960001153a53.html',
       'https://www.larazon.es/salud/bienestar/cuanto-tiempo-deberias-dormir-50-anos-ciencia-responde-p7m_2025022167b7729e500f96000113c91c.html',
       'https://www.larazon.es/murcia/macroperacion-retirar-500000-litros-liquidos-peligrosos-zincsa-cartagena_2025022167b865d5500f96000114bc6b.html',
       'https://www.larazon.es/internacional/australia-desvia-cinco-vuelos-ser-alertada-disparos-fuego-real-tres-barcos-guerra-chinos-maniobras_2025022167b85379417ec20001011624.html',
       'https://www.elperiodico.com/es/politica/20250221/gobierno-ahondar-caso-monedero-errejon-114541414',
       'https://www.elperiodico.com/es/sociedad/20250220/arturo-torro-exalcalde-gandia-ultima-hora-directo-114495046',
       'https://www.elperiodico.com/es/ser-feliz/20250221/fases-ruptura-reflejan-dia-dia-evg-114208279',
       'https://www.elperiodico.com/es/salud/20250221/estimulacion-magnetica-transcraneal-depresion-resistente-113769430',
       'https://www.elperiodico.com/es/medio-ambiente/20250221/millones-personas-queman-plastico-cocinar-114543384',
       'https://www.elperiodico.com/es/ocio-y-cultura/20250221/nadia-werba-directora-retrato-espana-114546291',
       'https://www.elperiodico.com/es/internacional/20250221/santorini-terremotos-grecia-volcan-etna-hoy-ultima-hora-directo-114073834',
       'https://www.elperiodico.com/es/opinion/20250221/irene-vallejo-rara-clase-pronuncia-honoris-causa-articulo-juan-cruz-114560967',
       'https://www.elperiodico.com/es/opinion/20250221/smi-distinto-ciudad-o-barrio-articulo-marti-saballs-pons-114546150',
       'https://www.elperiodico.com/es/ocio-y-cultura/20250221/the-new-yorker-semanario-nacio-114474485',
       'https://www.elperiodico.com/es/tendencias-21/20250221/nuevo-estudio-comprueba-alarmante-reduccion-114536636',
       'https://www.elperiodico.com/es/tendencias-21/20250221/descubren-egipto-primera-tumba-real-114551145',
       'https://www.elperiodico.com/es/sociedad/20250221/cataluna-invertira-43-millones-tecnologia-cuantica-illa-114554303',
       'https://www.elperiodico.com/es/tarragona/20250221/santiago-castella-futura-zona-logistica-port-tarragona-mejores-terrenos-industriales-catalunya-114315020',
       'https://www.elperiodico.com/es/tarragona/20250221/mercados-asiatico-sudamericano-fijan-port-tarragona-futuras-inversiones-estrategicas-114511296',
       'https://www.elespanol.com/valencia/economia/20250221/banco-santander-nombra-javier-gallardo-director-territorial-comunitat-valenciana-murcia/925907512_0.html',
       'https://www.elfielato.es/articulo/comarca-picos-de-europa/usana-madera-viceconsejera-medio-ambiente/20250221173329075537.html',
       'https://www.elespanol.com/sociedad/20250221/cancion-efectiva-recomiendan-expertos-calmar-sintomas-ansiedad-kwi/925907600_0.html',
       'https://www.elespanol.com/sevilla/20250221/guia-turistico-sevilla-condenado-agredir-sexualmente-estudiantes-seguira-libertad-provisional/925907633_0.html',
       'https://www.elespanol.com/reportajes/20250221/patricio-pablo-gemelos-anos-cartel-sinaloa-espana-detenidos-muerte-narco-serbio-tarragona/925657858_0.html',
       'https://www.elespanol.com/treintayseis/cultura/20250221/arquitecto-gallego-opta-premio-princesa-girona-arte/925907830_0.html',
       'https://www.elperiodico.com/es/estilo-y-famosos/20250220/inout-barcelona-olistic-miin-fenomeno-cosmetica-beauty-114494597',
       'https://www.elperiodico.com/es/eixample/20250221/museu-egipci-festeja-hitos-piramidescos-114443105',
       'https://www.elperiodico.com/es/economia/20250221/millonario-jose-elias-opina-comprar-alquilar-vivienda-2025-ganas-2000-euros-mes-dv-114384001',
       'https://www.elperiodico.com/es/internacional/20250221/donald-trump-aranceles-ultima-hora-directo-113951568',
       'https://www.elperiodico.com/es/economia/20250221/gobierno-apuesta-elevar-peso-construccion-economia-114549610',
       'https://www.elperiodico.com/es/economia/20250220/energeticas-bancos-dividendos-ibex-record-114526042',
       'https://www.elperiodico.com/es/economia/20250219/prensa-iberica-banc-sabadell-premiaran-dia-26-talento-empresarial-catalan-114462828',
       'https://www.laopiniondemalaga.es/tendencias21/2023/05/07/chimpances-forman-oraciones-palabras-comunicarse-86914833.html',
       'https://www.laopiniondemalaga.es/tendencias21/2025/02/21/descubren-egipto-primera-tumba-real-114551152.html',
       'https://www.laopiniondemalaga.es/tendencias21/2025/02/16/comprender-oraciones-escritas-parpadeo-110824608.html',
       'https://www.laopiniondemalaga.es/tendencias21/2025/02/21/nuevo-estudio-comprueba-alarmante-reduccion-114536622.html',
       'https://www.laopiniondemalaga.es/ocio/tv/2025/02/14/paso-tercera-valeria-resumimos-temporada-3-114300571.html',
       'https://www.laopiniondemalaga.es/opinion/2025/02/21/lopez-rodriguez-navarro-asociados-114524177.html',
       'https://www.laprovincia.es/buzzeando/2025/02/21/influencer-archipielago-islas-canarias-son-como-jackson-five-solo-te-sabes-dos-dv-114545469.html',
       'https://www.laprovincia.es/cultura/2025/02/21/carolina-padron-acrobata-canaria-pinta-114556575.html',
       'https://www.infobae.com/mexico/2025/02/21/cjng-corresponsable-de-la-crisis-de-credibilidad-que-sufren-las-policias-y-corporaciones-de-seguridad/',
       'https://www.infobae.com/mexico/2025/02/21/alerta-actividad-en-el-volcan-de-fuego-de-colima-hoy-21-de-febrero/',
       'https://www.infobae.com/espana/agencias/2025/02/21/temas-del-dia-de-efe-espana-del-sabado-22-de-febrero/',
       'https://www.infobae.com/peru/2025/02/21/examen-de-admision-de-la-cantuta-2025-fechas-de-inscripcion-costos-y-carreras-disponibles/',
       'https://www.infobae.com/colombia/2025/02/21/exministra-de-transporte-maria-constanza-garcia-se-enfrento-a-su-exjefe-gustavo-petro-quien-hablo-de-corrupcion-en-la-cartera-que-ella-dirigia-no-puedo-quedarme-en-silencio-ante-esta-acusacion/',
       'https://www.infobae.com/colombia/2025/02/21/preocupante-panorama-seis-ciudades-colombianas-estan-entre-las-mas-violentas-del-mundo-en-2024/',
       'https://www.laopiniondemalaga.es/nacional/2025/02/21/chat-desmonta-monedero-siguio-direccion-114561396.html',
       'https://www.laopiniondemalaga.es/medio-ambiente/2025/02/21/millones-personas-queman-plastico-cocinar-114543379.html',
       'https://www.laopiniondemalaga.es/malaga/2025/02/21/malaga-aprueba-ordenanza-quiere-tramitar-114546317.html',
       'https://www.laopiniondemalaga.es/malaga/2025/02/21/foro-satelites-sssif-malaga-crece-alabanza-nasa-114541789.html',
       'https://www.laopiniondemalaga.es/cultura-espectaculos/2025/02/21/museo-picasso-maf-presentan-conferencias-114546661.html',
       'https://www.teleprensa.com/articulo/deportes/csd-embajada-britanica-reafirman-importancia-liderazgo-femenino-deporte/202502211642192041099.html',
       'https://www.teleprensa.com/articulo/deportes/montse-tome-delia-losa-candela-garcia-optan-premio-mujer-sierense-2025/202502211822162041209.html',
       'https://www.teleprensa.com/articulo/almeria-sociedad/setenta-participantes-dan-cita-fase-local-olimpiada-quimica-2025/202502211939402041218.html',
       'https://www.teleprensa.com/articulo/cordoba/proyeccion-documental-vida-gota-pone-foco-diagnostico-precoz-enfermedades-raras/202502211647382041112.html',
       'https://www.teleprensa.com/articulo/granada/elevan-cinco-victimas-identificadas-140-exhumadas-barranco-viznar/202502211012262040487.html',
       'https://www.teleprensa.com/articulo/internacional/menos-doce-muertos-casi-20-heridos-colision-autobus-camion-sao-paulo/202502211157292040691.html',
       'https://www.teleprensa.com/articulo/granada/mas-200-profesionales-comparten-experiencias-i-jornadas-nacionales-fisioterapia-cardiologia/202502211732252041159.html',
       'https://www.teleprensa.com/articulo/granada/investigadores-analizan-pts-potencial-ia-terapias-enfermedades-hoy-cura/202502211637242041088.html',
       'https://www.teleprensa.com/articulo/internacional/condenado-cadena-perpetua-autor-tiroteos-roterdam-2023-que-saldaron-tres-muertos/202502211402302040926.html',
       'https://www.teleprensa.com/articulo/almeria-sociedad/mas-60-doctores-doctoras-suman-claustro-ual/202502210127092040325.html',
       'https://www.teleprensa.com/articulo/almeria-sociedad/copao-premia-almeria-compromiso-psicologia-como-motor-cambio-social/202502211712432041044.html',
       'https://www.telecinco.es/noticias/economia/20250221/vivir-bien-sin-trabajar-como-jubilarte-antes-60-anos_18_014832840.html'],
      dtype=object)

## Buscar textos que tengan todas las palabras clave

In [ ]:
# Lista de palabras clave
keywords = ['universidad', 'oviedo']

# Crear una condición de filtro para cada palabra clave
filter_condition = data_df['texto'].str.contains(keywords[0], case=False, na=False)

for keyword in keywords[1:]:
    filter_condition &= data_df['texto'].str.contains(keyword, case=False, na=False)

# Aplicar filtro
filtered_df_all = data_df[filter_condition].reset_index(drop=True)

filtered_df_all

,fuente,url,titulo,fecha_publicacion,texto
0,La Razón,https://www.larazon.es/galicia/quien-era-alfre...,"<![CDATA[¿Quién era Alfredo Brañas, el ejemplo...",2025-02-21,Galicia España Local Opinión Internacional Eco...
1,La Razón,https://www.larazon.es/asturias/fernando-laser...,"Fernando Laserna Cocina, nombrado nuevo Fiscal...",2025-02-21,Asturias España Local Opinión Internacional Ec...
2,Nortes,https://www.nortes.me/2025/02/21/una-estatua-p...,NaN,2025-02-21,Las políticas asturianas de memoria han sido a...
3,Radiotelevisión del Principado de Asturias (RTPA),https://www.rtpa.es/noticias-asturias/2025-02-...,La sierense Susana Madera será la nueva viceco...,2025-02-21,Ver la transcripción del vídeo de esta noticia...
4,Nortes,https://www.nortes.me/articulos-recientes/,NaN,2025-02-21,El general Augusto Pinochet quería ser un augu...
...,...,...,...,...,...
152,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/oviedo/...,NaN,NaT,Andrew Silin y Kate Yakusheva se conocían de c...
153,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/siero/2...,NaN,NaT,"El alcalde de Siero, Ángel García, se ha mostr..."
154,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/turismo...,NaN,NaT,La Comarca Vaqueira toma su nombre de los vaqu...
155,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/turismo...,NaN,NaT,El concejo de Oviedo tiene en su corazón la ci...
156,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/lemos/ch...,NaN,NaT,Saltó la sorpresa en Chantada. El Universidad ...

In [ ]:
def mostrar_informacion(data_df):

    for index, fila in data_df.iterrows():
        if pd.isna(fila['fecha_publicacion']):
            fecha = 'Desconocido'
        else:
            fecha = fila['fecha_publicacion'].strftime('%Y/%m/%d')
        fuente = fila['fuente']

        titulo = 'Desconocido'
        if pd.notna(fila['titulo']):
            titulo = fila['titulo']

        print(titulo)
        print(fila['url'])
        print(f'{fecha} - {fuente}')
        print()

mostrar_informacion(filtered_df_all)

<![CDATA[¿Quién era Alfredo Brañas, el ejemplo que el PP pone como modelo de unidad y respeto?]]>
https://www.larazon.es/galicia/quien-era-alfredo-branas-ejemplo-que-pone-como-modelo-unidad-respeto-p7m_2025022167b868cc417ec20001013b82.html
2025/02/21 - La Razón

Fernando Laserna Cocina, nombrado nuevo Fiscal Delegado en la comunidad autónoma de Personas con Discapacidad y Mayores
https://www.larazon.es/asturias/fernando-laserna-cocina-nombrado-nuevo-fiscal-delegado-comunidad-autonoma-personas-discapacidad-mayores_2025022167b7b4e5500f9600011436eb.html
2025/02/21 - La Razón

Desconocido
https://www.nortes.me/2025/02/21/una-estatua-para-el-rector-alas/
2025/02/21 - Nortes

La sierense Susana Madera será la nueva viceconsejera de Medio Ambiente
https://www.rtpa.es/noticias-asturias/2025-02-21/La-sierense-Susana-Madera-sera-la-nueva-viceconsejera-de-Medio-Ambiente_111740125730.html
2025/02/21 - Radiotelevisión del Principado de Asturias (RTPA)

Desconocido
https://www.nortes.me/articulos-recientes/
2025/02/21 - Nortes

Desconocido
https://www.nortes.me/2025/02/21/video-entrevista-con-juan-ponte-sobre-su-libro-el-capitalismo-no-existe/
2025/02/21 - Nortes

Gijón estrena sus primeros seis autobuses eléctricos mientras ultima su plan para dar servicio a la zona rural
https://www.lne.es/gijon/2025/02/21/emtusa-estrena-primeros-seis-autobuses-114547133.html
2025/02/21 - La Nueva España

El rector de la Universidad de Oviedo, dispuesto a "avanzar en los proyectos en común" con Siero en el Centro de Inteligencia Artificial
https://www.lne.es/siero/2025/02/21/rector-universidad-oviedo-dispuesto-avanzar-114547345.html
2025/02/21 - La Nueva España

Así abrirá el nuevo IES de La Corredoria: con más de medio millar de alumnos, 40 profesores y los seis cursos
https://www.lne.es/oviedo/la-corredoria/2025/02/21/problemas-masificacion-resolveran-proximo-curso-114535565.html
2025/02/21 - La Nueva España

"A cualquier universitario le recomendaría ir a un colegio mayor"
https://www.lne.es/oviedo/2025/02/21/universitario-le-recomendaria-colegio-mayor-114527400.html
2025/02/21 - La Nueva España

Un torneo de debate reúne a más de 130 estudiantes en el Cristo
https://www.lne.es/oviedo/2025/02/21/torneo-debate-reune-130-estudiantes-114529229.html
2025/02/21 - La Nueva España

Así es Steven Verplancken, la nueva pieza del Alimerka en Primera FEB: "Pregunté por Oviedo y me dijeron ‘si no defiendes no vayas’"
https://www.lne.es/deportes/deporte-astur/2025/02/21/steven-verplancken-nueva-pieza-alimerka-114524452.html
2025/02/21 - La Nueva España

La firme voluntad de Asturias de crecer en innovación: solo Galicia crece tanto en la inversión (pero seguimos por debajo de la media)
https://www.lne.es/asturias/2025/02/21/firme-voluntad-asturias-crecer-innovacion-114528260.html
2025/02/21 - La Nueva España

Los exrectores ven "necesaria" la nueva ley de Ciencia y piden cumplirla: "Puede llegar a ser insuficiente"
https://www.lne.es/asturias/2025/02/21/exrectores-ven-necesaria-nueva-ley-114528568.html
2025/02/21 - La Nueva España

El llamativo experimento de un científico asturiano en la Antártida (y tiene relación con la basura y el whiskey)
https://www.lne.es/asturias-exterior/2025/02/21/llamativo-experimento-cientifico-asturiano-antartida-114535615.html
2025/02/21 - La Nueva España

Una escucha activa y empatía, claves para una mejor relación paternofilial
https://www.lne.es/aviles/2025/02/21/escucha-activa-empatia-claves-mejor-114528055.html
2025/02/21 - La Nueva España

Cuatro mil hogares ya pueden conocer en tiempo real su consumo de agua
https://www.lne.es/aviles/2025/02/21/cuatro-mil-hogares-conocer-tiempo-114528069.html
2025/02/21 - La Nueva España

«Somos el altavoz del Colegio Mayor América»
https://www.elcomercio.es/oviedo/antiguos-alumnos-colegio-mayor-america-miguel-cuesta-20250221080826-nt.html
2025/02/21 - El Comercio

Drones para estudiar a las carabelas portuguesas y predecir su llegada a la costa de Gran Canaria
https://www.eldiario.es/canariasahora/ciencia_y_medio_ambiente/drones-estudiar-carabelas-portuguesas-predecir-llegada-costa-gran-canaria_1_12073769.html
2025/02/21 - ElDiario.es

La Fiscalía recurre la absolución del exministro Álvarez-Cascos por uso indebido de fondos de Foro Asturias
https://www.eldiario.es/asturias/fiscalia-recurre-absolucion-exministro-alvarez-cascos-indebido-fondos-foro-asturias_1_12073557.html
2025/02/21 - ElDiario.es

Divulgar para combatir los bulos y la pseudociencia
https://www.elcomercio.es/asturias/alba-moran-divulgar-combatir-bulos-pseudociencia-20250220165646-nt.html
2025/02/20 - El Comercio

Carlos López: «La orografía hace que Asturias sea una potencia investigadora y un referente en geología»
https://www.elcomercio.es/culturas/aula-cultura/aula-cultura-voz-aviles-carlos-lopez-argayos-asturias-20250220104352-nt.html
2025/02/20 - El Comercio

Susana Madera será viceconsejera de Medio Ambiente del Principado de Asturias
https://www.elcomercio.es/asturias/susana-madera-viceconsejera-medio-ambiente-principado-asturias-20250220213822-nt.html
2025/02/20 - El Comercio

ACTOS LA REGENTA OVIEDO | Oviedo celebra los  140 años de La Regenta" con cine, teatro, zarzuela, conciertos, lecturas: fechas y horas de las actividades
https://www.lne.es/oviedo/2025/02/20/oviedo-celebra-140-anos-regenta-114516730.html
2025/02/20 - La Nueva España

Desconocido
https://www.lne.es/oviedo/2025/02/20/medio-siglo-colegio-mayor-cambio-114488808.html
2025/02/20 - La Nueva España

PROYECTOS SOCIALES | La Fundación Vinjoy quiere exportar sus proyectos a Iberoamérica
https://www.lne.es/oviedo/2025/02/20/fundacion-vinjoy-quiere-exportar-proyectos-114525237.html
2025/02/20 - La Nueva España

El Acuario de Gijón pasa a jugar "en la Champions League": "Sois un modelo a seguir en la élite de la conservación"
https://www.lne.es/gijon/gijon-oeste/2025/02/20/acuario-gijon-pasa-jugar-champions-114525005.html
2025/02/20 - La Nueva España

Álex Tirador, del Alimerka Oviedo Baloncesto, pasa a jugar en Tercera FEB con el Universidad
https://www.lne.es/deportes/deporte-astur/2025/02/20/alex-tirador-alimerka-oviedo-baloncesto-114524469.html
2025/02/20 - La Nueva España

Desconocido
https://www.lne.es/asturias/2025/02/20/fernando-laserna-nuevo-fiscal-delegado-114503956.html
2025/02/20 - La Nueva España

SOCIALISTAS DE ASTURIAS | De los gusanitos y el albergue a lo más alto del socialismo asturiano: la historia de la generación de Barbón que controla la FSA
https://www.lne.es/asturias/2025/02/20/gusanitos-albergue-alto-socialismo-asturiano-114299241.html
2025/02/20 - La Nueva España

La sierense Susana Madera, nueva viceconsejera de Medio Ambiente del Principado
https://www.lne.es/asturias/2025/02/20/sierense-susana-madera-nueva-viceconsejera-114526767.html
2025/02/20 - La Nueva España

¿Cuál es el origen de la expresión ponerse como el Quico?
https://www.telecinco.es/noticias/curioso/20250220/origen-expresion-ponerse-como-quico_18_014595274.html
2025/02/20 - Telecinco

El nuevo instituto de La Corredoria Margarita Salas se inaugurará en septiembre
https://www.rtpa.es/noticias-asturias/2025-02-20/El-nuevo-instituto-de-La-Corredoria-Margarita-Salas-se-inaugurara-en-septiembre_111740058734.html
2025/02/20 - Radiotelevisión del Principado de Asturias (RTPA)

Noelia Rico sustituye a Roger Campione al frente del Centro de Estudios sobre el Impacto Social de la Inteligencia Artificial
https://www.rtpa.es/noticias-asturias/2025-02-20/Noelia-Rico-sustituye-a-Roger-Campione-al-frente-del-Centro-de-Estudios-sobre-el-Impacto-Social-de-la-Inteligencia-Artificial_111740044761.html
2025/02/20 - Radiotelevisión del Principado de Asturias (RTPA)

Qué hacer en Asturias hoy, 20 de febrero
https://www.elcomercio.es/planes/que-hacer-asturias-20-febrero-agenda-planes-20250220093928-nt.html
2025/02/20 - El Comercio

Yolanda Díaz avanza una futura Ley de Democracia en la Empresa basándose en propuestas de expertos
https://www.elespanol.com/invertia/empresas/20250220/yolanda-diaz-avanza-futura-ley-democracia-empresa-basandose-propuestas-expertos/925657799_0.html
2025/02/20 - El Español

Yolanda Díaz arranca el estudio para que los trabajadores ganen poder en las empresas: “Es una revolución democrática”
https://www.eldiario.es/economia/yolanda-diaz-arranca-estudio-dar-trabajadores-empresas-revolucion-democratica_1_12070002.html
2025/02/20 - ElDiario.es

Fernando Laserna, nuevo fiscal delegado en Asturias de Personas con Discapacidad y Mayores
https://www.eldiario.es/asturias/fernando-laserna-nuevo-fiscal-delegado-asturias-personas-discapacidad-mayores_1_12068985.html
2025/02/20 - ElDiario.es

Dos candidaturas optan a dirigir el PSOE de Oviedo: Delia Losa disputa el cargo con Aquilino Díaz
https://www.eldiario.es/asturias/candidaturas-optan-dirigir-agrupacion-socialista-oviedo-delia-losa-disputa-cargo-aquilino-diaz_1_12069529.html
2025/02/20 - ElDiario.es

Encontrado en Ribadeo el gusano invasor que come mejillones y ostras
https://www.rtpa.es/noticias-asturias/2025-02-19/Encontrado-en-Ribadeo-el-gusano-invasor-que-devora-mejillones-y-ostras_111739966898.html
2025/02/19 - Radiotelevisión del Principado de Asturias (RTPA)

Desconocido
https://www.rtpa.es/audio:La-radio-es-mia_1739970650.html
2025/02/19 - Radiotelevisión del Principado de Asturias (RTPA)

Alba Rodríguez, nueva secretaria general de las Juventudes Socialistas de Avilés
https://www.elcomercio.es/aviles/alba-rodriguez-secretaria-general-juventudes-socialistas-aviles-20250219175846-nt.html
2025/02/19 - El Comercio

Desconocido
https://www.elcomercio.es/asturias/universidad-oviedo-doctorados-europeos-inteligencia-artificial-desarrollo-sostenible-20250219142942-nt.html
2025/02/19 - El Comercio

Desconocido
https://www.elcomercio.es/asturias/ley-ciencia-asturias-aprobada-bases-csic-asturiano-20250219104744-nt.html
2025/02/19 - El Comercio

Desconocido
https://www.elcomercio.es/asturias/dia-mujer-8m-asturias-educacion-igualdad-20250219095638-nt.html
2025/02/19 - El Comercio

Desconocido
https://www.elcomercio.es/asturias/colegio-oficial-medicos-asturias-luis-antuna-candidatura-20250219211724-nt.html
2025/02/19 - El Comercio

Desconocido
https://www.elcomercio.es/culturas/aula-cultura/aula-cultura-voz-aviles-carlos-lopez-argayos-20250219093103-nt.html
2025/02/19 - El Comercio

«En Asturias están en peligro casi 2.000 puestos de trabajo de las consejerías Hacienda y Derechos Sociales»
https://www.elcomercio.es/asturias/asturias-peligro-2000-puestos-trabajo-consejerias-hacienda-20250219151711-nt.html
2025/02/19 - El Comercio

La profesora Noelia Rico, nueva directora del centro de Inteligencia Artificial de Lugones
https://www.elcomercio.es/area-metropolitana-asturias/siero-centro/noelia-rico-directora-centro-inteligencia-artificial-lugones-20250219202621-nt.html
2025/02/19 - El Comercio

El PSOE dice que Foro y PP están convirtiendo Gijón en una ciudad gregaria de Oviedo
https://www.elcomercio.es/gijon/psoe-foro-pp-gijon-ciudad-gregaria-oviedo-20250219203919-nt.html
2025/02/19 - El Comercio

Desconocido
https://www.eldiario.es/asturias/mieres-apoya-creacion-junta-productores-garantizar-actividad-ganadera-pastos-leon_1_12065983.html
2025/02/19 - ElDiario.es

Desconocido
https://www.eldiario.es/asturias/audiencia-asturias-sobresee-causa-penal-cinco-activistas-climaticos-coacciones-arcelor_1_12065931.html
2025/02/19 - ElDiario.es

Desconocido
https://www.eldiario.es/asturias/llamamiento-urgente-donar-sangre-asturias-grave-escasez-reservas_1_12066382.html
2025/02/19 - ElDiario.es

Desconocido
https://www.elcomercio.es/asturias/universidad-oviedo-grados-conjuntos-ciudades-europa-alianza-ingenium-20250218145311-nt.html
2025/02/18 - El Comercio

Desconocido
https://migijon.com/los-tres-templos-de-el-bibio/
2025/02/18 - Mi Gijón

Desconocido
https://www.elcomercio.es/culturas/tv/asturiana-minerva-piquero-pionera-mujer-tiempo-pasapalabra-20250218195808-nt.html
2025/02/18 - El Comercio

Desconocido
https://www.elcomercio.es/area-metropolitana-asturias/siero-centro/siero-universidad-oviedo-inteligencia-artificial-20250218094531-nt.html
2025/02/18 - El Comercio

Desconocido
https://www.culturalgijonesa.org/laboral-centro-de-arte-y-asturias-el-experimentalismo-popular-de-pablo-de-soto/
2025/02/18 - Cultural Gijonesa

Desconocido
https://www.eldiario.es/asturias/maestro-presidente-asturias-antonio-trevin-master-vida-dedicada-politica-socialismo_1_12060775.html
2025/02/18 - ElDiario.es

Desconocido
https://www.elcomercio.es/asturias/universidad-oviedo-doble-grado-pedagogia-20250218155838-nt.html
2025/02/18 - El Comercio

Desconocido
https://www.eldiario.es/asturias/puesta-libertad-maltratador-multirreincidente-asturias-enfrenta-fiscalia-tsja_1_12061740.html
2025/02/18 - ElDiario.es

Desconocido
https://www.eldiario.es/asturias/bomberos-asturias-excarcelan-conductores-atrapados-vehiculos-brutal-colision-mieres_1_12062008.html
2025/02/18 - ElDiario.es

Reunión del Ingenium Alliance Council en la Universidad de Oviedo
https://www.rtpa.es/noticias-asturias/2025-02-18/Reunion-del-Ingenium-Alliance-Council-en-la-Universidad-de-Oviedo_111739885990.html
2025/02/18 - Radiotelevisión del Principado de Asturias (RTPA)

Desconocido
https://www.elcomercio.es/oviedo/preuniversitarios-oviedo-jornadas-orientacion-busca-futuro-20250217180258-nt.html
2025/02/18 - El Comercio

Desconocido
https://www.elfielato.es/opinion/borja/director-bosch-parador-cangas/20250218094611075448.html
2025/02/18 - El Fielato y El Nora

Desconocido
https://www.eldiario.es/canariasahora/fuerteventuraahora/falta-lluvia-condena-tarabilla-canaria-ave-endemica-fuerteventura_1_12062762.html
2025/02/18 - ElDiario.es

Desconocido
https://www.eldiario.es/edcreativo/peregrinar-asturias-tres-caminos-santiago_1_12047088.html
2025/02/18 - ElDiario.es

Desconocido
http://www.asturiasmundial.com/noticia/111057/peter-burke-id-arcelormittal-gregory-ludkovsky-honoris-causa-por-oviedo/#.XcBLIdT1TaQ.tumblr
Desconocido - Asturials Mundial

Desconocido
http://www.asturiasmundial.com/noticia/138972/asturias-convierte-8m-mes-accion-educacion-cine-deporte-impulsar-igualdad-real/
Desconocido - Asturials Mundial

Desconocido
http://www.asturiasmundial.com/noticia/138978/asturias-blinda-futuro-cientifico-nueva-ley-ciencia-mas-financiacion-csic-propio-ecosistema-innovador/
Desconocido - Asturials Mundial

Desconocido
http://www.asturiasmundial.com/noticia/138997/noelia-rico-nueva-directora-ceisia-una-experta-inteligencia-artificial-frente-futuro-tecnologico-asturias/
Desconocido - Asturials Mundial

Desconocido
http://www.asturiasmundial.com/noticia/139005/asturias-consolida-como-referente-computacion-cuantica-avances-clave-simulacion-aplicaciones-empresariales/
Desconocido - Asturials Mundial

Desconocido
http://www.asturiasmundial.com/noticia/139025/aguas-aviles-lanza-plan-estrategico-resencialr-30-medidas-transformar-gestion-agua-ciudad/
Desconocido - Asturials Mundial

Desconocido
http://www.gentedigital.es/albacete/noticia/4005052/una-marcha-en-albacete-dara-10-millones-de-pasos-y-recaudara-3000-euros-para-reparar-el-restaurante-el-buho-de-letur/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/albacete/noticia/4006825/uclm-acoge-en-albacete-el-i-congreso-internacional-sobre-la-enfermedad-neurodegenerativa-demencia-con-cuerpos-de-lewy/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4006506/teatre-arniches-presenta-la-maestra-de-la-compania-de-titeres-anita-maravillas/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4006757/el-cenid-presenta-un-metodo-para-agilizar-procesos-administrativos-mediante-automatizacion-e-ia/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4007606/un-estudio-de-csic-umh-revela-un-mecanismo-clave-para-controlar-la-actividad-que-regula-la-identidad-neuronal/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4008564/investigadores-de-la-ua-reutilizan-residuos-de-posidonia-oceanica-para-recuperar-el-sabor-del-tomate/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/alicante/noticia/4008669/hydros-power-del-parque-cientifico-de-la-ua-capta-190000-euros-del-instituto-de-tecnologia-europeo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/almeria/noticia/4008134/diputacion-la-alianza-almeria-unida-por-la-igualdad-presenta-sus-actividades-de-cara-al-dia-de-la-mujer/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/avila/noticia/4005365/la-ucav-bate-record-de-participacion-en-el-85-encuentro-de-universitarios-con-mas-de-170-participantes/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/avila/noticia/4007892/la-ucav-aborda-en-unas-jornadas-la-proteccion-de-la-naturaleza-en-el-ambito-policial/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/burgos/noticia/4002695/el-73-de-los-jovenes-de-burgos-que-usan-el-servicio-de-salud-joven-consultan-por-ansiedad-y-gestion-emocional/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/burgos/noticia/4002816/la-ubu-se-une-al-observatorio-tecnologico-del-hidrogeno-enagas-para-impulsar-la-innovacion-en-hidrogeno-renovable/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/burgos/noticia/4003371/proteccion-civil-de-burgos-se-centra-en-2024-en-la-concienciacion-en-seguridad-en-los-centros-escolares/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ciudad-real/noticia/4007043/rozalen-y-la-unidad-militar-de-emergencias-entre-los-reconocimientos-del-consejo-social-de-la-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cordoba/noticia/4007654/la-universidad-loyola-y-ey-reunen-a-un-centenar-de-profesionales-para-abordar-los-retos-de-la-gestion-financiera/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cordoba/noticia/4008177/cien-escolares-de-cabra-aprenderan-a-prevenir-accidentes-con-la-campana-aprende-a-crecer-con-seguridad/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/cordoba/noticia/4008297/villamandos-apuesta-por-el-liderazgo-de-los-andaluces-como-eslabon-crucial-en-la-cadena-innovadora/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/gijon/noticia/4008117/diaz-avanza-una-futura-ley-de-democracia-en-la-empresa-basada-en-propuestas-de-expertos-uno-de-la-universidad-de-oviedo/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/granada/noticia/4007231/la-junta-subraya-que-2025-sera-clave-para-la-construccion-del-edificio-que-albergue-el-ifmif-dones/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/granada/noticia/4008084/el-escritor-jorge-volpi-reflexionara-sobre-la-historia-del-mundo-en-una-charla-en-la-madraza/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/guadalajara/noticia/4005020/c-lm-tendra-lista-antes-de-semana-santa-la-estrategia-para-blindar-la-gratuidad-del-primer-ano-de-matricula-en-la-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/guadalajara/noticia/4005186/video-c-lm-tendra-lista-antes-de-semana-santa-la-estrategia-para-blindar-gratuidad-del-primer-ano-de-matricula-en-uclm/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4007372/la-catedra-de-innovacion-social-de-aguas-de-huelva-entrega-sus-premios-trabajos-fin-de-grado-y-de-master/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4008100/el-proyecto-bioecon4fish-incorpora-la-dimension-economica-y-social-a-la-pesqueria-del-boqueron-en-el-golfo-de-cadiz/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/huelva/noticia/4008222/rosa-maria-leon-y-rosario-marquez-reciben-el-premio-a-la-excelencia-investigadora-jose-luis-garcia-palacios/
Desconocido - Gente Digital

Desconocido
http://www.gentedigital.es/ibiza/noticia/4006628/educacion-gestionara-la-cobertura-de-las-plazas-de-los-ates-a-partir-de-septiembre/