## Instalación de librerías

In [1]:
!pip install -q scrapy
#!pip install -q newspaper4k
!pip install -q newspaper3k
!pip install -q lxml_html_clean

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 793.6 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 25.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.8/259.8 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.9/104.9 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.6/74.6 kB 3.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 41.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.3/81.3 kB 5.2 MB/s eta 0:00:00
  Building wheel for tinysegmenter (setup.py) ... done
  Building wheel for feedfinder2 (setup.py) ... done
  Building wheel for jieba3k (setup.py) ... done
  Building wheel for sgmllib3k (setup.py) ... done

# Articulos de mapas de sitio usando scrapy

In [1]:
!scrapy startproject news_scraper

Error: scrapy.cfg already exists in C:\Users\rebec\OneDrive - Universidad de Oviedo\Escritorio\TFG\news_scraper

## Extracción de URLs

In [2]:
%cd news_scraper

c:\Users\rebec\OneDrive - Universidad de Oviedo\Escritorio\TFG\news_scraper

### Sitios web

In [ ]:
%%writefile "config_urls.py"
# Metadata: nombre y sitemap
METADATA_URLS={
    'https://www.elcomercio.es/': {'nombre': 'El Comercio'},
    'https://www.lne.es/': {'nombre': 'La Nueva España'},
    'https://www.lavanguardia.com/': {'nombre': 'La Vanguardia',
                              'sitemap': ['sitemap-google-news.xml',
                                          'sitemap-news-agencias.xml'] +
                              [f'sitemap-news-agencias-{i}.xml' for i in range(1, 10)]},
    'https://www.larazon.es/': {'nombre': 'La Razón'},
    'https://www.rtpa.es/': {'nombre': 'Radiotelevisión del Principado de Asturias (RTPA)',
                              'sitemap': 'sitemap-noticias.xml'},
    'https://www.europapress.es/': {'nombre': 'Europa Press'},
    'https://www.20minutos.es/': {'nombre': '20 Minutos',
                                  'sitemap': 'sitemap-google-news.xml'},
    'https://www.elperiodico.com/' : {'nombre': 'El Periódico',
                                      'sitemap': 'google-news.xml'},
    'https://www.eldiario.es/' : {'nombre': 'ElDiario.es'},
    'https://www.elconfidencial.com/': {'nombre': 'El Confidencial',
                                        'sitemap': 'newsitemap_4.xml'},
    'https://www.culturalgijonesa.org/': {'nombre': 'Cultural Gijonesa'},
    'https://www.elespanol.com/' : {'nombre': 'El Español',
                                    'sitemap': 'sitemap_google_news.xml'},
    'https://www.nortes.me/': {'nombre': 'Nortes'},
    'https://www.tribunasalamanca.com/': {'nombre': 'Tribuna Salamanca'},
    'https://migijon.com/': {'nombre': 'Mi Gijón'},
    'https://www.infobae.com/' : {'nombre': 'Infobae',
                                  'sitemap': 'arc/outboundfeeds/news-sitemap2/'},
    'https://www.telecinco.es/' : {'nombre': 'Telecinco'},
    'https://www.laprovincia.es/' : {'nombre': 'La Provincia'},
    'https://www.laopiniondemalaga.es/': {'nombre': 'La Opinión de Málaga'},
    'https://www.elfielato.es/': {'nombre': 'El Fielato y El Nora'},
    'https://www.teleprensa.com/': {'nombre': 'Teleprensa'},
    'https://forbes.es/': {'nombre': 'Forbes'},
    'https://itg.es/': {'nombre': 'ITG centro tecnológico'},
    'https://www.eldia.es/': {'nombre': 'El Dia'},
    'https://www.nationalgeographic.es/': {'nombre': 'Historia National Geographic'},
    'https://iymagazine.es/': {'nombre': 'IyMagazine'},
    'https://www.lacerca.com/': {'nombre': 'La Cerca'},
    'https://www.tribunaavila.com/': {'nombre': 'Tribuna de Ávila'},
    'https://www.latribunadealbacete.es/': {'nombre': 'La Tribuna de Albacete'},
    'https://www.eldiariomontanes.es/': {'nombre': 'El Diario Montañés'},
    "https://www.larioja.com/":{"nombre": "La Rioja"},
    "https://www.almerianoticias.es/":{"nombre": "Almería Noticias"},
    "https://news.ual.es/":{"nombre": "UALNEWS"},
    "https://www.farodevigo.es/":{"nombre": "Faro de Vigo"},
    "https://www.diariocordoba.com/": {'nombre': 'Diario Córdoba'},
    "https://www.diariodeibiza.es/": {'nombre': 'Diario de Ibiza'},
    "https://segoviaudaz.es/": {'nombre': 'SegoviAudaz'},
    'https://www.noticiasde.es/': {'nombre': 'NoticiasDe'},
    'https://www.redaccionmedica.com/': {'nombre': 'Redacción Médica'},
    'https://cronicadeandalucia.com/': {'nombre': 'Crónica de Andalucía'},
    'https://www.diariodevalderrueda.es/': {'nombre': 'Diario de Valderrueda'},
    'https://galiciadigital24horas.com/': {'nombre': 'Galicia Digital 24 Horas'},
    'https://www.laescena.es/': {'nombre': 'La Escena'},
    'https://valencia24horas.com/': {'nombre': 'Valencia 24 Horas'},
    'https://www.eleconomista.es/': {'nombre': 'El Economista'},
    'https://www.ondacero.es/': {'nombre': 'Onda Cero'},
    'https://www.laopinioncoruna.es/': {'nombre': 'La Opinión A Coruña'},
    'https://economia3.com/': {'nombre': 'Economía 3'},
    'https://inmediaciones.org/': {'nombre': 'Inmediaciones' },
    'https://www.sport.es/': {'nombre': 'Sport'},
    'https://ort-ort.com/': {'nombre': 'ORT Noticias del Occidente de Asturias'},
    'https://ethic.es/': {'nombre': 'Ethic'},
    'https://www.tribunaavila.com/': {'nombre': 'Tribuna Ávila'},
    'https://www.laopiniondezamora.es/': {'nombre': 'La Opinión de Zamora'},
    'https://www.elcorreogallego.es/': {'nombre': 'El Correo Gallego'},
    'https://www.informacion.es/': {'nombre': 'INFORMACIÓN'},
    'https://www.elperiodicoextremadura.com/': {'nombre': 'El Periódico Extremadura'},
    'https://www.laopiniondemurcia.es/': {'nombre': 'La Opinión de Murcia'},
    'https://www.levante-emv.com/': {'nombre': 'Levante-EMV' },
    'https://www.diariodemallorca.es/': {'nombre': 'Diario de Mallorca'},
    'https://www.elperiodicodearagon.com/': {'nombre': 'El Periódico de Aragón'},
    'https://www.latribunadealbacete.es/': {'nombre': 'La Tribuna de Albacete'},
    'https://www.diariosur.es/': {'nombre': 'Diario Sur'},
    'https://www.malagahoy.es/': {'nombre': 'Málaga Hoy'},
    'https://www.superdeporte.es/': {'nombre': 'Superdeporte'},
    'https://www.elperiodicomediterraneo.com/': {'nombre': 'El Periódico Mediterráneo'},
    'https://www.salamanca24horas.com/': {'nombre': 'Salamanca 24 Horas' },
    'https://www.lacerca.com/': {'nombre': 'La Cerca'},
    'https://deportesmenorca.com/': {'nombre': 'Deportes Menorca'},
    'https://menorcaaldia.com/': {'nombre': 'Menorca al Día'},
    'https://www.lanzadigital.com/': {'nombre': 'Lanza Digital'},
    'https://www.menorca.info/': {'nombre': 'MENORCA'},
    'https://www.lacomarcadepuertollano.com/': {'nombre': 'La Comarca de Puerto Llano'},
    'https://www.gciencia.com/': {'nombre': 'GCiencia'},
    'https://www.eldebate.com/': {'nombre': 'El Debate', 'sitemap': 'sitemap-index.xml' },
    'https://www.magisnet.com/': {'nombre': 'Magisnet', 'sitemap': 'sitemap_index.xml'},
    'https://www.corresponsables.com/': {'nombre': 'Corresponsables',
                                          'sitemap': [f'post-sitemap{i}.xml' for i in range(30, 50)]},
    'https://www.diariodepontevedra.es/': {'nombre': 'Diario de Pontevedra'},
    'https://www.infoclm.es/': {'nombre': 'Periódico digital de Castilla-La Mancha'},
    'https://mariskalrock.com/': {'nombre': 'MariskalRock'},
    'https://salamancartvaldia.es/': {'nombre': 'Salamanca al Día'},
            'https://diariofarma.com/': {'nombre': 'Diario Farma'},
    'https://valenciaplaza.com/': {'nombre': 'Valencia Plaza'},
    'https://www.mundiario.com/': {'nombre': 'Mundiario'},
    'https://www.farmaventas.es/': {'nombre': 'Farmaventas',
                                    'sitemap': 'sitemap.xml'},
    'https://elportaluco.com/': {'nombre': 'El Portaluco'},
            'https://entomelloso.com/': {'nombre': 'Tomelloso'},
    'https://www.granadadigital.es/': {'nombre': 'Granada Digital',
                                        'sitemap': 'sitemap_index.xml'},
    'https://www.lavozdegalicia.es/': {'nombre': 'La Voz de Galicia'},
    'https://www.asturiasmundial.com/': {'nombre': 'Asturias Mundial'},
    'https://www.lagacetadesalamanca.es/': {'nombre': 'La Gaceta de Salamanca'},
    'https://noticias.juridicas.com/': {'nombre': 'Noticias Jurídicas'},
    'https://fernandezrozas.com/': {'nombre': 'Blog de José Carlos Fernández Rozas',
                                    'sitemap': 'news-sitemap.xml'},
    'https://www.vozpopuli.com/': {'nombre': 'Voz Populi'},
    'https://www.diariodelpuerto.com/': {'nombre': 'Diario del Puerto'},
    'https://www.abc.es/': {'nombre': 'ABC'}, #newspaper
    'https://www.lavozdeasturias.es/': {'nombre': 'La Voz de Asturias'},
    'https://cualia.es/': {'nombre': 'Cualia'},
    'http://www.gentedigital.es/' : {'nombre': 'Gente Digital'},
    'https://www.8directo.com/':{'nombre': '8directo'},
    'https://www.lanuevacronica.com/': {'nombre': 'La Nueva Crónica'},
    'https://elpais.com/': {'nombre': 'El Pais'},
    'https://www.elperiodicodecanarias.es/': {'nombre': 'El Periodico de Canarias'},
    'https://www.immedicohospitalario.es/': {'nombre': 'IM Médico'},
    'https://bilbao24horas.com/': {'nombre': 'Bilbao 24 Horas'},
    'https://www.diariodeleon.es/': {'nombre': 'Diario de León'},
    'https://cronicaeconomica.com/': {'nombre': 'Crónica Económica'},
    'https://ahoraleon.com/': {'nombre': 'Ahora León'},
    "https://www.feb.es/": {'nombre': 'Federación Española de Baloncesto'},
    'https://www.consalud.es/': {'nombre': 'ConSalud'},
    'https://www.rrhhdigital.com/': {'nombre': 'RRHH Digital'},
    'https://www.diariomedico.com/': {'nombre': 'Diario Médico'},
    'https://vivirediciones.es/': {'nombre': 'Vivir Ediciones'},
    'https://www.granadahoy.com/': {'nombre': 'Granada Hoy'},
    'https://www.espormadrid.es/': {'nombre': 'Es por madrid'},
    'https://www.granadaesnoticia.com/': {'nombre': 'Granada es noticia'},
    'https://novaciencia.es/': {'nombre': 'Nova Ciencia'},
    'https://www.industriaquimica.es/': {'nombre': 'Industria Química'},
    'https://www.bolsamania.com/': {'nombre': 'Bolsamania',
                                    'sitemap': 'sitemap.xml'},
    'https://www.rutapesquera.com/': {'nombre': 'Ruta Pesquera'},
    'https://www.santanderdigital24horas.com/': {'nombre': 'Santander Digital 24 Horas'},
    'https://isanidad.com/': {'nombre': 'iSanidad'},
    'https://www.vocesdecuenca.com/': {'nombre': 'Voces de Cuenca'}
}

Overwriting config_urls.py

Copiar archivo a carpeta

In [4]:
# !cp config_urls.py news_scraper/
!copy config_urls.py news_scraper\

        1 archivo(s) copiado(s).

### Extracción de enlaces

In [5]:
%%writefile "news_extractor_spider.py"
import scrapy
from newspaper import build, Config, Article
import requests
from urllib.parse import urljoin, urlparse
import os
import time
import re
from datetime import datetime
import gzip
from scrapy.selector import Selector
import dateutil
from config_urls import METADATA_URLS


class NewsUrlExtractorSpider(scrapy.Spider):
    name = 'news_extractor'

    def __init__(self, date="2025-01-01", *args, **kwargs):
        super(NewsUrlExtractorSpider, self).__init__(*args, **kwargs)
        self.from_date = datetime.strptime(date, '%Y-%m-%d').date()
        self.invalid_url_words = {'section', 'tag', 'template',
                                  'category', 'author', 'page-sitemap'
                                  'categories', 'video', 'image', 'temas',
								                  'live', 'microsite', 'focus', 'blog',
                                  'ocio', 'cine', 'board', 'character',
                                  'galeria', 'categoria', 'ficha', 'firmante',
                                  'secciones', 'hemeroteca', 'landing',
                                  'sorteo', 'elecciones', 'autor', 'hilos', 'cartelera'}
        self.metadata_urls = METADATA_URLS

    #metadata_urls = {
    #    'https://fernandezrozas.com/': {'nombre': 'Blog de José Carlos Fernández Rozas'},
    #}

    custom_settings = {
        'USER_AGENT': "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0",
        #'DOWNLOAD_DELAY': 2,   # Agregar delay 0.5 segundos entre requests
        #'RETRY_TIMES': 5       #
    }

    # Para extracción de xmls
    namespaces = {
        'ns': 'http://www.sitemaps.org/schemas/sitemap/0.9',  # Default namespace
        'news': 'http://www.google.com/schemas/sitemap-news/0.9'
    }

    def get_base_url(self, url):
        parsed_url = urlparse(url)
        return f"{parsed_url.scheme}://{parsed_url.netloc}/"

    def normalize_date(self, date_string):
        try:
            # Conviertir la cadena de fechas en un objeto datetime
            parsed_date = dateutil.parser.parse(date_string)
            # Formatea el objeto datetime como 'YYYY-MM-DD'
            #return parsed_date.strftime('%Y-%m-%d')
            return parsed_date.date()
        except (ValueError, TypeError):
            #raise ValueError(f"Formato de fecha inválido: '{date_string}'")
            print(f"Formato de fecha inválido: '{date_string}'")
            return None

    def is_valid_xml_url(self, sitemap_url):
        for invalid_word in self.invalid_url_words:
            if invalid_word in sitemap_url:
                return False

        pattern = r'\b(1[0-9]{3}|20[0-1][0-9]|202[0-4])\b' # Matches 1000-1999, 2000-2019, and 2020-2024
        match_url = re.search(pattern, sitemap_url)
        if match_url:
            return False
        else:
            return True

    def start_requests(self):
        for url in self.metadata_urls:
            #yield scrapy.Request(url=url, callback=self.parse, errback=lambda failure: self.handle_error(failure, url))
            yield scrapy.Request(url=url, callback=self.parse)


    def handle_error(self, failure, domain=None):
        if failure and failure.value and failure.value.response:
            print(f"Request fallida: {failure.value.response.status} para {failure.request.url}")
        else:
            print(f"Request fallida para {failure.request.url}")
        print(f"Accediendo a enlaces con librería Newspaper...")
        if domain is None:
            domain = failure.request.url
        yield from self.get_news_urls(domain)


    def parse(self, response):
        robots_url = urljoin(response.url, "/robots.txt")
        print(f'Robots URL: {robots_url}')
        self.valid_robots = False
        yield scrapy.Request(robots_url, callback=self.parse_robots,
                             meta={'domain': response.url},
                             errback=lambda failure: self.handle_error(failure, response.url))#self.get_base_url(response.url)))


    def is_full_url(self, url):
        parsed = urlparse(url)
        return bool(parsed.scheme) and bool(parsed.netloc)


    def parse_robots(self, response):
        if response.status != 200:
            print(f"Error al acceder a la url: {response.status}.")
            return
        self.valid_robots = True

        domain = response.meta['domain']
        domain_base = self.get_base_url(domain)

        current_sitemap_urls = set() #[]

        # Extraer urls de sitemaps de robots.txt
        for line in response.text.splitlines():
            if line.lower().startswith('sitemap:'):
                sitemap_url = line.split(':', 1)[1].strip()
                parsed_url = urlparse(sitemap_url)
                file_path = parsed_url.path
                file_name, file_extension = os.path.splitext(file_path)
                if self.is_valid_xml_url(sitemap_url):
                    current_sitemap_urls.add(sitemap_url)

        if len(current_sitemap_urls) > 0:
            print(f"Se encontraron los siguientes enlaces xml: {current_sitemap_urls}")

            for enum, sitemap_url in enumerate(current_sitemap_urls):
                print(f"Accediendo al siguiente enlace... {sitemap_url}")
                #yield scrapy.Request(sitemap_url, callback=self.parse_sitemap)  # Llamada recursiva
                if enum == 0:
                    yield scrapy.Request(sitemap_url,
                                         callback=lambda response: self.parse_sitemap(response, domain),
                                         errback=lambda failure: self.handle_error(failure, domain) )
                else:
                    yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain) )

        elif domain_base in self.metadata_urls and 'sitemap' in self.metadata_urls[domain_base]:
            print("No se encontraron enlaces xml en robots.txt.", end=" ")
            sitemap_names = self.metadata_urls[domain_base]['sitemap']
            if isinstance(sitemap_names, list):
                for sitemap_name in sitemap_names:
                    sitemap_url = urljoin(domain_base, sitemap_name)
                    print(f"Accediendo al siguiente enlace especificado... {sitemap_url}")
                    yield scrapy.Request(sitemap_url, callback=lambda response: self.parse_sitemap(response, domain_base) )
            else:
                sitemap_url = urljoin(domain_base, sitemap_names)
                print(f"Accediendo al siguiente enlace especificado... {sitemap_url}")
                #yield scrapy.Request(sitemap_url, callback=self.parse_sitemap)
                yield scrapy.Request(sitemap_url,
                                     callback=lambda response: self.parse_sitemap(response, domain_base),
                                     errback=lambda failure: self.handle_error(failure, domain) )
        else:
            print("No se encontraron enlaces xml. Accediendo a enlaces con librería Newspaper...")
            # Si no se encuentra ningún mapa del sitio,
            # utilizar Newspaper4k para obtener las URL de los artículos de noticias
            yield from self.get_news_urls(domain)


    def parse_sitemap(self, response, domain=None):

        # Sitemaps anidados. Tag <sitemap>
        for sitemap in response.xpath('//ns:sitemap', namespaces=self.namespaces):
            sitemap_loc = sitemap.xpath('./ns:loc/text()', namespaces=self.namespaces).get()

            # Omitir sitemaps antiguos
            last_mod = sitemap.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()
            if last_mod:
                lastmod = self.normalize_date(last_mod)
                if lastmod < self.from_date:
                    continue
            #else:
            #    continue

            # Algunas sitemaps no contiene la url completa, agregar base_url
            if not self.is_full_url(sitemap_loc):
                sitemap_loc = urljoin(domain, sitemap_loc)


            # Verificar que la url es un archivo xml
            parsed_url = urlparse(sitemap_loc)
            file_path = parsed_url.path
            file_name, file_extension = os.path.splitext(file_path)


            if file_extension.lower() != '.gz' and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                #print(f'Se encontró otro xml dentro del archivo actual: {sitemap_loc}') ## lots of outputs
                if sitemap_loc:
                    #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap)  # Llamada recursiva
                    yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap(response, domain) )
            elif file_extension.lower() == '.gz'  and self.is_valid_xml_url(sitemap_loc):#'section' not in sitemap_loc:
                print(f"Se encontró archivo comprimido {sitemap_loc}")
                #yield scrapy.Request(sitemap_loc, callback=self.parse_sitemap_gz)
                yield scrapy.Request(sitemap_loc, callback=lambda response: self.parse_sitemap_gz(response, domain) )



        # Verificar que el archivo tenga noticias recientes
        selector_list = response.xpath('//ns:url', namespaces=self.namespaces)
        if len(selector_list) > 1:
            first_publication_date = selector_list[1].xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            if first_publication_date is None:
                first_publication_date = selector_list[1].xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            last_publication_date = selector_list[-1].xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            if last_publication_date is None:
                last_publication_date = selector_list[-1].xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            if first_publication_date and last_publication_date:
                first_publication_date = self.normalize_date(first_publication_date)
                last_publication_date = self.normalize_date(last_publication_date)
                if first_publication_date < self.from_date and last_publication_date < self.from_date:
                    return # No cumple con las fechas requeridas
            else:
                return # No se tienen fechas

        # Extraer datos de cada tag <url>
        for url in selector_list:
            loc = url.xpath('./ns:loc/text()', namespaces=self.namespaces).get()
            title = url.xpath('./news:news/news:title/text()', namespaces=self.namespaces).get()
            publication_date = url.xpath('./news:news/news:publication_date/text()', namespaces=self.namespaces).get()
            fuente = url.xpath('./news:news/news:publication/news:name/text()', namespaces=self.namespaces).get()

            if loc is None or not self.is_full_url(loc):
                break

            title = "" if title is None else title

            if publication_date is None:
                publication_date = url.xpath('./ns:lastmod/text()', namespaces=self.namespaces).get()

            if publication_date is not None:
                publication_date_comp = self.normalize_date(publication_date)
                if publication_date_comp < self.from_date:
                    continue
            else:
                continue


            if domain is not None:
                domain_base = self.get_base_url(domain)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']

            yield {
                'fuente': fuente,
                'url': loc,
                'titulo': title,
                'fecha_publicacion': publication_date,
            }


    def parse_sitemap_gz(self, response, domain=None):
        compressed_file = response.body
        decompressed_file = gzip.decompress(compressed_file).decode("utf-8")
        selector = Selector(text=decompressed_file, type="xml")
        yield from self.parse_sitemap(selector, domain)


    def get_news_urls(self, domain):

        config = Config()
        config.request_timeout = 5
        config.language= 'es'
        config.thread_timeout_seconds = 5
        config.memoize_articles = False
        config.fetch_images = False
        config.follow_meta_refresh = True
        config.number_threads = 4
        config.browser_user_agent = self.custom_settings['USER_AGENT']
        config.headers = {
            "User-Agent": self.custom_settings['USER_AGENT'],
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate",
            "Connection": "keep-alive",
            "Upgrade-Insecure-Requests": "1",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Sec-Fetch-User": "?1",
            "Cache-Control": "max-age=0",
        }

        try:
            print(f'Extrayendo noticias con librería Newspaper para url: {domain}')
            start_time = time.time()
            paper = build(domain, config=config)
            print(f"--- {(time.time() - start_time):.2f}s segundos ---")
            articulos_urls = set(paper.article_urls())
            print(f'Se encontraron {len(articulos_urls)} enlaces de noticias.')

            # Obtener fuente
            if domain is not None:
                domain_base = self.get_base_url(domain)
                #print(domain_base, ' ', domain_base in self.metadata_urls)
                if domain_base in self.metadata_urls:
                    fuente = self.metadata_urls[domain_base]['nombre']
                else:
                    found_match = re.search(r"www\.(.*?)\.(.+)", domain)
                    fuente = ''
                    if found_match:
                        fuente = found_match.group(1)


            titulo, fecha_publicacion = '', None
            for articulo_url in articulos_urls:
                yield {
                    'fuente': fuente,
                    'url': articulo_url,
                    'titulo': titulo,
                    'fecha_publicacion': fecha_publicacion,
                }
        except Exception as e:
            print(f"No se pudieron obtener noticias de {domain}")

Overwriting news_extractor_spider.py

Copiar archivo spider a carpeta para ejecutar

In [6]:
# !cp news_extractor_spider.py news_scraper/spiders
!copy news_extractor_spider.py news_scraper\spiders

        1 archivo(s) copiado(s).

Eliminar csv para generar uno nuevo

In [7]:
# Eliminar csv
import os
output_file_csv = "news_output.csv"
if os.path.exists(output_file_csv):
    os.remove(output_file_csv)

Ejecutar spyder de scrapy para gener el archivo csv con los enlaces

In [8]:
!scrapy crawl news_extractor -o news_output.csv -s LOG_ENABLED=False -s ROBOTSTXT_OBEY=False
#!scrapy crawl news_extractor -o news_output.csv -s ROBOTSTXT_OBEY=False
#30 min 34.5s

Robots URL: https://www.20minutos.es/robots.txt
Robots URL: https://www.europapress.es/robots.txt
Robots URL: https://www.eldiario.es/robots.txt
Robots URL: https://www.elcomercio.es/robots.txt
Robots URL: https://www.elconfidencial.com/robots.txt
Robots URL: https://www.lne.es/robots.txt
Robots URL: https://www.elespanol.com/robots.txt
Robots URL: https://www.rtpa.es/robots.txt
Robots URL: https://migijon.com/robots.txt
Robots URL: https://www.culturalgijonesa.org/robots.txt
Robots URL: https://www.lavanguardia.com/robots.txt
Robots URL: https://www.tribunasalamanca.com/robots.txt
Robots URL: https://www.infobae.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.eldiario.es/sitemap_google_news_25b87.xml', 'https://www.eldiario.es/sitemap_index_25b87.xml'}
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_google_news_25b87.xml
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_index_25b87.xml
Robots URL: https://www.nortes.me/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.europapress.es/sitemap_index/', 'https://www.europapress.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.europapress.es/sitemap_index/
Accediendo al siguiente enlace... https://www.europapress.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.lne.es/sitemap_today_52e19.xml', 'https://www.lne.es/sitemap_google_news_52e19.xml'}
Accediendo al siguiente enlace... https://www.lne.es/sitemap_today_52e19.xml
Accediendo al siguiente enlace... https://www.lne.es/sitemap_google_news_52e19.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elconfidencial.com/newsitemap_4.xml
Robots URL: https://www.elperiodico.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.elcomercio.es/sitemap.xml', 'https://www.elcomercio.es/sitemap.incremental.xml'}
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.xml
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.incremental.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.20minutos.es/sitemap-google-news.xml
Se encontraron los siguientes enlaces xml: {'https://migijon.com/xmlsitemap.xml', 'https://migijon.com/sitemap_index.xml'}
Accediendo al siguiente enlace... https://migijon.com/xmlsitemap.xml
Accediendo al siguiente enlace... https://migijon.com/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.rtpa.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.rtpa.es/sitemap.xml
Robots URL: https://www.laprovincia.es/robots.txt
Robots URL: https://www.laopiniondemalaga.es/robots.txt
Robots URL: https://www.telecinco.es/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elespanol.com/sitemap_google_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.culturalgijonesa.org/sitemap.xml', 'https://www.culturalgijonesa.org/sitemap.rss'}
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.xml
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.rss
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-google-news.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-1.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-2.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-3.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-4.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-5.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-6.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-7.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-8.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-9.xml
Se encontraron los siguientes enlaces xml: {'https://www.tribunasalamanca.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunasalamanca.com/sitemap_last_news.xml
Robots URL: https://www.nationalgeographic.es/robots.txt
Robots URL: https://www.eldia.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.laprovincia.es/sitemap_google_news_89aa6.xml', 'https://www.laprovincia.es/sitemap_index_89aa6.xml'}
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_google_news_89aa6.xml
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_index_89aa6.xml
Se encontraron los siguientes enlaces xml: {'https://www.telecinco.es/sitemap_ampstories.xml', 'https://www.telecinco.es/sitemap_index.xml', 'https://www.telecinco.es/sitemap_google_news.xml'}
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_ampstories.xml
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_index.xml
Accediendo al siguiente enlace... https://www.telecinco.es/sitemap_google_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml', 'https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml'}
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml
Robots URL: https://iymagazine.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.nortes.me/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.nortes.me/sitemap_index.xml
Robots URL: https://www.lacerca.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.nationalgeographic.es/sitemap/sitemap.xml', 'https://www.nationalgeographic.es/google-news.xml'}
Accediendo al siguiente enlace... https://www.nationalgeographic.es/sitemap/sitemap.xml
Accediendo al siguiente enlace... https://www.nationalgeographic.es/google-news.xml
Robots URL: https://www.elfielato.es/robots.txt
Robots URL: https://forbes.es/robots.txt
Se encontraron los siguientes enlaces xml: {'http://www.lacerca.com/system/sitemaps/sitemap.xml'}
Accediendo al siguiente enlace... http://www.lacerca.com/system/sitemaps/sitemap.xml
Robots URL: https://www.teleprensa.com/robots.txt
Robots URL: https://itg.es/robots.txt
Robots URL: https://www.larazon.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.larazon.es/sitemaps/news.xml', 'https://www.larazon.es/sitemaps/content_sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/news.xml
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/content_sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://itg.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://itg.es/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.teleprensa.com/sitemap.news.xml.gz', 'https://www.teleprensa.com/sitemap.xml'}
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.news.xml.gz
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.xml
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-10.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-11.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-12.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-13.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-14.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-15.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-1.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-2.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-3.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-4.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-5.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-6.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-7.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-8.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-9.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-news-es-1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.categories.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.24.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.25.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.26.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.27.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.28.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.29.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.02.30.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.24.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.25.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.26.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.27.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.28.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.29.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.01.30.xml.gz
Se encontraron los siguientes enlaces xml: {'https://forbes.es/wp-sitemap.xml'}
Accediendo al siguiente enlace... https://forbes.es/wp-sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.elfielato.es/sitemap.xml', 'https://www.elfielato.es/sitemap.news.xml.gz'}
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.xml
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.categories.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.03.1.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.02.1.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.01.1.xml.gz
Se encontraron los siguientes enlaces xml: {'https://iymagazine.es/sitemap.xml'}
Accediendo al siguiente enlace... https://iymagazine.es/sitemap.xml
Se encontró archivo comprimido https://iymagazine.es/sitemaps/sitemap_1.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.eldia.es/sitemap_index_f10b6.xml', 'https://www.eldia.es/sitemap_google_news_f10b6.xml'}
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_index_f10b6.xml
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_google_news_f10b6.xml
Se encontraron los siguientes enlaces xml: {'https://www.elperiodico.com/es/sitemap-noticias.xml', 'https://www.elperiodico.com/es/google-news.xml'}
Accediendo al siguiente enlace... https://www.elperiodico.com/es/sitemap-noticias.xml
Accediendo al siguiente enlace... https://www.elperiodico.com/es/google-news.xml
Se encontraron los siguientes enlaces xml: {'https://www.infobae.com/arc/outboundfeeds/news-sitemap2/', 'https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/', 'https://www.infobae.com/arc/outboundfeeds/sitemap2/'}
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/news-sitemap2/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap2/
Robots URL: https://www.noticiasde.es/robots.txt
Robots URL: https://www.larioja.com/robots.txt
Robots URL: https://www.eldiariomontanes.es/robots.txt
Robots URL: https://www.diariodevalderrueda.es/robots.txt
Robots URL: https://www.latribunadealbacete.es/robots.txt
Robots URL: https://www.ondacero.es/robots.txt
Robots URL: https://cronicadeandalucia.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.eldiariomontanes.es/sitemap.incremental.xml', 'https://www.eldiariomontanes.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.incremental.xml
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.diariodevalderrueda.es/sitemap.xml', 'https://www.diariodevalderrueda.es/sitemap/lastarticles'}
Accediendo al siguiente enlace... https://www.diariodevalderrueda.es/sitemap.xml
Accediendo al siguiente enlace... https://www.diariodevalderrueda.es/sitemap/lastarticles
Se encontraron los siguientes enlaces xml: {'https://www.larioja.com/sitemap.incremental.xml', 'https://www.larioja.com/sitemap.xml'}
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.incremental.xml
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.xml
Robots URL: https://www.redaccionmedica.com/robots.txt
Robots URL: https://www.eleconomista.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.latribunadealbacete.es/sitemap.xml', 'https://www.latribunadealbacete.es/sitemap.news.xml'}
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.xml
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.news.xml
Robots URL: https://www.laopinioncoruna.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.noticiasde.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.noticiasde.es/sitemap.xml
Robots URL: https://www.laescena.es/robots.txt
Robots URL: https://www.tribunaavila.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.redaccionmedica.com/sitemap.xml', 'https://www.redaccionmedica.com/sitemaps/sitemap-recursos-salud.xml', 'https://www.redaccionmedica.com/sitemaps/sitemap-news.xml'}
Accediendo al siguiente enlace... https://www.redaccionmedica.com/sitemap.xml

## Filtrar articulos por fecha

In [9]:
import pandas as pd
from datetime import datetime
import numpy as np

# Cargar la data extraída
data_df = pd.read_csv("news_output.csv")

# Convertir a tipo datetime usando UTC para tener un formato estandarizado
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'], format='mixed', errors='coerce', utc=True)
# Convertir a zona horaria de españa
data_df['fecha_publicacion'] = data_df['fecha_publicacion'].dt.tz_convert('Europe/Madrid')
# Eliminar duplicados y ordenar por fecha
data_df = data_df.drop_duplicates().sort_values(by='fecha_publicacion', ascending=False).reset_index(drop=True)
data_df

,fuente,url,titulo,fecha_publicacion
0,Telecinco,https://www.telecinco.es/noticias/sociedad/202...,Hallan a un hombre ahorcado en un parque de Ibiza,2025-03-05 10:42:07.137537+01:00
1,Telecinco,https://www.telecinco.es/noticias/sociedad/202...,Qué hacer ante la alerta por el temporal de ll...,2025-03-05 10:34:24.729401+01:00
2,Bolsamania,https://www.bolsamania.com/noticias/resultados...,"Adidas vuelve al beneficio en 2024, gana 764 m...",2025-03-05 10:23:00+01:00
3,Granada Digital,https://www.granadadigital.es/granada-inicio-c...,NaN,2025-03-05 10:22:37+01:00
4,Granada Digital,https://www.granadadigital.es/seccion/semana-s...,NaN,2025-03-05 10:22:37+01:00
...,...,...,...,...
408346,Ruta Pesquera,https://www.rutapesquera.com/cadiz-acogera-la-...,NaN,NaT
408347,Ruta Pesquera,https://www.rutapesquera.com/gobierno-acordara...,NaN,NaT
408348,Ruta Pesquera,https://www.rutapesquera.com/la-flota-de-arras...,NaN,NaT
408349,Ruta Pesquera,https://www.rutapesquera.com/la-patrulla-norue...,NaN,NaT
408350,Ruta Pesquera,https://www.rutapesquera.com/planas-analizo-co...,NaN,NaT

In [10]:
data_df['fuente'].value_counts()

fuente
Europa Press            74721
Teleprensa              31152
Onda Cero               26648
La Razón                25884
Levante-EMV             19999
                        ...
Vivir Ediciones            10
Asturias Mundial            7
Ruta Pesquera               7
Crónica de Andalucía        6
Gente Digital               4
Name: count, Length: 111, dtype: int64

### Eliminar enlaces duplicados

In [11]:
def remover_url_duplicados(df):
    df['non_null_count'] = df.notnull().sum(axis=1)
    df = df.sort_values(by=['url', 'non_null_count'], ascending=[True, False])
    df = df.drop_duplicates(subset=['url'], keep='first')
    df = df.drop(columns=['non_null_count'])
    df = df.sort_values(by='fecha_publicacion', ascending=False).reset_index(drop=True)
    return df

data_df = remover_url_duplicados(data_df)
data_df

,fuente,url,titulo,fecha_publicacion
0,Telecinco,https://www.telecinco.es/noticias/sociedad/202...,Hallan a un hombre ahorcado en un parque de Ibiza,2025-03-05 10:42:07.137537+01:00
1,Telecinco,https://www.telecinco.es/noticias/sociedad/202...,Qué hacer ante la alerta por el temporal de ll...,2025-03-05 10:34:24.729401+01:00
2,Bolsamania,https://www.bolsamania.com/noticias/resultados...,"Adidas vuelve al beneficio en 2024, gana 764 m...",2025-03-05 10:23:00+01:00
3,Granada Digital,https://www.granadadigital.es/granada-inicio-c...,NaN,2025-03-05 10:22:37+01:00
4,Granada Digital,https://www.granadadigital.es/seccion/semana-s...,NaN,2025-03-05 10:22:37+01:00
...,...,...,...,...
389916,Sport,https://www.sport.es/es/noticias/real-madrid/m...,NaN,NaT
389917,Sport,https://www.sport.es/es/noticias/real-madrid/v...,NaN,NaT
389918,Sport,https://www.sport.es/es/noticias/sucesos/deten...,NaN,NaT
389919,Sport,https://www.sport.es/es/noticias/valencia/hart...,NaN,NaT
389920,Sport,https://www.sport.es/es/noticias/valencia/vale...,NaN,NaT

In [12]:
data_df['fuente'].value_counts()

fuente
Europa Press            69742
Teleprensa              31152
Onda Cero               26067
La Razón                24883
Levante-EMV             19341
                        ...
Vivir Ediciones            10
Asturias Mundial            7
Ruta Pesquera               7
Crónica de Andalucía        6
Gente Digital               4
Name: count, Length: 111, dtype: int64

### Verificar la existencia de url

In [13]:
list_urls = ["https://fernandezrozas.com/2025/03/02/la-ley-union-europea-no-133-febrero-2024/",
             "https://www.lavanguardia.com/local/asturias/20250302/10437957/barbon-enfrenta-preguntas-sobre-financiacion-autonomica-modelo-cuidados-pleno-semana-agenciaslv20250302.html",
             "https://www.lavanguardia.com/local/asturias/20250302/10438022/psoe-reprocha-pp-sectarismo-sumarse-homenajes-rafael-altamira-agenciaslv20250302.html",
             "http://www.gentedigital.es/oviedo/noticia/4014802/barbon-se-enfrenta-a-preguntas-sobre-financiacion-autonomica-y-modelo-de-cuidados-en-el-pleno-de-esta-semana/",
             "https://www.europapress.es/asturias/noticia-barbon-enfrenta-preguntas-financiacion-autonomica-modelo-cuidados-pleno-semana-20250302120008.html",
             "https://ticker-noticiasep.microcontenidos.com/NoticiaRSS.vbhtml?user=TNTY874EPS&cod=20250302120007",
             "http://www.gentedigital.es/oviedo/noticia/4014826/el-psoe-reprocha-al-pp-su-sectarismo-al-no-sumarse-a-los-homenajes-a-rafael-altamira/",
             "https://www.europapress.es/asturias/noticia-psoe-reprocha-pp-sectarismo-no-sumarse-homenajes-rafael-altamira-20250302122445.html",
             "https://isanidad.com/322012/el-diseno-de-iniciativas-de-promocion-de-la-salud-no-es-competencia-exclusiva-de-la-enfermeria-pero-juega-un-papel-destacado-en-atencion-primaria/",
             "https://isanidad.com/322020/la-cirugia-reduce-la-mortalidad-en-mas-de-un-35-en-comparacion-con-la-amputacion-en-personas-con-pie-diabetico/",
             "https://www.vocesdecuenca.com/cuenca/casi-la-mitad-del-alumnado-del-campus-de-cuenca-es-de-fuera-del-29-en-ade-al-83-en-bellas-artes/",
             "https://www.eldiario.es/politica/objetivo-final-pareja-ayuso-pactar-evitar-carcel-no-le-llame-defraudador-confeso_1_12054734.html",
             "https://www.eldiario.es/catalunya/ocho-meses-espera-eutanasia-pleitos-abogados-cristianos-ralentizan-muerte-digna_1_12085857.html",
             "https://www.lne.es/sociedad/2025/03/03/8m-avanza-imparable-asturias-consulta-114865353.html",
             "https://www.lne.es/deportes/deporte-astur/2025/03/03/alzaga-mesa-ganan-ii-duatlon-114866790.html",
             "https://www.lne.es/asturias/2025/03/03/explosion-facultades-medicina-pais-hay-114866449.html",
             "https://www.lne.es/oviedo/2025/03/03/tonada-doctorado-musicologia-sorprendente-carrera-114867985.html",
             "https://www.lne.es/oviedo/2025/03/03/equipo-abrio-paso-argayo-huerna-114868031.html",
             "https://www.vozpopuli.com/ciencia/neuroderechos-que-dice-neurociencia.html",
             "https://www.elcomercio.es/gijon/facultad-enfermeria-gijon-traslado-laboral-decano-20250303062720-nt.html",
             "https://www.elcomercio.es/culturas/fundacion-margarita-salas-lucia-vinuela-20250303071124-nt.html",
             "https://www.diariodelpuerto.com/maritimo/nieves-roqueni-sera-la-nueva-presidenta-del-puerto-de-gijon-JN22856087"
             ]

for url in list_urls:
    informacion = data_df[data_df['url'].str.startswith(url)].values
    if len(informacion) == 0:
        print(f"- Url no encontrada: {url}")
    else:
        print(f"- Url encontrada: {url}")
        print(f'  Fuente: {informacion[0][0]}\n  Titulo: {informacion[0][2]}\n  Fecha de publicación: {informacion[0][3]}')
    print()

- Url no encontrada: https://fernandezrozas.com/2025/03/02/la-ley-union-europea-no-133-febrero-2024/

- Url no encontrada: https://www.lavanguardia.com/local/asturias/20250302/10437957/barbon-enfrenta-preguntas-sobre-financiacion-autonomica-modelo-cuidados-pleno-semana-agenciaslv20250302.html

- Url no encontrada: https://www.lavanguardia.com/local/asturias/20250302/10438022/psoe-reprocha-pp-sectarismo-sumarse-homenajes-rafael-altamira-agenciaslv20250302.html

- Url no encontrada: http://www.gentedigital.es/oviedo/noticia/4014802/barbon-se-enfrenta-a-preguntas-sobre-financiacion-autonomica-y-modelo-de-cuidados-en-el-pleno-de-esta-semana/

- Url encontrada: https://www.europapress.es/asturias/noticia-barbon-enfrenta-preguntas-financiacion-autonomica-modelo-cuidados-pleno-semana-20250302120008.html
  Fuente: Europa Press
  Titulo: Barbón se enfrenta a preguntas sobre financiación autonómica y modelo de cuidados en el pleno de esta semana
  Fecha de publicación: 2025-03-02 12:00:08+01:00

- Url no encontrada: https://ticker-noticiasep.microcontenidos.com/NoticiaRSS.vbhtml?user=TNTY874EPS&cod=20250302120007

- Url no encontrada: http://www.gentedigital.es/oviedo/noticia/4014826/el-psoe-reprocha-al-pp-su-sectarismo-al-no-sumarse-a-los-homenajes-a-rafael-altamira/

- Url encontrada: https://www.europapress.es/asturias/noticia-psoe-reprocha-pp-sectarismo-no-sumarse-homenajes-rafael-altamira-20250302122445.html
  Fuente: Europa Press
  Titulo: El PSOE reprocha al PP su "sectarismo" al no sumarse a los homenajes a Rafael Altamira
  Fecha de publicación: 2025-03-02 12:24:45+01:00

- Url no encontrada: https://isanidad.com/322012/el-diseno-de-iniciativas-de-promocion-de-la-salud-no-es-competencia-exclusiva-de-la-enfermeria-pero-juega-un-papel-destacado-en-atencion-primaria/

- Url no encontrada: https://isanidad.com/322020/la-cirugia-reduce-la-mortalidad-en-mas-de-un-35-en-comparacion-con-la-amputacion-en-personas-con-pie-diabetico/

- Url no encontrada: https://www.vocesdecuenca.com/cuenca/casi-la-mitad-del-alumnado-del-campus-de-cuenca-es-de-fuera-del-29-en-ade-al-83-en-bellas-artes/

- Url encontrada: https://www.eldiario.es/politica/objetivo-final-pareja-ayuso-pactar-evitar-carcel-no-le-llame-defraudador-confeso_1_12054734.html
  Fuente: ElDiario.es
  Titulo: nan
  Fecha de publicación: 2025-03-02 22:25:18+01:00

- Url encontrada: https://www.eldiario.es/catalunya/ocho-meses-espera-eutanasia-pleitos-abogados-cristianos-ralentizan-muerte-digna_1_12085857.html
  Fuente: ElDiario.es
  Titulo: Ocho meses a la espera de la eutanasia: los pleitos de Abogados Cristianos ralentizan la muerte digna
  Fecha de publicación: 2025-03-02 22:25:18+01:00

- Url no encontrada: https://www.lne.es/sociedad/2025/03/03/8m-avanza-imparable-asturias-consulta-114865353.html

- Url no encontrada: https://www.lne.es/deportes/deporte-astur/2025/03/03/alzaga-mesa-ganan-ii-duatlon-114866790.html

- Url no encontrada: https://www.lne.es/asturias/2025/03/03/explosion-facultades-medicina-pais-hay-114866449.html

- Url no encontrada: https://www.lne.es/oviedo/2025/03/03/tonada-doctorado-musicologia-sorprendente-carrera-114867985.html

- Url no encontrada: https://www.lne.es/oviedo/2025/03/03/equipo-abrio-paso-argayo-huerna-114868031.html

- Url no encontrada: https://www.vozpopuli.com/ciencia/neuroderechos-que-dice-neurociencia.html

- Url encontrada: https://www.elcomercio.es/gijon/facultad-enfermeria-gijon-traslado-laboral-decano-20250303062720-nt.html
  Fuente: El Comercio
  Titulo: nan
  Fecha de publicación: 2025-03-03 06:28:16+01:00

- Url encontrada: https://www.elcomercio.es/culturas/fundacion-margarita-salas-lucia-vinuela-20250303071124-nt.html
  Fuente: El Comercio
  Titulo: nan
  Fecha de publicación: 2025-03-03 07:12:24+01:00

- Url no encontrada: https://www.diariodelpuerto.com/maritimo/nieves-roqueni-sera-la-nueva-presidenta-del-puerto-de-gijon-JN22856087

## Acceder al contenido de las noticias

### Extracción con request

In [14]:
import requests
from bs4 import BeautifulSoup
from datetime import datetime

# Lista de user-agents para probar
user_agents = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
    "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/W.X.Y.Z Safari/537.36",
    #'python-requests/2.31.0',
]

def extraer_texto_articulos_request(url):
    try:
        # Primer intento sin user-agent
        response = requests.get(url)

        # Si la respuesta no es exitosa o el contenido está vacío, intente con agentes de usuario
        if response.status_code != 200 or not response.content:
            for user_agent in user_agents:
                headers = {
                    "User-Agent": user_agent,
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
                    "Accept-Language": "en-US,en;q=0.5",
                    "Accept-Encoding": "gzip, deflate",
                    "Connection": "keep-alive",
                }
                response = requests.get(url, headers=headers)

                if response.status_code == 200 and response.content:
                    break

        html_str = response.content
        soup = BeautifulSoup(html_str, 'lxml')

        # Extract title
        title = soup.title.string if soup.title else None
        if not title:
            h1 = soup.find('h1')
            title = h1.text.strip() if h1 else None

        # Extract publication date
        pub_date = None
        time_element = soup.find('time')
        if time_element and 'datetime' in time_element.attrs:
            pub_date = time_element['datetime']
        elif time_element:
            pub_date = time_element.text.strip()
        #else:
        #    time_element = soup.find("div", class_="date")
        #    print(time_element)
        #    print(time_element.text())

        # Remove footer
        footer = soup.find('footer')
        if footer:
            footer.decompose()

        text_content = soup.find_all('p')

        text = ''
        for i in text_content:
            text += i.text.strip() + " "

        return {
            'url': url,
            'titulo': title.strip() if title else None,
            'fecha_publicacion': pub_date,
            'texto': text.strip() if text.strip() else None
        }

    except Exception as e:
        print(f"Error in url: {url}, error: {e}")
        return {'url': url, 'titulo': None, 'fecha_publicacion': None, 'texto': None}

#url_test = 'https://www.elperiodicodecanarias.es/el-juez-peinado-pone-el-foco-en-la-asesora-de-moncloa-que-asiste-a-begona-gomez/'
url_test = 'https://www.europapress.es/asturias/noticia-psoe-reprocha-pp-sectarismo-no-sumarse-homenajes-rafael-altamira-20250302122445.html'
extraer_texto_articulos_request(url_test)

{'url': 'https://www.europapress.es/asturias/noticia-psoe-reprocha-pp-sectarismo-no-sumarse-homenajes-rafael-altamira-20250302122445.html',
 'titulo': 'El PSOE reprocha al PP su "sectarismo" al no sumarse a los homenajes a Rafael Altamira',
 'fecha_publicacion': None,
 'texto': 'Menú Boletines Abonados OVIEDO 2 Mar. (EUROPA PRESS) - El concejal del Grupo Municipal Socialista en el Ayuntamiento de Oviedo Jorge García Monsalve ha lamentado este domingo el rechazo del PP a una proposición del PSOE para que la ciudad se adhiera a las actividades del Año de Rafael Altamira, iniciativa impulsada por la Comunidad Valenciana, el Ayuntamiento de El Campello y la Universidad de Alicante. Rafael Altamira y Crevea (Alicante, 1866 - Ciudad de México, 1951) fue una de las figuras "más destacadas" del Regeneracionismo español y del Grupo de Oviedo, según ha explicado el edil, que ha recriminado al PP su "sectarismo" por rechazar el homenaje. García Monsalve ha explicado que la vinculación de Altamira con la ciudad "fue profunda", ya que formó parte del Claustro de la Universidad de Oviedo desde 1898 hasta 1910, ocupando la cátedra de Historia del Derecho e impulsando la Extensión Universitaria. El pasado 10 de febrero, sus restos fueron trasladados desde México a España y enterrados en El Campello (Alicante), en una ceremonia presidida por Su Majestad el Rey Felipe VI. "Rafael Altamira tuvo una estrecha relación con Oviedo y dejó un legado fundamental en nuestra Universidad", ha recordado el edil. Por ello, desde el PSOE entienden que la ciudad debía sumarse a este homenaje y "aprovecharlo para tejer lazos que ayuden a impulsar la candidatura de Oviedo a Capital Europea de la Cultura en 2031". "Sin embargo, la respuesta del PP ha sido el habitual \'no\' ante cualquier iniciativa del PSOE, lo que demuestra, además de un sectarismo preocupante, dejadez y falta de ambición, casi desidia", ha aseverado.  Qué significa que aparezcan peces de plata en tu casa La Inteligencia ucraniana advierte de que Rusia prepara ataques con hasta 500 drones para próximos meses Detenido un vendedor ambulante en Chiclana (Cádiz) por importar monedas de dos euros falsas procedentes de China China suspende la importación de troncos desde EE.UU. y las compras de soja a tres empresas estadounidenses La empresaria que asegura que entregó 90.000 euros en Ferraz, en su declaración en el TS: "Me estaban esperando"'}

In [15]:
from concurrent.futures import ThreadPoolExecutor
import time

num_threads = 4

start_time = time.time()
with ThreadPoolExecutor(max_workers=num_threads) as executor:
    results = list(executor.map(extraer_texto_articulos_request, data_df['url']))

print(f"--- {(time.time() - start_time):.2f}s seconds ---")

C:\Users\rebec\AppData\Local\Temp\ipykernel_872\484414440.py:35: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  soup = BeautifulSoup(html_str, 'lxml')

Error in url: https://elportaluco.com/canto-de-las-marzas-en-el-parlamento-de-cantabria/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/la-consejera-de-inclusion-social-mantuvo-una-reunion-en-la-oficina-de-inclusion-social-del-pueblo-gitano/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/flick-el-benfica-es-uno-de-los-mejores-equipos-en-transicion/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/los-solistas-del-real-madrid-frustran-a-la-orquesta-rojiblanca/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/asi-hemos-narrado-la-victoria-del-real-madrid-ante-el-atletico/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/el-arsenal-se-pasea-el-aston-villa-avista-los-cuartos-y-el-lille-contiene-al-dortmund/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/edeon-mas-de-una-decada-potenciando-la-comunicacion-empresarial/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/atos-y-esri-se-alian-para-impulsar-gemelos-digitales-con-ia-y-mejorar-el-conocimiento-territorial/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/worldline-participara-en-el-evento-talentarena-con-una-conferencia-y-una-mesa-redonda-sobre-inclusion/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://www.europapress.es/videos/video-papa-mantiene-estable-reanudara-noche-ventilacion-mecanica-no-invasiva-20250304205108.html, error: ('Connection aborted.', ConnectionResetError(10054, 'Se ha forzado la interrupción de una conexión existente por el host remoto', None, 10054, None))
Error in url: https://galiciadigital24horas.com/edeon-mas-de-una-decada-potenciando-la-comunicacion-empresarial/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/atos-y-esri-se-alian-para-impulsar-gemelos-digitales-con-ia-y-mejorar-el-conocimiento-territorial/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/worldline-participara-en-el-evento-talentarena-con-una-conferencia-y-una-mesa-redonda-sobre-inclusion/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/graid-technology-obtiene-30-millones-de-dolares-serie-b-para-el-crecimiento-de-almacenamiento-de-datos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/el-numero-de-mujeres-migrantes-en-edad-de-trabajar-crece-un-41-en-la-ultima-decada-mientras-que-las-espanolas-caen-un-1-segun-un-informe-de-la-fundacion-adecco/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/cambios-en-las-tendencias-de-viaje-mayor-competencia-y-combatir-las-ineficiencias-claves-del-boom-tecnologico-en-la-gestion-de-ingresos-hoteleros-segun-siteminder/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/edeon-mas-de-una-decada-potenciando-la-comunicacion-empresarial/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/atos-y-esri-se-alian-para-impulsar-gemelos-digitales-con-ia-y-mejorar-el-conocimiento-territorial/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/graid-technology-obtiene-30-millones-de-dolares-serie-b-para-el-crecimiento-de-almacenamiento-de-datos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/worldline-participara-en-el-evento-talentarena-con-una-conferencia-y-una-mesa-redonda-sobre-inclusion/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/el-barca-vuelve-a-da-luz-con-la-leccion-aprendida/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/graid-technology-obtiene-30-millones-de-dolares-serie-b-para-el-crecimiento-de-almacenamiento-de-datos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/el-numero-de-mujeres-migrantes-en-edad-de-trabajar-crece-un-41-en-la-ultima-decada-mientras-que-las-espanolas-caen-un-1-segun-un-informe-de-la-fundacion-adecco/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/cambios-en-las-tendencias-de-viaje-mayor-competencia-y-combatir-las-ineficiencias-claves-del-boom-tecnologico-en-la-gestion-de-ingresos-hoteleros-segun-siteminder/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/el-numero-de-mujeres-migrantes-en-edad-de-trabajar-crece-un-41-en-la-ultima-decada-mientras-que-las-espanolas-caen-un-1-segun-un-informe-de-la-fundacion-adecco/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/cambios-en-las-tendencias-de-viaje-mayor-competencia-y-combatir-las-ineficiencias-claves-del-boom-tecnologico-en-la-gestion-de-ingresos-hoteleros-segun-siteminder/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/loar-holdings-inc-anuncia-el-ascenso-de-tc-queener-a-vicepresidente-ejecutivo/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/la-otra-cara-de-los-eventos-tecnologicos-contaminacion-agotamiento-de-recursos-y-conflictos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/un-legado-inmortal-la-biografia-del-dr-juan-jose-fernandez-cobra-vida-en-el-perico-fernandez/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/los-pacientes-oncologicos-no-reciben-informacion-suficiente-ni-resuelven-sus-dudas-en-consulta-advierte-fundacion-alivia/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/la-otra-cara-de-los-eventos-tecnologicos-contaminacion-agotamiento-de-recursos-y-conflictos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/loar-holdings-inc-anuncia-el-ascenso-de-tc-queener-a-vicepresidente-ejecutivo/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/un-legado-inmortal-la-biografia-del-dr-juan-jose-fernandez-cobra-vida-en-el-perico-fernandez/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/los-pacientes-oncologicos-no-reciben-informacion-suficiente-ni-resuelven-sus-dudas-en-consulta-advierte-fundacion-alivia/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/loar-holdings-inc-anuncia-el-ascenso-de-tc-queener-a-vicepresidente-ejecutivo/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/la-otra-cara-de-los-eventos-tecnologicos-contaminacion-agotamiento-de-recursos-y-conflictos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/un-legado-inmortal-la-biografia-del-dr-juan-jose-fernandez-cobra-vida-en-el-perico-fernandez/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/final-anticipada-en-el-parque-de-los-principes-y-duelo-fratricida-en-munich/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/los-pacientes-oncologicos-no-reciben-informacion-suficiente-ni-resuelven-sus-dudas-en-consulta-advierte-fundacion-alivia/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/marco-flores-premio-nacional-de-baile-flamenco-y-premio-max-2020-lleva-al-festival-de-jerez-tierra-virgen-un-espectaculo-que-reinterpreta-lo-clasico-y-lo-sacro/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/miguel-zaragoza-fuentes-liderando-el-cambio-hacia-un-futuro-energetico-mas-sostenible/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/clean-air-metals-intercepta-410-m-con-una-graduacion-de-132-g-t-pt-eq-en-el-proyecto-current/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/marco-flores-premio-nacional-de-baile-flamenco-y-premio-max-2020-lleva-al-festival-de-jerez-tierra-virgen-un-espectaculo-que-reinterpreta-lo-clasico-y-lo-sacro/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/miguel-zaragoza-fuentes-liderando-el-cambio-hacia-un-futuro-energetico-mas-sostenible/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/clean-air-metals-intercepta-410-m-con-una-graduacion-de-132-g-t-pt-eq-en-el-proyecto-current/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/marco-flores-premio-nacional-de-baile-flamenco-y-premio-max-2020-lleva-al-festival-de-jerez-tierra-virgen-un-espectaculo-que-reinterpreta-lo-clasico-y-lo-sacro/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/miguel-zaragoza-fuentes-liderando-el-cambio-hacia-un-futuro-energetico-mas-sostenible/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/clean-air-metals-intercepta-410-m-con-una-graduacion-de-132-g-t-pt-eq-en-el-proyecto-current/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/la-rollerie-presenta-su-menu-diario-para-la-temporada-de-primavera-2025/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/la-empresa-autocines-se-posiciona-como-uno-de-los-espacios-referentes-en-la-capital-aumentando-su-facturacion-en-mas-de-un-15-en-2024/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/destinux-se-convierte-en-el-primer-saas-del-sector-business-travel-en-obtener-la-certificacion-iso-27001/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/reinaldo-ramos-dagostino-y-grupo-capital-presentan-una-estrategia-para-fortalecer-empresas-cotizadas/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/la-torrelagunera-francisca-lozano-de-94-anos-premio-a-los-valores-cooperativos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/pruebas-gratuitas-de-densitometria-para-la-prevencion-de-la-osteoporosis-con-comitas-ehealth/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/boulton-pumps-innovacion-y-adaptabilidad-en-el-mercado-de-bombas-hidraulicas/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/krack-el-gigante-del-calzado-espanol-acelera-su-expansion-nacional-con-tormo-franquicias-consulting/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/las-mejores-paradas-de-la-jornada-29-en-segunda/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/los-mejores-goles-de-la-jornada-29-en-segunda/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/la-rollerie-presenta-su-menu-diario-para-la-temporada-de-primavera-2025/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/la-empresa-autocines-se-posiciona-como-uno-de-los-espacios-referentes-en-la-capital-aumentando-su-facturacion-en-mas-de-un-15-en-2024/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/reinaldo-ramos-dagostino-y-grupo-capital-presentan-una-estrategia-para-fortalecer-empresas-cotizadas/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/la-torrelagunera-francisca-lozano-de-94-anos-premio-a-los-valores-cooperativos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/destinux-se-convierte-en-el-primer-saas-del-sector-business-travel-en-obtener-la-certificacion-iso-27001/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/pruebas-gratuitas-de-densitometria-para-la-prevencion-de-la-osteoporosis-con-comitas-ehealth/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/krack-el-gigante-del-calzado-espanol-acelera-su-expansion-nacional-con-tormo-franquicias-consulting/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://valencia24horas.com/boulton-pumps-innovacion-y-adaptabilidad-en-el-mercado-de-bombas-hidraulicas/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/la-rollerie-presenta-su-menu-diario-para-la-temporada-de-primavera-2025/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/la-empresa-autocines-se-posiciona-como-uno-de-los-espacios-referentes-en-la-capital-aumentando-su-facturacion-en-mas-de-un-15-en-2024/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/destinux-se-convierte-en-el-primer-saas-del-sector-business-travel-en-obtener-la-certificacion-iso-27001/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/reinaldo-ramos-dagostino-y-grupo-capital-presentan-una-estrategia-para-fortalecer-empresas-cotizadas/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/la-torrelagunera-francisca-lozano-de-94-anos-premio-a-los-valores-cooperativos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/pruebas-gratuitas-de-densitometria-para-la-prevencion-de-la-osteoporosis-con-comitas-ehealth/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/krack-el-gigante-del-calzado-espanol-acelera-su-expansion-nacional-con-tormo-franquicias-consulting/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/boulton-pumps-innovacion-y-adaptabilidad-en-el-mercado-de-bombas-hidraulicas/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/mosaic-factor-transforma-la-industria-con-soluciones-ia-y-big-data/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/aurea-clinic-lanza-un-nuevo-metodo-de-medicina-regenerativa-capilar/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/eim-consultores-lidera-la-formacion-de-docentes-para-la-era-digital/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/empresas-tokenizadas-en-espana-el-desafio-de-ser-el-primero-en-la-historia/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/polaris-renewable-energy-anuncia-el-cierre-de-una-adquisicion-en-puerto-rico/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/alianzas-360o-el-nuevo-canal-de-partners-de-grupo-castilla/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://galiciadigital24horas.com/el-trabajo-de-buscar-trabajo-y-sus-claves-para-optimizar-esfuerzos/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/mosaic-factor-transforma-la-industria-con-soluciones-ia-y-big-data/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error in url: https://elportaluco.com/aurea-clinic-lanza-un-nuevo-metodo-de-medicina-regenerativa-capilar/, error: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

KeyboardInterrupt:

In [ ]:
data_results = pd.DataFrame(results)
data_results

,url,titulo,fecha_publicacion,texto
0,https://www.elespanol.com/valencia/20250303/ca...,Derrota del aparato de Sánchez en Valencia: Bi...,2025-03-03T01:12:39+01:00,El secretario general del PSPV-PSOE en la prov...
1,https://www.infobae.com/entretenimiento/2025/0...,Conan O’Brien a Karla Sofía Gascón en los prem...,None,"2 Mar, 2025 Por Antonela Rabanal Luego del ac..."
2,https://www.menorca.info/balears.html,Balears,None,Cargando... Cargando... Cargando... Cargando.....
3,https://www.menorca.info/aviso_legal.html,Aviso legal en Menorca - Es diari,None,Cargando... Cargando... Cargando... Cargando.....
4,https://www.infobae.com/colombia/2025/03/03/su...,Superintendencia de Salud pide investigar pres...,None,"2 Mar, 2025 Por Katherine Lancheros La Superi..."
...,...,...,...,...
27054,https://www.xataka.com/perifericos/fin-base-ca...,Por fin una base de carga de auriculares que n...,2025-03-02T17:56:20Z,Enrique Pérez Soñando con ovejas eléctricas. E...
27055,https://www.xataka.com/tablets/honor-pad-v9-ca...,"Nueva Honor Pad V9, características, precio y ...",2025-03-02T17:03:56Z,"Juan Carlos López Aunque acaba de empezar, est..."
27056,https://www.xataka.com/tablets/xiaomi-pad-7-pa...,"Nuevas Xiaomi Pad 7 y Pad 7 Pro, característic...",2025-03-02T14:33:00Z,Juan Carlos López Xiaomi ha sacado la artiller...
27057,https://www.xataka.com/transporte/presidentes-...,"Xi Jinping también tiene su particular ""Air Fo...",2025-03-02T20:01:56Z,Javier Marquez Cada vez que el presidente de C...
27058,https://www.xataka.com/transporte/startup-quie...,"Una startup quiere construir el ""Tesla de los ...",2025-03-02T17:01:56Z,Alejandro Alcolea La electrificación del trans...

### Combinar resultados de request con la data extraída

Los resultados de request incluyen títulos y fechas que posiblemente no hayan sido extraidas inicialmente por ello se combina esa información para reducir la cantidad de data faltante

In [ ]:
# Combinar dataframes
merged_df = pd.merge(data_df, data_results, on='url', how='outer', suffixes=('_df1', '_df2'))

# Crear nuevas columnas para el título y la fecha, priorizando los valores no nulos
merged_df['titulo'] = merged_df['titulo_df1'].fillna(merged_df['titulo_df2'])
merged_df['fecha_publicacion'] = merged_df['fecha_publicacion_df1'].fillna(merged_df['fecha_publicacion_df2'])

# Eliminar las columnas de título y fecha originales
merged_df = merged_df.drop(columns=['titulo_df1', 'titulo_df2', 'fecha_publicacion_df1', 'fecha_publicacion_df2'])

In [ ]:
merged_df

,fuente,url,texto,titulo,fecha_publicacion
0,Gente Digital,http://gentedigital.es/actualidad/noticia/3992...,La Comunidad de Madrid ha celebrado hoy en la ...,La Comunidad de Madrid reconoce las mejores pr...,None
1,Gente Digital,http://gentedigital.es/avila/noticia/3956625/l...,"La Cámara de Comercio, Industria y Servicios d...",Las cámaras de Ávila y Madrid llegan a un acue...,None
2,Gente Digital,http://gentedigital.es/comunidad/diver-gente/2...,Bizum se ha convertido rápidamente en uno de l...,Bizum como método seguro en Casinos Online: Un...,None
3,Gente Digital,http://gentedigital.es/comunidad/diver-gente/2...,No hace falta ir a un periódico nacional para ...,La información diversa y actual » Diver-gente,None
4,Gente Digital,http://gentedigital.es/portada/noticia/3925090...,El Hospital HLA Moncloa explica una técnica co...,Ondas de choque focales como tratamiento no in...,None
...,...,...,...,...,...
27054,Bilbao 24 Horas,https://www.xataka.com/perifericos/fin-base-ca...,Enrique Pérez Soñando con ovejas eléctricas. E...,Por fin una base de carga de auriculares que n...,2025-03-02T17:56:20Z
27055,Bilbao 24 Horas,https://www.xataka.com/tablets/honor-pad-v9-ca...,"Juan Carlos López Aunque acaba de empezar, est...","Nueva Honor Pad V9, características, precio y ...",2025-03-02T17:03:56Z
27056,Bilbao 24 Horas,https://www.xataka.com/tablets/xiaomi-pad-7-pa...,Juan Carlos López Xiaomi ha sacado la artiller...,"Nuevas Xiaomi Pad 7 y Pad 7 Pro, característic...",2025-03-02T14:33:00Z
27057,Bilbao 24 Horas,https://www.xataka.com/transporte/presidentes-...,Javier Marquez Cada vez que el presidente de C...,"Xi Jinping también tiene su particular ""Air Fo...",2025-03-02T20:01:56Z
27058,Bilbao 24 Horas,https://www.xataka.com/transporte/startup-quie...,Alejandro Alcolea La electrificación del trans...,"Una startup quiere construir el ""Tesla de los ...",2025-03-02T17:01:56Z

Filtrar la nueva data por fecha

In [ ]:
# Fecha inicial
fecha_inicial = "2025-3-1"

merged_df['fecha_publicacion'] = pd.to_datetime(merged_df['fecha_publicacion'], format='mixed', errors='coerce', utc=True)
merged_df['fecha_publicacion'] = pd.to_datetime(merged_df['fecha_publicacion'].dt.strftime("%Y-%m-%d"))
merged_df = merged_df[(merged_df['fecha_publicacion'].between(fecha_inicial, datetime.now().strftime('%Y-%m-%d'))) | (pd.isna(merged_df['fecha_publicacion']))]
merged_df = merged_df.sort_values(by='fecha_publicacion', ascending=False).drop_duplicates().reset_index(drop=True)
merged_df

,fuente,url,texto,titulo,fecha_publicacion
0,Infobae,https://www.infobae.com/america/agencias/2024/...,"2 Mar, 2025 Por Newsroom Infobae Los Ángeles...",Acusan a 17 de robar vehículos en Denver y lue...,2025-03-03
1,El Español,https://www.elespanol.com/elandroidelibre/tuto...,Móvil Android\n ...,Adiós a usar una sola app a la vez: la sencill...,2025-03-03
2,MENORCA,https://www.menorca.info/hemeroteca.html,Cargando... Cargando... Cargando... Cargando.....,Hemeroteca,2025-03-03
3,La Provincia,https://www.laprovincia.es/ud-las-palmas/2025/...,"Diego Martínez, el pasado octubre, en su prese...",Los diez pecados dialécticos (y futbolísticos)...,2025-03-03
4,La Provincia,https://www.laprovincia.es/ud-las-palmas/2025/...,"La caída del 10 Moleiro encara a Anuar, del Re...","UD LAS PALMAS: Moleiro, inédito desde el desco...",2025-03-03
...,...,...,...,...,...
25954,Federación Española de Baloncesto,https://www.seleccionbaloncesto.es/2025/2/23/b...,None,59-52 España supera a Bélgica a base de garra ...,NaT
25955,Federación Española de Baloncesto,https://www.seleccionbaloncesto.es/2025/2/26/b...,None,Unas Ventanas con 7 debutantes oficiales más |...,NaT
25956,Nova Ciencia,https://www.ubu.es/grados-ordenados-por-ramas-...,Jump to navigation Ir al listado de grados or...,Grados ordenados por ramas de conocimiento | U...,NaT
25957,Nova Ciencia,https://www.unileon.es/noticias/sara-garcia-vu...,"León, 18 de febrero de 2024. La investigadora ...",Sara García vuelve a la ‘órbita’ de la Univers...,NaT
25958,ABC,https://www.welife.es/mente/como-aceptar-reali...,Suscríbete a la Newsletter NO TE PIERDAS\n\n\t...,Arugamama: cómo aceptar la realidad para poder...,NaT

In [ ]:
merged_df['fuente'].value_counts()

fuente
La Vanguardia                              2402
La Voz de Galicia                          1636
Gente Digital                              1576
Europa Press                               1162
NoticiasDe                                 1000
                                           ...
ORT Noticias del Occidente de Asturias        3
Periódico digital de Castilla-La Mancha       3
Crónica de Andalucía                          3
GCiencia                                      2
Bolsamania                                    1
Name: count, Length: 103, dtype: int64

In [ ]:
merged_df['fecha_publicacion'].isna().sum()

5934

In [ ]:
merged_df['texto'].isna().sum()

2473

In [ ]:
(merged_df['texto'] == '').sum()

0

In [ ]:
merged_df['texto'].iloc[-2]

"León, 18 de febrero de 2024. La investigadora biomédica leonesa Sara García regresa a la Universidad de León para protagonizar un “fascinante encuentro” en el que compartirá su trayectoria científica y espacial que la han convertido en un referente nacional y la inspiración de las niñas del presente y el futuro. Una visita que, según destaca la rectora de la Universidad, Nuria González, brinda la oportunidad de escuchar de primera mano la experiencia de una “mujer, pionera en la Ciencia y el Espacio, cuyo ejemplo inspira a las nuevas generaciones a soñar en grande y a perseguir con determinación sus metas”. “Sara es, sin duda, un recordatorio del talento y la excelencia que emergen de las aulas de la Universidad de León. Contar con una egresada de su nivel es un motivo de orgullo y este encuentro es una gran oportunidad para todos. Su ejemplo es inspirador y nos demuestra que no hay que poner límites a los sueños”, señala la rectora de la ULE. Licenciada en Biotecnológica por la Universidad de León, Sara ha trazado una singular órbita en la que los desafíos de la investigación sobre el cáncer se han entrelazado con la fascinación por los misterios del Universo tras su nombramiento como miembro de la reserva de astronautas de la Agencia Espacial Europea -ESA-. Un “inspirador viaje” a través de la ciencia y el espacio, según ha destacado la rectora, que tendrá lugar el próximo viernes 28 de febrero en el salón de actos de la Escuela de Ingenierías Industrial, Informática y Aeroespacial a partir de las 12:30 horas. ENCUENTRO CON SUS MENTORAS La decana de la Facultad de Ciencias Biológicas y Ambientales, Laura López, y la profesora e investigadora Margarita Marqués acompañarán a Sara durante el encuentro-charla en la que abordará cuestiones como el futuro de las carreras STEM y la brecha de género que aún persiste, los retos actuales en el ámbito de la Biotecnológica o cómo se pueden fusionar dos profesiones a priori tan dispares como el de investigadora y astronauta. Reflexiones, todas ellas, que la leonesa ha volcado en ‘Órbitas. Apuntes de una vida en continua exploración', un libro en el que combina autobiografía, ensayo y ficción para invitar al lector a recorrer el camino hacia la consecución de un sueño que la primera astronauta mujer española de la ESA ha perseguido desde niña. Al término del encuentro, Sara García realizará una firma de su libro, que estará disponible para su compra en el hall de la Escuela de Ingenierías. Asimismo, los asistentes podrán formular preguntas a la investigadora al término de su intervención. La conferencia, que estará abierta a toda la comunidad universitaria y al conjunto de la sociedad leonesa hasta completar aforo, se retrasmitirá en directo a través del canal de Youtube de la Universidad de León. Previamente, y acompañada por la rectora y miembros del cuerpo docente de Ciencias Biológicas, Sara recorrerá algunas estancias de la que fue su facultad y el laboratorio que lleva su nombre, donde realizará un encuentro con los medios de comunicación. Sara García se licenció en\xa0Biotecnología\xa0en 2012 y terminó un\xa0Máster en Investigación Biomédica y Biológica\xa0en 2013, ambos por la Universidad de León (España), siendo galardonada con dos premios diferentes por su excelencia académica. Posteriormente, se doctoró en Biología Molecular del cáncer e Investigación Traslacional por la Universidad de Salamanca (España) y ha dedicado su carrera a la investigación en el Centro Nacional de Investigaciones Oncológicas (CNIO), donde ha contribuido significativamente al avance del conocimiento en su campo."

In [ ]:
merged_df.iloc[-3].values

array(['Nova Ciencia',
       'https://www.ubu.es/grados-ordenados-por-ramas-de-conocimiento',
       'Jump to navigation  Ir al listado de grados ordenados por centro',
       'Grados ordenados por ramas de conocimiento | Universidad de Burgos',
       NaT], dtype=object)

## Filtrar textos

### Buscar textos que tengan al menos una palabra clave

In [ ]:
# Filtrar por palabras clave
keywords = ['universidad', 'oviedo']

# Regex pattern
pattern = '|'.join(keywords)

# Filtrar dataframe
filtered_df = merged_df[merged_df['texto'].str.contains(pattern, case=False, na=False)].reset_index(drop=True)

filtered_df

,fuente,url,texto,titulo,fecha_publicacion
0,MENORCA,https://www.menorca.info/balears.html,Cargando... Cargando... Cargando... Cargando.....,Balears,2025-03-03
1,20 Minutos,https://www.20minutos.es/cinemania/noticias/ar...,Hollywood vuelve a vestirse de gala para los O...,Ariana Grande y Cynthia Erivo desafían la grav...,2025-03-03
2,20 Minutos,https://www.20minutos.es/cinemania/noticias/ha...,Halle Berry ha dado una sorpresa a Adrien Brod...,Halle Berry besa por sorpresa a Adrien Brody e...,2025-03-03
3,Bilbao 24 Horas,https://www.elcorreo.com/bizkaia/cajas-nido-ra...,MiCORREO Mis noticias Mis intereses Newsletter...,Cajas nido para rapaces contra las plagas en B...,2025-03-03
4,20 Minutos,https://www.20minutos.es/cinemania/noticias/pr...,Los Premios Oscar 2025 se entregan esta madrug...,Premios Oscar 2025: Todos los ganadores de la ...,2025-03-03
...,...,...,...,...,...
3189,RRHH Digital,https://www.rrhhdigital.com/secciones/quien-es...,Gemma Baz se ha incorporado al comité de direc...,"Gemma Baz, nueva directora de Recursos Humanos...",NaT
3190,Ruta Pesquera,https://www.rutapesquera.com/murcia-avanza-en-...,27 de febrero de 2025 La Comunidad Autónoma a...,Murcia avanza en la constitución del Consejo d...,NaT
3191,Ruta Pesquera,https://www.rutapesquera.com/xunta-destina-mas...,"26 de febrero de 2025 El consejero del Mar, A...",Xunta destina más de 200.000 euros con USC par...,NaT
3192,Santander Digital 24 Horas,https://www.santander.es/noticia/ayuntamiento-...,Zulema Gancedo se reúne con representantes de ...,El Ayuntamiento mejorará la atención de las pe...,NaT
3193,Nova Ciencia,https://www.unileon.es/noticias/sara-garcia-vu...,"León, 18 de febrero de 2024. La investigadora ...",Sara García vuelve a la ‘órbita’ de la Univers...,NaT

In [ ]:
filtered_df['url'].values[0:100]

array(['https://www.menorca.info/balears.html',
       'https://www.20minutos.es/cinemania/noticias/ariana-grande-cynthia-erivo-wicked-actuacion-musical-premios-oscar-5687324/',
       'https://www.20minutos.es/cinemania/noticias/halle-berry-beso-adrien-brody-oscar-2025-venganza-actriz-5687329/',
       'https://www.elcorreo.com/bizkaia/cajas-nido-rapaces-plagas-bilbao-20250303010833-nt.html',
       'https://www.20minutos.es/cinemania/noticias/premios-oscars-2025-directo-ganadores-gala-nominados-invitados-alfombra-roja-5687300/',
       'https://www.eldebate.com/obituarios/20250303/tote-ruperez-enamorado-palabra_274846.html',
       'https://www.elespanol.com/enclave-ods/historias/20250303/arroz-elite-nueva-variedad-alto-rendimiento-emite-metano-cultivo/926907576_0.html',
       'https://www.elespanol.com/valencia/20250303/carlos-fernandez-bielsa-gana-primarias-socialistas-provincia-valencia-solo-votos-frente-robert-raga/928407153_0.html',
       'https://www.nortes.me/2025/03/03/los-mazcaritos-celebran-el-domingo-gordu-de-antroxu/',
       'https://www.eldiario.es/blog/al-dia/podcast-trump-musk-saludo-nazi_132_12090902.html',
       'https://www.infobae.com/peru/deportes/2025/03/01/tabla-de-posiciones-liga-peruana-de-voley-2025-en-vivo-fecha-2-fase-2-universitario-alianza-lima-regatas-lima-san-martin-resultados/',
       'https://www.infobae.com/peru/deportes/2025/03/02/rodrigo-urena-amenazo-a-williams-riveros-en-pleno-partido-universitario-vs-alianza-universidad-en-el-vestuario-te-veo/',
       'https://www.infobae.com/peru/deportes/2025/03/03/autogol-christian-ramos-jugada-diego-churin-universitario-vs-alianza-universidad-liga-1-2025-video-hoy/',
       'https://www.infobae.com/peru/deportes/2025/03/02/universitario-vs-alianza-universidad-en-vivo-hoy-golperu-fecha-4-torneo-apertura-liga-1-2025-alineaciones-goles-resumen-resultado/',
       'https://www.infobae.com/peru/2025/03/03/alcanzo-vacante-emocion-y-lagrimas-en-las-reacciones-de-los-cachimbos-al-conocer-los-resultados-de-admision-san-marcos-2025-ii/',
       'https://www.infobae.com/peru/2025/03/02/joven-venezolana-celebra-su-ingreso-en-primer-puesto-a-san-marcos-pero-su-logro-genera-polemica-en-redes-sociales/',
       'https://www.infobae.com/colombia/2025/03/03/xavier-vendrell-recibio-un-honoris-causa-en-el-congreso-que-habria-generado-sospechas-periodista-revelo-detalles/',
       'https://www.larazon.es/espana/20n-sanchez-vacio-comisionada-que-gana-74000-euros_2025030367c4d265829a09000195fc5b.html',
       'https://www.laopinioncoruna.es/tendencias21/2025/03/02/polvo-sahara-alimenta-vida-oceanica-108802805.html',
       'https://www.laopiniondemalaga.es/andalucia/2025/03/02/andalucia-35-millones-financiacion-114848222.html',
       'https://www.laopinioncoruna.es/sociedad/2025/03/02/roman-rodriguez-cientificos-venan-galicia-114832199.html',
       'https://www.laopiniondemalaga.es/andalucia/2025/03/02/aspirantes-plazas-junta-andalucia-114849420.html',
       'https://www.laopinioncoruna.es/videos/deportes/2025/03/02/resumen-goles-highlights-real-oviedo-114863393.html',
       'https://www.laopiniondemalaga.es/tendencias21/2025/03/02/polvo-sahara-alimenta-vida-oceanica-108802816.html',
       'https://www.laopiniondemalaga.es/medio-ambiente/2025/03/02/explosion-demografica-jabalies-provoca-adentren-114351493.html',
       'https://www.laopiniondemalaga.es/medio-ambiente/2025/03/02/megainundacion-mediterraneo-desertico-relleno-agua-113693785.html',
       'https://www.laopiniondemalaga.es/malaga/2025/03/02/familias-jovenes-mayores-55-son-114824074.html',
       'https://www.laopiniondemalaga.es/malagacf/2025/03/02/malaga-cf-aumenta-distancia-descenso-eldense-114862755.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/real-oviedo-rival-depor-reto-114836514.html',
       'https://www.informacion.es/tendencias21/2025/03/02/polvo-sahara-alimenta-vida-oceanica-108802803.html',
       'https://www.informacion.es/politica/2025/03/02/mentira-arma-politica-atentados-11-114808411.html',
       'https://www.informacion.es/sociedad/2025/03/02/mujeres-lideran-desarrollo-tecnologias-futuro-114846093.html',
       'https://www.lacomarcadepuertollano.com/articulo/region/junta-renueva-convenio-academia-creteil-francia-cooperacion-desarrollo-actividades-educativas/20250302110652582344.html',
       'https://www.lacomarcadepuertollano.com/articulo/region/servicio-cirugia-maxilofacial-hospital-albacete-organiza-curso-teorico-practico-alto-nivel/20250301105533582286.html',
       'https://www.lacomarcadepuertollano.com/articulo/cultura/premio-internacional-literatura-gustavo-adolfo-becquer-2025-escritor-editor-colombiano-carlos-orlando-pardo-rodriguez/20250301154231582317.html',
       'https://www.informacion.es/elche-cf/2025/03/03/fernandez-mercau-recae-lesion-recto-114867469.html',
       'https://www.informacion.es/elche/2025/03/02/agricultor-asaja-mercadillos-camp-delx-agricultura-114725338.html',
       'https://www.informacion.es/elda/2025/03/02/replantear-turismo-masas-consume-recursos-114694808.html',
       'https://www.informacion.es/opinion/2025/03/02/ampliacion-puerto-valencia-114804781.html',
       'https://www.informacion.es/medio-ambiente/2025/03/02/megainundacion-mediterraneo-desertico-relleno-agua-113693802.html',
       'https://www.informacion.es/medio-ambiente/2025/03/02/explosion-demografica-jabalies-provoca-adentren-114351517.html',
       'https://www.informacion.es/internacional/2025/03/02/ia-llega-corea-norte-114844282.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/1-2-depor-asalta-tartiere-114859946.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/2-000-deportivistas-oviedo-114866199.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/cae-eldense-descuento-deportivo-aleja-114865076.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/deportivo-busca-victoria-alejar-viejos-114834696.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/gilsanz-cansamos-adjetivar-gente-victoria-114860906.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/horario-ver-tv-oviedo-deportivo-114846723.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/jose-angel-amplia-club-corunes-114865755.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/mario-soriano-dimos-golpe-mesa-114862424.html',
       'https://www.laopinioncoruna.es/deportivo/2025/03/02/resisten-apercibidos-deportivo-suma-soriano-114865862.html',
       'https://www.laopinioncoruna.es/medio-ambiente/2025/03/02/explosion-demografica-jabalies-provoca-adentren-114351486.html',
       'https://www.laopinioncoruna.es/medio-ambiente/2025/03/02/megainundacion-mediterraneo-desertico-relleno-agua-113693782.html',
       'https://www.lanzadigital.com/castilla-la-mancha/renuevan-el-convenio-con-la-academia-de-creteil-francia-para-las-actividades-educativas/',
       'https://www.laopinioncoruna.es/coruna/2025/03/02/sueldos-coruneses-suben-10-2022-114833243.html',
       'https://www.lanzadigital.com/provincia/campo-de-criptana/la-plataforma-stop-biometano-criptana-pide-al-alcalde-que-blinde-el-termino-contra-estas-plantas/',
       'https://www.laopinioncoruna.es/coruna/2025/03/02/fuese-bng-tuviese-doce-ediles-114833555.html',
       'https://www.lanzadigital.com/sociedad/casi-la-mitad-de-las-mujeres-nunca-ha-ascendido-en-su-trabajo-segun-un-estudio/',
       'https://www.lanzadigital.com/sociedad/intentar-ser-feliz-hace-ser-mas-infelices-al-anular-el-autocontrol-segun-un-nuevo-estudio/',
       'https://www.laopiniondemurcia.es/cultura/2025/03/02/ma-encarna-illan-viaje-semilla-114831907.html',
       'https://www.laprovincia.es/videos/deportes/2025/03/02/resumen-goles-highlights-real-oviedo-114863396.html',
       'https://www.laprovincia.es/ud-las-palmas/2025/03/02/bucle-panico-ud-palmas-379-114861716.html',
       'https://www.larazon.es/castilla-la-mancha/paraiso-torreznos-asi-llaman-restaurante-carretera-media-hora-madrid/20250302/1168941.html',
       'https://www.larazon.es/andalucia/guadalquivir-cloaca-mineria_2025030267c3e620cbf1400001b72eeb.html',
       'https://www.larazon.es/andalucia/inseguridad-lastra-vida-entrenucleos-barrio-que-mas-crece-sevilla_2025030267c3e61acbf1400001b72ed1.html',
       'https://www.laprovincia.es/medio-ambiente/2025/03/02/explosion-demografica-jabalies-provoca-adentren-114351510.html',
       'https://www.laprovincia.es/medio-ambiente/2025/03/02/megainundacion-mediterraneo-desertico-relleno-agua-113693800.html',
       'https://www.laprovincia.es/mundo/2025/03/02/ia-llega-corea-norte-114844276.html',
       'https://www.laprovincia.es/enfoques/2025/03/02/interes-cultural-114842321.html',
       'https://www.laprovincia.es/sociedad/2025/03/02/segregacion-genero-riesgo-sexismo-adolescencia-114804045.html',
       'https://www.laprovincia.es/tendencias21/2025/03/02/polvo-sahara-alimenta-vida-oceanica-108802825.html',
       'https://www.laprovincia.es/sociedad/2025/03/02/mujeres-lideran-desarrollo-tecnologias-futuro-114846089.html',
       'https://www.larazon.es/gente/famosos/sorpresa-angeles-belen-esteban-aparece-oscar-2025_2025030267c4d2af829a09000195fc69.html',
       'https://www.larazon.es/gente/poder/cronica-marta-robles-jessica-mujer-que-cobraba-empresas-publicas-trabajar_2025030267c3e6371ba31400010aaa8d.html',
       'https://www.larazon.es/espana/polemicos-altos-cargos-empresas-publicas-que-contrataron-jessica_2025030267c3b2061ba31400010a15b2.html',
       'https://www.larazon.es/espana/profesor-chiflado-harry-potter-manteo-pelele_2025030267c3e63f1ba31400010aaad3.html',
       'https://www.larazon.es/gente/casa-real/descubrimos-joyeria-secreta-perlas-reina-sofia-asturias_2025030267c3e632cbf1400001b72fcd.html',
       'https://www.larazon.es/gente/casa-real/todas-veces-que-megan-markle-inspiro-diana-gales-exito_2025030267c3e60ccbf1400001b72e43.html',
       'https://www.larazon.es/gente/famosos/anna-ferrer-buena-senda-hija-paz-padilla_2025030267c3e5f8cbf1400001b72d72.html',
       'https://www.larazon.es/murcia/socialistas-murcia-presentan-nueva-ejecutiva-presidida-jose-salvador-fuentes-zorita_2025030267c445e11ba31400010b3c48.html',
       'https://www.larazon.es/murcia/universidad-murcia-exhibe-replica-periscopio-disenado-isaac-peral-submarino_2025030267c42dcf829a0900019520f3.html',
       'https://www.larazon.es/cataluna/pymes-catalanas-reto_2025030267c48c0a829a09000195b88c.html',
       'https://www.larazon.es/espana/espana-octava-potencia-defensa-mundo_2025030267c3bb18829a090001942662.html',
       'https://www.larazon.es/economia/que-ocurre-cuando-renuncia-prestamo-que-firmado_2025030267c4808d829a09000195a20e.html',
       'https://www.larazon.es/espana/defensa/idi-colaboracion-publicoprivada-piezas-clave-manana_2025030267c0d0fc829a0900019039cb.html',
       'https://www.larazon.es/economia/final-tiempos-modernos_2025030267c3e5fa1ba31400010aa848.html',
       'https://www.larazon.es/economia/estos-son-barrios-mas-caros-alquilar-casa-espana_2025030267c4727d1ba31400010b7c90.html',
       'https://www.laopiniondemurcia.es/tendencias21/2025/03/02/polvo-sahara-alimenta-vida-oceanica-108802818.html',
       'https://www.laopiniondezamora.es/deportes/2025/03/02/mojon-entrenador-bm-caja-rural-114859114.html',
       'https://www.laopiniondezamora.es/comarcas/2025/03/02/portugal-rinde-antruejos-rayanos-114837676.html',
       'https://www.laopiniondemurcia.es/cultura/2025/03/02/filarmonica-della-scala-milan-dedica-114831060.html',
       'https://www.laopiniondemurcia.es/comunidad/2025/03/02/lista-completa-nueva-ejecutiva-psoe-murcia-114844219.html',
       'https://www.laopiniondemurcia.es/comunidad/2025/03/02/35-municipios-region-planes-generales-114830027.html',
       'https://www.laopiniondemalaga.es/videos/deportes/2025/03/02/resumen-goles-highlights-real-oviedo-114863397.html',
       'https://www.laopiniondemurcia.es/medio-ambiente/2025/03/02/explosion-demografica-jabalies-provoca-adentren-114351498.html',
       'https://www.laopiniondemurcia.es/medio-ambiente/2025/03/02/megainundacion-mediterraneo-desertico-relleno-agua-113693788.html',
       'https://www.laopiniondemurcia.es/formacion/universidades/2025/03/02/presidenta-ucam-distinguida-amiga-infanteria-114798884.html',
       'https://www.laopiniondemurcia.es/formacion/universidades/2025/03/02/ucam-abre-preinscripcion-curso-2025-114798560.html',
       'https://www.laopiniondemurcia.es/formacion/universidades/2025/03/02/voluntariado-compromiso-ucam-vulnerables-llenan-114798997.html',
       'https://www.laprovincia.es/canarias/2025/03/02/cinco-lugares-canarias-son-importantes-114840827.html'],
      dtype=object)

## Buscar textos que tengan todas las palabras clave

In [ ]:
# Lista de palabras clave
keywords = ['universidad', 'oviedo']

# Crear una condición de filtro para cada palabra clave
filter_condition = merged_df['texto'].str.contains(keywords[0], case=False, na=False)

for keyword in keywords[1:]:
    filter_condition &= merged_df['texto'].str.contains(keyword, case=False, na=False)

# Aplicar filtro
filtered_df_all = merged_df[filter_condition].reset_index(drop=True)

filtered_df_all

,fuente,url,texto,titulo,fecha_publicacion
0,La Nueva España,https://www.lne.es/sociedad/2025/03/02/agenda-...,VII Feria Internacional de Arte Gráfico en Ovi...,Agenda: qué hacer hoy 2 de marzo en Asturias,2025-03-02
1,La Nueva España,https://www.lne.es/oviedo/2025/03/02/crie-sind...,Entrevista | Juan Ramón García Secades Ingenie...,"""Me crie con el síndrome del patito feo porque...",2025-03-02
2,La Nueva España,https://www.lne.es/oviedo/2025/03/02/carlos-ca...,"Ciudad secreta Carlos Casaprima, frente a su e...","Carlos Casaprima, el hombre con el tiempo en s...",2025-03-02
3,La Vanguardia,https://www.lavanguardia.com/local/asturias/20...,"Asturias AGENCIAS OVIEDO, 2 (EUROPA PRESS) El ...",Barbón se enfrenta a preguntas sobre financiac...,2025-03-02
4,La Vanguardia,https://www.lavanguardia.com/local/asturias/20...,"Asturias AGENCIAS OVIEDO, 2 (EUROPA PRESS) El ...",El PSOE reprocha al PP su “sectarismo” al no s...,2025-03-02
...,...,...,...,...,...
94,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/siero/2...,"El alcalde de Siero, Ángel García, se ha mostr...",Siero arremete contra los ritmos de la Univers...,NaT
95,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/turismo...,La Comarca Vaqueira toma su nombre de los vaqu...,"La Comarca Vaqueira, un vasto territorio asoma...",NaT
96,La Voz de Asturias,https://www.lavozdeasturias.es/noticia/turismo...,El concejo de Oviedo tiene en su corazón la ci...,"Oviedo, un concejo con mucha historia que vio ...",NaT
97,La Voz de Asturias,https://www.lavozdegalicia.es/noticia/lavozdel...,Alexandra es única entre veinte millones. Esa ...,"Esther, madre de la única niña de España que s...",NaT
98,La Voz de Galicia,https://www.lavozdegalicia.es/noticia/sociedad...,"Una investigación de la Universidad de Oviedo,...",El cambio climático reduciría el hábitat del c...,NaT

In [ ]:
def mostrar_informacion(data_df):

    for index, fila in data_df.iterrows():
        if pd.isna(fila['fecha_publicacion']):
            fecha = 'Desconocido'
        else:
            fecha = fila['fecha_publicacion'].strftime('%Y/%m/%d')
        fuente = fila['fuente']

        titulo = 'Desconocido'
        if pd.notna(fila['titulo']):
            titulo = fila['titulo']

        print(titulo)
        print(fila['url'])
        print(f'{fecha} - {fuente}')
        print()

mostrar_informacion(filtered_df_all)

Agenda: qué hacer hoy 2 de marzo en Asturias
https://www.lne.es/sociedad/2025/03/02/agenda-hoy-2-marzo-asturias-114836104.html
2025/03/02 - La Nueva España

"Me crie con el síndrome del patito feo porque era muy buen estudiante"
https://www.lne.es/oviedo/2025/03/02/crie-sindrome-patito-feo-buen-114792213.html
2025/03/02 - La Nueva España

Carlos Casaprima, el hombre con el tiempo en sus manos
https://www.lne.es/oviedo/2025/03/02/carlos-casaprima-hombre-tiempo-manos-114840239.html
2025/03/02 - La Nueva España

Barbón se enfrenta a preguntas sobre financiación autonómica y modelo de cuidados en el pleno de esta semana
https://www.lavanguardia.com/local/asturias/20250302/10437957/barbon-enfrenta-preguntas-sobre-financiacion-autonomica-modelo-cuidados-pleno-semana-agenciaslv20250302.html
2025/03/02 - La Vanguardia

El PSOE reprocha al PP su “sectarismo” al no sumarse a los homenajes a Rafael Altamira
https://www.lavanguardia.com/local/asturias/20250302/10438022/psoe-reprocha-pp-sectarismo-sumarse-homenajes-rafael-altamira-agenciaslv20250302.html
2025/03/02 - La Vanguardia

El Círculo Gijón Noega Baloncesto se lleva el derbi ante el Universidad de Oviedo y roza la fase de ascenso (69-81)
https://www.lne.es/deportes/deporte-astur/2025/03/02/circulo-gijon-noega-baloncesto-lleva-114839669.html
2025/03/02 - La Nueva España

Fernández, Landeira y Artimez... Las historias de tres hijos de emigrantes asturianos que lucharon en el Desembarco de Normandía
https://www.lne.es/asturias-exterior/2024/06/06/fernandez-landeira-artimez-historias-tres-103316936.html
2025/03/02 - La Nueva España

A Candela le falla el camión del azúcar, pero eso no le impide superarse: "No camina, pero monta a caballo, nada sola, ha subido en parapente..."
https://www.lne.es/asturias/2025/03/02/candela-le-falla-camion-azucar-114834723.html
2025/03/02 - La Nueva España

Eucalipto, el árbol que ocupa los bosques del norte de España: «No podemos prescindir de él»
https://www.eldebate.com/sociedad/sociedad-medio-ambiente/20250302/eucalipto-arbol-ocupa-bosques-norte-espana-no-podemos-prescindir_274336.html
2025/03/02 - El Debate

El objetivo final de la pareja de Ayuso: pactar para evitar la cárcel pero que no se le llame "defraudador confeso"
https://www.eldiario.es/politica/objetivo-final-pareja-ayuso-pactar-evitar-carcel-no-le-llame-defraudador-confeso_1_12054734.html
2025/03/02 - ElDiario.es

Ocho meses a la espera de la eutanasia: los pleitos de Abogados Cristianos ralentizan la muerte digna
https://www.eldiario.es/catalunya/ocho-meses-espera-eutanasia-pleitos-abogados-cristianos-ralentizan-muerte-digna_1_12085857.html
2025/03/02 - ElDiario.es

Aurelio Martín (exconcejal): "'Naval Azul' puede convertirse en un nuevo 'solarón', en una acera 'prestosa' y nada más" - miGijón
https://migijon.com/aurelio-martin-exconcejal-naval-azul-puede-convertirse-en-un-nuevo-solaron-en-una-acera-prestosa-y-nada-mas/
2025/03/02 - Mi Gijón

Santander recibe al día 157.496 viajeros por carretera y el 54% es de municipios limítrofes
https://www.eldiariomontanes.es/santander/santander-recibe-dia-157496-viajeros-carretera-municipios-20250302074359-nt.html
2025/03/02 - El Diario Montañés

LABoral Centro de Arte incorpora a los gestores culturales Blanca de la Torre y Bartomeu Marí
https://www.lavanguardia.com/local/asturias/20250301/10436586/laboral-centro-arte-incorpora-gestores-culturales-blanca-torre-bartomeu-mari-agenciaslv20250301.html
2025/03/01 - La Vanguardia

La Universidad quiere dar un giro a la formación de los profesores de las primeras etapas educativas: nuevo grado y cambios en el máster
https://www.lne.es/asturias/2025/03/01/universidad-quiere-dar-giro-formacion-114811149.html
2025/03/01 - La Nueva España

febrero 2025 - Página 42 de 42 - miGijón
https://migijon.com/2025/02/page/42/
2025/03/01 - Mi Gijón

febrero 2025 - Página 39 de 42 - miGijón
https://migijon.com/2025/02/page/39/
2025/03/01 - Mi Gijón

febrero 2025 - Página 38 de 42 - miGijón
https://migijon.com/2025/02/page/38/
2025/03/01 - Mi Gijón

febrero 2025 - Página 22 de 42 - miGijón
https://migijon.com/2025/02/page/22/
2025/03/01 - Mi Gijón

Tres alumnas de la Universidad de Oviedo denuncian a un joven que entró en el aula y les realizó tocamientos - miGijón
https://migijon.com/tres-alumnas-de-la-universidad-de-oviedo-denuncian-a-un-joven-que-entro-en-el-aula-y-les-realizo-tocamientos/
2025/03/01 - Mi Gijón

Los castaños y las especies asociadas a este árbol tienen un futuro incierto con el cambio climático
https://novaciencia.es/los-castanos-y-las-especies-asociadas-a-este-arbol-tienen-un-futuro-incierto-con-el-cambio-climatico/
2025/03/01 - Nova Ciencia

Un nieto de Ortega y Gasset gana el premio internacional de ensayo Jovellanos
https://www.eldiario.es/asturias/nieto-ortega-gasset-gana-premio-internacional-ensayo-jovellanos_1_12094018.html
2025/03/01 - ElDiario.es

<![CDATA[Yo también he cantado el ‘Sarri Sarri’]]>
https://www.elperiodico.com/es/abril/20250301/yo-tambien-he-cantado-sarri-sarri-articulo-javier-garcia-rodriguez-114626568
2025/03/01 - El Periódico

Ha aprendido a surfear las malas olas de la vida
https://www.elcomercio.es/oviedo/aprendido-surfear-malas-olas-vida-20250302223351-nt.html
2025/03/01 - El Comercio

«Ni la sanidad pública es perfecta ni la privada elitista; son complementarias»
https://www.elcomercio.es/oviedo/sanidad-publica-perfecta-privada-elitista-complementarias-20250302223346-nt.html
2025/03/01 - El Comercio

Queda en libertad el acusado manosear a varias alumnas en la Facultad de Educación
https://www.elcomercio.es/oviedo/queda-libertad-acusado-manosear-varias-alumnas-facultad-20250302223339-nt.html
2025/03/01 - El Comercio

De Pekín a Estambul, el camino de la igualdad
https://www.elcomercio.es/asturias/pekin-estambul-camino-igualdad-20250302223241-nt.html
2025/03/01 - El Comercio

Fe Santoveña se incorpora como nueva académica del Alfoz de Gauzón
https://www.elcomercio.es/aviles/santovena-incorpora-nueva-academica-alfoz-gauzon-20250302224227-nt.html
2025/03/01 - El Comercio

«Aquí hay un sentido de comunidad muy arraigado que me recuerda a Asturias»
https://www.elcomercio.es/asturianos-por-el-mundo/sentido-comunidad-arraigado-recuerda-asturias-20250302223009-nt.html
2025/03/01 - El Comercio

LABoral Centro de Arte incorpora a los gestores culturales Blanca de la Torre y Bartomeu Marí
https://www.lavanguardia.com/cultura/20250301/10436587/laboral-centro-arte-incorpora-gestores-culturales-blanca-torre-bartomeu-mari-ep-agenciaslv20250301.html
2025/03/01 - La Vanguardia

Peter Burke y el  I+D de ArcelorMittal, Gregory Ludkovsky Honoris Causa por Oviedo. Asturias Mundial
http://www.asturiasmundial.com/noticia/111057/peter-burke-id-arcelormittal-gregory-ludkovsky-honoris-causa-por-oviedo/#.XcBLIdT1TaQ.tumblr
Desconocido - Asturias Mundial

La Sindicatura de Cuentas detecta deficiencias en la contratación autonómica: irregularidades en contratos de emergencia y retrasos en obras clave. Asturias Mundial
http://www.asturiasmundial.com/noticia/139138/sindicatura-cuentas-detecta-deficiencias-contratacion-autonomica-irregularidades-contratos-emergencia-retrasos-obras-clave/
Desconocido - Asturias Mundial

La Universidad de Oviedo aprueba 5.443 plazas para el curso 2025-2026 y avanza en su transformación educativa. Asturias Mundial
http://www.asturiasmundial.com/noticia/139183/universidad-oviedo-aprueba-5443-plazas-curso-20252026-avanza-transformacion-educativa/
Desconocido - Asturias Mundial

El profesorado de C-LM se forma para informar a los alumnos de la nueva Prueba de Acceso a la Universidad
http://www.gentedigital.es/albacete/noticia/4009971/el-profesorado-de-c-lm-se-forma-para-informar-a-los-alumnos-de-la-nueva-prueba-de-acceso-a-la-universidad/
Desconocido - Gente Digital

La compositora Sonia Megías y la artista Susana Guerrero ofrecen su espectáculo 'Tableau sonant' en el MUA
http://www.gentedigital.es/alicante/noticia/4011591/la-compositora-sonia-megias-y-la-artista-susana-guerrero-ofrecen-su-espectaculo-tableau-sonant-en-el-mua/
Desconocido - Gente Digital

Teatre Arniches ofrece 'Los guapos' de David Trueba y el espectáculo infantil 'Semilla'
http://www.gentedigital.es/alicante/noticia/4011800/teatre-arniches-ofrece-los-guapos-de-david-trueba-y-el-espectaculo-infantil-semilla/
Desconocido - Gente Digital

Investigadores de la UA trabajan un sistema para detectar noticias falsas, lenguaje nocivo y contenido de IA
http://www.gentedigital.es/alicante/noticia/4012570/investigadores-de-la-ua-trabajan-un-sistema-para-detectar-noticias-falsas-lenguaje-nocivo-y-contenido-de-ia/
Desconocido - Gente Digital

Cátedra de Turismo Ciudad de Alicante firma un acuerdo con APHA para realizar modelos predictivos de ocupación
http://www.gentedigital.es/alicante/noticia/4014967/catedra-de-turismo-ciudad-de-alicante-firma-un-acuerdo-con-apha-para-realizar-modelos-predictivos-de-ocupacion/
Desconocido - Gente Digital

La UCAV aborda en unas jornadas la protección de la naturaleza en el ámbito policial
http://www.gentedigital.es/avila/noticia/4007892/la-ucav-aborda-en-unas-jornadas-la-proteccion-de-la-naturaleza-en-el-ambito-policial/
Desconocido - Gente Digital

La UCAV celebra los diez años de la Cátedra de la Mujer con una jornada conmemorativa con destacadas ponentes
http://www.gentedigital.es/avila/noticia/4011669/la-ucav-celebra-los-diez-anos-de-la-catedra-de-la-mujer-con-una-jornada-conmemorativa-con-destacadas-ponentes/
Desconocido - Gente Digital

La UCAV celebra los 10 años de la Cátedra Santa Teresa de Jesús de Estudios sobre la Mujer
http://www.gentedigital.es/avila/noticia/4011748/la-ucav-celebra-los-10-anos-de-la-catedra-santa-teresa-de-jesus-de-estudios-sobre-la-mujer/
Desconocido - Gente Digital

El II Seminario de Humanismo Cristiano de UCAV busca impulsar los valores y el bien común a través de cuatro ponencias
http://www.gentedigital.es/avila/noticia/4012062/el-ii-seminario-de-humanismo-cristiano-de-ucav-busca-impulsar-los-valores-y-el-bien-comun-a-traves-de-cuatro-ponencias/
Desconocido - Gente Digital

El Ayuntamiento de Burgos y la UBU programan para marzo cuatro propuestas en el XXVIII Ciclo de Teatro Joven
http://www.gentedigital.es/burgos/noticia/4011120/el-ayuntamiento-de-burgos-y-la-ubu-programan-para-marzo-cuatro-propuestas-en-el-xxviii-ciclo-de-teatro-joven/
Desconocido - Gente Digital

Alcón dice que las universidades trabajan para responder a  necesidades, pero aún sin propuesta de Plan de Financiación
http://www.gentedigital.es/castellon/noticia/4014177/alcon-dice-que-las-universidades-trabajan-para-responder-a--necesidades-pero-aun-sin-propuesta-de-plan-de-financiacion/
Desconocido - Gente Digital

Alcón destaca que García Montero ha sido un "firme defensor" de la diversidad lingüística y las universidades públicas
http://www.gentedigital.es/castellon/noticia/4014184/alcon-destaca-que-garcia-montero-ha-sido-un-firme-defensor-de-la-diversidad-linguistica-y-las-universidades-publicas/
Desconocido - Gente Digital

Montserrat defiende tomar medidas con "riesgo" para transferir conocimiento de academia a empresas
http://www.gentedigital.es/catalunya/noticia/4014938/montserrat-defiende-tomar-medidas-con-riesgo-para-transferir-conocimiento-de-academia-a-empresas/
Desconocido - Gente Digital

La Junta firma un convenio para desarrollar un estudio sobre la religiosidad popular en Andalucía
http://www.gentedigital.es/cordoba/noticia/4014410/la-junta-firma-un-convenio-para-desarrollar-un-estudio-sobre-la-religiosidad-popular-en-andalucia/
Desconocido - Gente Digital

Un estudio de la UCLM demuestra que las alternativas vegetales a la carne tienen beneficios saludables a corto plazo
http://www.gentedigital.es/cuenca/noticia/4013229/un-estudio-de-la-uclm-demuestra-que-las-alternativas-vegetales-a-la-carne-tienen-beneficios-saludables-a-corto-plazo/
Desconocido - Gente Digital

Un proyecto de ciencia ciudadana involucra a la comunidad vecinal de Huelva para mejorar espacios urbanos
http://www.gentedigital.es/huelva/noticia/4013303/un-proyecto-de-ciencia-ciudadana-involucra-a-la-comunidad-vecinal-de-huelva-para-mejorar-espacios-urbanos/
Desconocido - Gente Digital

La Universidad de Huelva celebra su aniversario con dos conciertos especiales en el mes de marzo
http://www.gentedigital.es/huelva/noticia/4013478/la-universidad-de-huelva-celebra-su-aniversario-con-dos-conciertos-especiales-en-el-mes-de-marzo/
Desconocido - Gente Digital

Ayudas de 30.000 euros a ocho microproyectos de investigación de la Cátedra de la Provincia de la Universidad
http://www.gentedigital.es/huelva/noticia/4014163/ayudas-de-30000-euros-a-ocho-microproyectos-de-investigacion-de-la-catedra-de-la-provincia-de-la-universidad/
Desconocido - Gente Digital

La UHU y Platalea firman un convenio para la gestión y dinamización cultural del Cabezo de la Almagra
http://www.gentedigital.es/huelva/noticia/4014480/la-uhu-y-platalea-firman-un-convenio-para-la-gestion-y-dinamizacion-cultural-del-cabezo-de-la-almagra/
Desconocido - Gente Digital

La UHU y el Real Club de Tenis Huelva firman un convenio para fomentar la práctica deportiva
http://www.gentedigital.es/huelva/noticia/4015001/la-uhu-y-el-real-club-de-tenis-huelva-firman-un-convenio-para-fomentar-la-practica-deportiva/
Desconocido - Gente Digital

Educación gestionará la cobertura de las plazas de los ATEs a partir de septiembre
http://www.gentedigital.es/ibiza/noticia/4006628/educacion-gestionara-la-cobertura-de-las-plazas-de-los-ates-a-partir-de-septiembre/
Desconocido - Gente Digital

El Govern inicia las obras de ampliación del CEIP Can Misses de Ibiza
http://www.gentedigital.es/ibiza/noticia/4006894/el-govern-inicia-las-obras-de-ampliacion-del-ceip-can-misses-de-ibiza/
Desconocido - Gente Digital

Científicos andaluces aplican una técnica que reduce costes y tiempos para crear abono a partir de alperujo
http://www.gentedigital.es/jaen/noticia/4014350/cientificos-andaluces-aplican-una-tecnica-que-reduce-costes-y-tiempos-para-crear-abono-a-partir-de-alperujo/
Desconocido - Gente Digital

El PP señala la retirada de dos placas en la Universidad Popular con nombres de Fernández de Moya y González Romo
http://www.gentedigital.es/jaen/noticia/4015007/el-pp-senala-la-retirada-de-dos-placas-en-la-universidad-popular-con-nombres-de-fernandez-de-moya-y-gonzalez-romo/
Desconocido - Gente Digital

UR aborda en un curso la dimensión cultural del vino, de la mano del guionista Bernardo Sánchez o el pintor José Uríszar
http://www.gentedigital.es/logrono/noticia/4014429/ur-aborda-en-un-curso-la-dimension-cultural-del-vino-de-la-mano-del-guionista-bernardo-sanchez-o-el-pintor-jose-uriszar/
Desconocido - Gente Digital

El Curso 'Introducción a la cata de vinos blancos' de la UR ofrece la oportunidad de profundizar en este tipo de caldos
http://www.gentedigital.es/logrono/noticia/4014716/el-curso-introduccion-a-la-cata-de-vinos-blancos-de-la-ur-ofrece-la-oportunidad-de-profundizar-en-este-tipo-de-caldos/
Desconocido - Gente Digital

El PSOE reprocha al PP su "sectarismo" al no sumarse a los homenajes a Rafael Altamira
http://www.gentedigital.es/oviedo/noticia/4014826/el-psoe-reprocha-al-pp-su-sectarismo-al-no-sumarse-a-los-homenajes-a-rafael-altamira/
Desconocido - Gente Digital

El Ayuntamiento y la UPSA promocionan un documental sobre la soledad en la vejez y la interacción intergeneracional
http://www.gentedigital.es/salamanca/noticia/4013026/el-ayuntamiento-y-la-upsa-promocionan-un-documental-sobre-la-soledad-en-la-vejez-y-la-interaccion-intergeneracional/
Desconocido - Gente Digital

La Junta impulsa el emprendimiento femenino en la novena edición de 'Gira Mujeres'
http://www.gentedigital.es/sevilla/noticia/4014715/la-junta-impulsa-el-emprendimiento-femenino-en-la-novena-edicion-de-gira-mujeres/
Desconocido - Gente Digital

El X Curso de Truficultura práctica de Mora de Rubielos (Teruel) muestra las novedades del sector
http://www.gentedigital.es/teruel/noticia/4009325/el-x-curso-de-truficultura-practica-de-mora-de-rubielos-teruel-muestra-las-novedades-del-sector/
Desconocido - Gente Digital

El IVC subraya su apuesta por "fomentar el pensamiento creativo en espectadores" a través de la Comunitat IVC
http://www.gentedigital.es/valencia/noticia/4014990/el-ivc-subraya-su-apuesta-por-fomentar-el-pensamiento-creativo-en-espectadores-a-traves-de-la-comunitat-ivc/
Desconocido - Gente Digital

El tranvía circulará este sábado por la noche en Vitoria-Gasteiz dentro de un servicio especial por los Carnavales
http://www.gentedigital.es/vitoria/noticia/4014070/el-tranvia-circulara-este-sabado-por-la-noche-en-vitoria-gasteiz-dentro-de-un-servicio-especial-por-los-carnavales/
Desconocido - Gente Digital

Descubren un yacimiento en Tarifa con huellas de grandes mamíferos de hace 778.000 años
https://www.8directo.com/tarifa/descubren-yacimiento-en-tarifa-con-huellas-grandes-mamiferos-hace-778000-anos_622951_102.html
Desconocido - 8directo

Entrega del Premio Ana Casanueva a Aspace Asturias. Asturias Mundial
https://www.asturiasmundial.com/fotonews/852/entrega-premio-ana-casanueva-aspace-asturias/
Desconocido - Asturias Mundial

La Sindicatura de Cuentas detecta deficiencias en la contratación autonómica: irregularidades en contratos de emergencia y retrasos en obras clave. Asturias Mundial
https://www.asturiasmundial.com/noticia/139138/sindicatura-cuentas-detecta-deficiencias-contratacion-autonomica-irregularidades-contratos-emergencia-retrasos-obras-clave/
Desconocido - Asturias Mundial

La Universidad de Oviedo aprueba 5.443 plazas para el curso 2025-2026 y avanza en su transformación educativa. Asturias Mundial
https://www.asturiasmundial.com/noticia/139183/universidad-oviedo-aprueba-5443-plazas-curso-20252026-avanza-transformacion-educativa/
Desconocido - Asturias Mundial

ECOAQUA participa en un estudio novedoso de ámbito nacional en el que se observará la navegación de carabelas portuguesas
https://www.elperiodicodecanarias.es/ecoaqua-participa-en-un-estudio-novedoso-de-ambito-nacional-en-el-que-se-observara-la-navegacion-de-carabelas-portuguesas/
Desconocido - El Periodico de Canarias

noviembre 2023 | es por madrid
https://www.espormadrid.es/2023/11/
Desconocido - Es por madrid

La leonesa que nunca deja de sorprender: Nieves González Barrio
https://www.lanuevacronica.com/lnc-culturas/leonesa-nunca-deja-sorprender-nieves-gonzalez-barrio_171361_102.html
Desconocido - La Nueva Crónica

Cristina Olivar y Candela Aguilar-García, ganadoras del minicongreso de estudiantes del Instituto Universitario de Oncología
https://www.lavozdeasturias.es/noticia/asturias/2025/02/28/cristina-olivar-candela-aguilar-garcia-ganadoras-minicongreso-estudiantes-instituto-unviersitario-oncologia/00031740767459090388240.htm
Desconocido - La Voz de Asturias

Un joven, «oliendo a alcohol», se cuela en la facultad de Educación para tocar a varias alumnas
https://www.lavozdeasturias.es/noticia/asturias/2025/02/28/joven-cuela-facultad-educacion-oliendo-alcohol-tocar-varias-alumnas/00031740768053644495701.htm
Desconocido - La Voz de Asturias

¿Eres víctima de la fast fashion? Dos asturianas buscan soluciones
https://www.lavozdeasturias.es/noticia/asturiascon-r/2019/04/09/proyecto-concienciar-sobre-fast-fashion-ganador-dream-big-asturias-2019/00031554823709515350864.htm
Desconocido - La Voz de Asturias

La fantasía de una au pair: una familia maravillosa y no querer volver
https://www.lavozdeasturias.es/noticia/emigracion/2020/02/27/fantasia-au-pair-familia-maravillosa-querer-volver/00031582821536420638449.htm
Desconocido - La Voz de Asturias

La asturianía no entiende de fronteras: se lleva por dentro
https://www.lavozdeasturias.es/noticia/emigracion/2020/03/21/asturiania-entiende-fronteras-lleva-dentro/00031584812230822173974.htm
Desconocido - La Voz de Asturias

De auxiliar de español en Reino Unido a tener que serlo desde casa: «Siento que una parte de mí todavía está allí»

### Eliminando fecha desconocida

Se muestran solo los artículos con fecha

In [ ]:
mostrar_informacion(filtered_df_all.dropna())

Agenda: qué hacer hoy 2 de marzo en Asturias
https://www.lne.es/sociedad/2025/03/02/agenda-hoy-2-marzo-asturias-114836104.html
2025/03/02 - La Nueva España

"Me crie con el síndrome del patito feo porque era muy buen estudiante"
https://www.lne.es/oviedo/2025/03/02/crie-sindrome-patito-feo-buen-114792213.html
2025/03/02 - La Nueva España

Carlos Casaprima, el hombre con el tiempo en sus manos
https://www.lne.es/oviedo/2025/03/02/carlos-casaprima-hombre-tiempo-manos-114840239.html
2025/03/02 - La Nueva España

Barbón se enfrenta a preguntas sobre financiación autonómica y modelo de cuidados en el pleno de esta semana
https://www.lavanguardia.com/local/asturias/20250302/10437957/barbon-enfrenta-preguntas-sobre-financiacion-autonomica-modelo-cuidados-pleno-semana-agenciaslv20250302.html
2025/03/02 - La Vanguardia

El PSOE reprocha al PP su “sectarismo” al no sumarse a los homenajes a Rafael Altamira
https://www.lavanguardia.com/local/asturias/20250302/10438022/psoe-reprocha-pp-sectarismo-sumarse-homenajes-rafael-altamira-agenciaslv20250302.html
2025/03/02 - La Vanguardia

El Círculo Gijón Noega Baloncesto se lleva el derbi ante el Universidad de Oviedo y roza la fase de ascenso (69-81)
https://www.lne.es/deportes/deporte-astur/2025/03/02/circulo-gijon-noega-baloncesto-lleva-114839669.html
2025/03/02 - La Nueva España

Fernández, Landeira y Artimez... Las historias de tres hijos de emigrantes asturianos que lucharon en el Desembarco de Normandía
https://www.lne.es/asturias-exterior/2024/06/06/fernandez-landeira-artimez-historias-tres-103316936.html
2025/03/02 - La Nueva España

A Candela le falla el camión del azúcar, pero eso no le impide superarse: "No camina, pero monta a caballo, nada sola, ha subido en parapente..."
https://www.lne.es/asturias/2025/03/02/candela-le-falla-camion-azucar-114834723.html
2025/03/02 - La Nueva España

Eucalipto, el árbol que ocupa los bosques del norte de España: «No podemos prescindir de él»
https://www.eldebate.com/sociedad/sociedad-medio-ambiente/20250302/eucalipto-arbol-ocupa-bosques-norte-espana-no-podemos-prescindir_274336.html
2025/03/02 - El Debate

El objetivo final de la pareja de Ayuso: pactar para evitar la cárcel pero que no se le llame "defraudador confeso"
https://www.eldiario.es/politica/objetivo-final-pareja-ayuso-pactar-evitar-carcel-no-le-llame-defraudador-confeso_1_12054734.html
2025/03/02 - ElDiario.es

Ocho meses a la espera de la eutanasia: los pleitos de Abogados Cristianos ralentizan la muerte digna
https://www.eldiario.es/catalunya/ocho-meses-espera-eutanasia-pleitos-abogados-cristianos-ralentizan-muerte-digna_1_12085857.html
2025/03/02 - ElDiario.es

Aurelio Martín (exconcejal): "'Naval Azul' puede convertirse en un nuevo 'solarón', en una acera 'prestosa' y nada más" - miGijón
https://migijon.com/aurelio-martin-exconcejal-naval-azul-puede-convertirse-en-un-nuevo-solaron-en-una-acera-prestosa-y-nada-mas/
2025/03/02 - Mi Gijón

Santander recibe al día 157.496 viajeros por carretera y el 54% es de municipios limítrofes
https://www.eldiariomontanes.es/santander/santander-recibe-dia-157496-viajeros-carretera-municipios-20250302074359-nt.html
2025/03/02 - El Diario Montañés

LABoral Centro de Arte incorpora a los gestores culturales Blanca de la Torre y Bartomeu Marí
https://www.lavanguardia.com/local/asturias/20250301/10436586/laboral-centro-arte-incorpora-gestores-culturales-blanca-torre-bartomeu-mari-agenciaslv20250301.html
2025/03/01 - La Vanguardia

La Universidad quiere dar un giro a la formación de los profesores de las primeras etapas educativas: nuevo grado y cambios en el máster
https://www.lne.es/asturias/2025/03/01/universidad-quiere-dar-giro-formacion-114811149.html
2025/03/01 - La Nueva España

febrero 2025 - Página 42 de 42 - miGijón
https://migijon.com/2025/02/page/42/
2025/03/01 - Mi Gijón

febrero 2025 - Página 39 de 42 - miGijón
https://migijon.com/2025/02/page/39/
2025/03/01 - Mi Gijón

febrero 2025 - Página 38 de 42 - miGijón
https://migijon.com/2025/02/page/38/
2025/03/01 - Mi Gijón

febrero 2025 - Página 22 de 42 - miGijón
https://migijon.com/2025/02/page/22/
2025/03/01 - Mi Gijón

Tres alumnas de la Universidad de Oviedo denuncian a un joven que entró en el aula y les realizó tocamientos - miGijón
https://migijon.com/tres-alumnas-de-la-universidad-de-oviedo-denuncian-a-un-joven-que-entro-en-el-aula-y-les-realizo-tocamientos/
2025/03/01 - Mi Gijón

Los castaños y las especies asociadas a este árbol tienen un futuro incierto con el cambio climático
https://novaciencia.es/los-castanos-y-las-especies-asociadas-a-este-arbol-tienen-un-futuro-incierto-con-el-cambio-climatico/
2025/03/01 - Nova Ciencia

Un nieto de Ortega y Gasset gana el premio internacional de ensayo Jovellanos
https://www.eldiario.es/asturias/nieto-ortega-gasset-gana-premio-internacional-ensayo-jovellanos_1_12094018.html
2025/03/01 - ElDiario.es

<![CDATA[Yo también he cantado el ‘Sarri Sarri’]]>
https://www.elperiodico.com/es/abril/20250301/yo-tambien-he-cantado-sarri-sarri-articulo-javier-garcia-rodriguez-114626568
2025/03/01 - El Periódico

Ha aprendido a surfear las malas olas de la vida
https://www.elcomercio.es/oviedo/aprendido-surfear-malas-olas-vida-20250302223351-nt.html
2025/03/01 - El Comercio

«Ni la sanidad pública es perfecta ni la privada elitista; son complementarias»
https://www.elcomercio.es/oviedo/sanidad-publica-perfecta-privada-elitista-complementarias-20250302223346-nt.html
2025/03/01 - El Comercio

Queda en libertad el acusado manosear a varias alumnas en la Facultad de Educación
https://www.elcomercio.es/oviedo/queda-libertad-acusado-manosear-varias-alumnas-facultad-20250302223339-nt.html
2025/03/01 - El Comercio

De Pekín a Estambul, el camino de la igualdad
https://www.elcomercio.es/asturias/pekin-estambul-camino-igualdad-20250302223241-nt.html
2025/03/01 - El Comercio

Fe Santoveña se incorpora como nueva académica del Alfoz de Gauzón
https://www.elcomercio.es/aviles/santovena-incorpora-nueva-academica-alfoz-gauzon-20250302224227-nt.html
2025/03/01 - El Comercio

«Aquí hay un sentido de comunidad muy arraigado que me recuerda a Asturias»
https://www.elcomercio.es/asturianos-por-el-mundo/sentido-comunidad-arraigado-recuerda-asturias-20250302223009-nt.html
2025/03/01 - El Comercio

LABoral Centro de Arte incorpora a los gestores culturales Blanca de la Torre y Bartomeu Marí
https://www.lavanguardia.com/cultura/20250301/10436587/laboral-centro-arte-incorpora-gestores-culturales-blanca-torre-bartomeu-mari-ep-agenciaslv20250301.html
2025/03/01 - La Vanguardia