# Instalación de librerías

In [1]:
!pip install -q scrapy
!pip install -q newspaper3k
!pip install -q lxml_html_clean

# Extraer enlaces de noticias

Eliminar csv para generar uno nuevo

In [ ]:
# # Eliminar csv
# import os
# output_file_csv = "news_output.csv"
# if os.path.exists(output_file_csv):
#     os.remove(output_file_csv)

Ejecutar spider de scrapy para generar el archivo csv con los enlaces

In [ ]:
import os
from datetime import date

hoy = date.today().strftime("%d-%m-%Y")
comando = f"scrapy crawl news_extractor -o news_scraper/csv/{hoy}.csv -s LOG_ENABLED=False -s ROBOTSTXT_OBEY=False"
os.system(comando)

In [8]:
!scrapy crawl news_extractor -o news_scraper/csv/hoy.csv -s LOG_ENABLED=False -s ROBOTSTXT_OBEY=False

Fecha de inicio: 2025-03-28
Robots URL: https://www.elcomercio.es/robots.txt
Robots URL: https://www.europapress.es/robots.txt
Robots URL: https://www.20minutos.es/robots.txt
Robots URL: https://www.lne.es/robots.txt
Robots URL: https://www.elespanol.com/robots.txt
Robots URL: https://www.eldiario.es/robots.txt
Robots URL: https://www.elconfidencial.com/robots.txt
Robots URL: https://www.rtpa.es/robots.txt
Robots URL: https://www.larazon.es/robots.txt
Robots URL: https://migijon.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.elcomercio.es/sitemap.incremental.xml', 'https://www.elcomercio.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.incremental.xml
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.xml
Robots URL: https://www.lavanguardia.com/robots.txt
Robots URL: https://www.culturalgijonesa.org/robots.txt
Robots URL: https://www.nortes.me/robots.txt
Robots URL: https://www.elperiodico.com/robots.txt
Robots URL: https://www.tribunasalamanca.com/robots.txt
Robots URL: https://www.infobae.com/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elespanol.com/sitemap_google_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.eldiario.es/sitemap_index_25b87.xml', 'https://www.eldiario.es/sitemap_google_news_25b87.xml'}
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_index_25b87.xml
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_google_news_25b87.xml
Se encontraron los siguientes enlaces xml: {'https://www.europapress.es/sitemap_index/', 'https://www.europapress.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.europapress.es/sitemap_index/
Accediendo al siguiente enlace... https://www.europapress.es/sitemap.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elconfidencial.com/newsitemap_4.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.20minutos.es/sitemap-google-news.xml
Robots URL: https://www.laprovincia.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.rtpa.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.rtpa.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.larazon.es/sitemaps/content_sitemap_index.xml', 'https://www.larazon.es/sitemaps/news.xml'}
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/content_sitemap_index.xml
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/news.xml
Se encontraron los siguientes enlaces xml: {'https://migijon.com/sitemap_index.xml', 'https://migijon.com/xmlsitemap.xml'}
Accediendo al siguiente enlace... https://migijon.com/sitemap_index.xml
Accediendo al siguiente enlace... https://migijon.com/xmlsitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.lne.es/sitemap_today_52e19.xml', 'https://www.lne.es/sitemap_google_news_52e19.xml'}
Accediendo al siguiente enlace... https://www.lne.es/sitemap_today_52e19.xml
Accediendo al siguiente enlace... https://www.lne.es/sitemap_google_news_52e19.xml
Robots URL: https://www.laopiniondemalaga.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.infobae.com/arc/outboundfeeds/sitemap2/', 'https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/', 'https://www.infobae.com/arc/outboundfeeds/news-sitemap2/'}
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap2/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/news-sitemap2/
Robots URL: https://www.nationalgeographic.es/robots.txt
Robots URL: https://www.eldia.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.tribunasalamanca.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunasalamanca.com/sitemap_last_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.laprovincia.es/sitemap_google_news_89aa6.xml', 'https://www.laprovincia.es/sitemap_index_89aa6.xml'}
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_google_news_89aa6.xml
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_index_89aa6.xml
Robots URL: https://forbes.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.elperiodico.com/es/sitemap-noticias.xml', 'https://www.elperiodico.com/es/google-news.xml'}
Accediendo al siguiente enlace... https://www.elperiodico.com/es/sitemap-noticias.xml
Accediendo al siguiente enlace... https://www.elperiodico.com/es/google-news.xml
Robots URL: https://www.lacerca.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.nortes.me/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.nortes.me/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml', 'https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml'}
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml
Robots URL: https://www.tribunaavila.com/robots.txt
Robots URL: https://www.elfielato.es/robots.txt
Robots URL: https://www.teleprensa.com/robots.txt
Robots URL: https://www.latribunadealbacete.es/robots.txt
Robots URL: https://iymagazine.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.tribunaavila.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunaavila.com/sitemap_last_news.xml
Se encontraron los siguientes enlaces xml: {'https://forbes.es/wp-sitemap.xml'}
Accediendo al siguiente enlace... https://forbes.es/wp-sitemap.xml
Robots URL: https://itg.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://iymagazine.es/sitemap.xml'}
Accediendo al siguiente enlace... https://iymagazine.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.teleprensa.com/sitemap.news.xml.gz', 'https://www.teleprensa.com/sitemap.xml'}
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.news.xml.gz
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.elfielato.es/sitemap.xml', 'https://www.elfielato.es/sitemap.news.xml.gz'}
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.xml
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.news.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.latribunadealbacete.es/sitemap.news.xml', 'https://www.latribunadealbacete.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.news.xml
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://itg.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://itg.es/sitemap_index.xml
Se encontró archivo comprimido https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.03.1.xml.gz
Se encontró archivo comprimido https://iymagazine.es/sitemaps/sitemap_1.xml.gz
Se encontraron los siguientes enlaces xml: {'http://www.lacerca.com/system/sitemaps/sitemap.xml'}
Accediendo al siguiente enlace... http://www.lacerca.com/system/sitemaps/sitemap.xml
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-10.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-11.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-12.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-13.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-14.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-15.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-1.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-2.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-3.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-4.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-5.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-6.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-7.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-8.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-9.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-news-es-1.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.nationalgeographic.es/sitemap/sitemap.xml', 'https://www.nationalgeographic.es/google-news.xml'}
Accediendo al siguiente enlace... https://www.nationalgeographic.es/sitemap/sitemap.xml
Accediendo al siguiente enlace... https://www.nationalgeographic.es/google-news.xml
Se encontraron los siguientes enlaces xml: {'https://www.eldia.es/sitemap_google_news_f10b6.xml', 'https://www.eldia.es/sitemap_index_f10b6.xml'}
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_google_news_f10b6.xml
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_index_f10b6.xml
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.24.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.25.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.26.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.27.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.28.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.29.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.30.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.31.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.32.xml.gz
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-google-news.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-1.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-2.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-3.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-4.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-5.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-6.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-7.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-8.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-9.xml
Se encontraron los siguientes enlaces xml: {'https://www.culturalgijonesa.org/sitemap.xml', 'https://www.culturalgijonesa.org/sitemap.rss'}
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.xml
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.rss
Robots URL: https://www.almerianoticias.es/robots.txt
Robots URL: https://www.larioja.com/robots.txt
Robots URL: https://www.eldiariomontanes.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.larioja.com/sitemap.xml', 'https://www.larioja.com/sitemap.incremental.xml'}
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.xml
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.incremental.xml
Se encontraron los siguientes enlaces xml: {'https://www.eldiariomontanes.es/sitemap.xml', 'https://www.eldiariomontanes.es/sitemap.incremental.xml'}
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.xml
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.incremental.xml
Robots URL: https://news.ual.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.almerianoticias.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.almerianoticias.es/sitemap_index.xml
Robots URL: https://www.farodevigo.es/robots.txt
Robots URL: https://www.diariocordoba.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.farodevigo.es/sitemap_index_246e7.xml', 'https://www.farodevigo.es/sitemap_google_news_246e7.xml'}
Accediendo al siguiente enlace... https://www.farodevigo.es/sitemap_index_246e7.xml
Accediendo al siguiente enlace... https://www.farodevigo.es/sitemap_google_news_246e7.xml
Se encontraron los siguientes enlaces xml: {'https://www.diariocordoba.com/sitemap_google_news_9665f.xml', 'https://www.diariocordoba.com/sitemap_index_9665f.xml'}
Accediendo al siguiente enlace... https://www.diariocordoba.com/sitemap_google_news_9665f.xml
Accediendo al siguiente enlace... https://www.diariocordoba.com/sitemap_index_9665f.xml
Se encontraron los siguientes enlaces xml: {'http://news.ual.es/sitemap_index.xml'}
Accediendo al siguiente enlace... http://news.ual.es/sitemap_index.xml
Robots URL: https://www.diariodeibiza.es/robots.txt
Robots URL: https://segoviaudaz.es/robots.txt
Robots URL: https://www.noticiasde.es/robots.txt
Robots URL: https://www.redaccionmedica.com/robots.txt
Robots URL: https://www.diariodevalderrueda.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.diariodeibiza.es/sitemap_google_news_fdff0.xml', 'https://www.diariodeibiza.es/sitemap_index_fdff0.xml'}
Accediendo al siguiente enlace... https://www.diariodeibiza.es/sitemap_google_news_fdff0.xml
Accediendo al siguiente enlace... https://www.diariodeibiza.es/sitemap_index_fdff0.xml
Robots URL: https://cronicadeandalucia.com/robots.txt
Se encontraron los siguientes enlaces xml: {'http://segoviaudaz.es/sitemap.xml'}
Accediendo al siguiente enlace... http://segoviaudaz.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.noticiasde.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.noticiasde.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.diariodevalderrueda.es/sitemap/lastarticles', 'https://www.diariodevalderrueda.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.diariodevalderrueda.es/sitemap/lastarticles
Accediendo al siguiente enlace... https://www.diariodevalderrueda.es/sitemap.xml
Robots URL: https://www.ondacero.es/robots.txt
Robots URL: https://www.laopinioncoruna.es/robots.txt
Robots URL: https://www.laescena.es/robots.txt
Robots URL: https://www.eleconomista.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://cronicadeandalucia.com/sitemap_index.xml', 'https://cronicadeandalucia.com/sitemap-news.xml'}
Accediendo al siguiente enlace... https://cronicadeandalucia.com/sitemap_index.xml
Accediendo al siguiente enlace... https://cronicadeandalucia.com/sitemap-news.xml
Robots URL: https://economia3.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://economia3.com/sitemap.xml'}
Accediendo al siguiente enlace... https://economia3.com/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.laopinioncoruna.es/sitemap_google_news_967c1.xml', 'https://www.laopinioncoruna.es/sitemap_index_967c1.xml'}
Accediendo al siguiente enlace... https://www.laopinioncoruna.es/sitemap_google_news_967c1.xml
Accediendo al siguiente enlace... https://www.laopinioncoruna.es/sitemap_index_967c1.xml
Se encontraron los siguientes enlaces xml: {'https://www.eleconomista.es/sitemap_news_ssl.php', 'https://www.eleconomista.es/sitemap_noticias.php', 'http://www.eleconomista.es/sitemap.xml', 'http://www.eleconomista.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.eleconomista.es/sitemap_news_ssl.php
Accediendo al siguiente enlace... https://www.eleconomista.es/sitemap_noticias.php
Accediendo al siguiente enlace... http://www.eleconomista.es/sitemap.xml
Accediendo al siguiente enlace... http://www.eleconomista.es/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.ondacero.es/sitemaps/GENERAL_C108_elections_NEWS_content_2023.xml', 'https://www.ondacero.es/sitemaps/news.xml', 'https://www.ondacero.es/sitemaps/content_sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.ondacero.es/sitemaps/GENERAL_C108_elections_NEWS_content_2023.xml
Accediendo al siguiente enlace... https://www.ondacero.es/sitemaps/news.xml
Accediendo al siguiente enlace... https://www.ondacero.es/sitemaps/content_sitemap_index.xml

Fecha de inicio: 2025-03-28
Robots URL: https://www.20minutos.es/robots.txt
Robots URL: https://www.elcomercio.es/robots.txt
Robots URL: https://www.europapress.es/robots.txt
Robots URL: https://www.culturalgijonesa.org/robots.txt
Robots URL: https://www.lne.es/robots.txt
Robots URL: https://www.eldiario.es/robots.txt
Robots URL: https://www.elespanol.com/robots.txt
Robots URL: https://www.larazon.es/robots.txt
Robots URL: https://www.rtpa.es/robots.txt
Robots URL: https://www.elconfidencial.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.elcomercio.es/sitemap.incremental.xml', 'https://www.elcomercio.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.incremental.xml
Accediendo al siguiente enlace... https://www.elcomercio.es/sitemap.xml
Robots URL: https://migijon.com/robots.txt
Robots URL: https://www.nortes.me/robots.txt
Robots URL: https://www.tribunasalamanca.com/robots.txt
Robots URL: https://www.lavanguardia.com/robots.txt
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.20minutos.es/sitemap-google-news.xml
Robots URL: https://www.elperiodico.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.lne.es/sitemap_today_52e19.xml', 'https://www.lne.es/sitemap_google_news_52e19.xml'}
Accediendo al siguiente enlace... https://www.lne.es/sitemap_today_52e19.xml
Accediendo al siguiente enlace... https://www.lne.es/sitemap_google_news_52e19.xml
Robots URL: https://www.laopiniondemalaga.es/robots.txt
Robots URL: https://www.laprovincia.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.culturalgijonesa.org/sitemap.xml', 'https://www.culturalgijonesa.org/sitemap.rss'}
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.xml
Accediendo al siguiente enlace... https://www.culturalgijonesa.org/sitemap.rss
Se encontraron los siguientes enlaces xml: {'https://www.europapress.es/sitemap.xml', 'https://www.europapress.es/sitemap_index/'}
Accediendo al siguiente enlace... https://www.europapress.es/sitemap.xml
Accediendo al siguiente enlace... https://www.europapress.es/sitemap_index/
Se encontraron los siguientes enlaces xml: {'https://www.larazon.es/sitemaps/content_sitemap_index.xml', 'https://www.larazon.es/sitemaps/news.xml'}
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/content_sitemap_index.xml
Accediendo al siguiente enlace... https://www.larazon.es/sitemaps/news.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elespanol.com/sitemap_google_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.eldiario.es/sitemap_index_25b87.xml', 'https://www.eldiario.es/sitemap_google_news_25b87.xml'}
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_index_25b87.xml
Accediendo al siguiente enlace... https://www.eldiario.es/sitemap_google_news_25b87.xml
Robots URL: https://www.eldia.es/robots.txt
Robots URL: https://forbes.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.rtpa.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.rtpa.es/sitemap.xml
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.elconfidencial.com/newsitemap_4.xml
Robots URL: https://www.nationalgeographic.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.nortes.me/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.nortes.me/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://migijon.com/xmlsitemap.xml', 'https://migijon.com/sitemap_index.xml'}
Accediendo al siguiente enlace... https://migijon.com/xmlsitemap.xml
Accediendo al siguiente enlace... https://migijon.com/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.tribunasalamanca.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunasalamanca.com/sitemap_last_news.xml
Robots URL: https://iymagazine.es/robots.txt
Robots URL: https://www.tribunaavila.com/robots.txt
Robots URL: https://www.lacerca.com/robots.txt
Robots URL: https://www.larioja.com/robots.txt
Robots URL: https://www.eldiariomontanes.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.eldia.es/sitemap_google_news_f10b6.xml', 'https://www.eldia.es/sitemap_index_f10b6.xml'}
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_google_news_f10b6.xml
Accediendo al siguiente enlace... https://www.eldia.es/sitemap_index_f10b6.xml
Robots URL: https://www.infobae.com/robots.txt
Robots URL: https://www.latribunadealbacete.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://forbes.es/wp-sitemap.xml'}
Accediendo al siguiente enlace... https://forbes.es/wp-sitemap.xml
Robots URL: https://www.elfielato.es/robots.txt
Robots URL: https://itg.es/robots.txt
Robots URL: https://www.teleprensa.com/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.infobae.com/arc/outboundfeeds/sitemap2/', 'https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/', 'https://www.infobae.com/arc/outboundfeeds/news-sitemap2/'}
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap2/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/sitemap-index-static/
Accediendo al siguiente enlace... https://www.infobae.com/arc/outboundfeeds/news-sitemap2/
Se encontraron los siguientes enlaces xml: {'https://www.tribunaavila.com/sitemap_last_news.xml'}
Accediendo al siguiente enlace... https://www.tribunaavila.com/sitemap_last_news.xml
Se encontraron los siguientes enlaces xml: {'https://www.larioja.com/sitemap.incremental.xml', 'https://www.larioja.com/sitemap.xml'}
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.incremental.xml
Accediendo al siguiente enlace... https://www.larioja.com/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.latribunadealbacete.es/sitemap.news.xml', 'https://www.latribunadealbacete.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.news.xml
Accediendo al siguiente enlace... https://www.latribunadealbacete.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'http://www.lacerca.com/system/sitemaps/sitemap.xml'}
Accediendo al siguiente enlace... http://www.lacerca.com/system/sitemaps/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.elfielato.es/sitemap.xml', 'https://www.elfielato.es/sitemap.news.xml.gz'}
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.xml
Accediendo al siguiente enlace... https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.news.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.eldiariomontanes.es/sitemap.xml', 'https://www.eldiariomontanes.es/sitemap.incremental.xml'}
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.xml
Accediendo al siguiente enlace... https://www.eldiariomontanes.es/sitemap.incremental.xml
Se encontraron los siguientes enlaces xml: {'https://www.teleprensa.com/sitemap.xml', 'https://www.teleprensa.com/sitemap.news.xml.gz'}
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.xml
Accediendo al siguiente enlace... https://www.teleprensa.com/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.news.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.nationalgeographic.es/google-news.xml', 'https://www.nationalgeographic.es/sitemap/sitemap.xml'}
Accediendo al siguiente enlace... https://www.nationalgeographic.es/google-news.xml
Accediendo al siguiente enlace... https://www.nationalgeographic.es/sitemap/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://iymagazine.es/sitemap.xml'}
Accediendo al siguiente enlace... https://iymagazine.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://itg.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://itg.es/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml', 'https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml'}
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_index_fcad9.xml
Accediendo al siguiente enlace... https://www.laopiniondemalaga.es/sitemap_google_news_fcad9.xml
Se encontraron los siguientes enlaces xml: {'https://www.laprovincia.es/sitemap_index_89aa6.xml', 'https://www.laprovincia.es/sitemap_google_news_89aa6.xml'}
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_index_89aa6.xml
Accediendo al siguiente enlace... https://www.laprovincia.es/sitemap_google_news_89aa6.xml
Se encontró archivo comprimido https://iymagazine.es/sitemaps/sitemap_1.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-10.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-11.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-12.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-13.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-14.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-15.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-1.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-2.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-3.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-4.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-5.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-6.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-7.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.elperiodico.com/es/sitemap-noticias.xml', 'https://www.elperiodico.com/es/google-news.xml'}
Accediendo al siguiente enlace... https://www.elperiodico.com/es/sitemap-noticias.xml
Accediendo al siguiente enlace... https://www.elperiodico.com/es/google-news.xml
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-8.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-articles-es-9.xml.gz
Se encontró archivo comprimido https://www.lacerca.com/system/sitemaps/sitemap-news-es-1.xml.gz
No se encontraron enlaces xml en robots.txt. Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-google-news.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-1.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-2.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-3.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-4.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-5.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-6.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-7.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-8.xml
Accediendo al siguiente enlace especificado... https://www.lavanguardia.com/sitemap-news-agencias-9.xml
Se encontró archivo comprimido https://www.elfielato.es/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.elfielato.es/sitemap.contents.2025.03.1.xml.gz
Robots URL: https://www.farodevigo.es/robots.txt
Robots URL: https://www.diariocordoba.com/robots.txt
Robots URL: https://www.almerianoticias.es/robots.txt
Robots URL: https://news.ual.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.diariocordoba.com/sitemap_google_news_9665f.xml', 'https://www.diariocordoba.com/sitemap_index_9665f.xml'}
Accediendo al siguiente enlace... https://www.diariocordoba.com/sitemap_google_news_9665f.xml
Accediendo al siguiente enlace... https://www.diariocordoba.com/sitemap_index_9665f.xml
Se encontraron los siguientes enlaces xml: {'https://www.farodevigo.es/sitemap_index_246e7.xml', 'https://www.farodevigo.es/sitemap_google_news_246e7.xml'}
Accediendo al siguiente enlace... https://www.farodevigo.es/sitemap_index_246e7.xml
Accediendo al siguiente enlace... https://www.farodevigo.es/sitemap_google_news_246e7.xml
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.news.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.latest.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.1.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.2.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.3.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.4.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.5.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.6.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.7.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.8.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.9.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.10.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.11.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.12.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.13.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.14.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.15.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.16.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.17.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.18.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.19.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.20.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.21.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.22.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.23.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.24.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.25.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.26.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.27.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.28.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.29.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.30.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.31.xml.gz
Se encontró archivo comprimido https://www.teleprensa.com/sitemap.contents.2025.03.32.xml.gz
Se encontraron los siguientes enlaces xml: {'https://www.almerianoticias.es/sitemap_index.xml'}
Accediendo al siguiente enlace... https://www.almerianoticias.es/sitemap_index.xml
Se encontraron los siguientes enlaces xml: {'http://news.ual.es/sitemap_index.xml'}
Accediendo al siguiente enlace... http://news.ual.es/sitemap_index.xml
Robots URL: https://www.noticiasde.es/robots.txt
Robots URL: https://www.diariodeibiza.es/robots.txt
Robots URL: https://www.redaccionmedica.com/robots.txt
Robots URL: https://cronicadeandalucia.com/robots.txt
Robots URL: https://segoviaudaz.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.diariodeibiza.es/sitemap_index_fdff0.xml', 'https://www.diariodeibiza.es/sitemap_google_news_fdff0.xml'}
Accediendo al siguiente enlace... https://www.diariodeibiza.es/sitemap_index_fdff0.xml
Accediendo al siguiente enlace... https://www.diariodeibiza.es/sitemap_google_news_fdff0.xml
Se encontraron los siguientes enlaces xml: {'https://www.noticiasde.es/sitemap.xml'}
Accediendo al siguiente enlace... https://www.noticiasde.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.redaccionmedica.com/sitemaps/sitemap-recursos-salud.xml', 'https://www.redaccionmedica.com/sitemaps/sitemap-news.xml', 'https://www.redaccionmedica.com/sitemap.xml'}
Accediendo al siguiente enlace... https://www.redaccionmedica.com/sitemaps/sitemap-recursos-salud.xml
Accediendo al siguiente enlace... https://www.redaccionmedica.com/sitemaps/sitemap-news.xml
Accediendo al siguiente enlace... https://www.redaccionmedica.com/sitemap.xml
Robots URL: https://www.diariodevalderrueda.es/robots.txt
Robots URL: https://www.laescena.es/robots.txt
Robots URL: https://valencia24horas.com/robots.txt
Se encontraron los siguientes enlaces xml: {'http://segoviaudaz.es/sitemap.xml'}
Accediendo al siguiente enlace... http://segoviaudaz.es/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.diariodevalderrueda.es/sitemap.xml', 'https://www.diariodevalderrueda.es/sitemap/lastarticles'}
Accediendo al siguiente enlace... https://www.diariodevalderrueda.es/sitemap.xml
Accediendo al siguiente enlace... https://www.diariodevalderrueda.es/sitemap/lastarticles
Robots URL: https://www.laopinioncoruna.es/robots.txt
Robots URL: https://www.ondacero.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://cronicadeandalucia.com/sitemap_index.xml', 'https://cronicadeandalucia.com/sitemap-news.xml'}
Accediendo al siguiente enlace... https://cronicadeandalucia.com/sitemap_index.xml
Accediendo al siguiente enlace... https://cronicadeandalucia.com/sitemap-news.xml
Robots URL: https://www.eleconomista.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://valencia24horas.com/sitemap.rss', 'https://valencia24horas.com/sitemap.xml'}
Accediendo al siguiente enlace... https://valencia24horas.com/sitemap.rss
Accediendo al siguiente enlace... https://valencia24horas.com/sitemap.xml
Se encontraron los siguientes enlaces xml: {'https://www.laopinioncoruna.es/sitemap_index_967c1.xml', 'https://www.laopinioncoruna.es/sitemap_google_news_967c1.xml'}
Accediendo al siguiente enlace... https://www.laopinioncoruna.es/sitemap_index_967c1.xml
Accediendo al siguiente enlace... https://www.laopinioncoruna.es/sitemap_google_news_967c1.xml
Se encontraron los siguientes enlaces xml: {'http://www.laescena.es/sitemap_index.xml'}
Accediendo al siguiente enlace... http://www.laescena.es/sitemap_index.xml
Robots URL: https://www.sport.es/robots.txt
Se encontraron los siguientes enlaces xml: {'https://www.ondacero.es/sitemaps/news.xml', 'https://www.ondacero.es/sitemaps/content_sitemap_index.xml', 'https://www.ondacero.es/sitemaps/GENERAL_C108_elections_NEWS_content_2023.xml'}

# Cargar datos obtenidos

In [ ]:
import pandas as pd
from datetime import datetime
import numpy as np

# Cargar la data extraída
data_df = pd.read_csv("news_output.csv")

# Convertir a tipo datetime usando UTC para tener un formato estandarizado
data_df['fecha_publicacion'] = pd.to_datetime(data_df['fecha_publicacion'], format='mixed', errors='coerce', utc=True)
# Convertir a zona horaria de españa
data_df['fecha_publicacion'] = data_df['fecha_publicacion'].dt.tz_convert('Europe/Madrid')
# Eliminar duplicados y ordenar por fecha
data_df = data_df.drop_duplicates().sort_values(by='fecha_publicacion', ascending=False).reset_index(drop=True)
data_df

,fuente,url,titulo,fecha_publicacion
0,Levante-EMV,https://www.levante-emv.com/economia/2025/03/1...,Digitaliza tu empresa con éxito: descubre las ...,2025-03-17 07:30:00+01:00
1,MENORCA,https://www.menorca.info/hemeroteca.html,NaN,2025-03-17 05:51:28+01:00
2,MENORCA,https://www.menorca.info/opinion.html,NaN,2025-03-17 05:51:28+01:00
3,MENORCA,https://www.menorca.info/quienes_somos.html,NaN,2025-03-17 05:51:28+01:00
4,MENORCA,https://www.menorca.info/contacto/publicidad.html,NaN,2025-03-17 05:51:28+01:00
...,...,...,...,...
27517,Santander Digital 24 Horas,https://www.santanderdigital24horas.com/redotp...,NaN,NaT
27518,Santander Digital 24 Horas,https://www.santanderdigital24horas.com/lexiwa...,NaN,NaT
27519,Santander Digital 24 Horas,https://www.santanderdigital24horas.com/pablo-...,NaN,NaT
27520,Santander Digital 24 Horas,https://www.santanderdigital24horas.com/medida...,NaN,NaT
27521,Santander Digital 24 Horas,https://www.santanderdigital24horas.com/mimma-...,NaN,NaT

In [ ]:
data_df['fuente'].value_counts()

fuente
La Voz de Galicia                          1650
La Vanguardia                              1339
Gente Digital                              1335
ABC                                        1210
Europa Press                               1166
                                           ...
Diario del Puerto                             5
Deportes Menorca                              5
Tomelloso                                     3
Crónica de Andalucía                          2
Periódico digital de Castilla-La Mancha       1
Name: count, Length: 105, dtype: int64

## Eliminar enlaces duplicados

In [ ]:
def remover_url_duplicados(df):
    df['non_null_count'] = df.notnull().sum(axis=1)
    df = df.sort_values(by=['url', 'non_null_count'], ascending=[True, False])
    df = df.drop_duplicates(subset=['url'], keep='first')
    df = df.drop(columns=['non_null_count'])
    df = df.sort_values(by='fecha_publicacion', ascending=False).reset_index(drop=True)
    return df

data_df = remover_url_duplicados(data_df)
data_df

,fuente,url,titulo,fecha_publicacion
0,Levante-EMV,https://www.levante-emv.com/economia/2025/03/1...,Digitaliza tu empresa con éxito: descubre las ...,2025-03-17 07:30:00+01:00
1,MENORCA,https://www.menorca.info/deportes.html,NaN,2025-03-17 05:51:28+01:00
2,MENORCA,https://www.menorca.info/,NaN,2025-03-17 05:51:28+01:00
3,MENORCA,https://www.menorca.info/hemeroteca.html,NaN,2025-03-17 05:51:28+01:00
4,MENORCA,https://www.menorca.info/participa.html,NaN,2025-03-17 05:51:28+01:00
...,...,...,...,...
20768,Bilbao 24 Horas,https://www.xataka.com/robotica-e-ia/openai-se...,NaN,NaT
20769,Bilbao 24 Horas,https://www.xataka.com/robotica-e-ia/todos-mir...,NaN,NaT
20770,Bilbao 24 Horas,https://www.xataka.com/streaming/peliculas-ter...,NaN,NaT
20771,Bilbao 24 Horas,https://www.xataka.com/wearables/este-controla...,NaN,NaT
20772,ABC,https://www.zendalibros.com/alejandro-palomas-...,NaN,NaT

In [ ]:
data_df['fuente'].value_counts()

fuente
La Voz de Galicia                          1645
La Vanguardia                              1339
Gente Digital                              1335
ABC                                        1210
MENORCA                                     751
                                           ...
Deportes Menorca                              5
Diario del Puerto                             5
Tomelloso                                     3
Crónica de Andalucía                          2
Periódico digital de Castilla-La Mancha       1
Name: count, Length: 105, dtype: int64